### ISSUE TITLE
Control config Mode via env 

### ISSUE THREAD

**Issue by pnaildev** [boredazfcuk/docker-icloudpd#10]
Hi there,

please keep up the great work! I’m trying to run your code on a NAS from Synology. My problem is that Synology always runs docker containers interactively, so your script is always in „config mode“ trying to renew the auth. cookie.

Would you be so kind to extend this check so that we can deactivate config mode also by setting an env e.g. „disableSetup=1“.

Thanks again!

**Comment by boredazfcuk** [comment]
I can't see myself abandoning this any time soon. My latest iPhone is less than a month old and I upgraded from a 5... guessing I have this one for a long time yet!

So anyway, I've added a new variable:
```
interactive_only
```
Just give it a value and it should skip the 2FA cookie generation functions. I've not actually tested it, but it's a fairly simple change and it doesn't look like it'll have any knock on effects... but if you do have a problem just re-open the Issue.
