### ISSUE TITLE
convert_heic_to_jpeg fails since last update

### ISSUE THREAD

**Issue by Cartman84** [boredazfcuk/docker-icloudpd#101]
Hi,

since last update, the conversion .heic to .jpg fails with error msg "/usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found"

After fully re-composing the docker image, it worked for one time but also since the second attempt, all I get is this error msg.

In addition, for whatever reason, it creates an empty file with file ending .jpg for the first three files (IMG_7255, IMG_7254 and IMG_7253).

> 2021-09-12 21:19:51 INFO Downloading /home/user/iCloud/2021/08/IMG_7307.HEIC
> 2021-09-12 21:19:52 INFO Downloading /home/user/iCloud/2021/08/IMG_7305.HEIC
> 2021-09-12 21:19:52 INFO Downloading /home/user/iCloud/2021/08/IMG_7304.HEIC
> 2021-09-12 21:19:53 INFO All photos have been downloaded!
> 2021-09-12 21:19:53 INFO Convert HEIC files to JPEG
> 2021-09-12 21:19:53 INFO Convert HEIC to JPEG...
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7255.HEIC to /home/user/iCloud/2021/09/IMG_7255.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Thu Sep 9 15:24:30 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7255.JPG to Thu Sep 9 15:24:30 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7254.HEIC to /home/user/iCloud/2021/09/IMG_7254.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Thu Sep 9 15:24:24 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7254.JPG to Thu Sep 9 15:24:24 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7253.HEIC to /home/user/iCloud/2021/09/IMG_7253.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Thu Sep 9 15:24:19 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7253.JPG to Thu Sep 9 15:24:19 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7395.HEIC to /home/user/iCloud/2021/09/IMG_7395.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Sat Sep 4 18:58:06 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7395.JPG to Sat Sep 4 18:58:06 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7394.HEIC to /home/user/iCloud/2021/09/IMG_7394.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Sat Sep 4 18:57:52 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7394.JPG to Sat Sep 4 18:57:52 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7381.HEIC to /home/user/iCloud/2021/09/IMG_7381.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Sat Sep 4 11:41:40 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7381.JPG to Sat Sep 4 11:41:40 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7375.HEIC to /home/user/iCloud/2021/09/IMG_7375.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 16:14:19 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7375.JPG to Fri Sep 3 16:14:19 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7373.HEIC to /home/user/iCloud/2021/09/IMG_7373.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 15:40:00 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7373.JPG to Fri Sep 3 15:40:00 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7371.HEIC to /home/user/iCloud/2021/09/IMG_7371.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:18:03 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7371.JPG to Fri Sep 3 12:18:03 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7370.HEIC to /home/user/iCloud/2021/09/IMG_7370.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:18:00 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7370.JPG to Fri Sep 3 12:18:00 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7369.HEIC to /home/user/iCloud/2021/09/IMG_7369.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:17:56 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7369.JPG to Fri Sep 3 12:17:56 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7368.HEIC to /home/user/iCloud/2021/09/IMG_7368.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:17:51 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7368.JPG to Fri Sep 3 12:17:51 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7364.HEIC to /home/user/iCloud/2021/09/IMG_7364.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:03:04 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7364.JPG to Fri Sep 3 12:03:04 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7363.HEIC to /home/user/iCloud/2021/09/IMG_7363.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:02:38 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7363.JPG to Fri Sep 3 12:02:38 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7362.HEIC to /home/user/iCloud/2021/09/IMG_7362.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:02:36 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7362.JPG to Fri Sep 3 12:02:36 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7360.HEIC to /home/user/iCloud/2021/09/IMG_7360.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:01:31 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7360.JPG to Fri Sep 3 12:01:31 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7359.HEIC to /home/user/iCloud/2021/09/IMG_7359.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:01:25 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7359.JPG to Fri Sep 3 12:01:25 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7357.HEIC to /home/user/iCloud/2021/09/IMG_7357.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 12:00:14 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7357.JPG to Fri Sep 3 12:00:14 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7351.HEIC to /home/user/iCloud/2021/09/IMG_7351.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 11:38:50 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7351.JPG to Fri Sep 3 11:38:50 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7350.HEIC to /home/user/iCloud/2021/09/IMG_7350.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 11:38:47 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7350.JPG to Fri Sep 3 11:38:47 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7349.HEIC to /home/user/iCloud/2021/09/IMG_7349.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Fri Sep 3 11:38:25 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7349.JPG to Fri Sep 3 11:38:25 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7348.HEIC to /home/user/iCloud/2021/09/IMG_7348.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Thu Sep 2 17:02:18 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7348.JPG to Thu Sep 2 17:02:18 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7342.HEIC to /home/user/iCloud/2021/09/IMG_7342.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Thu Sep 2 16:16:45 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7342.JPG to Thu Sep 2 16:16:45 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7341.HEIC to /home/user/iCloud/2021/09/IMG_7341.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Thu Sep 2 15:04:50 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7341.JPG to Thu Sep 2 15:04:50 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7338.HEIC to /home/user/iCloud/2021/09/IMG_7338.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Thu Sep 2 11:30:25 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7338.JPG to Thu Sep 2 11:30:25 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7333.HEIC to /home/user/iCloud/2021/09/IMG_7333.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 19:46:09 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7333.JPG to Wed Sep 1 19:46:09 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7332.HEIC to /home/user/iCloud/2021/09/IMG_7332.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 19:46:09 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7332.JPG to Wed Sep 1 19:46:09 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7331.HEIC to /home/user/iCloud/2021/09/IMG_7331.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 19:46:09 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7331.JPG to Wed Sep 1 19:46:09 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7330.HEIC to /home/user/iCloud/2021/09/IMG_7330.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 17:49:15 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7330.JPG to Wed Sep 1 17:49:15 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7328.HEIC to /home/user/iCloud/2021/09/IMG_7328.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 16:11:22 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7328.JPG to Wed Sep 1 16:11:22 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7327.HEIC to /home/user/iCloud/2021/09/IMG_7327.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 16:11:22 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7327.JPG to Wed Sep 1 16:11:22 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7326.HEIC to /home/user/iCloud/2021/09/IMG_7326.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 16:11:14 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7326.JPG to Wed Sep 1 16:11:14 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7322.HEIC to /home/user/iCloud/2021/09/IMG_7322.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 14:54:16 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7322.JPG to Wed Sep 1 14:54:16 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7321.HEIC to /home/user/iCloud/2021/09/IMG_7321.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 12:30:48 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7321.JPG to Wed Sep 1 12:30:48 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7320.HEIC to /home/user/iCloud/2021/09/IMG_7320.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 12:30:44 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7320.JPG to Wed Sep 1 12:30:44 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7319.HEIC to /home/user/iCloud/2021/09/IMG_7319.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 12:30:33 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7319.JPG to Wed Sep 1 12:30:33 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7318.HEIC to /home/user/iCloud/2021/09/IMG_7318.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 12:18:53 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7318.JPG to Wed Sep 1 12:18:53 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7317.HEIC to /home/user/iCloud/2021/09/IMG_7317.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 12:18:51 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7317.JPG to Wed Sep 1 12:18:51 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/09/IMG_7316.HEIC to /home/user/iCloud/2021/09/IMG_7316.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Wed Sep 1 12:18:50 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/09/IMG_7316.JPG to Wed Sep 1 12:18:50 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/08/IMG_7312.HEIC to /home/user/iCloud/2021/08/IMG_7312.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Tue Aug 31 11:27:38 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/08/IMG_7312.JPG to Tue Aug 31 11:27:38 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/08/IMG_7311.HEIC to /home/user/iCloud/2021/08/IMG_7311.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Tue Aug 31 11:27:36 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/08/IMG_7311.JPG to Tue Aug 31 11:27:36 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/08/IMG_7310.HEIC to /home/user/iCloud/2021/08/IMG_7310.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Tue Aug 31 11:27:35 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/08/IMG_7310.JPG to Tue Aug 31 11:27:35 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/08/IMG_7309.HEIC to /home/user/iCloud/2021/08/IMG_7309.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Tue Aug 31 10:14:54 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/08/IMG_7309.JPG to Tue Aug 31 10:14:54 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/08/IMG_7308.HEIC to /home/user/iCloud/2021/08/IMG_7308.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Tue Aug 31 10:13:53 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/08/IMG_7308.JPG to Tue Aug 31 10:13:53 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/08/IMG_7307.HEIC to /home/user/iCloud/2021/08/IMG_7307.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Tue Aug 31 10:13:48 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/08/IMG_7307.JPG to Tue Aug 31 10:13:48 2021
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/08/IMG_7305.HEIC to /home/user/iCloud/2021/08/IMG_7305.JPG
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Mon Aug 30 19:44:28 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/08/IMG_7305.JPG to Mon Aug 30 19:44:28 2021
> /usr/local/bin/sync-icloud.sh: line 504: heif-convert: not found
> 2021-09-12 21:19:53 INFO Converting /home/user/iCloud/2021/08/IMG_7304.HEIC to /home/user/iCloud/2021/08/IMG_7304.JPG
> 2021-09-12 21:19:53 INFO Timestamp of HEIC file: Mon Aug 30 19:43:33 2021
> 2021-09-12 21:19:53 INFO Setting timestamp of /home/user/iCloud/2021/08/IMG_7304.JPG to Mon Aug 30 19:43:33 2021
> 2021-09-12 21:19:53 INFO Synchronisation complete for user
> 2021-09-12 21:19:53 INFO Web cookie expires: 2021-11-11 @ 18:35:56
> 2021-09-12 21:19:53 INFO Two factor authentication cookie expires: 2021-12-11 @ 18:36:07
> 2021-09-12 21:19:53 INFO Days remaining until expiration: 89
> 2021-09-12 21:19:53 INFO iCloud login counter = 2
> 2021-09-12 21:19:53 INFO Synchronisation ended at 21:19:53
> 2021-09-12 21:19:53 INFO Total time taken: 00:08:56
> 2021-09-12 21:19:53 INFO Next synchronisation at 21:10:57

**Comment by boredazfcuk** [comment]
My bad. I had to change the HEIC to JPEG conversion tool, as the previous one was rotating images when it shouldn't.

Fixed and new Dockerhub imge pushed. Give it a test and let me know.

**Comment by boredazfcuk** [comment]
Oh, and to convert the HEICs that will have been missed during the period where it wasn't working, you can use the --ConvertAllHEICs command line option detailed in the readme. Thanks.

**Comment by Cartman84** [comment]
Thank you so much for your work @boredazfcuk. Issue is solved.
