### ISSUE TITLE
private db access disabled for this account

### ISSUE THREAD

**Issue by jotka** [boredazfcuk/docker-icloudpd#109]
it's been working fine for months. Recently:

2021-10-14 08:35:22 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
private db access disabled for this account.  Please wait a few minutes then try again.  The remote servers might be trying to throttle requests. (ACCESS_DENIED)

The same when 2fa has been refreshed with /usr/local/bin/sync-icloud.sh --Initialise

**Comment by jotka** [comment]
yeah, but the thing is I have the normal update interval, like once per day. 
I needed to reboot the NAS device docker-iclodpd is running on, after the first container start I have this :-|

**Comment by boredazfcuk** [comment]
To be honest, I'd just keep an eye on it for a while. These things usually clear themselves up.

However, I've also notice that they stack, so if you trigger it, it might lock you out for 15mins, but if you hit it again within those 15mins, the second hit adds half and hour, third hit may add an hour. I've had it before where I've needed to switch of the sync on it for a day so that it went 48hrs between syncs.

**Comment by jotka** [comment]
yeah, it seems that I had some other integration trying to connect (Home Assistant). I was getting emails from iCloud all the time saying "something was trying to connect to your iCloud account). I think it may be the reason. I will wait 48h and try again with icloudpd. Thanks for the awesome container!

**Comment by Alban9** [comment]
Try to turn off ADP (Advanced Data Protection). I turned if off on my iPhone.

**Comment by Recurzion** [comment]
I know this is a closed issue, but I found another cause of this message in case this helps someone:
Turning off "Access iCloud Data on the Web" will also show this error message. From an iPhone, this setting is under Settings, Apple ID, iCloud, Access iCloud Data on the Web.

**Comment by fredsherbet** [comment]
And to add to @Recurzion's comment - you also need to disable Advanced Data Protection (in the same place - Settings > Apple ID > iCloud > Advanced Data Protection)

**Comment by scartech** [comment]
For those struggling with this issue, disabling Advanced Data Protection is the fix. Verified  in January 2026.
