### ISSUE TITLE
Synchronisation Interval is being ignored

### ISSUE THREAD

**Issue by makutaku** [boredazfcuk/docker-icloudpd#111]
To repro: installed latest version and changed synchronisation_interval to 3 hours (10800 seconds)

Expectation: log should indicate next synchronization will happen in 3 hours

Actual: log indicates next synchronization will happen in 24 hours:
2021-10-24 21:48:54 INFO Days remaining until expiration: 89
2021-10-24 21:48:54 INFO iCloud login counter = 2
2021-10-24 21:48:54 INFO Synchronisation ended at 21:48:54
2021-10-24 21:48:54 INFO Total time taken: 00:00:11
2021-10-24 21:48:54 INFO Next synchronisation at 21:48:43

Here are my environment variables:

HISTFILE='/root/.ash_history'
HOME='/root'
HOSTNAME=<REMOVED>
HOST_OS='Unraid'
IFS=' 
'
LINENO=''
OPTIND='1'
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
PGID='100'
PPID='0'
PS1='\w \$ '
PS2='> '
PS4='+ '
PUID='99'
PWD='/'
SHLVL='1'
TERM='xterm'
TZ='America/Chicago'
UMASK='000'
apple_id=REMOVED
authentication_type='2FA'
command_line_options=' --auto-delete --folder-structure {:%Y/%m}'
config_dir='/config'
directory_permissions='777'
file_permissions='666'
notification_type=''
prowl_api_key=''
pushbullet_api_key=''
synchronisation_interval='10800'
telegram_chat_id=''
telegram_token=''

**Comment by boredazfcuk** [comment]
Just closing this off as it's expected behaviour.
