### ISSUE TITLE
Download only new Photos

### ISSUE THREAD

**Issue by AlexanderSch90** [boredazfcuk/docker-icloudpd#112]
Does the recent and until-found functionality rely on checking the photo files locally or does it track somewhere what's already been downloaded?

I imagine a super common workflow is using this tool to download photos and then moving their location (e.g. importing them to a locally hosted photogallery), so the downloaded photos will no longer exist in the same path the tool is being run from.

Is there a Solution?

**Comment by boredazfcuk** [comment]
Hi,

Nothing is tracked as the app doesn’t keep a database of what has been downloaded.

It simply scans the icloud.com website for photos, and checks to see if they exist on the local file system. If they don’t, it downloads them.

I import everything to a local photo gallery as you mentioned. I then remove the photos from my phone to prevent them being downloaded again. You could try linking the files to their new location, but I don’t know if the app would treat the link as a downloaded file. It could also be fairly time consuming if you are doing them individually.

Thanks.

**Comment by AlexanderSch90** [comment]
Hey, is there any way you could have reached the container around a database? This would give you much more possibilities...

**Comment by boredazfcuk** [comment]
Unfortunately not. The container invokes [this](https://github.com/icloud-photos-downloader/icloud_photos_downloader) Python script to perform the synchronisation, and it's not capable of tracking the download status of individual files.

**Comment by boredazfcuk** [comment]
Closing this off as there's nothing I can do about it. Will require development further upstream.
