### ISSUE TITLE
Request: make synchronisation_interval value more flexible

### ISSUE THREAD

**Issue by overbyrn** [boredazfcuk/docker-icloudpd#113]
Whilst I understand Apple can throttle, I've had no issues running every two hours.  Currently I'm using an ugly hack during container start to sed out the sync interval case statement in the intialize function so that the value I assign in my compose file doesn't get overwritten.  It would be great if the sync interval could be set to any value.

**Comment by bauzer714** [comment]
@boredazfcuk - I agree with this. I think the logic should use whatever value the user provides, with a default value if none is provided.  Then throw a warning into the log if it's more frequent then X hours that there may be throttling.

**Comment by boredazfcuk** [comment]
The syncronisation period used to be configurable, but it lead to a significant number of issues being raised here, and over at the underlying app's page, during a particularly throttle-y month(ish) from Apple. My sync period at the time was set to 4 hours and I was getting locked out most days.

I introduced the fixed syncronisation periods to avoid a reoccurrence of this scenario. The underlying tool isn't meant to be a syncronisation utility like the iCloud control panel, but a rather a backup utility to prevent significant data loss.

**Comment by overbyrn** [comment]
Not a problem. Thanks for the reply and I do understand your reasoning. I'll run a localised version with the necessary changes for my use case.

**Comment by boredazfcuk** [comment]
No problem. I actually ran into the: `private db access disabled for this account. Please wait a few minutes then try again. The remote servers might be trying to throttle requests. (ACCESS_DENIED)` problem on my child's Apple ID last night. He was asleep at the time, so I know he wasn't logged in to multiple devices, or even active.

I have his `synchronisation_interval` set at 24hrs so it had to be Apple throttling connections, or some sort of outage at their end. If I'd been synchronising every hour, it may have generated a lot of errors. Some people like to open issues if it hasn't worked for a couple of hours. With a higher interval, a lot of these problems resolve themselves before people come to log issues lol.

Thanks for your understanding.
