### ISSUE TITLE
Can support WeChat push notifications?

### ISSUE THREAD

**Issue by Alano-i** [boredazfcuk/docker-icloudpd#114]
First of all, thank the author, this tool is great.

Recently discovered a tool iyuu that push WeChat messages via GET/POST.
https://iyuu.cn/help.html

Can iCloudpd receive push notifications in this way?
It would be great if it could be achieved.
Thanks.

**Comment by boredazfcuk** [comment]
I've had a look into this, but cannot find any documentation on how to actually perform the post to the WeChat API. The example in your documentation posts to iyuu.cn, but that doesn't seem to be a WeChat domain.

[THIS](https://wechat-oauth2.readthedocs.io/en/latest/api.html) documentation suggests that WeChat's API is located at: https://api.weixin.qq.com

But it doesn't give any decent examples of how to send a basic message unfortunately.

**Comment by Alano-i** [comment]
> I've had a look into this, but cannot find any documentation on how to actually perform the post to the WeChat API. The example in your documentation posts to iyuu.cn, but that doesn't seem to be a WeChat domain.
> 
> [THIS](https://wechat-oauth2.readthedocs.io/en/latest/api.html) documentation suggests that WeChat's API is located at: https://api.weixin.qq.com
> 
> But it doesn't give any decent examples of how to send a basic message unfortunately.

The official WeChat official does not provide an API that can be notified directly. WeChat notifications can be made through a third-party token. 
Can icloudpd send notifications in this way? The only environment variable that needs to be configured is iyuu's token.

Get iyuu's token: Scan the QR code in the middle of the homepage of https://iyuu.cn/ through the WeChat app (appears after click the green button on the homepage).

Then,
Pass the title of the notice to "text";
Pass the content of the notice to "desp".

I don't know if it will work. hope  it can be support, that would be great. thank you very much.

**Comment by boredazfcuk** [comment]
Hi,

I'm not sure I understand what `desp` is used for. The only reference I can see for it is: `$desp = "这是内容";`, but I have no idea what that means.

I've created a new container `boredazfcuk/icloudpd:testing` which adds `IYUU` as a **notification_type**, but I do not post anything for `desp` at the moment.

Can you test and let me know if it works? If it fails, what the error is?

**Comment by Alano-i** [comment]
> 



> Hi,
> 
> I'm not sure I understand what `desp` is used for. The only reference I can see for it is: `$desp = "这是内容";`, but I have no idea what that means.
> 
> I've created a new container `boredazfcuk/icloudpd:testing` which adds `IYUU` as a **notification_type**, but I do not post anything for `desp` at the moment.
> 
> Can you test and let me know if it works? If it fails, what the error is?

Hi, thanks .
The iyuu notification is ready to be sent, but all the notification content is put in the header.
so, it is necessary to adjust the splicing of sending notification fields.

![image](https://user-images.githubusercontent.com/68833595/143726081-c730a86a-e024-48e4-8e98-884ff350b9f6.png)


Here is an example you can take a look.
If  send the following example notification, then the actual notification received is shown in the picture.
![image](https://user-images.githubusercontent.com/68833595/143726050-59fb42a9-e4d2-47ef-9897-cf395ebf7d48.png)

**Comment by Alano-i** [comment]
> Hi,
> 
> I'm not sure I understand what `desp` is used for. The only reference I can see for it is: `$desp = "这是内容";`, but I have no idea what that means.
> 
> I've created a new container `boredazfcuk/icloudpd:testing` which adds `IYUU` as a **notification_type**, but I do not post anything for `desp` at the moment.
> 
> Can you test and let me know if it works? If it fails, what the error is?

Could you please optimize the notifications of IYUU.  it is better to adjust the splicing rules of notification variables.now all the notification content is put in the header.

**Comment by boredazfcuk** [comment]
Hi, I've pushed a new version this morning which should now send the correct `text` and `desp` information. Please test and let me know. Thanks.

**Comment by Alano-i** [comment]
> Hi, I've pushed a new version this morning which should now send the correct `text` and `desp` information. Please test and let me know. Thanks.

It works well. The notifications are all sent normally.  Thanks for your selfless contribution.

![image](https://user-images.githubusercontent.com/68833595/145678598-ac42e806-237f-41c1-be45-c230ee64b188.png)

**Comment by boredazfcuk** [comment]
Great news. I'll close this issue.
