### ISSUE TITLE
user_id & group_id is higher than what adduser command in Alpine Linux

### ISSUE THREAD

**Issue by rayiins** [boredazfcuk/docker-icloudpd#116]
Hi. 
When I initializing docker-icloudpd in Synology docker, I received a message as follows :
"addgroup: number 1000001 is not in 0..256000 range"
"adduser: number 1000001 is not in 0..256000 range"

The core issue is that Alpine Linux doesn't handle user ids & gourp ids above 256000, and in this case its over 600 million.I use synology with LDAP service and system auto-generated UID & GID is larger than 256000.

I reviewed a workaround posted here:
https://stackoverflow.com/questions/41807026/cant-add-a-user-with-a-high-uid-in-docker-alpine

i try in container, and it works. would you mind change CreateGroup() and CreateUser() implementation?

**Comment by boredazfcuk** [comment]
Hi, I've pushed a new version which switches to using groupadd/useradd from the shadow package. Give it a test and let me know. If it doesn't work, just re-open this issue.

Thanks.
