### ISSUE TITLE
Hidden album

### ISSUE THREAD

**Issue by DJFraz** [boredazfcuk/docker-icloudpd#120]
Hello,
Thanks for the work on this project. This is a feature request to allow items in hidden album to be downloaded to a separate directory or at least a way to move hidden items without being redownloaded to the main directory.

Thanks

**Comment by boredazfcuk** [comment]
Hi,

Sorry, that would be outside the scope of this project. This is a just a Docker container for the icloud_photos_downloader application which handles the interactions with iCloud. I have no Python skills whatsoever, so wouldn't be able to make the requested modifications to the packaged application.

I'm closing this off as I can see you've raised this as a feature request over at the developer's GitHub (https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/399). That's the correct place to raise it, as they can make the requested modifications, however, the two guys that maintain it have been pretty quiet the past few months, unfortunately.

Thanks.
