### ISSUE TITLE
Setup clarification

### ISSUE THREAD

**Issue by jnbarlow** [boredazfcuk/docker-icloudpd#121]
One thing that the docs don't quite cover is if the sync happens automatically or not.  Do I need to set up the `sync-icloud.sh` to run in a cron job in the container or does the container automatically do that?  I kicked it off manually once to get the initial pull in, but I'm unclear as to if it will remain in sync.

**Comment by boredazfcuk** [comment]
Hi,

When the container is launched non-interactively, it runs the `sync-icloud.sh` script continuously (it won't ever exit). It repeats the download process as per the `synchronisation_interval` variable's value. If you have the variable set to `43200` then the container will synchronise the file system with what is in icloud every 12 hours.

If you launch the container interactively, it will operate differently, and take you through the process for authenticating against icloud, storing your password in the container's keyring, and also for generating a multi-factor authentication token, if you have that enabled on your account.

You don't need to set up any cron jobs within the container. Doing so may cause conflicts if the cron job runs at the same time as a synchronisation occurs.

Thanks.

**Comment by jnbarlow** [comment]
Yeah, thanks for the clarification.  After I let it sit I did verify that it was auto-running in the background.  The only thing I'd suggest is just clarifying that in the readme.  It wasn't clear that it would just run, and all you had to do was set up the keyring.

Thanks for the quick reply :)

**Comment by boredazfcuk** [comment]
Quick? Ha!

**Comment by jnbarlow** [comment]
3 days is better than 3 weeks, I'll take it :)
