### ISSUE TITLE
iCloud Drive documents

### ISSUE THREAD

**Issue by josdegroot** [boredazfcuk/docker-icloudpd#126]
Maybe an idea to add the ability to download (backup) all the iCloud Drive documents as well?

Would really help me to have an offline backup of all my iCloud stored images and documents.

**Comment by boredazfcuk** [comment]
This is just a container for the application you can find here: https://github.com/icloud-photos-downloader/icloud_photos_downloader

Additional features will need to be requested upstream before I can enable them in my container. Development over there has been a bit quiet recently though.
