### ISSUE TITLE
Pushover config. issue?

### ISSUE THREAD

**Issue by jonbackhaus** [boredazfcuk/docker-icloudpd#129]
Apologies if this is something obvious or stupid -- I'm trying to get Pushover notifications configured and I'm getting a 400 error that's causing the container to die. Here's the `.env` file that I'm including for the Pushover config.: 

```
# For Pushover notifications
notification_type=Pushover
notification_title="iCloud Photo Downloader"
pushover_user=<my email address>
pushover_token=<my user token>
download_notifications=True
delete_notifications=True
```

Does this configuration look right? Here's a log snippet with the error: 

```
2022-02-05 21:12:52 INFO     Sending Pushover startup notification
2022-02-05 21:12:52 ERROR    Pushover startup notification failed with status code: 400
```

After that, the container dies and restarts. The container runs fine without these environment variables, so I think the rest of my configuration is good. Thank you!

**Comment by boredazfcuk** [comment]
Hi,

The **pushover_user** is the Pushover user key that is given to you when you create your account.

The **pushover_token** is the Application API token that is generated when your create an Application when logged in via the web.

Sorry, the documentation didn't make that very clear, so I've updated it. I don't use Pushover personally, so didn't really know the correct terminology. I just added it as a notification method as someone requested it on here. I downloaded and installed the app today to test it though, as I made some changes to the way notifications are sent a couple of days ago, and thought I must have broken Pushover.
