### ISSUE TITLE
Discord startup notification failed with status code: 204

### ISSUE THREAD

**Issue by mikniche** [boredazfcuk/docker-icloudpd#134]
Hi, I'm running into the following issue when trying to use Discord for notifications.

Error in container logs:
```
INFO     Cleaned notification title: iCloudPD
INFO     Discord notifications enabled
INFO     Discord Discord ID: ***
INFO     Discord Discord token: ***
INFO     Discord notification URL: https://discord.com/api/webhooks/***/***
INFO     Notification period: 7
INFO     Sending Discord startup notification
ERROR    Discord startup notification failed with status code: 204
```
In Discord I have the webhook setup in a channel, and I actually do receive a container started notification.
The container then restarts after 3 minutes and falls into the same error above on repeat, Discord continues to notify me every 3 minutes with the same status.
![image](https://user-images.githubusercontent.com/26928/153634557-ece10ad0-560a-4811-8aa5-45e54bac7852.png)

In my environmental variables config I've got the follow related to notifications:
```
notification_type=Discord
notification_title=iCloudPD
discord_id=***
discord_token=***
```

When I disable notifications by commenting out this block, the container runs nicely. But it would be nice to get notifications when cookies expire, downloads, etc.

I'm running this in docker-compose FWIW.
Thanks in advance for creating this and any help you might be able to offer:)

**Comment by bauzer714** [comment]
This is a bug from a recent merge. @boredazfcuk, here's an example why regex for 2xx might be better.

**Comment by boredazfcuk** [comment]
Yeah, it's just regex doesn't work in the ash shell in Alpine. I've actually managed to achieve the same thing through parameter expansion though, with:
```
if [ "${notification_result:0:1}" -eq 2 ]; then
```
basically, chop the first character off the exit code, and if it's a two, we're all good.

New version was pushed to Dockerhub a few moments ago.
