### ISSUE TITLE
auto_delete .HEIC files leaves HEVC.MOV files. 

### ISSUE THREAD

**Issue by joshuakohut77** [boredazfcuk/docker-icloudpd#139]
I deleted some LivePhotos. Upon running, the service, it found the xxxx.HEIC file in 'Recently Deleted' and removed the file. However it seems like there was an accompanying xxxx_HEVC.MOV file that is associated with the xxxx.HEIC file. That second file was not deleted. 
Maybe this is a config issue on my end? It seems like almost ever LivePhoto downloads both a .HEIC and HEVC.MOV file

**Comment by boredazfcuk** [comment]
This is a problem with the underlying Python script. A "live photo" is actually two files. The HEIC is the first frame of the video, and then the accompanying video is the "live" part.

I think this is a bug in the underlying Python script. In theory, when a live photo is deleted, it should remove both elements. However, it also depends on how Apple presents this information. The underlying Python script basically emulates a person logging on to the iCloud website, downloading all the photos, looking in "Recently Deleted" and removing matching files. It depends on how Apple presents that "Recently Deleted" folder. Apple may keep the association of HEIC and MOV hidden from the end user, but recognise that when the HEIC is deleted, it has to remove the associated MOV. It may not be possible for the underlying Python app to see such an association, so it cannot delete the .MOV when the .HEIC is removed, as it can't say for sure that the two files are connected.

**Comment by joshuakohut77** [comment]
That makes sense and is too bad. The only association that I can see which is consistent is that all the file names match. 
If the file name of the LivePhoto is IMG_1234.HEIC, the paired file is always named IMG_1234_HEVC.MOV. This is consistent with every one of my LivePhotos. Maybe it's not the same for everyone but I'm not sure why it wouldn't be. 
If it's possible I would like to see at least an optional parameter enhancement where if it deletes a IMG_1234.HEIC it also searches and deletes the IMG_1234_HEVC.MOV file. 
I know there's no guaranteed way know these are linked together however the only consequence is that it's deleted temporarily until the next service run. If the IMG_1234_HEVC.MOV still exists on iCloud it will just be downloaded again. So in my mind it's very little downside. 
With how it is now, the delete feature still requires manual intervention to keep the directory clean and in sync with what you really want. If it's a new environment variable then people can decide if it's really worth the "risk" even though you're only losing it locally for a short time if it was a false match. 
Obviously I'm not the maintainer of the code just my running thoughts and wanted to share. I appreciate all the hard work you have done with this project and I love using it.

**Comment by boredazfcuk** [comment]
The filenames are ambiguous though. You phone will start at IMG_0000.HEIC (or maybe 0001, I don't recall which) and go all the way up to IMG_9999.HEIC and then loops back around from the beginning. I've seen people on here with 140k photos, so they will have 14 files named IMG_1234.HEIC... Say one of those is a live photo with an associated movie, there's no way of determining which is the correct associated file.

Also, if you have your pictures in a flat file format, the app will de-duplicate files with the same name, by adding part of the file size to it's name.

So, for example, say you have four "IMG_1234" files. The first would be named IMG_1234.HEIC but the remaining three would be called something like: IMG_1234-27445.HEIC, IMG_1234-26483.HEIC, IMG_1234-28574.HEIC.

Now, say the third file, IMG_1234-26483.HEIC, is actually a live photo. Its associated movie would be named IMG_1234.HEVC.MOV. Now let's say file four is also a live photo, the second IMG_1234.HEVC.MOV file would need to be de-duplicated, and would end up having a de-duplicated name something like IMG_1234.HEVC-84753.MOV. but actually be partnered with IMG_1234-27445.HEIC.

> Obviously I'm not the maintainer of the code just my running thoughts and wanted to share. I appreciate all the hard work you have done with this project and I love using it.

I'm not the maintainer of the code either. I just made a Docker container for the Python application available here: https://github.com/icloud-photos-downloader/icloud_photos_downloader

I'm not a coder by trade. I'm sysadmin. So while I'm competent with scripting languages (bash, batch, powershell, vbscript), I've not really got a clue about Python. The last time I did real programming it was in Pascal, Turbo C and COBOL back in my University days.... I've started a Udemy course on Python, and I'm 100 lessons deep so far, but I think it's going to be a good while before I'm competent enough to be able to contribute to the underlying Python app.

**Comment by joshuakohut77** [comment]
Well I learned a bunch of things I didn't know about iCloud photos and de-duplication for this. Thank for you that. 

> I'm not the maintainer of the code either.
If I had half a brain I would have known that from your github references and not opened issues unrelated to the docker project. 
Regardless I think it's a shame that those orphaned files remain and with it could be resolved. I would open an issue on the other project but they have 50+ bugs/enhancement requests and don't seem to be handling many of them. 

For my case I wrote a quick and dirty python script to detect these orphaned files and delete them. I created some test directories and simulated several scenarios and I think it works well enough. 
The pseudo code is basically. 
- Find all HEVC.MOV files. 
- Does it have a .HEIC pair? 
--> if not, delete the HEVC.MOV orphan
--> if yes, get a list of all matching .HEIC files (the 3-4 files in your above example)
-----> is the creation date of any of these files within a couple seconds of the HEVC.MOV?
-------> if yes, it has a valid pair
-------> if no, delete the HEVC.MOV orphan

It is not pretty code but it works for me and I think it should handle any of the rollover names or de-duplication files I can just have it run on a CRON task every couple hours or so. 

Thanks again for all your hard work. I'm glad I have this Docker container.

**Comment by boredazfcuk** [comment]
I did try implementing something similar, but for JPG files. My daily driver is a Windows laptop and HEIC support is garbage, so I'm converting HEICs to JPG. When I delete a HEIC, it leaves the JPG behind. So I set the script to remove orphaned JPGs but then I realised that it was removing images that I'd saved to my camera roll from WhatApp/Signal (as they don't have a matching HEIC file). It was also removing dumb memes I'd saved off Reddit and stuff... So I canned that pretty quickly.

I have actually revisited this though, as I'm trying a new approach where I parse the output of the download log for for lines starting with "Deleted":
``
Deleting /home/boredazfcuk/iCloud/2022/02/IMG_5342.HEIC!
Deleting /home/boredazfcuk/iCloud/2022/02/IMG_5348.HEIC!
Deleting /home/boredazfcuk/iCloud/2022/02/IMG_5343.HEIC!
```
and then see if there is a matching JPG/HEVC.MOV, and remove it if it's found.

Just testing it on my beta version now.

**Comment by joshuakohut77** [comment]
That’s a good idea of parsing the log file. I might look into adding that into my code. 

I don’t convert my files to JPG so luckily I didn’t suffer from the problem you ran into. I only had to remove HEVC.MOV. 
I did notice sometimes I had a lower case extension on random files HEVC.mov and .heic so I had to add checks for that. 

I did run my code on both mine and my wife’s directories which contains about 22k files. I decided it was smart to output the found files before actually deleting them. So that let me
check if those were valid and adjust my code from there. 

I think this is a fun coding project but I don’t have enough test cases to write something that would work for everyone. 

I’m still not sure how to best handle the rollover image count and to not get a false pairing. I decided to check the file creation time stamp for files with the same base name. That seemed to work well. I purposely modified some file names to simulate de-duplication and rollover. 

I know there’s some holes in my code I need to fix but in the end I’m not losing any files since if I falsely delete them they just re-download. Plus I log to a file so I can check that to make sure it’s working. 

I would like to add in the notification system to send me a message if it finds an orphan.

**Comment by boredazfcuk** [comment]
I've pushed the new version to Dockerhub which removes the _HEVC.MOV files that accompany HEICs. Enable it by setting the new `delete_accompanying` variable to 'True'. It will also need `folder_structure` to be something other than `none` and for `set_exif_datetime` to not be set/set to `False`.

I'm only removing .HEVC and .JPG files. It's my understanding that the iOS Camera app only saves files as .HEIC and .MOV. The others that you see, such as .heic and .mov are likely photos taken with messaging apps such as Telegram/Signal/WhatsApp... I see these in my Mrs' photo stream quite a bit.

Also, I found issues with photos taken with those kinds of application. They will appear in the photo stream and also the 'Recently Deleted' bit at the same time. I've no idea why, I've just stopped using those apps to take photos. The container will download the picture, then delete it immediately... and continue doing that until it expires in 'Recently Deleted' after 30 days. Probably leaves an orphaned file behind too.

**Comment by joshuakohut77** [comment]
I tested this with a handful of files and it worked as expected for me!
The only other two oddities I've found are the "delete files" function only runs when a new file is downloaded which isn't ideal. The second is if you modify a file (crop, color, etc.), the python script doesn't check if the modified timestamp is newer than the local and therefore won't download the modified image. 
Neither of these things are the docker project problems and I'm not expecting fixes for either of these, I'm just mentioning things I've noticed in case anyone reading this notices them and finds this thread wondering the same thing.

Thanks for your hard work on this and a quick turnaround.

**Comment by boredazfcuk** [comment]
> The only other two oddities I've found are the "delete files" function only runs when a new file is downloaded which isn't ideal. 

I think this is just due to the way my script operates. I do a check prior to downloading files. If I detect files, then I kick off a download run. This is when it processes deleted items. If you set the `skip_check` variable to `True`, it will run the download script even if there are no files to download. It should then process the 'Recently Deleted' files on each run.

> The second is if you modify a file (crop, color, etc.), 

You can't actually modify photos on your phone/tablet. When you edit the photo, the device just creates a metadata file which contains the edit... IIRC this is a .AAE file. You can see them if you plug your device into a computer and browse the files on it directly. These aren't downloaded from iCloud by the Python script.

The same is true for 'portrait' photos. They're just regular photos with a filter applied. The photo downloaded from iCloud will be different to what you see on your phone. If you browse to the picture on your cable connected device, you'll see it has a paired .AAE file with it.
