### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by dansenxl** [boredazfcuk/docker-icloudpd#148]
it was running in the very begining, but error downloading after hours.
Log is attached. 
[icloud-dansenxl.csv](https://github.com/boredazfcuk/docker-icloudpd/files/8311527/icloud-dansenxl.csv)

**Comment by seanhong11** [comment]
same problem~~

**Comment by seanhong11** [comment]
did anyone solve the problem?

**Comment by boredazfcuk** [comment]
You have a fair few files there... I've noticed that some people, who have large libraries, benefit from setting the variable: `skip_check=True`

Can you try that an let me know?

**Comment by boredazfcuk** [comment]
I'm going to close this off as it seems abandoned. Just update the issue and I'll reopen it if it's not been resolved.

**Comment by seeyabye** [comment]
Still an issue even with `skip_check=True` set.
