### ISSUE TITLE
works at first day,then error ocurs

### ISSUE THREAD

**Issue by seanhong11** [boredazfcuk/docker-icloudpd#149]
[icloudpd-sean.csv](https://github.com/boredazfcuk/docker-icloudpd/files/8317804/icloudpd-sean.csv)
please check the log~

**Comment by seanhong11** [comment]
![截屏2022-03-22 上午12 53 45](https://user-images.githubusercontent.com/102058449/159326637-bb40fcac-5f61-4c2f-ad5c-366307fc9914.png)

same problem on the other account

**Comment by boredazfcuk** [comment]
Hi,

This is saying that a timeout has occurred... Basically Apple has ignored your request. 

Can you post a full log from container start up, so that I can see what your variables are all set to?

Please remove all identifying infomation, such as Apple ID, e-mail and username.

Thanks.

**Comment by boredazfcuk** [comment]
I'm closing this as I've not had a response in over a fortnight. Just reply with the requested information and I'll reopen it, if needs be.
