### ISSUE TITLE
Only download once

### ISSUE THREAD

**Issue by rocksolidsr** [boredazfcuk/docker-icloudpd#153]
Is it possible to only download files once?  So I would like to grab the files from iCloud then import them into Photoprism but when the import happens it moves the files and then when the re-sync happens it redownloads all the same files again.

**Comment by rocksolidsr** [comment]
Looks like someone has implemented it:
https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/314

https://github.com/icloud-photos-downloader/icloud_photos_downloader/compare/master...mooreandrew:master

Is it possible to get this implemented in this docker?

**Comment by boredazfcuk** [comment]
Hi,

I'll look into it over the next few days. I'd have to re-base my image to the repo, but then I don't know how that will turn out. The original repo does seem to have died somewhat, so maybe the new branch is the future. I'd like to avoid it if possible though.

So I'll see if I can diff the modifications in the new repo and apply them to the original repo after I clone it.

Probably take a few days though. I've been super busy the past couple of months, so I've been ignoring issues logged here. All that has finished now though, so I should have extra spare time in the evenings to look at it.

Thanks.

**Comment by boredazfcuk** [comment]
Hi,

I've applied this patch to my container, but unfortunately it doesn't work correctly. It does something which affects how files are named and unfortunately that meant it attempted to duplicate my entre photo collection.

I'll not be able to implement such a breaking change to my container as it will affect a lot of people.. so unless a different patch is created which respects the original file names, I'll not be able to integrate it.

Sorry about that.

**Comment by rocksolidsr** [comment]
I understand that makes sense, thanks for trying!
