### ISSUE TITLE
Fixed Sync Time

### ISSUE THREAD

**Issue by Sawrz** [boredazfcuk/docker-icloudpd#154]
According to #91, you already implemented a method to sync the iCloud on a fixed schedule. However, it seems you removed the `synchronization_method` variable as in #94. Since there is no further documentation on that topic:

Is the feature still present, or did you remove it for some reason? Even if the time interval is a nice solution, it takes away some control I need. For example, several backup mechanisms occur at night, and I prefer an iCloud sync in the evening hours. However, I have to start the container at the given time to achieve that. Although it's achievable, it's cumbersome, and I have to do that each time I have to restart the container.  

Still grateful for your work =)

**Comment by boredazfcuk** [comment]
Hi,

I've added a new variable `single_pass` which will exit after a single synchronisation. Please see the README for details.

Using this variable will mean you can schedule the launch of the container using cron on the host machine.

Any issues, just let me know and I'll reopen the issue.

Thanks

**Comment by Sawrz** [comment]
Sounds good to me. By my understanding, the health checks will still work. Hence, the notification to reenter the Apple credentials will still work, right?
