### ISSUE TITLE
only downloading JPG while there's also a raw version 

### ISSUE THREAD

**Issue by flyingwasabi** [boredazfcuk/docker-icloudpd#156]
I have quite a few photos in my iCloud photo library that has both jpg and raw version.   the JPG and RAW show up as 1 picture, but 2 versions that you can choose which to use, and I believe iCloud defaults to JPG.

I notice that the icloudpd is only downloading the JPG version, and leaving the RAW as if its not there.   any way we can download both versions? or let us choose which version to download (RAW is always better for archiving).

thanks, great project!

**Comment by flyingwasabi** [comment]
there's actually a way to download RAW files from iCloud.com

for those photos with raw and jpg version, you can click the three dots on the upper right corner and choose more download options, and selecting 'unmodified originals' will give you a zip file containing both JPG and RAW files of the same photo.

I'm not an expert on coding, so I don't know if it is possible to be integrated into scripts.

**Comment by boredazfcuk** [comment]
How do you get RAW files into your icloud? I don't get that option when I select a singe/multiple files and download the unmodified originals. They are still downloaded as JPG files.

I'm not a coder either. I'm a sysadmin so my experience is all bash/batch/PowerShell/VBscript... The underlying Python script, which may have been able to automate downloading RAW files, is maintained by a couple of guys have been quiet for a fair few months. I think development has stalled in the application (even recent PRs have been ignored), so I'm not sure if it would be something they would have time to add.

**Comment by flyingwasabi** [comment]
when you shoot RAW+jpg on your DSLRs and import them into your photo library, either on Mac or iPad/iPhone, the pair will be recognized as one photo but two assets.   and both are uploaded into iCloud. 
on iPad/iPhone and Mac, the photo will have a JPEG+RAW tag on the upper left hand.

this article should give you some idea
[https://appleinsider.com/articles/21/02/23/how-to-use-raw-images-with-photos-app-on-the-mac]

**Comment by boredazfcuk** [comment]
I've raised an issue with the creators of the underlying application, requesting the addition of this feature.

Unfortunately, the guys over there have been fairly quiet recently, but hopefully they will be able to find some time to get it moving again.

**Comment by flyingwasabi** [comment]
I think I'm onto something. I just SSH'ed into the Synology and ran this command 
[sudo /var/packages/SynologyPhotos/target/usr/bin/synofoto-bin-index-tool -t reindex -i /volume1/homes/xxx/Photos] and the photos app started to re-index. 

so is there any way to incorporate this command into the docker? so that every time after it downloads some photo, it just run this command?

**Comment by boredazfcuk** [comment]
Looks like this was added at some point: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/662 so it should work in my container.

Will close as presume working.
