### ISSUE TITLE
Feature request - Webhooks

### ISSUE THREAD

**Issue by eldudemeister** [boredazfcuk/docker-icloudpd#16]
Hi, is it possible/doable to have webhooks as a notification service or notification to an mqtt broker? Loving the container!

**Comment by boredazfcuk** [comment]
Probably, the Discord webhook has this curl command : https://birdie0.github.io/discord-webhooks-guide/tools/curl.html and an example:
```
url='https://discordapp.com/api/webhooks/"203019812404264973/rptBmYgoehu70kw2rItSlhRqKi7kMJh1bM2KCUUD2vR6grZckvtdl62h4xR7XWUS5463'
curl -H "Content-Type: application/json" \
-X POST \
-d '{"username": "test", "content": "hello"}' $url
```
which is pretty similar to to my Telegram command:
```
curl --silent --request POST "${notification_url}" \
         --data chat_id="${telegram_chat_id}" \
         --data parse_mode="markdown" \
         --data text="${2}"
```

My Webhooks one would probably look like:
```
notification_url='https://discordapp.com/api/webhooks/"203019812404264973/rptBmYgoehu70kw2rItSlhRqKi7kMJh1bM2KCUUD2vR6grZckvtdl62h4xR7XWUS5463'

curl --silent --request POST "${notification_url}" \
         --data username="${webhook_username}" \
         --data content="${2}"
```

I don't have a webhooks notification system I can test with though... To be honest, I don't even know if the PushBullet notification method works coz I don't have that either, but it looks like it should as the API is pretty much the same. What webhooks service in particular are you using?

**Comment by eldudemeister** [comment]
I'm using Home Assistant as a notifier service that would generate the webhook which would then send a notification to my phone depending on the message json payload passed from icloud-pd. 
If it helps, I think i used the pushbullet notification previously and pretty sure it was working good!

**Comment by boredazfcuk** [comment]
Hi,
I've just pushed a new version that has untested Webhook support. It probably won't work as I'm unsure of the format of the data that I should be sending.

I've found this [link](https://community.home-assistant.io/t/forward-webhook-with-automation-help/187929) which suggests it should be formatted as:
```
curl --request POST \
  --url http://HomeAsisstant:8123/api/webhook/MyWebhookID\
  --header 'content-type: application/json' \
  --data '{
	"data":"Forwarded"
}'
```
So I've just imitated this, but changed "Forwarded" to the message I send via Telegram.

Give it a test and let me know what you find.

**Comment by eldudemeister** [comment]
Thanks so much for this, I've pulled the new image and updated my compose, just a couple of questions, should the host ip address be the full ```http://HomeAsisstant:8123/api/webhook/MyWebhookID``` or just the host ip and the port as I specify the webhook id separately.

**Comment by boredazfcuk** [comment]
Host IP is just the IP address, nothing else... You could put the hostname of the computer in it if you like... in fact, I’ll rename that variable to webhook_server in the next push, I’ll sort that tonight.

I combine the webhook_https, host_ip_address and webhook_id variable to generate the server’s URL.

**Comment by boredazfcuk** [comment]
I've pushed this to Dockerhub now. The variables it uses for the webhooks URL are now:
```
webhook_server
webhook_port
webhook_id
webhook_https
```

It puts them all together to generate the notification URL like this:
```
notification_url="${webhook_scheme}://${webhook_server}:${webhook_port}/api/webhook/${webhook_id}"
```

Let me know how you get on and I'll either update again, or close the issue.

Thanks.

**Comment by eldudemeister** [comment]
I've pulled the latest image but I get the following in the logs
```020-05-28 14:28:56 WARNING  Webhook notifications enabled, but API key/token not set - disabling notifications```
My compose looks like this? 
     - notification_type=Webhook
     - notification_days=14
     - webhook_server=192.168.68.110
     - webhook_port=8123
     - webhook_id=VCyx4YOljF0apiIEK3Gu7ssWj9hSDT9T
     - webhook_https=false
     - synchronisation_interval=43200
```
Have I gone wrong somewhere?

**Comment by boredazfcuk** [comment]
My mistake. There was an additional check when configuring notifications that I had missed. I've updated and pushed to Dockerhub again.

**Comment by eldudemeister** [comment]
That worked! Thanks so much again, the message is being passed to home assistant so now I just need to configure the payload in my notification on my phone

**Comment by boredazfcuk** [comment]
No worries. I use some emoji characters in it which may not be translated well on the receiving system.

If you need me to amend the message, then just reply back here.

**Comment by eldudemeister** [comment]
That would be amazing if you could, this character ↵ is causing some issues?

**Comment by eldudemeister** [comment]
and the backslashes and carriage return?

**Comment by boredazfcuk** [comment]
I've removed those all. That's going to make the downloaded/deleted files previews look a little weird. Let me know if you need those removing too.
