### ISSUE TITLE
【Solved】Synology Moments can NOT show photos after completed rebuild Index

### ISSUE THREAD

**Issue by Howardnm** [boredazfcuk/docker-icloudpd#165]
### This way can solve the problem
- You can edit the number of scanning days
- I believe you can run it successfully

![image](https://user-images.githubusercontent.com/55622355/171091397-a45879f5-a6aa-4d00-ae32-d67eb8a7da3c.png)

- **Scheduled Tasks，user: root**
```sh
sh /volume1/web/icloudpd.sh
```

- **icloudpd.sh  (update: 2022-06-01)**
```sh
#!/bin/bash

# Author: Howardnm

# #####-----------#####-----------#####-----------#####-----------#####-----------#####
# config
down_directory="/volume1/homes/howard/Drive/Moments/icloud" # Photo download directory (照片下载目录)

Script_cache_file="/volume1/web" # Script cache file storage (脚本缓存文件存放区)

days=2 # check files from the last 2 days (扫描前2天的照片)

synophoto_index_tool="/var/packages/SynologyMoments/target/usr/bin/synophoto-bin-index-tool" # DSM 6.2 moments tool
#synophoto_index_tool="/var/packages/SynologyPhotos/target/usr/bin/synofoto-bin-index-tool" # mybe DSM 7.0 ? (i don't know)

# #####-----------#####-----------#####-----------#####-----------#####-----------#####






# execution area

search_file(){
    find ${down_directory} -mtime -${days} -name '*.*' > ${Script_cache_file}/log.txt
    sleep 2s
    sed '/@eaDir/d' ${Script_cache_file}/log.txt > ${Script_cache_file}/log_update.txt
    sleep 2s
    num_files=$(cat ${Script_cache_file}/log_update.txt | wc -l)
    echo "[Find ${num_files} files from the last ${days} days]"
}

search_file

file=1
while(( $file<=$num_files ))
do
    file_path=$(sed -n "${file}p" ${Script_cache_file}/log_update.txt)
    echo "[$file]$file_path"
    ${synophoto_index_tool} -t basic_reindex -i ${file_path}
    sleep 1s
    let "file++"
done

echo "[------Finish------]"
```

- **successful !**
![未标题-1](https://user-images.githubusercontent.com/55622355/171097601-014fbd7b-1847-4203-8766-601100a54527.jpg)

**Comment by 404gods** [comment]
我就用中文说了啊，非常感谢，正在遇到这个麻烦，请问兄弟2个问题：
1，还需要添加synology_photos_app_fix这个变量吗？这个变量是不是没起到作用？
2，directory_1/2/3是不是只留一个就行了？我的变量里只设置了folder_structure:{:%Y} 多谢啦

**Comment by Howardnm** [comment]
@404gods 
1、my docker: --env synology_photos_app_fix=True; But this variable doesn't work
2、sure !
you can
```sh
directory_1=$(date -d "${today} days ago" +%Y)    # @1 [%Y] = 2022
directory_structure=${directory_1}    # @3 your docker: --env folder_structure={:%Y}
```

**Comment by Alano-i** [comment]
@Howardnm 
`This script is awesome, thanks!`

**Comment by 404gods** [comment]
> @404gods 1、my docker: --env synology_photos_app_fix=True; But this variable doesn't work 2、sure ! you can
> 
> ```shell
> # config
> days=0  # Because yesterday was also 2022, no need to scan the same directory multiple times a day
>         # days=0 (It means scan today only)
> directory_1=$(date -d "${today} days ago" +%Y)    # @1 [%Y] = 2022
> directory_structure=${directory_1}    # @3 your docker: --env folder_structure={:%Y}
> ```
> 
> **But I suggest your directory name contains `%d`** **I recommend you to use my directory structure！Save more CPU performance.**

十分感谢，如果包含 %d，我觉得一天一个文件夹实在太多了，我想把变量设置为{:%Y/%m}，这样在年度文件夹下面每月一个文件夹还能接受，当然最方便还是一年一个文件夹。
请问如果这样的话，脚本该如何设置才能运行的时候只索引短期内的照片呢，多谢啦

**Comment by Howardnm** [comment]
@404gods 
这个脚本是搜索最近日期的文件夹名称，然后扫描该文件夹里面的所有内容，激活moments工具，生成缩略图。如果只设置%Y，也就是一个文件夹存放一年的照片，扫描的时候，由于过量的照片，导致cpu长时间高负载。
最近在探索怎样实现扫描最近新建的图片，而不是整个文件夹扫描。

**Comment by boredazfcuk** [comment]
Hi,

I've closed this as it's marked as [Solved].

Thanks.

**Comment by daya0576** [comment]
FYI

Reindex command in DSM 7.1-42661:
```shell
/var/packages/SynologyPhotos/target/usr/bin/synofoto-bin-index-tool -i ${down_directory} -t basic_reindex
```

**Comment by jinnxu75** [comment]
> @404gods 我已经解决这个的问题了，现在的脚本只索引短期内的照片，重新复制上面的`icloudpd.sh`吧！

太棒了，搜索了几天，好像只有你这个办法好使啊

**Comment by jinnxu75** [comment]
# mybe DSM 7.0 ? (i don't know)
it works for DSM 7.2, the question mark can be confirmed.
这个注释可以把问号去掉了，我在7.2里面试过了，是对的，FYI
@404gods

**Comment by jinnxu75** [comment]
@Howardnm 大佬，这个方法很好。不过我后来发现，这个索引真的是完全忽视容器的操作啊。

用这个办法把PhotoIndex搞定了。但是文件的索引还是没有刷新，比如CloudSync就不会被激活。用手机Photo应用同步的安卓照片就没问题，用容器下载的iCloud照片就不会被自动同步到CloudSync里面去。

我现在用的办法是直接每个月操作一次，改一下目录名，就重建这个目录的索引了。有没有什么比较好的命令，能够一次把所有地方的文件索引都重建呢？

Thanks again.

**Comment by Howardnm** [comment]
你是指一次扫描多个文件夹吗？（即多个down_directory？）你可以新建多个计划任务，多脚本运行也是可以的。
如果你是指扫描一个文件夹内的所有照片，你可以把扫描天数（即days）改成几千，就相当于无限了，这样就不会把超出天数范围的照片筛选掉，就可以扫描完文件内所有的照片了

**Comment by Howardnm** [comment]
@jinnxu75 
你是指一次扫描多个文件夹吗？（即多个down_directory？）你可以新建多个计划任务，多脚本运行也是可以的。
如果你是指扫描一个文件夹内的所有照片，你可以把扫描天数（即days）改成几千，就相当于无限了，这样就不会把超出天数范围的照片筛选掉，就可以扫描完文件内所有的照片了。

**Comment by yizhitangtongxue** [comment]
修改search_file函数，屏蔽.mounted文件
```shell
search_file(){
    find ${down_directory} -mtime -${days} -name '*.*' > ${Script_cache_file}/log.txt
    sleep 2s
    sed '/@eaDir/d' ${Script_cache_file}/log.txt > ${Script_cache_file}/log_update.txt
    # Add the following line to exclude .mounted files
    sed -i '/\.mounted/d' ${Script_cache_file}/log_update.txt
    sleep 2s
    num_files=$(cat ${Script_cache_file}/log_update.txt | wc -l)
    echo "[Find ${num_files} files from the last ${days} days]"
}
```

避免出现如下报错
```shell
terminate called after throwing an instance of 'synophoto::Exception<(synophoto::ExceptionTag)5>'
what():  /source/synofoto/src/lib/index/path_info.cpp:107 path in invalid dir: /volume1/homes/xxx/Photos/iCloud/.mounted
icloudpd-xxx-reindex.sh: line 41: 24809 Aborted                 (core dumped) ${synophoto_index_tool} -t basic_reindex -i ${file_path                                         }
```

**Comment by handsomebin666** [comment]
Synology photos也能用这个方法吗？

**Comment by handsomebin666** [comment]
<img width="1707" alt="截屏2023-10-19 11 44 19" src="https://github.com/boredazfcuk/docker-icloudpd/assets/105508181/dc4ef07d-985a-499a-9d03-507ffaa0fd56">
复制代码后只修改了图片下载目录，没成功，小白求助！7.1的系统

**Comment by Howardnm** [comment]
@handsomebin666 你要把代码保存成sh文件，在计划任务运行该文件，7.1系统要修改代码config区域的路径

**Comment by handsomebin666** [comment]
> @handsomebin666 你要把代码保存成sh文件，在计划任务运行该文件，7.1系统要修改代码config区域的路径
感谢大佬指点。但还是出现报错，再次请教处理方法
[Find 27 files from the last 2 days]
[1]/volume2/homes/mrbin/Photos/iCloud/2023/10/.DS_Store
/volume2/homes/mrbin/icloudpd.sh: line 41: /var/packages/SynologyMoments/target/usr/bin/synophoto-bin-index-tool: No such file or directory

find: `/volume2/homes/mrbin/Photos/iCloud/2023/09/17/@eaDir': Permission denied
<img width="1961" alt="截屏2023-10-21 23 55 05" src="https://github.com/boredazfcuk/docker-icloudpd/assets/105508181/41d3ab6d-740b-4b05-8a47-5c43b73e6913">

**Comment by ljw89** [comment]
[Find 10782 files from the last 7300 days]
[1]/volume1/homes/wen/Photos/iCloud_Photos/.mounted
terminate called after throwing an instance of 'synophoto::Exception&lt;(synophoto::ExceptionTag)5&gt;'
  what():  /source/synofoto/src/lib/index/path_info.cpp:107 path in invalid dir: /volume1/homes/wen/Photos/iCloud_Photos/.mounted
/volume1/docker/icloudpd/icloudpd.sh: line 44: 24658 Aborted                 (core dumped) ${synophoto_index_tool} -t basic_reindex -i ${file_path}

自动执行脚本后,显示以上错误

**Comment by wanglewis** [comment]
Just as a tipps for others, The script running as sh file works not in schedule(DSM 7.2). So I write the script direkt into the Schedule,  replacing the parameter definition with direct folder information, and it worked.

**Comment by atcodrinky** [comment]
> Just as a tipps for others, The script running as sh file works not in schedule(DSM 7.2). So I write the script direkt into the Schedule, replacing the parameter definition with direct folder information, and it worked.

Can you please provide a screenshot on how your set that up? I'm not that into programming and don't know how to set and write the code on Task Scheduler.
Thanks

**Comment by jiawen1929** [comment]
> [查找过去 7300 天的 10782 个文件] [1]/volume1/homes/wen/Photos/iCloud_Photos/.mounted 在抛出 'synophoto::Exception<(synophoto::ExceptionTag)5>' 实例后终止调用 什么( ）：/source/synofoto/src/lib/index/path_info.cpp:107 无效目录中的路径：/volume1/homes/wen/Photos/iCloud_Photos/.mounted /volume1/docker/icloudpd/icloudpd.sh：第 44 行： 24658 已中止（核心已转储）${synophoto_index_tool} -t basic_reindex -i ${file_path}
> 
> 自动执行脚本后，显示以上错误

一样

**Comment by jinnxu75** [comment]
> @jinnxu75 你是指一次扫描多个文件夹吗？（即多个down_directory？）你可以新建多个计划任务，多脚本运行也是可以的。 如果你是指扫描一个文件夹内的所有照片，你可以把扫描天数（即days）改成几千，就相当于无限了，这样就不会把超出天数范围的照片筛选掉，就可以扫描完文件内所有的照片了。

我说的是这个脚本可以解决Synology Photos的索引问题，可以被群晖照片正常看到。但是实际上跟群晖自己通过Synology Drive或者Photos上传的文件还是有区别，其他的一些应用还是看不到这个文件，比如CloudSync（我设置了把照片加密备份到百度云上）就没法被触发（正常有新文件了，CloudSync会自动备份）

**Comment by FFatTiger** [comment]
> 用这个办法把PhotoIndex搞定了。但是文件的索引还是没有刷新，比如CloudSync就不会被激活。用手机Photo应用同步的安卓照片就没问题，用容器下载的iCloud照片就不会被自动同步到CloudSync里面去。

我也发现了，用pd同步下来的照片没法触发cloudsync，必须手动重新触发一下文件夹

**Comment by ni7ht** [comment]
thx.

**Comment by xiaojianqaq** [comment]
但是通过这种方法出来的缩略图怎么实况的视频和照片是分开来的呢，需要怎么修改一下呢

<img width="341" height="230" alt="Image" src="https://github.com/user-attachments/assets/7f6b15b0-1b7b-4114-9034-b11c686088fe" />

**Comment by HyperBen** [comment]
> 但是通过这种方法出来的缩略图怎么实况的视频和照片是分开来的呢，需要怎么修改一下呢
> 
> <img alt="Image" width="341" height="230" src="https://private-user-images.githubusercontent.com/46419880/482232983-7f6b15b0-1b7b-4114-9034-b11c686088fe.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg0MzIyNTEsIm5iZiI6MTc1ODQzMTk1MSwicGF0aCI6Ii80NjQxOTg4MC80ODIyMzI5ODMtN2Y2YjE1YjAtMWI3Yi00MTE0LTkwMzQtYjExYzY4NjA4OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTIxVDA1MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYzI4YTMzN2JlNWU1NjJhNWVlOTgzYjA0NzIyNDBjMzlkOGFiMjRjNDk2NzNmMWMzMGE5MzNhYjMxNjhjMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ms4sVK94NX6H1NwgLCz3ttEduxCcUpQW3q7sKpyDeas">

加一个变量
live_photo_mov_filename_polciy
值为original

**Comment by xiaojianqaq** [comment]
> > 但是通过这种方法出来的缩略图怎么实况的视频和照片是分开来的呢，需要怎么修改一下呢
> > <img alt="Image" width="341" height="230" src="https://private-user-images.githubusercontent.com/46419880/482232983-7f6b15b0-1b7b-4114-9034-b11c686088fe.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg0MzIyNTEsIm5iZiI6MTc1ODQzMTk1MSwicGF0aCI6Ii80NjQxOTg4MC80ODIyMzI5ODMtN2Y2YjE1YjAtMWI3Yi00MTE0LTkwMzQtYjExYzY4NjA4OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTIxVDA1MTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYzI4YTMzN2JlNWU1NjJhNWVlOTgzYjA0NzIyNDBjMzlkOGFiMjRjNDk2NzNmMWMzMGE5MzNhYjMxNjhjMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ms4sVK94NX6H1NwgLCz3ttEduxCcUpQW3q7sKpyDeas">
> 
> 加一个变量 live_photo_mov_filename_polciy 值为original

谢谢，但是这个变量加上之后还是分开的，已经打算放弃了，可能是遇上系统bug了可能，以前都是好的能正常显示live

<img width="1505" height="419" alt="Image" src="https://github.com/user-attachments/assets/69f1d540-7c1d-4dea-a303-3b79d8cf0db3" />

<img width="518" height="369" alt="Image" src="https://github.com/user-attachments/assets/f24e23b5-1fbc-487e-979b-a75d8f9a7297" />

**Comment by xu75** [comment]
> > 用这个办法把PhotoIndex搞定了。但是文件的索引还是没有刷新，比如CloudSync就不会被激活。用手机Photo应用同步的安卓照片就没问题，用容器下载的iCloud照片就不会被自动同步到CloudSync里面去。
> 
> 我也发现了，用pd同步下来的照片没法触发cloudsync，必须手动重新触发一下文件夹

我觉得应该有什么Driver的命令，直接把文件的index搞定的。或者是不是在脚本里面把文件夹改一下名字？反正touch是不行的。希望有哪个大哥研究一下，也做个脚本把这个遗憾给填补掉啊
