### ISSUE TITLE
Script stuck at "generating list of files..."

### ISSUE THREAD

**Issue by softtrymee** [boredazfcuk/docker-icloudpd#168]
Hi there,

Love your script! I've been using it for a month now with my Synology NAS and absolutely love it! However I ran into this weird issue yesterday (and a week ago) and hope that you might know the fix to it: after running flawlessly for 6 days, all of sudden it got stuck at "generating list of files...".

<img width="1209" alt="Screen Shot 2022-06-06 at 10 26 36 AM" src="https://user-images.githubusercontent.com/35638008/172213757-0cd7bee5-14cc-490e-b5db-1dd30fe60775.png">

and I doubt that it will ever unstuck itself, because the CPU usage of the container is 0%, meaning that it's not actually anything. The same issue happened a week ago, also after the container was started for several days. Restarting the container is one way to "fix" it, but that defeats the purpose of having an automated script. I tried digging into the script myself but due to my limited shell script knowledge I couldn't seem to find out the root cause. 

Your help will be greatly appreciated!

**Comment by boredazfcuk** [comment]
Hi,

Try setting `skip_check=True` I see this error quite a bit when people have large photo libraries.

Thanks.

**Comment by boredazfcuk** [comment]
I'll take it that no news is good news and that your issue is now resolved...
