### ISSUE TITLE
Cannot find keyring file when user is root

### ISSUE THREAD

**Issue by FrankHdf** [boredazfcuk/docker-icloudpd#175]
Hello,
when the user is root the symbolic link to the keyring directory is created in /home/root/.local/share/ (line 187 in sync-icloud.sh)
But if user is root it should be created in /root/.local/share/
Would it be possible to create the symbolic link in the correct directory also for user root?
Thanks
Frank

**Comment by boredazfcuk** [comment]
Hi,

You shouldn't really be running your container as root, I've no idea what other issues you may run into.

But, can you confirm if creating this link makes the container work as intended? If it does, then I'll add it, but I'm sure that there are many other parts of the container that have `/home/` hardcoded when looking for things.

Thanks.

**Comment by boredazfcuk** [comment]
Hi,

I changed some stuff in an attempt to get this to work, but it broke a load of stuff for unRAID users. I'm not going to look into this any more as the container should really run as a non-root user for security purposes.

Thanks.
