### ISSUE TITLE
typing password impossible in QNAP

### ISSUE THREAD

**Issue by 1977wim** [boredazfcuk/docker-icloudpd#176]
Hello there and thank you for your hard work on this matter.
I'm trying to get things set up but encounter an error I cannot seem to overcome.
When using the command "icloudpd sync-icloud.sh --Initialise" I get to the part where I have to enter my password. 

2022-07-01 18:34:45 INFO     Configure password
2022-07-01 18:34:45 INFO     Adding password to keyring file: /config/python_keyring/keyring_pass.cfg
Enter iCloud password for daantje1979@msn.com: 

However, the keystrokes do not have any effect, nothing happens.
What am I doing wrong here?
Or else, is there a possibility to create the keyring file by hand? And if so, what would the file look like?
Many thanks
Wim
![error](https://user-images.githubusercontent.com/108549132/176953510-0eeffd7d-13f3-4c30-be92-f9249833043b.JPG)

**Comment by FadingArabChristians** [comment]
I believe the keystrokes are being registered its just being hidden for security purposes. Just slowly make sure you enter the right password and hit enter and it should work.

Hope that helps!

**Comment by 1977wim** [comment]
The issue has been solved. I didn't have any input device switched on in the settings.
Furthermore you were right FadingArabChristians: you don't see any characters being typed. Thanks.
On to the next step in this journey...

**Comment by boredazfcuk** [comment]
Glad you got it working.
