### ISSUE TITLE
does not allow capitals in username

### ISSUE THREAD

**Issue by markuswells** [boredazfcuk/docker-icloudpd#182]
I have a host system that users capitals in the username (I know its bad, but...) it apears alpine does allow for _useradd --badnames_. is there a way I can get the docker-compose to allow for 'badnames' ?

**Comment by boredazfcuk** [comment]
Hi,

I've changed the script to allow this and pushed an updated container to Dockerhub. Update to the latest version and let me know.

Thanks.

**Comment by markuswells** [comment]
That worked perfectly, I am able to create the accounts with Capital letter.
thanks

**Comment by boredazfcuk** [comment]
Great. Thanks for letting me know.

**Comment by markuswells** [comment]
Hi, Thanks again for this script.
I am still having issues. The script seems to initialize fine. I even get the message saying something like "syncing should be happening". I DO see the python keyring stuff. I DO get the 2FA propts on the phone and it all seems to work fine.
Just not downloading any files.I am able to connect to the Docker but I am not finding any logs, if you tell me where they are, I might be able to debug this more.
ThanksMarkus

    On Saturday, July 16, 2022, 7:57:55 AM EDT, boredazfcuk ***@***.***> wrote:  
 
 


Closed #182 as completed.

**Comment by boredazfcuk** [comment]
Hi,

The script has fairly informative log files which are output to the console. If you connect to docker, then run sync-icloud.sh manually, it will log to screen.

Container logs for what your current container is doing will live in: `/var/lib/docker/containers/<container_id>`
