### ISSUE TITLE
Warnings on Synology server when working with the Photos app

### ISSUE THREAD

**Issue by ericdum** [boredazfcuk/docker-icloudpd#184]
I'm running boredazfcuk-icloudpd1 on the docker on Synology server.
After sync photos to the server, the Photos app will index it and create @eaDir in every sub-folder automatically.
After that, when the program scanning the folder will occurs a lot of warning:
 `chgrp: connot dereference '/......./@eaDir/.....': No such file or directory`
So I suggest to give a parameter to avoid some of these folders for scanning and changing.

![image](https://user-images.githubusercontent.com/690825/179953974-29671691-d6fc-40d1-b1dd-29a3b7200f95.png)

**Comment by ericdum** [comment]
Awesome, I will check it now.

**Comment by boredazfcuk** [comment]
Excellent. Thanks for the update.

**Comment by Koramchad** [comment]
Have the same issue on Container Station in Qnap.

Here's some of the output when I run the container now:

`  chgrp: cannot dereference '/download/2021/01/03/.@__thumb/adefaultIMG_2491_HEVC.MOV': No such file or directory
                                                                                                                 chgrp: cannot dereference '/download/2021/01/03/.@__thumb/a100IMG_0427.MOV': No such file or directory
                                                                                                                                                                                                                       chgrp: cannot dereference '/download/2021/01/03/.@__thumb/a100IMG_2493_HEVC.MOV': No such file or directory
                                                                      chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_0708_HEVC.MOV': No such file or directory
                                                                                                                                                                                     chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3484_HEVC.MOV': No such file or directory
                                    chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3472_HEVC.MOV': No such file or directory
                                                                                                                                               chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100RingVideo_6924120183257747526.mp4': No such file or directory
              chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3471_HEVC.MOV': No such file or directory
                                                                                                                             chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_0710_HEVC.MOV': No such file or directory
                                                                                                                                                                                                                                            chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3475_HEVC.MOV': No such file or directory
                                                                                           chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3483_HEVC.MOV': No such file or directory
                                                                                                                                                                                                      chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3469_HEVC.MOV': No such file or directory
                                                         chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3480_HEVC.MOV': No such file or directory
                                                                                                                                                                        chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3479_HEVC.MOV': No such file or directory
                           chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3476_HEVC.MOV': No such file or directory
                                                                                                                                          chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultRingVideo_6924119916969775174.mp4': No such file or directory
             chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3470_HEVC.MOV': No such file or directory
                                                                                                                            chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3486_HEVC.MOV': No such file or directory
                                                                                                                                                                                                                                           chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100RingVideo_6924120453840687174.mp4': No such file or directory
                                                                                                          chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_0709_HEVC.MOV': No such file or directory
                                                                                                                                                                                                                         chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3485_HEVC.MOV': No such file or directory
                                                                        chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3473_HEVC.MOV': No such file or directory
                                                                                                                                                                                   chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3481_HEVC.MOV': No such file or directory
                                      chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_0712_HEVC.MOV': No such file or directory
                                                                                                                                                 chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3477_HEVC.MOV': No such file or directory
    chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3478_HEVC.MOV': No such file or directory
                                                                                                                   chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_0716.MOV': No such file or directory
                                                                                                                                                                                                                         chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_0716.MOV': No such file or directory
                                                                       chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3474_HEVC.MOV': No such file or directory
                                                                                                                                                                                  chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3482_HEVC.MOV': No such file or directory
                                 chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3477_HEVC.MOV': No such file or directory
                                                                                                                                            chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3478_HEVC.MOV': No such file or directory
                                                                                                                                                                                                                                                       chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_0712_HEVC.MOV': No such file or directory
                                                                                                          chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3481_HEVC.MOV': No such file or directory
                                                                                                                                                                                                                     chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3482_HEVC.MOV': No such file or directory
                                                                        chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3474_HEVC.MOV': No such file or directory
                                                                                                                                                                                       chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3486_HEVC.MOV': No such file or directory
                                      chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultRingVideo_6924120183257747526.mp4': No such file or directory
                                                                                                                                                                     chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3488.MOV': No such file or directory
                   chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3470_HEVC.MOV': No such file or directory
                                                                                                                              chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3488.MOV': No such file or directory
                                                                                                                                                                                                                                    chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3473_HEVC.MOV': No such file or directory
                                                                                       chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3485_HEVC.MOV': No such file or directory
                                                                                                                                                                                                      chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_0709_HEVC.MOV': No such file or directory
                                                     chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3483_HEVC.MOV': No such file or directory
                                                                                                                                                                    chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3475_HEVC.MOV': No such file or directory
                       chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_0710_HEVC.MOV': No such file or directory
                                                                                                                                  chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3479_HEVC.MOV': No such file or directory
                                                                                                                                                                                                                                             chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3476_HEVC.MOV': No such file or directory
                                                                                            chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3469_HEVC.MOV': No such file or directory
                                                                                                                                                                                                       chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3480_HEVC.MOV': No such file or directory
                                                      chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultRingVideo_6924120453840687174.mp4': No such file or directory
                                                                                                                                                                                     chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3472_HEVC.MOV': No such file or directory
                                        chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3484_HEVC.MOV': No such file or directory
                                                                                                                                                       chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_0708_HEVC.MOV': No such file or directory
      chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100RingVideo_6924119916969775174.mp4': No such file or directory
                                                                                                                                 chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3471_HEVC.MOV': No such file or directory
                                                                                                                                                                                                                                            chgrp: cannot dereference '/download/2021/01/31/.@__thumb/adefaultIMG_3487.MOV': No such file or directory
                                                                                          chgrp: cannot dereference '/download/2021/01/31/.@__thumb/a100IMG_3487.MOV': No such file or directory
                                                                                                                                                                                                chgrp: cannot dereference '/download/2021/01/10/.@__thumb/adefaultIMG_2673_HEVC.MOV': No such file or directory
                                                   chgrp: cannot dereference '/download/2021/01/10/.@__thumb/a100IMG_0509.MOV': No such file or directory
                                                                                                                                                         chgrp: cannot dereference '/download/2021/01/10/.@__thumb/a100IMG_2688_HEVC.MOV': No such file or directory
        chgrp: cannot dereference '/download/2021/01/10/.@__thumb/adefaultIMG_0506.MOV': No such file or directory
                                                                                                                  chgrp: cannot dereference '/download/2021/01/10/.@__thumb/a100IMG_2671_HEVC.MOV': No such file or directory
                                                                                                                                                                                                                             chgrp: cannot dereference '/download/2021/01/10/.@__thumb/adefaultIMG_2674_HEVC.MOV': No such file or directory
                                                                                chgrp: cannot dereference '/download/2021/01/10/.@__thumb/adefaultIMG_0510.MOV': No such file or directory
                                                                                                                                                                                          chgrp: cannot dereference '/download/2021/01/10/.@__thumb/adefaultIMG_2687.MOV': No such file or directory
                                        chgrp: cannot dereference '/download/2021/01/10/.@__thumb/adefaultIMG_2682_HEVC.MOV': No such file or directory`

I've checked and there are indeed a lot of symlinks in each of those folders:

`[Koramchad@CroganMedia photoprism]$ cd /share/Photos/iCloud/2014/06/05
[Koramchad@CroganMedia 05]$ ls
IMG_4017.JPG  IMG_5509.JPG  IMG_5512.JPG  IMG_5515.JPG	IMG_5518.JPG  IMG_5521.JPG  IMG_5524.JPG  IMG_5527.JPG	IMG_5530.JPG  IMG_5533.JPG  IMG_5536.MOV  IMG_5539.MOV
IMG_5507.MOV  IMG_5510.JPG  IMG_5513.JPG  IMG_5516.JPG	IMG_5519.JPG  IMG_5522.JPG  IMG_5525.JPG  IMG_5528.JPG	IMG_5531.JPG  IMG_5534.JPG  IMG_5537.MOV  IMG_5560.JPG
IMG_5508.MOV  IMG_5511.JPG  IMG_5514.MOV  IMG_5517.JPG	IMG_5520.JPG  IMG_5523.JPG  IMG_5526.JPG  IMG_5529.JPG	IMG_5532.JPG  IMG_5535.JPG  IMG_5538.MOV
[Koramchad@CroganMedia 05]$ find . -type l 
./.@__thumb/adefaultIMG_5539.MOV
./.@__thumb/a100IMG_5514.MOV
./.@__thumb/adefaultIMG_5537.MOV
./.@__thumb/a100IMG_5537.MOV
./.@__thumb/adefaultIMG_5514.MOV
./.@__thumb/a100IMG_5539.MOV
./.@__thumb/adefaultIMG_5536.MOV
./.@__thumb/adefaultIMG_5538.MOV
./.@__thumb/a100IMG_5538.MOV
./.@__thumb/a100IMG_5536.MOV
./.@__thumb/a100IMG_5507.MOV
./.@__thumb/adefaultIMG_5507.MOV
./.@__thumb/a100IMG_5508.MOV
./.@__thumb/adefaultIMG_5508.MOV
[Koramchad@CroganMedia 05]$ `

Any idea how to skip that or ignore the symlinks?

Thanks!

**Comment by boredazfcuk** [comment]
Container already skips symlinks when is runs the `chgrp` command on the download directory:
```
   LogInfo "Set group, ${group}, on iCloud directory, if required"
   find "${download_path}" ! -type l ! -group "${group}" -exec chgrp "${group}" {} +
```
...the `! -type l` means ignore links.

Are you using an out of date container?

Also, can you post a few lines before these errors start occurring so I can see exactly which bit is generating them, so I can be doubly sure... just in case it's following a link elsewhere and ending up in your downloads folder.
