### ISSUE TITLE
WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues

### ISSUE THREAD

**Issue by ericdum** [boredazfcuk/docker-icloudpd#185]
I just notice this warning and I downloading everythings ok.
`2022-07-20 15:26:50 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues`

**Comment by boredazfcuk** [comment]
Hi, 

Yes, you will get that if `icloud_china=True`. When I implemented the code to use icloud.com.cn, I had no way of testing it, as I do not have a Chinese Apple ID.

I also have no way of investigating future issues, or testing potential fixes. Having this warning makes sure that if future problems do arise, people log the ticket here correctly. A lot of people were logging issues at a related project's page, so I would not get to see them and the other guys wouldn't investigate them either.

You are safe to ignore this, as it is only a warning.
