### ISSUE TITLE
Setting synology_photos_app_fix doesn't index new files

### ISSUE THREAD

**Issue by np-22** [boredazfcuk/docker-icloudpd#187]
I set synology_photos_app_fix to True but new photos are not auto indexed by Synology photos.

**Comment by boredazfcuk** [comment]
Hi,

Please see this thread for further details: https://github.com/boredazfcuk/docker-icloudpd/issues/165

I'm not sure what else they needed to do to get it working, and I don't have a Synology device for me to test and document the process myself, but that thread should point you in the right direction.

Thanks,

James.

**Comment by boredazfcuk** [comment]
Hi,

I'm going to assume that no news is good news and that this issue is now resolved.

Thanks.
