### ISSUE TITLE
iCloud Photo Library not finished indexing.

### ISSUE THREAD

**Issue by YunhaoJiang** [boredazfcuk/docker-icloudpd#188]
Hi,
I just followed the instruction and deployed the docker. However, it seems that there are some problems preventing me from downloading the photos.
The log shows
`iCloud Photo Library not finished indexing.  Please try again in a few minutes` 
`2022-07-26 15:37:42 ERROR    Failed check for new files files`
And the error debugging info is empty

**Comment by estepnv** [comment]
@YunhaoJiang hey what was the resolution?

**Comment by boredazfcuk** [comment]
Solution is to wait and try again. The larger the library, the longer it takes. It can take hours.
