### ISSUE TITLE
Setting file_permissions is not effective

### ISSUE THREAD

**Issue by Nadleeh1988** [boredazfcuk/docker-icloudpd#189]
Thank you for developing such a convenient program.
I set file_ Permissions is 777, but photo file permission is 640.

2022-07-28 11:05:07 INFO     Set 777 permissions on iCloud directories, if required
2022-07-28 11:05:08 INFO     Set 777 permissions on iCloud files, if required

![image](https://user-images.githubusercontent.com/59426415/181419731-7b2aee71-9cf3-473b-bc1d-2c5b615c5610.png)

**Comment by boredazfcuk** [comment]
Hi,

The function which corrects the permissions, runs just before the download. This means that permissions will be corrected on the next scheduled synchronisation.

However, this behaviour isn't ideal, so I now also run the permissions correcting function after files have been successfully downloaded.

I've pushed a new version to Dockerhub. Please pull the latest version of the container and check again.

Thanks.

**Comment by Nadleeh1988** [comment]
Thank you very much！
I use QNAP, and I also have index problems. But I found that changing the permissions of directories and files to 775 can solve the problem.

**Comment by boredazfcuk** [comment]
There have been people having indexing problem on Synology devices. Hopefully this change will help them too.

I'll close the issue. If you have any further requests, please let me know.

Thanks.
