### ISSUE TITLE
I found a solution for QNAP indexing

### ISSUE THREAD

**Issue by Nadleeh1988** [boredazfcuk/docker-icloudpd#190]
hello，boredazfcuk

I pull the latest version of the container  and set directory_permissions and file_ Permissions and is 777, photo file and directory  permission change 777.But the index doesn't work. However, I can trigger the index through SSH Chmod 777 -R directory.
So I set up a scheduled job（chmod 777 -R photo directory） in QNAP NAS to solve the index problem.
I don't have Synology NAS, so I suggest they try this

**Comment by boredazfcuk** [comment]
I believe that's similar to what they are doing. It seems like it's not possible for changes from within the container to trigger a re-index. They need to run scheduled tasks which run the re-index process for them.

Thanks for the info though. It may help others with QNAP devices.
