### ISSUE TITLE
Sync or One-way Download?

### ISSUE THREAD

**Issue by martijndierckx** [boredazfcuk/docker-icloudpd#193]
It's unclear to me what would happen if I sync my photos, and afterwards I delete a photo from my phone.
Will that photo also be deleted from my NAS? If so, is there a way to prevent this?

I want to backup my photos using this setup, so I can periodically delete a bunch of old photos to create some space on my iCloud drive.

**Comment by boredazfcuk** [comment]
^^What this guy said :)
