### ISSUE TITLE
example.env typo

### ISSUE THREAD

**Issue by Cpt-Proton** [boredazfcuk/docker-icloudpd#199]
[example.env](https://github.com/boredazfcuk/docker-icloudpd/blob/master/docker-compose/example.env) has a typo

`synchronisation_interval=`

Won't work whit an equal sign. Works with a colon instead.

`synchronisation_interval:`

**Comment by boredazfcuk** [comment]
The file you have linked doesn't have the typo in?

I've checked all the other versions of this file (there's only 4 of them) and none of those have the error either. Not sure where you're seeing this.

**Comment by Cpt-Proton** [comment]
I just realize it doesn't support synchronization interval under 6 hours anymore. That's why it wasn't work for me.  The .env file still has the template of the old interval values, that's what confused me.

**Comment by boredazfcuk** [comment]
Ah yeah, sorry. I need to update the docker-compose stuff. I don't like touching the .env files in case I accidentally do something which uploads my api tokens to the world lol
