### ISSUE TITLE
Doesn't work on Raspberry Pi 3 :/

### ISSUE THREAD

**Issue by ketz** [boredazfcuk/docker-icloudpd#2]
When trying to run this on raspbian I get the following error:

`standard_init_linux.go:178: exec user process caused "exec format error"`

Any idea why?

Thanks for getting this up and running

**Comment by boredazfcuk** [comment]
Sorry for the late reply, life got in the way....

The "exec format error" points to it an architecture issue. I run this on x86_x64 hardware whereas the Raspberry Pi 3 is ARMv8 based.

If you change the 1st line of the Dockerfile to:
```
FROM arm64v8/alpine:latest
```
It should build the container so it can run on your RPi3.

**Comment by ketz** [comment]
Thanks @boredazfcuk. That helped it start, but it gets stuck on step 4:

`sudo docker build -t boredazfuck ./
Sending build context to Docker daemon  117.4MB
Step 1/9 : FROM arm64v8/alpine:latest
 ---> 915beeae4675
Step 2/9 : MAINTAINER boredazfcuk
 ---> Using cache
 ---> 96bf29baf305
Step 3/9 : ENV CONFIGDIR "/config" REQUIREMENTS "python3 py-pip exiftool coreutils tzdata curl" BUILDDEPENDENCIES "git gcc python3-dev musl-dev libffi-dev openssl-dev" PYTHONDEPENDENCIES "docopt piexif click==6.0 certifi pytz tzlocal six chardet idna urllib3 requests future keyrings.alt==1.0 keyring==8.0 pyicloud-ipd tqdm schema python-dateutil" REPO "ndbroadbent/icloud_photos_downloader"
 ---> Using cache
 ---> b9f7fcc6260a
Step 4/9 : COPY sync-icloud.sh /usr/local/bin/sync-icloud.sh
lstat sync-icloud.sh: no such file or directory`

Any idea why?

**Comment by ketz** [comment]
Thanks @boredazfcuk. That helped get things going, but it's still not fully going through.

This is what I'm getting:

```
sudo docker build -t boredazfuck .
Sending build context to Docker daemon  15.36kB
Step 1/9 : FROM arm64v8/alpine:latest
 ---> 915beeae4675
Step 2/9 : MAINTAINER boredazfcuk
 ---> Using cache
 ---> 96bf29baf305
Step 3/9 : ENV CONFIGDIR "/config" REQUIREMENTS "python3 py-pip exiftool coreutils tzdata curl" BUILDDEPENDENCIES "git gcc python3-dev musl-dev libffi-dev openssl-dev" PYTHONDEPENDENCIES "docopt piexif click==6.0 certifi pytz tzlocal six chardet idna urllib3 requests future keyrings.alt==1.0 keyring==8.0 pyicloud-ipd tqdm schema python-dateutil" REPO "ndbroadbent/icloud_photos_downloader"
 ---> Using cache
 ---> b9f7fcc6260a
Step 4/9 : COPY sync-icloud.sh /usr/local/bin/sync-icloud.sh
 ---> 864410c4d6e1
Removing intermediate container 682250d83d36
Step 5/9 : COPY healthcheck.sh /usr/local/bin/healthcheck.sh
 ---> 83da9f008044
Removing intermediate container f1914feab3dc
Step 6/9 : RUN echo "$(date '+%d/%m/%Y - %H:%M:%S') | Install build dependencies" &&    apk add --no-cache --no-progress --virtual=build-deps ${BUILDDEPENDENCIES} && echo "$(date '+%d/%m/%Y - %H:%M:%S') | Install requirements" &&    apk add --no-progress --no-cache ${REQUIREMENTS} && echo "$(date '+%d/%m/%Y - %H:%M:%S') | Install Python dependencies" &&    pip3 install --upgrade pip  &&    pip3 install ${PYTHONDEPENDENCIES} && echo "$(date '+%d/%m/%Y - %H:%M:%S') | Install ${REPO}" &&    TEMP=$(mktemp -d) &&    git clone -b master "https://github.com/${REPO}.git" "${TEMP}" &&    cd "${TEMP}" &&    python3 setup.py install && echo "$(date '+%d/%m/%Y - %H:%M:%S') | Set permissions on startup script, clean up and exit" &&    chmod +x /usr/local/bin/sync-icloud.sh /usr/local/bin/healthcheck.sh &&    rm -r "${TEMP}" &&    apk del --no-progress --purge build-deps
 ---> Running in 38018c5bfcad
**standard_init_linux.go:178: exec user process caused "exec format error"**
The command '/bin/sh -c echo "$(date '+%d/%m/%Y - %H:%M:%S') | Install build dependencies" &&    apk add --no-cache --no-progress --virtual=build-deps ${BUILDDEPENDENCIES} && echo "$(date '+%d/%m/%Y - %H:%M:%S') | Install requirements" &&    apk add --no-progress --no-cache ${REQUIREMENTS} && echo "$(date '+%d/%m/%Y - %H:%M:%S') | Install Python dependencies" &&    pip3 install --upgrade pip  &&    pip3 install ${PYTHONDEPENDENCIES} && echo "$(date '+%d/%m/%Y - %H:%M:%S') | Install ${REPO}" &&    TEMP=$(mktemp -d) &&    git clone -b master "https://github.com/${REPO}.git" "${TEMP}" &&    cd "${TEMP}" &&    python3 setup.py install && echo "$(date '+%d/%m/%Y - %H:%M:%S') | Set permissions on startup script, clean up and exit" &&    chmod +x /usr/local/bin/sync-icloud.sh /usr/local/bin/healthcheck.sh &&    rm -r "${TEMP}" &&    apk del --no-progress --purge build-deps' returned a non-zero code: 1
```

Any idea of how to move past this error?

Thanks again

**Comment by boredazfcuk** [comment]
Hi, ketz.

Can you build using this dockerfile please?

https://pastebin.com/raw/zhxYgWFy

It will make it easier to identify which specific command is generating that error.

**Comment by ketz** [comment]
Sure thing, though should the top line be  `FROM arm64v8/alpine:latest` as before?

**Comment by boredazfcuk** [comment]
Sorry, yes that's right.

**Comment by ketz** [comment]
Thanks. Currently it's failing on the pip3 call, but that's something wrong with my Raspbian setup.

Simply calling pip3 shows 

`/usr/local/lib/python3.4/dist-packages/requests-2.22.0-py3.4.egg/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.9.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)`

I've been trying to resolve this one for a while now. Will keep trying and then run your script again.

Thanks!

**Comment by boredazfcuk** [comment]
> ...it's failing on the pip3 call, but that's something wrong with my Raspbian setup.

This docker container will be unaware of your Raspian setup as it runs on Alpine Linux and has no access to the host's OS.

Also,
> /usr/local/lib/python3.4/dist-packages

Where are you getting Python 3.4 from? The dockerfile should install Python 3.7.

Your
>RequestsDependencyWarning: urllib3 (1.9.1) or chardet (2.3.0)
error suggests that can't find urllib3 v1.9.1 or chardet v2.3.0, presumably because your old version doesn't have these newer versions available.

Just exactly how are you building the containter? Like this:

```
docker build /path/to/Dockerfile -t boredazfcuk/icloudpd
```

**Comment by ketz** [comment]
If I just run your command, this is what I see:

`Error response from daemon: Dockerfile parse error line 18: Unknown instruction: PIP3`

That's what led me down the path of a faulty pip3 installation

**Comment by boredazfcuk** [comment]
Can you open your file in notepad++ and check the End Of Line type? Seems this error can be down to having an MSDOS text file instead of a Unix text file.

Notepad++ can switch between the different versions. It's on the Edit menu, called EOL conversion.

**Comment by ketz** [comment]
Did that. Same error, sadly :/

**Comment by boredazfcuk** [comment]
Hi, ketz.

So, I still don't have an RPi3 to test this on (I have a spare 1b & 2), but I've built an arm32v7 version and pushed it to Dockerhub. You should be able to pull the image with
```
docker pull boredazfcuk/icloudpd:arm32v7
```
...then launch your container using that image instead.

I know that the RPi3 is 64-bit and arm v8, but from what I've read, Raspbian hasn't caught up yet.

I can also build an arm32v8 version, if this doesn't work, so let me know how you get on.

**Comment by boredazfcuk** [comment]
So, I just built it anyway...
```
docker pull boredazfcuk/icloudpd:arm64v8
```

**Comment by boredazfcuk** [comment]
New ARM images pushed just now. Presume these are working on RPi, but cannot test myself.

Closing issue due to lack of feedback.
