### ISSUE TITLE
Any command to update my passwords?

### ISSUE THREAD

**Issue by zsw12abc** [boredazfcuk/docker-icloudpd#201]
Hey Mate, i updated my icloud passwords then my icloudPD didnt work
is there any command to update passwords?

**Comment by boredazfcuk** [comment]
Hi,

If you want to update your password, you'll need to re-initialise the container.

Once upon a time I took advantage of the `--delete-from-keyring` option available in one of the underlying applications, but found it was buggy (it thre Python errors IIRC).

The `--Initialise` command just deletes the keyring, cookie and starts from scratch. Which I found to be more reliable.

Thanks.

**Comment by zsw12abc** [comment]
![image](https://user-images.githubusercontent.com/11704698/189027341-ade2302a-1cd9-47d7-b51a-ba804cf58dd6.png)
Here is the issue i face when i run `/usr/local/bin/sync-icloud.sh --Initialise`

**Comment by boredazfcuk** [comment]
Hi,

Can you update to the latest version and give it another go... It seems the code was missing. I've no idea why. Maybe I removed it for some reason and forgot about it.

Anyway, I've added in a new command line switch to remove the keyring file if it exists. Hopefully this should do the trick. Invoke it with `/usr/local/bin/sync-icloud.sh --DeleteKeyring`.

After that, run `/usr/local/bin/sync-icloud.sh --Initialise` and you should be good.

Thanks.
