### ISSUE TITLE
Feature Request: Different download directories for HEIC and JPG/MOV

### ISSUE THREAD

**Issue by millercentral** [boredazfcuk/docker-icloudpd#203]
I love the ability to generate jpgs of heic files as some of my clients don't support heic files. That said, for the clients that do, all images are doubled. It would be nice if we could specify a different directory for the original heic files, and separate them from the folder structure of the jpg files.  Loving this project, thanks for the work on it.

**Comment by boredazfcuk** [comment]
Hi,

I think that should be it... I've pushed a new version to Dockerhub which has a **jpeg_path** variable which you can set to specify the location of the JPEG files.

It will only work on newly downloaded files, however, you should be able to convert your entire photo library again using the --ForceConvertAllHEICs switch detailed in the README.

It will not remove JPEG files which have already been downloaded though, you'll need to do that manually.

Give it a test and report back problems.

Thanks.

**Comment by millercentral** [comment]
That's awesome, thank you!

**Comment by millercentral** [comment]
Thanks again for implementing this. The only addition I'd ask for is that it does not appear to move "non-converted" jpgs (that is, jpg/jpeg files that are natively in the icloud library, not ones that were the result of converting a heic) to the jpeg_path. It would be nice to have those move too. 

It would also be nice to have a "mov_path" equivalent as well, especially for actual movies (not `*HEIC.MOV` files), but that is feature creep beyond my original request :)

**Comment by boredazfcuk** [comment]
Hi,

No, JPEGs that are in your photo stream are not moved. There's not much point, as the script will re-download them at the next run, if they are still in your iCloud.com account. Same for HEIC.MOV files.

I'll close this off though as the original feature request is working as expected.

Thanks.
