### ISSUE TITLE
why --DeleteKeyring parameter is innvaild ?

### ISSUE THREAD

**Issue by neohob** [boredazfcuk/docker-icloudpd#204]
I changed icloud pwd, so I need clear icloudpd data use --DeleteKeyring parameter, but console return msg : "WARNING  Ignoring innvalid launch parameter specified: --DeleteKeyring", is that still woking?

**Comment by boredazfcuk** [comment]
Sorry, I was going to name it --DeleteKeyring but changed it to --RemoveKeyring at the last minute and forgot to update the README

**Comment by boredazfcuk** [comment]
Documentation updated.

**Comment by tokyoqiang** [comment]
![image](https://user-images.githubusercontent.com/99979431/191876891-e233e241-0d1b-4946-a58f-05cdde80eb39.png)
Hi boredazfcuk,
still show warnning when use --RemoveKeyring, can help to check? Thanks a lot!

**Comment by boredazfcuk** [comment]
Missed a bit off that sanitises the launch parameters... Pull the latest version and try again.

Thanks.
