### ISSUE TITLE
the docker had been perfectly processed for monthes，but these days it aways warns me an error

### ISSUE THREAD

**Issue by HuLuXi** [boredazfcuk/docker-icloudpd#207]
like i have said above，it warns me this：

`iCloudPD failed download check for new files files for Apple ID: 115…@… Exit code 1`

and i will put log if necessary
thank for take care！

**Comment by boredazfcuk** [comment]
Yeah, I'll need a larger log snip to be able to tell what's happening here.

If you have a large library, it could be worth adding the variable `skip_check=True`.

**Comment by boredazfcuk** [comment]
Closing as it's gone two weeks without a response.
