### ISSUE TITLE
Feature Request - Sync on Cron schedule

### ISSUE THREAD

**Issue by onestix** [boredazfcuk/docker-icloudpd#209]
Hi @boredazfcuk, I hope all is well. 

Would it be possible to consider introducing syncing capability via a cron schedule? 

ie. set variable "synchronisation_cron=0 4 * * *" which in return would trigger a sync at 4 am every day?

This would give us greater flexibility in setting a sync schedule, as opposed to starting the schedule/timer as of running the container.

The reason I am bringing this up is because I have set my container to run once every 24 hours and this usually results in a sync throughout the day. I wouldn't be bringing this up if it weren't for the heavy CPU & read/write activity (indexing, conversion- resulting in noisy disks in the living room) that my NAS triggers after each successful download. Having the ability to set a cron schedule for this to run in the middle of the night would be a very convenient way to resolve this.

I do respect the current mechanism in place to trigger a sync at pre-defined intervals, because you wouldn't want someone to trigger a sync every minute or so which would of course result in a ban.. but perhaps we could add a note/warning to the documentation?

Thanks for considering this.

**Comment by onestix** [comment]
Apologies.. should've read the previous tickets on this topic. Please feel free to close if this is not being considered.

**Comment by boredazfcuk** [comment]
Set `single_pass=True` so the script exits immediately instead of looping. Then launch the container on a schedule from the host machine via crontab, or some other method.

Thanks.
