### ISSUE TITLE
Face KeyError: dsinfo while entering icloud password

### ISSUE THREAD

**Issue by zsw12abc** [boredazfcuk/docker-icloudpd#221]
![image](https://user-images.githubusercontent.com/11704698/195957874-bed0b8d8-2b9a-439f-bc8f-16788fb2de26.png)

Hey mate
i got this error everytimes when i try to initialise it.
and it also ask me to input icloud passwords again and with following error message
![image](https://user-images.githubusercontent.com/11704698/195957997-9284a275-e17a-4964-9060-64bd79379d19.png)

**Comment by boredazfcuk** [comment]
Please login to iCloud.com and check that your account isn't locked out. It may also be prompting for additional information which you need to silence before icloudpd will work.

**Comment by YuHayring** [comment]
icloud_china: Set this to True to use icloud.com.cm instead of icloud.com as the download source.
国内要设置这个参数。

**Comment by boredazfcuk** [comment]
I'm closing this off as there's been no response in over a month.
