### ISSUE TITLE
the docket just cant download a pic with envs set  down

### ISSUE THREAD

**Issue by HuLuXi** [boredazfcuk/docker-icloudpd#225]
i have set the cookie successhully，but it had downloaded nothing.
it just start download stop without a pic，and continue the circulation

[icloudpd.csv](https://github.com/boredazfcuk/docker-icloudpd/files/9909296/icloudpd.csv)

**Comment by boredazfcuk** [comment]
I can see this error in the log file:

```
2022-10-25 07:33:22,stdout,2022-10-25 15:33:22 ERROR    Check failed - Exit code: 1
2022-10-25 07:33:22,stdout,"pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2022-10-25 07:33:22,stdout,"    raise PyiCloudFailedLoginException(msg, error)
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 216, in authenticate
2022-10-25 07:33:22,stdout,    self.authenticate()
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 193, in __init__
2022-10-25 07:33:22,stdout,    icloud = pyicloud_ipd.PyiCloudService(
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py\", line 29, in authenticate
2022-10-25 07:33:22,stdout,    icloud = authenticate(
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py\", line 255, in main
2022-10-25 07:33:22,stdout,"    return callback(*args, **kwargs)
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 535, in invoke
2022-10-25 07:33:22,stdout,"    return ctx.invoke(self.callback, **ctx.params)
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 895, in invoke
2022-10-25 07:33:22,stdout,    rv = self.invoke(ctx)
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 697, in main
2022-10-25 07:33:22,stdout,"    return self.main(*args, **kwargs)
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 722, in __call__
2022-10-25 07:33:22,stdout,"    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
2022-10-25 07:33:22,stdout,"  File \"/usr/bin/icloudpd\", line 33, in <module>
2022-10-25 07:33:22,stdout,Traceback (most recent call last):
2022-10-25 07:33:22,stdout,
2022-10-25 07:33:22,stdout,"During handling of the above exception, another exception occurred:
2022-10-25 07:33:22,stdout,
2022-10-25 07:33:22,stdout,pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
2022-10-25 07:33:22,stdout,    raise api_error
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 122, in _raise_error
2022-10-25 07:33:22,stdout,"    self._raise_error(code, reason)
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 100, in request
2022-10-25 07:33:22,stdout,"    return self.request('POST', url, data=data, json=json, **kwargs)
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/requests/sessions.py\", line 590, in post
2022-10-25 07:33:22,stdout,    req = self.session.post(
2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 209, in authenticate
2022-10-25 07:33:22,stdout,Traceback (most recent call last):
```

It's claiming that the e-mail/password combination is incorrect. Please reinitialise the container.

Also, it says that it is using Python 3.8. The container has been using Pythong 3.10 for quite some time, so please upgrade your container to the latest version on Dockerhub.

**Comment by HuLuXi** [comment]
i have upgaded both the 2 FA and the container but it also cant download just like above

**Comment by HuLuXi** [comment]
> I can see this error in the log file:
> 
> ```
> 2022-10-25 07:33:22,stdout,2022-10-25 15:33:22 ERROR    Check failed - Exit code: 1
> 2022-10-25 07:33:22,stdout,"pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
> 2022-10-25 07:33:22,stdout,"    raise PyiCloudFailedLoginException(msg, error)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 216, in authenticate
> 2022-10-25 07:33:22,stdout,    self.authenticate()
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 193, in __init__
> 2022-10-25 07:33:22,stdout,    icloud = pyicloud_ipd.PyiCloudService(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py\", line 29, in authenticate
> 2022-10-25 07:33:22,stdout,    icloud = authenticate(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py\", line 255, in main
> 2022-10-25 07:33:22,stdout,"    return callback(*args, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 535, in invoke
> 2022-10-25 07:33:22,stdout,"    return ctx.invoke(self.callback, **ctx.params)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 895, in invoke
> 2022-10-25 07:33:22,stdout,    rv = self.invoke(ctx)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 697, in main
> 2022-10-25 07:33:22,stdout,"    return self.main(*args, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 722, in __call__
> 2022-10-25 07:33:22,stdout,"    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
> 2022-10-25 07:33:22,stdout,"  File \"/usr/bin/icloudpd\", line 33, in <module>
> 2022-10-25 07:33:22,stdout,Traceback (most recent call last):
> 2022-10-25 07:33:22,stdout,
> 2022-10-25 07:33:22,stdout,"During handling of the above exception, another exception occurred:
> 2022-10-25 07:33:22,stdout,
> 2022-10-25 07:33:22,stdout,pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
> 2022-10-25 07:33:22,stdout,    raise api_error
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 122, in _raise_error
> 2022-10-25 07:33:22,stdout,"    self._raise_error(code, reason)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 100, in request
> 2022-10-25 07:33:22,stdout,"    return self.request('POST', url, data=data, json=json, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/requests/sessions.py\", line 590, in post
> 2022-10-25 07:33:22,stdout,    req = self.session.post(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 209, in authenticate
> 2022-10-25 07:33:22,stdout,Traceback (most recent call last):
> ```
> 
> It's claiming that the e-mail/password combination is incorrect. Please reinitialise the container.
> 
> Also, it says that it is using Python 3.8. The container has been using Pythong 3.10 for quite some time, so please upgrade your container to the latest version on Dockerhub.

i have upgaded both the 2 FA and the container but it also cant download just like above

> I can see this error in the log file:
> 
> ```
> 2022-10-25 07:33:22,stdout,2022-10-25 15:33:22 ERROR    Check failed - Exit code: 1
> 2022-10-25 07:33:22,stdout,"pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
> 2022-10-25 07:33:22,stdout,"    raise PyiCloudFailedLoginException(msg, error)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 216, in authenticate
> 2022-10-25 07:33:22,stdout,    self.authenticate()
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 193, in __init__
> 2022-10-25 07:33:22,stdout,    icloud = pyicloud_ipd.PyiCloudService(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py\", line 29, in authenticate
> 2022-10-25 07:33:22,stdout,    icloud = authenticate(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py\", line 255, in main
> 2022-10-25 07:33:22,stdout,"    return callback(*args, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 535, in invoke
> 2022-10-25 07:33:22,stdout,"    return ctx.invoke(self.callback, **ctx.params)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 895, in invoke
> 2022-10-25 07:33:22,stdout,    rv = self.invoke(ctx)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 697, in main
> 2022-10-25 07:33:22,stdout,"    return self.main(*args, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 722, in __call__
> 2022-10-25 07:33:22,stdout,"    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
> 2022-10-25 07:33:22,stdout,"  File \"/usr/bin/icloudpd\", line 33, in <module>
> 2022-10-25 07:33:22,stdout,Traceback (most recent call last):
> 2022-10-25 07:33:22,stdout,
> 2022-10-25 07:33:22,stdout,"During handling of the above exception, another exception occurred:
> 2022-10-25 07:33:22,stdout,
> 2022-10-25 07:33:22,stdout,pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
> 2022-10-25 07:33:22,stdout,    raise api_error
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 122, in _raise_error
> 2022-10-25 07:33:22,stdout,"    self._raise_error(code, reason)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 100, in request
> 2022-10-25 07:33:22,stdout,"    return self.request('POST', url, data=data, json=json, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/requests/sessions.py\", line 590, in post
> 2022-10-25 07:33:22,stdout,    req = self.session.post(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 209, in authenticate
> 2022-10-25 07:33:22,stdout,Traceback (most recent call last):
> ```
> 
> It's claiming that the e-mail/password combination is incorrect. Please reinitialise the container.
> 
> Also, it says that it is using Python 3.8. The container has been using Pythong 3.10 for quite some time, so please upgrade your container to the latest version on Dockerhub.

i have upgaded both the 2 FA and the container but it also cant download just like above

**Comment by HuLuXi** [comment]
i have upgaded both the 2 FA and the container but it also cant download just like above

> I can see this error in the log file:
> 
> ```
> 2022-10-25 07:33:22,stdout,2022-10-25 15:33:22 ERROR    Check failed - Exit code: 1
> 2022-10-25 07:33:22,stdout,"pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
> 2022-10-25 07:33:22,stdout,"    raise PyiCloudFailedLoginException(msg, error)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 216, in authenticate
> 2022-10-25 07:33:22,stdout,    self.authenticate()
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 193, in __init__
> 2022-10-25 07:33:22,stdout,    icloud = pyicloud_ipd.PyiCloudService(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py\", line 29, in authenticate
> 2022-10-25 07:33:22,stdout,    icloud = authenticate(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py\", line 255, in main
> 2022-10-25 07:33:22,stdout,"    return callback(*args, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 535, in invoke
> 2022-10-25 07:33:22,stdout,"    return ctx.invoke(self.callback, **ctx.params)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 895, in invoke
> 2022-10-25 07:33:22,stdout,    rv = self.invoke(ctx)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 697, in main
> 2022-10-25 07:33:22,stdout,"    return self.main(*args, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 722, in __call__
> 2022-10-25 07:33:22,stdout,"    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
> 2022-10-25 07:33:22,stdout,"  File \"/usr/bin/icloudpd\", line 33, in <module>
> 2022-10-25 07:33:22,stdout,Traceback (most recent call last):
> 2022-10-25 07:33:22,stdout,
> 2022-10-25 07:33:22,stdout,"During handling of the above exception, another exception occurred:
> 2022-10-25 07:33:22,stdout,
> 2022-10-25 07:33:22,stdout,pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
> 2022-10-25 07:33:22,stdout,    raise api_error
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 122, in _raise_error
> 2022-10-25 07:33:22,stdout,"    self._raise_error(code, reason)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 100, in request
> 2022-10-25 07:33:22,stdout,"    return self.request('POST', url, data=data, json=json, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/requests/sessions.py\", line 590, in post
> 2022-10-25 07:33:22,stdout,    req = self.session.post(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 209, in authenticate
> 2022-10-25 07:33:22,stdout,Traceback (most recent call last):
> ```
> 
> It's claiming that the e-mail/password combination is incorrect. Please reinitialise the container.
> 
> Also, it says that it is using Python 3.8. The container has been using Pythong 3.10 for quite some time, so please upgrade your container to the latest version on Dockerhub.

i have upgaded both the 2 FA and the container but it also cant download just like above

**Comment by HuLuXi** [comment]
I upgrade container to the latest and the python is still 3.8

**Comment by HuLuXi** [comment]
i have select the latest docker but after it is done 
i found that it is still old version in the log

**Comment by HuLuXi** [comment]
> I can see this error in the log file:
> 
> ```
> 2022-10-25 07:33:22,stdout,2022-10-25 15:33:22 ERROR    Check failed - Exit code: 1
> 2022-10-25 07:33:22,stdout,"pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
> 2022-10-25 07:33:22,stdout,"    raise PyiCloudFailedLoginException(msg, error)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 216, in authenticate
> 2022-10-25 07:33:22,stdout,    self.authenticate()
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 193, in __init__
> 2022-10-25 07:33:22,stdout,    icloud = pyicloud_ipd.PyiCloudService(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/authentication.py\", line 29, in authenticate
> 2022-10-25 07:33:22,stdout,    icloud = authenticate(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/icloudpd-1.7.2-py3.8.egg/icloudpd/base.py\", line 255, in main
> 2022-10-25 07:33:22,stdout,"    return callback(*args, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 535, in invoke
> 2022-10-25 07:33:22,stdout,"    return ctx.invoke(self.callback, **ctx.params)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 895, in invoke
> 2022-10-25 07:33:22,stdout,    rv = self.invoke(ctx)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 697, in main
> 2022-10-25 07:33:22,stdout,"    return self.main(*args, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/click/core.py\", line 722, in __call__
> 2022-10-25 07:33:22,stdout,"    sys.exit(load_entry_point('icloudpd==1.7.2', 'console_scripts', 'icloudpd')())
> 2022-10-25 07:33:22,stdout,"  File \"/usr/bin/icloudpd\", line 33, in <module>
> 2022-10-25 07:33:22,stdout,Traceback (most recent call last):
> 2022-10-25 07:33:22,stdout,
> 2022-10-25 07:33:22,stdout,"During handling of the above exception, another exception occurred:
> 2022-10-25 07:33:22,stdout,
> 2022-10-25 07:33:22,stdout,pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
> 2022-10-25 07:33:22,stdout,    raise api_error
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 122, in _raise_error
> 2022-10-25 07:33:22,stdout,"    self._raise_error(code, reason)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 100, in request
> 2022-10-25 07:33:22,stdout,"    return self.request('POST', url, data=data, json=json, **kwargs)
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/requests/sessions.py\", line 590, in post
> 2022-10-25 07:33:22,stdout,    req = self.session.post(
> 2022-10-25 07:33:22,stdout,"  File \"/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py\", line 209, in authenticate
> 2022-10-25 07:33:22,stdout,Traceback (most recent call last):
> ```
> 
> It's claiming that the e-mail/password combination is incorrect. Please reinitialise the container.
> 
> Also, it says that it is using Python 3.8. The container has been using Pythong 3.10 for quite some time, so please upgrade your container to the latest version on Dockerhub.

I have updated successfully but there is a new problem just like the case in **tissue 227**

**Comment by boredazfcuk** [comment]
I've just had the exact same error. When I logged in to icloud.com, the account was locked and I had to enter the answers to the security questions. After I did that and unlocked the account, the error went away.

Thanks.

**Comment by HuLuXi** [comment]
> I've just had the exact same error. When I logged in to icloud.com, the account was locked and I had to enter the answers to the security questions. After I did that and unlocked the account, the error went away.
> 
> Thanks.

but i have log in with .com.cn and there is no security questions.
sorry about bothering you

**Comment by boredazfcuk** [comment]
Hi,
Run this to remove the password:
`docker exec -it icloudpd sync-icloud.sh --RemoveKeyring`
then
`docker exec -it icloudpd sync-icloud.sh --Initialise`
to re-initialise the container and enter the password again.
