### ISSUE TITLE
Sync ends unexpectedly and doesn't download images

### ISSUE THREAD

**Issue by epheterson** [boredazfcuk/docker-icloudpd#230]
I have three iCloudPD containers and recently one stopped downloading images. During sync, it does see new images but then shows an odd error, appears to think the check/sync was successful, and doesn't download images, repeatedly even after relaunching. The permissions haven't been intentionally changed between when it worked and now, and appear to be the same between the three instances. Not sure what to try configuration-wise, could it be a bug?

```
2022-11-21 16:35:28 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
/path/to/new/pics1.jpg
/path/to/new/pics2.jpg ...
/home/user/iCloud: line 0: can't create /tmp/icloudpd/icloudpd_check_exit_code: Permission denied
ash: out of range
2022-11-21 16:51:29 INFO     Check successful
ash: out of range
2022-11-21 16:51:29 INFO     New files detected: 88
```

**Comment by boredazfcuk** [comment]
Hi,
Have you upgraded the OS or anything like that? Raspberry Pi type devices have permission issues as the containers are not run in privileged mode by default. I'd try enabling that on the container and see what happens.

Thanks.

**Comment by epheterson** [comment]
Hey, thanks I didn't change anything and it resolved itself a few days later. I should've included the config, this is a Synology NAS not a Pi.
