### ISSUE TITLE
Synology Photo Fix doesn't work

### ISSUE THREAD

**Issue by magicmychal** [boredazfcuk/docker-icloudpd#236]
Hi, 

I have the icloudpd running in a docker on my Synology. 
I set the synology_photos_app_fix to True and in the logs I can see
Fixing Synology Photos App import issue... in the logs, but the Synology App doesn't see it unless I manually go there and press "re index".

**Comment by Arnold4869** [comment]
you can solve it by this link
https://github.com/boredazfcuk/docker-icloudpd/issues/165

**Comment by boredazfcuk** [comment]
Yeah, unfortunately this is beyond my control. The Synology app lives outside my container and for most people, it doesn't auto-index when the files are touched, however, one person says that this solution is working for them, so I left it in.
