### ISSUE TITLE
> > > > I am not seeing any changes to my iCloud website... Or the website hasn't been changed enough to break the script at least.

### ISSUE THREAD

**Issue by china31** [boredazfcuk/docker-icloudpd#242]
> > > > I am not seeing any changes to my iCloud website... Or the website hasn't been changed enough to break the script at least.
> > > 
> > > 
> > > which script file name? I try to debug it,thanks
> > 
> > 
> > This is the project which does I use to download everything: https://github.com/icloud-photos-downloader/icloud_photos_downloader
> > If you figure it out I might need to fork their project, so you can merge changes to the fork, as nobody seems to be maintaining that project anymore.
> 
> @boredazfcuk https://github.com/picklepete/pyicloud this porject has implemented the new auth version. maybe u can take a look. thanks

![image](https://user-images.githubusercontent.com/2271609/205558877-ab624270-df09-4822-a11c-95e08f43d6a4.png)

@boredazfcuk  https://github.com/picklepete/pyicloud 

I tested the project also, and it did solve the problem

_Originally posted by @sk163 in https://github.com/boredazfcuk/docker-icloudpd/issues/227#issuecomment-1336782249_

Sorry, I can't use

**Comment by boredazfcuk** [comment]
This should be resolved in the latest version of the container.
