### ISSUE TITLE
Webhook Configuration

### ISSUE THREAD

**Issue by acandido** [boredazfcuk/docker-icloudpd#243]
Hi, can't seem to get this working correctly and getting this error:

WARINING webhook notifications enabled, but configured incorrectly - disabling notifications

My compose file looks like this:

notification_type: webhook                                                                                                                                                                       
webhook_server: homeassistant.somedomain.com                                                                                                                                                                    
webhook_port: 443                                                                                                                                                                                
webhook_id: -xx-xxxxxxxxxxxxxxx
webhook_https: true

Not sure what I'm missing since this should satisfy this condition:

elif [ "${notification_type}" = "Webhook" ] && [ "${webhook_server}" ] && [ "${webhook_id}" ]; then

No matter what I set webhook_server & webhook_id to I get the error.

Thanks!

**Comment by boredazfcuk** [comment]
`notification_type: webhook`
`elif [ "${notification_type}" = "Webhook" ]`

Spot the difference

**Comment by acandido** [comment]
D'oh, I thought the upper case didn't matter since the env variables are all set lower case.  Thanks!

**Comment by boredazfcuk** [comment]
Case insensitivity is something I keep meaning to implement. Just not had much time recently. Hopefully I'll get a few nights over the Christmas break.
