### ISSUE TITLE
I get an exception error using sync-icloud.sh --Initialise

### ISSUE THREAD

**Issue by MagicStarTrace** [boredazfcuk/docker-icloudpd#246]
![image](https://user-images.githubusercontent.com/15685376/207790720-f7b51686-8874-48c3-973c-1ec62e6e1d3d.png)
![image](https://user-images.githubusercontent.com/15685376/207791572-d515ae6c-e0b8-459e-b724-a06d94cd0d1d.png)

**Comment by soelu** [comment]
Same issue here with the latest tag DIGEST:sha256:f421ddb37f1edfb75df639d68c956cd7a10172216a1af75cee178b11093e7c9a

**Comment by MagicStarTrace** [comment]
Is there a version of the docker image available?

**Comment by boredazfcuk** [comment]
This version of the container is over a year old. Please update to the latest version, run `sync-icloud.sh --RemoveKeyring` and then reinitialise. Your version of the container is so old, I doubt it will have the `--RemoveKeyring` functionality, so it will definitely need updating.

The error happen if the password is entered incorrectly. It will not be able to add the incorrect password to the keyring so the keyring file gets created, but is empty, resulting in the error above.

It can also happen if the Apple ID is changed, as the keyring file exists, but the user's password is not stored in it. Following the process outlined above should again fix this though.

**Comment by MagicStarTrace** [comment]
> This version of the container is over a year old. Please update to the latest version, run `sync-icloud.sh --RemoveKeyring` and then reinitialise. Your version of the container is so old, I doubt it will have the `--RemoveKeyring` functionality, so it will definitely need updating.
> 
> The error happen if the password is entered incorrectly. It will not be able to add the incorrect password to the keyring so the keyring file gets created, but is empty, resulting in the error above.
> 
> It can also happen if the Apple ID is changed, as the keyring file exists, but the user's password is not stored in it. Following the process outlined above should again fix this though.

Is it possible to provide an available image tag?
