### ISSUE TITLE
Too slow when verifying the permissions

### ISSUE THREAD

**Issue by andycylam** [boredazfcuk/docker-icloudpd#247]
Please have a look on the screenshot. Every time the program runs, it takes a lot of time to check the permissions. Is there any way to prevent it?
![Capture](https://user-images.githubusercontent.com/8168724/208396794-ef5b9d6a-4908-404b-9dc1-a72726660af0.PNG)

**Comment by boredazfcuk** [comment]
> Is there any way to prevent it?

No. The script needs to make sure the permissions are correct or it breaks things. It's already optimised to be as fast as it can be, as it only changes the permissions on the files which are non-compliant, but it will have to read the permissions of all the files in your download path to assess which files need changing.

However, I have split this into two different functions now. One that applies to the configuration related file paths and one that only applies to the download folder.

Scanning and changing the configuration related file paths only takes a second, so I can still run this multiple times throughout the script. The one that processes the downloads folder should now only run after files are downloaded.

I've pushed a new version to Dockerhub. Please update to this new version and let me know.
