### ISSUE TITLE
download all files

### ISSUE THREAD

**Issue by scorpio2k2** [boredazfcuk/docker-icloudpd#248]
Hello,

this downloads only photos? 
It is possible to download all documents from icloud?

Thanks

**Comment by boredazfcuk** [comment]
Hi,

This container uses the [icloud_photos_downloader](https://github.com/icloud-photos-downloader/icloud_photos_downloader) application to download photos. It doesn't support downloading anything else, and at this moment in time, the project seems abandoned, unfortunately.

Thanks.
