### ISSUE TITLE
Advanced Data Protection = private db access disabled for this account.

### ISSUE THREAD

**Issue by Xaositek** [boredazfcuk/docker-icloudpd#250]
With the update to iOS 16.2 and enabling Advanced Data Protection; this will immediately break icloudpd with the following error.

2022-12-27 22:12:51 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
private db access disabled for this account.  Please wait a few minutes then try again.  The remote servers might be trying to throttle requests. (ACCESS_DENIED)

Running an initialize will request a new 2FA token but this does not change the outcome. While I highly doubt it's plausible to work around, perhaps an update to the wording with something like "iOS 16.2 Advanced Data Protection will not permit access to icloudpd"

**Comment by nemesislvlup** [comment]
I had the same error, but restarting the container fixed this for me. ADP is disabled.

**Comment by Xaositek** [comment]
ADP makes this error actually permanent. I did report also in the parent of this project - https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/514

**Comment by boredazfcuk** [comment]
`private db access disabled for this account. Please wait a few minutes then try again. The remote servers might be trying to throttle requests. (ACCESS_DENIED)`

This error is generated by the underlying application, I just push it out to the logs.

Reading this: https://support.apple.com/en-us/HT212520 says that you can revert to standard protection by disabling ADP. This should then allow this container to download photos again.
>How to turn off Advanced Data Protection for iCloud
>You can turn off Advanced Data Protection at any time. Your device will securely upload the required encryption keys to Apple servers, and your account will once again use [standard data protection](https://support.apple.com/kb/HT202303).
>-     iPhone or iPad: In Settings, tap your name, then tap iCloud. Then scroll down and turn off Advanced Data Protection.
>-     Mac: In System Settings, click your name, then click iCloud. Then click Advanced Data Protection and click Turn Off.

I've updated the Troubleshooting steps in the ReadMe to inform users that ADP will need to be switched off for this container to download photos.
