### ISSUE TITLE
can download livephoto without _HEVC Suffix

### ISSUE THREAD

**Issue by yanghano** [boredazfcuk/docker-icloudpd#254]
Or can i custom the .mov name

**Comment by Arnold4869** [comment]
https://github.com/boredazfcuk/docker-icloudpd/issues/227，这个里边有这个问题的暂时解决办法，你可以看下

**Comment by lhlxx2010** [comment]
> 



> #227 这边有这个问题的临时解决办法，你可以看下

问问看,作者修复这个问题了吗

**Comment by yunxiaofeng1001** [comment]
@yanghano 这个问题解决了吗? 再提示的227 问题里面.没有看到有关HEVC 前缀取消的设置.
