### ISSUE TITLE
folder_structure album failed and lower memory

### ISSUE THREAD

**Issue by stefano1986** [boredazfcuk/docker-icloudpd#258]
First Issue: 

When i use environment variable folder_structure = album, the container will not create the albums of the icloud account. Instead it creates a directory "album" and download all files to this directory. 

i've tried different version:  
--env folder_structure=album
--env folder_structure={:album}
--env folder_structure={album}

All these version does not create my album from iCloud (e.g. Whatsapp, latestPhotos,  PSExpress, Instagramm...)

second issue; 
i've downloaded approx 4500 Files. Icloud shows memory of approx 16Gigabytes for that. The downloaded files are only 9GB. 
I use photo_size original and jpeg quality 100% and dont convert from HEIC to jpeg. 

Can anyone help with this two issues?
Thanks

**Comment by JonasPerrin** [comment]
I have exactly the same issue and looking to resolve it.

**Comment by AndreyNikiforov** [comment]
IIUC you need to specify `--album` parameter with the name of the album you want to download and `--directory` where it will be saved. One album at a time.

**Comment by boredazfcuk** [comment]
Closed as question answered.
