### ISSUE TITLE
Error using testing branch

### ISSUE THREAD

**Issue by khargy** [boredazfcuk/docker-icloudpd#259]
I've been using the testing branch for about a month now so I can download the shared libraries... not sure if something changed. I starting getting the following error a few days ago:

2023-01-08 10:00:00 ERROR    Failed to download new files
2023-01-08 10:00:00 ERROR     - Can you log into iCloud.com without receiving pop-up notifications?
2023-01-08 10:00:00 ERROR    Error debugging info:
2023-01-08 10:00:00 ERROR    
2023-01-08 10:00:00 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

I checked out iCloud.com nothing weird there and I re-added my 2FA token and no change.

**Comment by epheterson** [comment]
Actually also stopped working for me, last successful sync was 1/5.

I'm seeing a different error:
```
iCloud Photo Library not finished indexing.  Please try again later. This process may take hours.
```

**Comment by epheterson** [comment]
Randomly I did get images sync'd again last night, no change to the container.

**Comment by 7Mattias** [comment]
Same for me. The stable version immediately works flawless (but sadly not for the shared library ;-)).

**Comment by boredazfcuk** [comment]
Latest version of the container should support shared libraries again. However, it will not display the names of the shared libraries as standard. This has been moved to a new function to prevent errors being displayed for people who are not using shared libraries If you wish to see the names of the libraries again. Please run:
```
docker exec -it icloudpd sync-icloud --ListLibraries
```
