### ISSUE TITLE
Feature request - make the path of a webhook accessible via config

### ISSUE THREAD

**Issue by Seb0815** [boredazfcuk/docker-icloudpd#26]
Hi,

I love your container and it make my life a lot easier ;-). However for the notification via webhook it would be great to have a way configure the path of the request.

At the moment it's hardcoded (I guess for homeassist): notification_url="${webhook_scheme}://${webhook_server}:${webhook_port}/api/webhook/${webhook_id}" 

Would be great to have something to be flexible with the webhook service like:
webhook_path="/hook/myPath/"
notification_url="${webhook_scheme}://${webhook_server}:${webhook_port}${webhook_path}${webhook_id}"

**Comment by boredazfcuk** [comment]
Will do. Should be a pretty simple change and won't impact current users.

I'll not be able to look at it for a couple of days though as I'm busy with something else... I'll update here once I've pushed it.

**Comment by boredazfcuk** [comment]
I think this should be in the latest version... I changed the code a couple of days ago and it will have been pushed by one of my auto-build scripts over the last couple of days as I've been making a shed load of changes to some of my containers.

Give it a go and let me know... The variable is **webhook_url** and if it's not set, it will default to what I had it hard-coded to... /api/webhok IIRC.

**Comment by boredazfcuk** [comment]
Any problems, just reopen the issue.
