### ISSUE TITLE
How can i extend cookies?

### ISSUE THREAD

**Issue by AlexaAmaya** [boredazfcuk/docker-icloudpd#263]
dont know how to type in the docker :-(

like add a window from /bin/sh?

and type what?

**Comment by Floki-78** [comment]
/bin/ash
Then run sync-icloud.sh --Initialise again.

**Comment by AlexaAmaya** [comment]
> /bin/ash Then run sync-icloud.sh --Initialise again.

hi, thanks for your help, it seems work but still has some problem, please see:
1. I ran `sync-icloud.sh --Initialise` and it starts to roll
2. my iPhone got 2FA code, but seems to place for me to type in
3. error
4. btw, i am using China iCloud, and i have set icloud_china = 1
![9f1ba442e22c83d69134ae4002ffcc9](https://user-images.githubusercontent.com/109637800/215277240-1ad5b17b-b409-43bd-a0cf-ebebc0c5a421.png)

Thank you so much~

**Comment by AlexaAmaya** [comment]
pls see https://github.com/boredazfcuk/docker-icloudpd/issues/251#issuecomment-1369079973

**Comment by boredazfcuk** [comment]
This is resolved in latest version of the container.
