### ISSUE TITLE
Cannot find icloud.com IP address - Check DNS Settings

### ISSUE THREAD

**Issue by thew1se** [boredazfcuk/docker-icloudpd#267]
Hi, I have just tried installing this for the first time but am getting the above mentioned error.

![image](https://user-images.githubusercontent.com/57738712/214096891-21292d2f-106d-4751-8767-f5a8c3129b0a.png)

I am new-ish to docker so I think I configured everything correctly....

![image](https://user-images.githubusercontent.com/57738712/214097386-e0fb904c-da0f-4b51-9570-a9aa8cf8bca5.png)
![image](https://user-images.githubusercontent.com/57738712/214097476-98709b25-9043-491e-865c-f64bdee33cce.png)
![image](https://user-images.githubusercontent.com/57738712/214097603-c2815573-c191-4380-80f6-7342b9821134.png)

Can  you advise where my setup is wrong?  Thanks in advance!

**Comment by thew1se** [comment]
I figured this out...this was a firewall issue.  needed to allow the new subnet.

**Comment by huyixi** [comment]
How to allow the new subnet?

**Comment by thew1se** [comment]
@huyixi 

Its been a while since I set this up, but if I remember correctly, first you have to create a new bridge in docker specifically for icloud_PD.  That bridge is used for icloud_Pd container.  Whichever subnet you make for that bridge needs to be added to the synology firewall.   To add:

On synology UI > Security > Firewall > edit rules > add the internal ip range of the subnet. 

Hope this helps.
