### ISSUE TITLE
New user - a few questions regarding albums, changing settings in future, and syncing.

### ISSUE THREAD

**Issue by thew1se** [boredazfcuk/docker-icloudpd#270]
Brand new to icloudpd so a big thank you for a much needed program!   

Got it setup on synology/Docker without using SSH and just started syncing.   A few questions:

1. I have set to folder_structure = album, but my downloads are only going into downloadpath/album.  My icloud has its normal library (all photos) and a few albums I've setup.  I'm not sure what the intended structure will be with this setting...can you explain...will it eventually generate individual album folders and duplicate the pictures?

2. What will happen to all files if I restart the container with folder_structure variable changed to none?

3. I assume this is a 1-way sync, so any locally deleted files will be re-downloaded? (I did not see this expressly stated, other than this is a backup)

4. Figuring out synology using docker was a little harder than I expected, I am relatively new to docker and I often find docker instructions do not translate well to the Synology-Docker GUI.   Would you like a synology tutorial added?  I don't mind doing the ground work if you do.

Thanks again!

**Comment by Floki-78** [comment]
1. Am not sure on this one…
2. Photos will be placed singularly into the folder you have assigned for iCloudpd
3. Correct, in order to stop redownloading you will first have to delete the photo from iCloud first, then delete from your nas
4. I use portainer on my asustor nas to manage my docker images and like yourself took me awhile to understand the docker space.

**Comment by Floki-78** [comment]
No it wont reorganise already downloaded photos.
I use folder structure set to none, then use photo gallery to create the albums if i want them.

**Comment by boredazfcuk** [comment]
Closing as all questions answered.
