### ISSUE TITLE
Operation not permitted: '/home/user/.local/share/python_keyring/keyring_pass.cfg'

### ISSUE THREAD

**Issue by janjian** [boredazfcuk/docker-icloudpd#273]
I'm only using few custom parameters and getting this Operation not permitted error. 
Please help me to see how to solve it, running on the docker of win11. 

docker create \
   --name iCloudPD_boredazfcuk\
 --env apple_id=id\
 --env TZ=CST \
 --env icloud_china=True \
 --env authentication_type=web \
 --volume /mnt/c/home:/home \
 --volume /mnt/c/config:/config \
  boredazfcuk/icloudpd

Save password in keyring?  [y/N]: y
Traceback (most recent call last):
  File "/usr/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud-ipd==0.10.1', 'console_scripts', 'icloud')())
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/cmdline.py", line 209, in main
    utils.store_password_in_keyring(username, password)
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 53, in store_password_in_keyring
    return keyring.set_password(
  File "/usr/lib/python3.10/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py", line 93, in set_password
    self._ensure_file_path()
  File "/usr/lib/python3.10/site-packages/keyrings/alt/file_base.py", line 121, in _ensure_file_path
    os.chmod(self.file_path, user_read_write)
PermissionError: [Errno 1] Operation not permitted: '/home/user/.local/share/python_keyring/keyring_pass.cfg'

**Comment by boredazfcuk** [comment]
You'll need to run your container in privileged mode... I've seen a similar issue on Raspberry Pi devices.

The container needs to run as root, as it uses su to change user, sets permissions, changes owner etc, and that can't be done from a standard account

**Comment by janjian** [comment]
i

> You'll need to run your container in privileged mode... I've seen a similar issue on Raspberry Pi devices.
> 
> The container needs to run as root, as it uses `su` to change user, sets permissions, changes owner etc, and that can't be done from a standard account.
> 
> Thanks.

it works ! thanks.
but i run into a new error ,same as https://github.com/boredazfcuk/docker-icloudpd/issues/227 .
it seems unsalveable...sad

**Comment by boredazfcuk** [comment]
There's been quite a bit of development with the underlying application of late and the developers are aware of the issue. They are making changes which may resolve that issue. I'm just waiting for development to settle down a bit, and the release version to be stable, before I push a new version of the container. Hopefully it will be fixed in the near future.
