### ISSUE TITLE
Security key support

### ISSUE THREAD

**Issue by keanenwold** [boredazfcuk/docker-icloudpd#274]
Hello, thank you for this great application! I'm wondering if there are plans to support security keys (Yubikeys)? I am no longer able to authenticate since adding Yubikey support to my Apple ID. Thanks!

**Comment by AndreyNikiforov** [comment]
@keanenwold are you able to use Yubikeys to access iCloud.com from Web browser? `icloudpd` emulated Web access and if Yubikey somehow interferes with web access, then we have a problem.

**Comment by keanenwold** [comment]
@AndreyNikiforov, I am able to login to iCloud via Chrome (not Firefox as it's not supported) with my Yubikey. Is there anything else I can test? I tried to use my Yubikey for the 2FA response as I no longer get a six digit code on my devices and it did not work.

**Comment by AndreyNikiforov** [comment]
> 

Can you please describe what you see & do in web UI to auth with YubiKey? And what you see and do with icloudpd? I suspect that in web UI there is something special for Yubi, while in icloudpd you have only sms option.

It may be easier to experiment with upstream project, e.g. `docker run --rm -it icloudpd/icloudpd:1.8.1 icloudpd --username redacted@you.email --list-albums`

**Comment by keanenwold** [comment]
Sorry for the delay. 

Steps to login via web:
1. Enter user/pass
2. Prompted to hit continue on a screen that says, "Two-factor authentication. Use a security key to sign to your account with Apple ID: xx. I then hit continue. 
3. I am then prompted in browser to "use my security key" and I 'touch' my Yubikey to continue. 
4. The next screen prompts me if I want to trust this browser. 
5. I am logged in

I ran the 'docker run' command you provided above and see the following:

> 2023-02-11 22:33:51 DEBUG    Authenticating...
> iCloud Password: 
> 2023-02-11 22:34:03 INFO     Two-step/two-factor authentication is required!
>   0: SMS to ********
>   1: SMS to ********
>   2: Enter two-factor authentication code
> Please choose an option: [0]:  

I think the problem is I can no longer use SMS and the two-factor code does nothing for me even if I 'touch' my Yubikey?

**Comment by boredazfcuk** [comment]
There's a couple of problems I can predict with using a Yubikey... Firstly, the container would not be able to access the Yubikey without it being passed into the container somehow. It would appear it can be done by mapping certain files into the container, but I've no way of testing, as I do not own a Yubikey.

Also, it sounds like it changes how the icloud.com website presents itself. icloudpd emulates a web-browser, so any non-standard behaviour will prevent it from working. It sounds like using the Yubikey makes it present additional pop-up notification which would interfere with the icloudpd download process.

**Comment by raspberrycoulis** [comment]
I too would like to see if the use of security keys (including Yubikeys) can be implemented, as at the moment I have had to stop using the container because I've switched to security key 2fa on my Apple ID and it doesn't currently work.

If it helps, I've also tried using the verification code generated by macOS when getting to the security prompt when trying to re-initialise the container, but despite the 2fa code being generated by macOS, it is not accepted - I suspect it's a security thing on Apple's side.

Appreciate it may not be possible, but adding here just in case it does become a possibility!

**Comment by boredazfcuk** [comment]
If the capability is added upstream, then I should be able to add it to my container.

I'm closing this off though as it's not something I can add without it being added upstream first.

**Comment by keanenwold** [comment]
Is it correct to assume that this is still not working for a people using Yubikeys?

Thanks

**Comment by hcdio** [comment]
Still no access for me via Yubikey MFA
