### ISSUE TITLE
Failed to download new files

### ISSUE THREAD

**Issue by 54ybl** [boredazfcuk/docker-icloudpd#278]
I encountered this issue after setting skip_check = True.Log showed the number of iCloud files means it's not an authentication failure,but it just cannot download files.
Does anyone have the same issue?
![image](https://user-images.githubusercontent.com/51509360/216927181-8fc64113-6f8e-4a44-be27-4889aee65cb2.png)

**Comment by AndreyNikiforov** [comment]
Did you try without skip_check? 

Error suggests that tzdata package is not included. Don't know what skip_check does and why it is affecting tz data though.

**Comment by marcovn** [comment]
It seems to have an issue with the timezone set. What is the value of TZ?

**Comment by 54ybl** [comment]
> It seems to have an issue with the timezone set. What is the value of TZ?

OK,I removed the TZ variale and it works!Thanks for your idea.

**Comment by 54ybl** [comment]
> Did you try without skip_check?
> 
> Error suggests that tzdata package is not included. Don't know what skip_check does and why it is affecting tz data though.

Cause there‘re more than 10,000 photos in my iCloud library so I have to set skip_check or it won't work correctly.
Now I removed the TZ variable and it fixed.Thanks.
