### ISSUE TITLE
Synology Photos App Fix doesn't work for me

### ISSUE THREAD

**Issue by heeelga** [boredazfcuk/docker-icloudpd#281]
I'm running the docker container on my Synology NAS. Everything works as expected but unfortunately Synology Photos does not show any of the downloaded files.

I've set synology_photos_app_fix to True as described and tried to change the download directory but nothing seems to work.

Does anyone else encounter this problem or have a fix for that?

Thanks in advance!

**Comment by AlexaAmaya** [comment]
我是下载后再copy到另一个user的/photos里的，方法太笨，蹲一个回复。

**Comment by Arnold4869** [comment]
https://github.com/boredazfcuk/docker-icloudpd/issues/165，可以试试这个里边的脚本，我现在一直在用

**Comment by alienwow** [comment]
> 可以试试这个里边的脚本，我一直在用 #165

新增的还不错，但是删除的照片呢？我看我这边好像并没有工作，你那边有用吗？

**Comment by Arnold4869** [comment]
> > 可以试试这个里边的脚本，我一直在用 #165
> 
> 新增的还不错，但是删除的照片呢？我看我这边好像并没有工作，你那边有用吗？

什么删除的？我想你可以参考看下我用的那个脚本代码，里边是调用了官方的一个程序，在那个程序路径还有别的程序，有好几个模式，你可以参考下再修改脚本。太具体的我也记不清了，抱歉

**Comment by alienwow** [comment]
> > > 可以试试这个里边的脚本，我一直在用 #165
> > 
> > 
> > 新增的还不错，但是删除的照片呢？我看我这边好像并没有工作，你那边有用吗？
> 
> 什么删除的？我想你可以参考看下我用的那个脚本代码，里边是调用了官方的一个程序，在那个程序路径还有别的程序，有好几个模式，你可以参考下再修改脚本。太具体的我也记不清了，抱歉

就是有个照片被删除后，如何在已经生成的索引中删除它？

**Comment by Arnold4869** [comment]
> > > > 可以试试这个里边的脚本，我一直在用 #165
> > > 
> > > 
> > > 新增的还不错，但是删除的照片呢？我看我这边好像并没有工作，你那边有用吗？
> > 
> > 
> > 什么删除的？我想你可以参考看下我用的那个脚本代码，里边是调用了官方的一个程序，在那个程序路径还有别的程序，有好几个模式，你可以参考下再修改脚本。太具体的我也记不清了，抱歉
> 
> 就是有个照片被删除后，如何在已经生成的索引中删除它？

我这里没感觉不能在索引里删除吧，没太在意这个。你试试把脚本里的basic reindex改成别的参数

**Comment by Arnold4869** [comment]
> > > > 可以试试这个里边的脚本，我一直在用 #165
> > > 
> > > 
> > > 新增的还不错，但是删除的照片呢？我看我这边好像并没有工作，你那边有用吗？
> > 
> > 
> > 什么删除的？我想你可以参考看下我用的那个脚本代码，里边是调用了官方的一个程序，在那个程序路径还有别的程序，有好几个模式，你可以参考下再修改脚本。太具体的我也记不清了，抱歉
> 
> 就是有个照片被删除后，如何在已经生成的索引中删除它？

https://community.synology.com/enu/forum/20/post/142938
具体参考下这个链接里提到的几个参数

**Comment by alienwow** [comment]
> > > > > 可以试试这个里边的脚本，我一直在用 #165
> > > > 
> > > > 
> > > > 新增的还不错，但是删除的照片呢？我看我这边好像并没有工作，你那边有用吗？
> > > 
> > > 
> > > 什么删除的？我想你可以参考看下我用的那个脚本代码，里边是调用了官方的一个程序，在那个程序路径还有别的程序，有好几个模式，你可以参考下再修改脚本。太具体的我也记不清了，抱歉
> > 
> > 
> > 就是有个照片被删除后，如何在已经生成的索引中删除它？
> 
> https://community.synology.com/enu/forum/20/post/142938 具体参考下这个链接里提到的几个参数

好的 感谢，我试试吧。
我现在测试发现，类似于人像这种自动编辑过的照片，也无法自动备份成已编辑后的照片。

**Comment by boredazfcuk** [comment]
> I'm running the docker container on my Synology NAS. Everything works as expected but unfortunately Synology Photos does not show any of the downloaded files.
> 
> I've set synology_photos_app_fix to True as described and tried to change the download directory but nothing seems to work.
> 
> Does anyone else encounter this problem or have a fix for that?
> 
> Thanks in advance!

I'm only aware of one person who this fix works for. I don't know why it's only working for him and not others, maybe he is running an older version of the Synology OS. I said that I would not remove this feature, just for him lol

Other users have solved this by scheduling the Synology re-indexing tool to run after a download. See this link here: https://github.com/boredazfcuk/docker-icloudpd/issues/165#issuecomment-1269205183

**Comment by laoshu133** [comment]
可以使用 docker 创建一个本地 volume，然后在容器内挂载，这样就可以做到同步了，例如：

创建 volume
```
docker volume create --driver local \
--opt type=nfs \
--opt o=addr=127.0.0.1,rw \
--opt device=:/volume1/homes \
nashome
```

创建容器时挂载：
```
docker run -d \
  --name icloudpd \
 ...
  -e download_path=/mnt/laoshu133/Photos/iCloud \
  -v nashome:/mnt \
  boredazfcuk/icloudpd:1.0.289
```

**Comment by ljw89** [comment]
> 我是下载后再copy到另一个user的/photos里的，方法太笨，蹲一个回复。

有个博主(https://www.bilibili.com/read/cv24566413/)介绍了方法,因为7,2不允许Docker访问home,他就用映射photos文件夹到Docker能访问的目录,例如:mount --bind /volume1/homes/你的用户名/Photos/iCloud_Photos /volume1/docker/iCloudpd/iCloud_Photos (#你实际下载的路径这个指令),为了防止重启后这个映射丢了,要挂载个任务,重启再次执行映射

**Comment by lonevvolf** [comment]
@boredazfcuk I've tested the touch command from the Synology command line, and a much faster way is to use the file as a reference when touching itself.  Ie.
touch -r filename filename
This avoids having to create and delete a new file.  Do you think this would be possible to update?
