### ISSUE TITLE
Is it possible to sync photos or videos after editing?

### ISSUE THREAD

**Issue by alienwow** [boredazfcuk/docker-icloudpd#283]
After being edited on iPhone, photos only exist as original pictures after syncing with icloudpd, and there are no edited pictures. I hope I can keep both or at least keep the edited pictures.

**Comment by boredazfcuk** [comment]
Hi.

Unfortunately it's not possible to download edited photos as Apple only stores the originals.

Edits are an after-effect which is applied to the original file, in real time, via Apple software on whatever platform you are using iPhone/iCloud.com etc.

You can see these after-effect files by plugging your idevice into a PC and browsing the folders (should be named IMG_0001.AAE or similar). If you open them up in a text editor, you will also see they are encrypted, making them pretty much useless to anyone that doesn't have the decryption key (which is Apple, I believe).
