### ISSUE TITLE
Cannot build Docker image successfully

### ISSUE THREAD

**Issue by Xm798** [boredazfcuk/docker-icloudpd#284]
```log
Reading https://pypi.org/simple/keyrings-alt/
/usr/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
No local packages or working download links found for keyrings-alt<5,>=4.2.0
error: Could not find suitable distribution for Requirement.parse('keyrings-alt<5,>=4.2.0')
```

Although dependent "keyrings-alt 4.2.0" have been installed successfully.

**Comment by boredazfcuk** [comment]
Hi,

I'm aware of this. There have been quite a large number of changes to the iCloudPD downloaded that's packaged in my container. I think it stopped building at release 1.8 (now in 1.10)

There are quite a few features added to 1.8, 1.9 & 1.10, but I was hoping a fix would come for this issue: https://github.com/boredazfcuk/docker-icloudpd/issues/227 and I was going to build and release a new version of my container.

The good news is that the latest version that I'm running on my server at home in testing does build OK so I'll look at releasing early, even without the above fix included.

**Comment by Xm798** [comment]
The iCloudPD version in the Docker is still 1.7.2, and we are looking forward to a latest version. Thanks a lot!

**Comment by boredazfcuk** [comment]
Sorry, only just got around to this. I've pushed it a sort while ago. Hope this helps.
