### ISSUE TITLE
Add the `telegram_server` option to NOTIFICATION CONFIGURATION VARIABLES

### ISSUE THREAD

**Issue by Xm798** [boredazfcuk/docker-icloudpd#285]
As you may be aware, Telegram is inaccessible in China Mainland. Therefore, we often resort to using a reverse proxy API to connect. It would be helpful if the `telegram_server` option could be included in the NOTIFICATION CONFIGURATION VARIABLES.

**Comment by boredazfcuk** [comment]
```
         if [ "${telegram_server}" ] ; then
            notification_url="https://${telegram_server}/bot${telegram_token}/sendMessage"
         else
            notification_url="https://api.telegram.org/bot${telegram_token}/sendMessage"
         fi
```

The **telegram_server** variable is just a hostname e.g. proxy.server.com.

It assumes https, so if your server is http, then changes will be required.
