### ISSUE TITLE
How to change folder owner?

### ISSUE THREAD

**Issue by WuhanSy** [boredazfcuk/docker-icloudpd#29]
![image](https://user-images.githubusercontent.com/23512897/96600272-5b364b00-1323-11eb-8a30-f8c5d350e642.jpeg)

my folder owner is 1000,but I need owner is admin in synology nas 918+.because I use Moments to manage my photos.in docker, user and user_id are default. when user is admin and user_id is 1024, it reports error.

**Comment by boredazfcuk** [comment]
Hi,

This should show you how to find out your admin user/group IDs and names:

https://www.synoforum.com/resources/how-to-find-uid-userid-and-gid-groupid.77/

These can be passed to my container using the following variables:

**user
user_id
group
group_id**

The **force_gid** variable may also be required, depending on your system. Some Synology devices use a GID of 100, which is already in use in my container.

See the READ.ME file for more information.

**Comment by WuhanSy** [comment]
Thank you for your help!

**Comment by boredazfcuk** [comment]
No problem.
