### ISSUE TITLE
icloud download persistence

### ISSUE THREAD

**Issue by itzteajay-glitch** [boredazfcuk/docker-icloudpd#291]
So I have an interesting workflow and I'm wondering something before I trigger another icloud sync of 20k+ images and videos.

Currently I run this app in a custom truecharts container in my truenas server. I have icloudpd put all images into the import directory for photoprism.

In photoprism I have it trigger an import and move all files which effectively removes them from the import directory and restructures them. My question is does icloudpd persist the downloaded files in any sort of DB to prevent duplicates or does it just do a diff between the download directory and each file to prevent duplicates? Since photoprism deletes the source file on import I'm worried about a looping situation where photoprism imports, deletes the original file, icloudpd syncs and sees the file isn't there and redownloads it only to loop indefinitely till my disks fill up.

**Comment by AndreyNikiforov** [comment]
`icloudpd` does not have db, all data is just what you see in destination folder. There is an option to save cookies to speed up authentication, but that is irrelevant to your question.

In the scenario you described where photoprism deletes all photos previously downloaded by `icloudpd`, subsequent `icloudpd` execution will download all the same photos again.

**Comment by itzteajay-glitch** [comment]
Is there an opportunity for an enhancement request where only files since the last sync are downloaded? If a date could be stored in a file in the applications config dir then it could be referenced. Overall I'm super impressed with how smooth this has worked and photoprism may actually handle the de-duping but I hate for it to download them every time and waste bandwidth.

**Comment by AndreyNikiforov** [comment]
There is similar request in the [upstream project](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/466).

**Comment by itzteajay-glitch** [comment]
Ah awesome, yeah 100% admit I don't know your functionality just figure I'd call out my use case :)

**Comment by boredazfcuk** [comment]
Closing as question answered.
