### ISSUE TITLE
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter

### ISSUE THREAD

**Issue by wojing** [boredazfcuk/docker-icloudpd#296]
pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter

i seems  the  China region login issue haven't been solved.

**Comment by neohob** [comment]
same problem

**Comment by chenmiaorong** [comment]
same

**Comment by boredazfcuk** [comment]
Fixed in latest container.
