### ISSUE TITLE
Cannot convert HEIC to JPG using --ConvertAllHEICs

### ISSUE THREAD

**Issue by damianorenzetti** [boredazfcuk/docker-icloudpd#297]
Hello,
First of all. THANK YOU. this is a great tool.

I tried running a terminal command from my qnap container using --ConvertAllHEICs and I cannot seem to convert downloaded HEIC files to JPG.

I connected to /bin/sh of the container and tried to create a file in the jpeg directory mounted in the container, and I can so it's not a permissions issue. I also tried manually converting one file with the _convert_ command and I still get the following: 

`convert: unable to open image '/home/dren/iCloud/JPG/2023/03/18/IMG_7299.JPG': No such file or directory @ error/blob.c/OpenBlob/3570.`

Again not sure this is the issue, but checking the sync-icloud.sh code, it fails converting when launching this command and I also tested it manually so I suspect this would happen even with the regular conversion after downloading. 

**EDIT:** 
This doesn't happen when I convert straight after downloading. 
I found the bug: There's no `mkdir --parents "$(dirname "${jpeg_file}")"` instruction when converting with "--ConvertAllHEICs". If parent directory is created before the convert command the script works fine.

**Comment by boredazfcuk** [comment]
Thanks. I've fixed it in the latest version.
