### ISSUE TITLE
ERROR    Apple ID not set - exiting

### ISSUE THREAD

**Issue by terrylaanda** [boredazfcuk/docker-icloudpd#299]
Hi there, 

I keep getting the following error: ERROR    Apple ID not set - exiting. I'm not sure why?

Can anyone give me any pointers? Btw I'm using a NAS drive to store the photos and the config file. 

The docker-icloudpd folder is on my local Mac username folder

Many thanks!

**Comment by boredazfcuk** [comment]
Upgrade to the latest version of the container. This will have a configuration file in your config folder, which will likely be found at `/config/icloudpd.conf`

Set your Apple ID in there.
