### ISSUE TITLE
Notifications not being sent because notification_api_key is never set

### ISSUE THREAD

**Issue by mmazerolle** [boredazfcuk/docker-icloudpd#30]
Noting that my configured Prowl notifications are not being sent, I checked the source and noticed a bug.
The Notify() function uses notify_api_key in the curl call to send the notification, but this variable is never set based on prowl_api_key / pushbullet_api_key. This should probably be done in ConfigureNotifications().

**Comment by boredazfcuk** [comment]
I've just added these changes manually rather than merging the PR. The GitHub version of my code was quite far behind my local home lab version. I've just added your changes and pushed the latest code here.

I've also updated Dockerhub with a new image so it should be fixed now.

Thanks for the PR.

**Comment by mmazerolle** [comment]
Great! Are you planning to push a new image to Dockerhub? I'd like to pick
the fix up from there.

CALENDAR <https://bit.ly/33j4GYD> • SKYPE
<https://join.skype.com/invite/ghO0Pd2Cl4dC>
<https://foundry.com/>

**Comment by boredazfcuk** [comment]
Yeah, I pushed the new version an hour ago.
