### ISSUE TITLE
Changed the value of the environment variable setting, but the icloudpd.conf is not updated synchronously

### ISSUE THREAD

**Issue by Alano-i** [boredazfcuk/docker-icloudpd#308]
tag:  stable
Changed the value of the environment variable setting, but the icloudpd.conf is not updated synchronously.
After modifying the value of the environment variable, must to modify the value in the .conf file at the same time to take effect.
I don't know if it's just me.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/68833595/231039506-1e812ec8-1cf3-4675-b394-8d06daad6c24.png">

**Comment by boredazfcuk** [comment]
This is the expected behaviour. The settings in icloudpd.conf take priority over environment variables.

If the icloudpd.conf file does not exist, it creates a file with default settings, but will also migrate any configured environment variables into the file.

**Comment by Alano-i** [comment]
If the configuration is modified in the environment variable, would it be better to update it to the .conf file synchronously?

**Comment by Alano-i** [comment]
In the issue list, 
several errors were reported synchronously because the environment variable settings did not take effect due to the default value in icloudpd.conf,or the modification of the environment variable icloudpd.conf file was not updated to the new configuration, resulting in synchronous error reporting.
Can the icloudpd.conf file be updated synchronously?

**Comment by boredazfcuk** [comment]
I have made modifications which should mean that the environment variables now set the values in the `icloudpd.conf` configuration files,. I've just pushed a new latest container to DockerHub. Can you upgrade and test?

I will be looking to deprecate this capability at some point in the future though, as I really want to move away from configuration via variables.

**Comment by Alano-i** [comment]
You're right. There are too many environment variables, and it's troublesome to set them one by one. I have an idea maybe it's a solution?. 

List all configuration items in the .conf file and set the default value if there is any configuration in the environment variable to modify the value in the newly updated .conf file.

In this way, users can run icloudpd by either configuring the .conf file or supporting environment variables.

If don't want to configure environment variables, just modify the .config file.

Hope this can help.

**Comment by boredazfcuk** [comment]
Closing this as it should have been changed last week.

**Comment by AlexaAmaya** [comment]
heyy guys, i cant find the icloudpd.conf in my NAS or, it did not created in the right way.:-(
