### ISSUE TITLE
Invalid directory. Path is not readable

### ISSUE THREAD

**Issue by boredazfcuk** [boredazfcuk/docker-icloudpd#312]
Tried with latest version. Here's the log output:
![image](https://user-images.githubusercontent.com/5952023/230985206-c8489b78-68df-4349-9e20-a81f1979a230.png)

_Originally posted by @Dyrelund in https://github.com/boredazfcuk/docker-icloudpd/issues/266#issuecomment-1502237641_

**Comment by boredazfcuk** [comment]
https://github.com/boredazfcuk/docker-icloudpd/issues/266#issuecomment-1407261084

**Comment by boredazfcuk** [comment]
@jasonhorga Can you confirm the file system of the destination volume which you are attempting to save your files to?
@Dyrelund also has the same issue, and I was wondering if it was because your filesystems are btrfs.
I've only tested this with ext4 volumes

**Comment by q1067972249** [comment]
same question

**Comment by Arnold4869** [comment]
same error

**Comment by Arnold4869** [comment]
i solve it by set user，user_id，group，and group_id。
and i set the directory belong to the same user

**Comment by raeying06** [comment]
Error: Invalid value for '-d' / '--directory': Path '/share/Docker/icloudpd/iCloud' is not readable.  same question

**Comment by boredazfcuk** [comment]
> i solve it by set user，user_id，group，and group_id。 and i set the directory belong to the same user

Thanks for posting the resolution.

**Comment by xh2415** [comment]
> i solve it by set user，user_id，group，and group_id。 and i set the directory belong to the same user

Sorry to ask but I am not an expert in this. Would you mind going into a bit more detail on how to solve this? Many thanks.

**Comment by konastin** [comment]
> > i solve it by set user，user_id，group，and group_id。 and i set the directory belong to the same user
> 
> Sorry to ask but I am not an expert in this. Would you mind going into a bit more detail on how to solve this? Many thanks.

这个似乎是设置的“download_path”，我们都设置的是“/iCloud”，但是这个和环境变量里设置的那个路径有冲突（挂载路径），我尝试了下将download_path改成实际的可以过这一步的检查，但是会提示没有“.mounted”文件即使你有，搜了之前的方法是将环境变量中的“/iCloud”删除。但是还是没解决，但是已经不会出现这个问题了。会提示”INFO     Loading configuration from: /config/icloudpd.conf“

**Comment by willytylee** [comment]
I access the sh by /bin/sh, and then chmod 755 /iCloud, then the error passed.

**Comment by Humpback-whale0** [comment]
So excited!!! You only need to change param "TZ" to "Asia/Shanghai"!!!

**Comment by Humpback-whale0** [comment]
还有一点是，要把配置参数user=群晖用户名，用户id直接命令行输入id两个字符enter查看

**Comment by Humpback-whale0** [comment]
> So excited!!! You only need to change param "TZ" to "Asia/Shanghai"!!!

还有一点是，要把配置参数user=群晖用户名，用户id直接命令行输入id两个字符enter查看

**Comment by Humpback-whale0** [comment]
> > So excited!!! You only need to change param "TZ" to "Asia/Shanghai"!!!
> 
> 还有一点是，要把配置参数user=群晖用户名，用户id直接命令行输入id两个字符enter查看

Good Luck！！！

**Comment by handsomebin666** [comment]
> 我通过 /bin/sh 访问 sh，然后 chmod 755 /iCloud，然后错误通过了。

牛逼。按照此方法，我居然成功了！！！感谢！！

**Comment by handsomebin666** [comment]
> I access the sh by /bin/sh, and then chmod 755 /iCloud, then the error passed.
执行此命令后重启，在下载时候遇到以下问题
2023-09-18 08:27:54 ERROR    IOError while writing file to /iCloud/2023/09/17/IMG_1400.PNG! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...

**Comment by handsomebin666** [comment]
> > 我通过 /bin/sh 访问 sh，然后 chmod 755 /iCloud，然后错误通过了。
> > 执行此命令后重启，在下载时遇到以下问题
> > 2023-09-18 08:27:54 ERROR IOError whilewriting file到/iCloud/2023/09/17/IMG_1400.PNG！您可能已用完磁盘空间，或者文件对于您的操作系统来说太大。正在跳过该文件...

我艹，搞定了！！！！！/bin/sh 访问 sh，然后chmod 777 /iCloud

**Comment by handsomebin666** [comment]
> > I access the sh by /bin/sh, and then chmod 755 /iCloud, then the error passed.
> > 执行此命令后重启，在下载时候遇到以下问题
> > 2023-09-18 08:27:54 ERROR    IOError while writing file to /iCloud/2023/09/17/IMG_1400.PNG! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...

我艹，搞定了！！！！！/bin/sh 访问 sh，然后chmod 777 /iCloud

**Comment by geekqq** [comment]
> > I access the sh by /bin/sh, and then chmod 755 /iCloud, then the error passed.
> 
> This also helped me! thx
我启动了两个container 在同一台群晖上。我自己的运行没问题，但是给我太太的账号运行的就提示iCloud目录无法读取。user 和group ID 都一样的，所以应该不是这里的问题。不过按照后面的题型exec进去container修改了icloud目录的权限再重启container之后就可以了。
三万多张照片和视频已经开始下载了。

<img width="616" alt="image" src="https://github.com/user-attachments/assets/809072e1-18dd-4e7b-a52f-d37a22911b74">
<img width="515" alt="image" src="https://github.com/user-attachments/assets/98bf106b-44fb-4ac3-b73c-a222d1d98ce8">
<img width="381" alt="image" src="https://github.com/user-attachments/assets/eb8aa770-8426-458b-85d4-0eb128bac3df">

<img width="507" alt="image" src="https://github.com/user-attachments/assets/0ffa4943-fa48-4ee9-b7b7-a212a4e4cc73">
<img width="844" alt="image" src="https://github.com/user-attachments/assets/4be862b1-10bf-43ef-86a1-08782a40acf6">

**Comment by yoyitowang** [comment]
It works to use the following steps, I'm using the Synology NAS system:

Update the `.../iCloud` directory permission outside:
```bash
# stop container
docker-compose down

# update your iCloud directory permission and 
sudo mkdir -p /var/services/homes/user/Photos/iCloud
sudo chown -R yoyowang0720:users /var/services/homes/user/Photos/iCloud
sudo chmod -R 777 /var/services/homes/user/Photos/iCloud

# restart container
docker-compose up -d
```
