### ISSUE TITLE
How to correctly configure parameters when using the DingTalk notification option?

### ISSUE THREAD

**Issue by shaoj0013** [boredazfcuk/docker-icloudpd#313]
--env notification_type=Dingtalk \
   --env notification_title=shaoj0013 \

dingtalk_token  which format is correct

   --env dingtalk_token=XXXXXXXXXXXXXXXXXXXXx \

   --env dingtalk_token=https://oapi.dingtalk.com/robot/send?access_token=XXXXXXXXXXXXX \

**Comment by boredazfcuk** [comment]
The script sets the notification_url variable like this;
```
notification_url="https://oapi.dingtalk.com/robot/send?access_token=${dingtalk_token}"
```

if you set:
```
--env dingtalk_token=https://oapi.dingtalk.com/robot/send?access_token=XXXXXXXXXXXXX
```

then your notification url becomes:
```
notification_url="https://oapi.dingtalk.com/robot/send?access_token=https://oapi.dingtalk.com/robot/send?access_token=XXXXXXXXXXXXX"
```
and that will fail.

Definitely set:
```
--env dingtalk_token=XXXXXXXXXXXXXXXXXXXXx 
```

**Comment by shaoj0013** [comment]
Thank you. It has been configured and is working normally.

**Comment by boredazfcuk** [comment]
Closing this off as it looks resolved.
