### ISSUE TITLE
sync-icloud.sh --ListLibraries does not work

### ISSUE THREAD

**Issue by sir-andreas** [boredazfcuk/docker-icloudpd#316]
Hi, 

when I try to run 
`docker exec -it icloudpd sync-icloud.sh --ListLibraries`
as described in the Readme I only get the following error:

> 2023-04-17 09:14:12 WARNING  Ignoring invalid launch parameter specified: --ListLibraries
2023-04-17 09:14:12 WARNING  Please do not specify the above parameter when launching the container. Continuing in 2 minutes
2023-04-17 09:16:12 INFO     Shared libraries available:
Usage: icloudpd <options>
Try 'icloudpd -h' for help

What am I doing wrong?

By the way: When I am calling the binary direcly it also does not seem to work:
>icloudpd --list-libraries
Usage: icloudpd <options>
Try 'icloudpd -h' for help.
>
>Error: No such option: --list-libraries Did you mean --list-albums?`

**Comment by boredazfcuk** [comment]
Sorry, I removed this feature from the container as it doesn't work correctly and generates errors, preventing the container from working... I just forgot to update the documentation. 

The boredazfcuk/icloudpd:testing container does still have this functionality included, but I'm not actively developing that any more.

**Comment by sir-andreas** [comment]
Ok, thanks for the feedback. Just one question left: Does that mean, that the photo_library parameter also does not work? I just want to reach to sync a shared library...

**Comment by boredazfcuk** [comment]
It may, or it may not work. Different people get different results.

I don't use shared libraries, but the code would list the default ones fine... for about a week. Then it would just crash the container.

Other people are still using it to download from shared libraries though, so your mileage may vary.

**Comment by sir-andreas** [comment]
Ok, thanks. One final question: Does it work to sync shared folders on the so called "photo stream"?

**Comment by boredazfcuk** [comment]
No, it works by interacting with icloud.com... Basically logs in and downloads the photos same as you would in a browser. Unfortunately, shared albums are not available on icloud.com (or at least they weren't when I last checked).
