### ISSUE TITLE
CN login error IOexception with .p00.prod.me.com domain

### ISSUE THREAD

**Issue by GOUKI9999** [boredazfcuk/docker-icloudpd#318]
err message is
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: statusCode = UnknownServerError, IOException sending request [https://accountservice.p00.prod.me.com:443/api/get_challenge_devices](https://accountservice.p00.prod.me.com/api/get_challenge_devices), accountservice.p00.prod.me.com

I  think it's a same issue  as #294 ,but I read it and not find any solution worked for me
nslookup the domain  accountservice.p00.prod.me.com always return Non-existent domain what ever , with 8.8.8.8 1.1.1.1 or other dns server. 
 run with latest version image from dockerhub yesterday
env's here
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "config_dir=/config",
                "icloud_china=true",
                "TZ=CST-8",
                "download_path=/iCloud",
                "authentication_type=2FA",
                "apple_id= its@apple.id ",
                "synchronisation_interval=604800",
                "auth_china=true"

**Comment by Arnold4869** [comment]
我这边有个账号也出现这问题了。
我尝试在网页上直接登录icloud.com.cn，它的很多模块都提示未载入。点入后还提示报错，刚给 apple 的客服打电话，暂时没发现什么问题。等待明天联系我。
然后我是在尝试更换回官方的镜像时出现的这个问题，我之前几个月是用的pjoc的镜像，现在切换回去，也能正常备份下载。

**Comment by Arnold4869** [comment]
给客服打电话半小时后恢复正常

**Comment by swapfun** [comment]
I used the latest version of this author which didn't work. But I found the project of pjoc worked. You can try it and hope he can find the solution.

**Comment by boredazfcuk** [comment]
Pjoc's container is broken. It cannot download Live Photos correctly.

If you are seeing the `accountservice.p00.prod.me.com` error, then you do not have `auth_china=true` in your `/config/icloudpd.conf` configuration file.
