### ISSUE TITLE
Apple insists on using iCloud.com.cn for your request

### ISSUE THREAD

**Issue by leechao1981** [boredazfcuk/docker-icloudpd#322]
2023/4/21 23:04:03  2023-04-21 23:04:03 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****

2023/4/21 23:04:03  pyicloud_ipd.exceptions.PyiCloudConnectionException: Apple insists on using iCloud.com.cn for your request. Please use --domain parameter

what can i do？

**Comment by boredazfcuk** [comment]
You need to set `auth_china=true` in your `/config/icloudpd.conf` configuration file.

**Comment by leechao1981** [comment]
yes i have auth_china=true in my /config/icloudpd.conf
