### ISSUE TITLE
Failing to download photos

### ISSUE THREAD

**Issue by yhiji1** [boredazfcuk/docker-icloudpd#331]
sorry, here with a another issue. After I got everything working, I successfully downloaded everything, however I forgot to set it to download all albums instead of just raw onto the folder, so I deleted everything and started a redownload with that setting set to "all albums"

However now it will download a few, and then fail to download the rest. Not sure if this has to do with that setting or something else. Thank you!

![Screenshot 2023-04-28 at 12 04 11 AM](https://user-images.githubusercontent.com/131002872/235051787-7322d1c6-37e9-49a9-9888-45d5b8b5338f.png)

**Comment by vandreykiv** [comment]
Your log doesn’t show actuall error (should be before these errors). Seems like upstream icloudpd opening new session for each album and apple throttle such requests. I was unable to get through this at the moment and returned back to all photos into one folder download method (as it is one session rather then a new one for each album). 

Until we got some guidance from upstream I don’t think there is a good solution here

**Comment by yhiji1** [comment]
I see, that makes sense. Thanks for your reply, ill switch back to just downloading everything together.

**Comment by boredazfcuk** [comment]
Yeah, there is an issue downloading All Albums, until something is done about it upstream, I can't offer any further solutions. For now, it's best to stick to All Photos.
