### ISSUE TITLE
Keyring file does not exist

### ISSUE THREAD

**Issue by askalee2000** [boredazfcuk/docker-icloudpd#334]
when I used this docker from my nas，after enter my password，it notificate like this，can't continue 2FA process。 this situation I haven't seen yet，can somebody help？

Enter iCloud password for *****@gmail.com: 
Traceback (most recent call last):
  File "/opt/icloudpd_v1.7.2_china/bin/icloud", line 33, in <module>
    sys.exit(load_entry_point('pyicloud==1.0.0', 'console_scripts', 'icloud')())
  File "/opt/icloudpd_v1.7.2_china/lib/python3.10/site-packages/pyicloud/cmdline.py", line 191, in main
    api = PyiCloudService(username.strip(), password.strip())
  File "/opt/icloudpd_v1.7.2_china/lib/python3.10/site-packages/pyicloud/base.py", line 233, in __init__
    topdir = path.join(gettempdir(), "pyicloud")
  File "/usr/lib/python3.10/tempfile.py", line 299, in gettempdir
    return _os.fsdecode(_gettempdir())
  File "/usr/lib/python3.10/tempfile.py", line 292, in _gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/lib/python3.10/tempfile.py", line 223, in _get_default_tempdir
    raise FileNotFoundError(_errno.ENOENT,
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
2023-05-08 16:35:31 ERROR    Keyring file does not exist. Please try again.

**Comment by goobags** [comment]
This seems to be very similar to issue #309 where you have already commented, however the proposed suction does not work for both of us.

**Comment by askalee2000** [comment]
useri_d、user、force_id、group、group_id 这几个参数设置后，问题已解决

**Comment by willytylee** [comment]
I chmod -R to my NAS icloud config folder to 755, and the error passed.

**Comment by arthurfsy2** [comment]
> useri_d、user、force_id、group、group_id 这几个参数设置后，问题已解决

请问是要设置成什么内容才能不报错？我也遇到了相同的问题

**Comment by askalee2000** [comment]
> 
我是用极空间nas的docker功能，配置值仅供参考
user_id：0
group_id：0
force_gid：True
user：root
group：root

**Comment by askalee2000** [comment]
> > useri_d、user、force_id、group、group_id 这几个参数设置后，问题已解决
> 
> 请问是要设置成什么内容才能不报错？我也遇到了相同的问题

我是用极空间nas的docker功能，配置值仅供参考
user_id：0
group_id：0
force_gid：True
user：root
group：root

**Comment by arthurfsy2** [comment]
> > > useri_d、user、force_id、group、group_id 这几个参数设置后，问题已解决
> > 
> > 
> > 请问是要设置成什么内容才能不报错？我也遇到了相同的问题
> 
> 我是用极空间nas的docker功能，配置值仅供参考 user_id：0 group_id：0 force_gid：True user：root group：root

感谢老哥回答。不过我的是群晖的，无法用这个方法解决。琢磨了几天了，终于解决。
后面如果遇到和我类似的情况的朋友，可以参考：
1、尝试用你的账号登录icloud.com.cn，**我的账号显示无法从icloud.com.cn登录，但是可以从icloud.com登录**，所以不需要设置icloud_china、auth_china这两个参数。
2.在部署容器阶段删除以上两个参数，重新sync-icloud.sh --Initialize即可
