### ISSUE TITLE
How to config Bark notification?

### ISSUE THREAD

**Issue by mhqschen** [boredazfcuk/docker-icloudpd#335]
I can use below link to send a notification to my phone.
https://bark.XXXX.com/YYYY/

And my icloudpd.conf:
```
bark_device_key=YYYY
bark_server=bark.XXXX.com
```
And got this error "Bark startup notification failed with status code: 400"

Also tried ```bark_server=https://bark.XXXX.com``` and ```bark_server=bark.XXXX.com:443``` . No luck.
How shall I change the config?

**Comment by boredazfcuk** [comment]
I've pushed a new version which should correctly encode the JSON sent to the Bark server.
```
encoded_bark_text="$(echo -n "${bark_text}" | jq -Rsa .)"
```
Please update and try again.
