### ISSUE TITLE
“Generating list of files in iCloud” bug do not download

### ISSUE THREAD

**Issue by zlyon** [boredazfcuk/docker-icloudpd#337]
Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
After listing all content，Nothing happened.
Nothing errors

正在iCloud中生成文件列表。如果你有大量的照片收藏，这可能需要很长时间。请耐心等待。此时没有下载任何内容
在列出所有内容后，什么也没发生，没有错误。

**Comment by Sowevo** [comment]
Have you installed iOS 16 on your device and enabled the shared library feature?
> 您是否在设备上安装了 iOS 16 并启用了共享库功能？
共享图库好像暂时不支持

**Comment by boredazfcuk** [comment]
How long did you wait? This can take days on large libraries.

You may also want to set **skip_check** to **true** as the check also has issues on large libraries.

**Comment by boredazfcuk** [comment]
Closing as no response in two weeks.
