### ISSUE TITLE
Path structure downloading spefic album

### ISSUE THREAD

**Issue by ppurice** [boredazfcuk/docker-icloudpd#340]
Hello everyone,
I downloaded my icloud Photo by Album configuration ..... My problem is that in this folder I have 50000 photos because this Album is shared with all my family devices.

The guide says:
When downloading photo albums, the folder structure will be set to be the name of the album eg "/home/boredazfcuk/iCloud/one/IMG_0001.HEIC", "/home/boredazfcuk/iCloud/two/IMG_0002.HEIC" and "/home/boredazfcuk/iCloud/three and four/IMG_0003.HEIC" .....  

Is there a solution to modify the structure in .....

/home/boredazfcuk/iCloud/two/{:%Y/%m/%d}/IMG_0002.HEIC  ?????

Thanks 

Paolo

**Comment by boredazfcuk** [comment]
Hi,

I've pushed a new version of the container which should do this when the variable **folders_with_dates** is set to **true**.

Please test and let me know if it works. If it throws and error, please post a snip of the log file.

Thanks.

**Comment by boredazfcuk** [comment]
Closing as no response in two weeks.
