### ISSUE TITLE
Seems like delete_after_download flag is not working properly

### ISSUE THREAD

**Issue by hanxan3** [boredazfcuk/docker-icloudpd#343]
### What happened
It seems like it will delete photo/movie even if download failed.

### Version
```
INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.432 started *****
```
### Log
```
2023-05-31 15:59:15 INFO     Downloading /iCloud/2023/04/03/IMG_9303.MOV
2023-05-31 15:59:45 ERROR    Error downloading IMG_9303.MOV, retrying after 5 seconds...
2023-05-31 15:59:54 INFO     Deleting IMG_9303.MOV
```

Thanks!

**Comment by boredazfcuk** [comment]
Thanks. This is the second time there have been problems reported with this functionality in the upstream package. I will remove this capability in the next version as it's obviously not stable enough for release just yet and it has the potential to cause data loss.
