### ISSUE TITLE
Synology Socket Closed

### ISSUE THREAD

**Issue by jinnxu75** [boredazfcuk/docker-icloudpd#346]
Hi all, this is not a issue of icloudpd, but i can only find a lot of similar questions with no answer, and i believe it is not a single case for guys using synology. The solution will be using for those who are using an Synology.

The first time, everything works perfect, but since i didnot set any group and user, all files owner is uid 1000. Nothing wrong with it, but i just feel uncomfortable. //I am expecting the correct user could be help for the SynologyPhoto index (now all photos can not be found by Synology Photo)

So i delete the container and redo it with all configuration options i need including user_id and group_id(with force_gid), I found i can not access the docker terminal any more.

Is there any one can give me a hand?

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/92104817/0e374240-88bf-4c21-b08f-18257d25f7a8)

**Comment by jinnxu75** [comment]
Update: the issue happened only when remote access. when i back to home and access from local network, everything is fine.

I do not know what happened when i deleted and reinstalled the container.

**Comment by boredazfcuk** [comment]
Thanks for letting me know this is fixed now.
