### ISSUE TITLE
Keyring file does not exist

### ISSUE THREAD

**Issue by zhubaiming** [boredazfcuk/docker-icloudpd#349]
When i config the

user=root
user_id=0
group=root
group_id=0

in the config file.

```
nter iCloud password for xxxxxxxx@qq.com: 
Save password in keyring? [y/N]: y

Two-step authentication required. 
Please enter validation code
(string) --> 368083

ERROR    Keyring file does not exist. Please try again.
```

The 'keyring_pass.cfg' file in the '/root/.local/share/python_keyring/keyring_pass.cfg' path, but not in the '/config/python_keyring' path.

But if I exec the docker container, I can do 'cp'or'mv' the 'keyring_pass.cfg' file to the '/config/python_keyring' path.
When I did this operation,it works properly.

I don't know if there is something wrong with my configuration or it's a bug.

Please reply to me,thanks!

**Comment by boredazfcuk** [comment]
I've pushed a new container which applies file ownership differently. Hopefully it should work now. I have completely removed my /config folder and the script saved my keyring/cookie without issue.

If you still have a problem, please message back.
