### ISSUE TITLE
something error of notification_title

### ISSUE THREAD

**Issue by zhubaiming** [boredazfcuk/docker-icloudpd#350]
I from China, so some configures I will write Chinese.

In the 'icloudpd.conf' file, I use 'notification_type' is Webhook.
But if I write the value of volume 'notification_title' in Chinese like '你好', the webhook(nginx) can get the request body like '??'.
And if I use Laravel to request, I can't get the body.

I don't know it's the bug of the 'notification_title' in Chinese or some errors of the config of nginx/Laravel.

Please help me.

Thanks!

**Comment by zhubaiming** [comment]
The question is in the file 'sync-icloud.sh' on line 395 `notification_title="${notification_title//[^a-zA-Z0-9_ ]/}"`.

It will filter Chinese!

**Comment by boredazfcuk** [comment]
This was done to sanitise the code. Certain non alpha-numeric characters will break the commands that send the notifications. I've amended the code so that this clean-up of the notification title does not happen when using WeCom, IYUU and Dingtalk.

**Comment by boredazfcuk** [comment]
Closing this as no response in over two weeks.
