### ISSUE TITLE
how to download all photos but Screenshots

### ISSUE THREAD

**Issue by jinnxu75** [boredazfcuk/docker-icloudpd#352]
photo album="All Photos"
skip_albums= "Screenshots,Recently Deleted"

Does it work with the parameters above? 

I would like to also keep the original folder structer with %Y/%M/%D, the para "photo album" will change the folder structer or not?

Thank you so much for this awsome app.

**Comment by boredazfcuk** [comment]
It should do... but...

I don't use the feature myself as there are problems with it. Every folder will start it's own download run, and authenticate against Apple servers. Authenticate too many times in quick succession, and Apple will force you to re-confirm your multi-factor authentication code. I hit this problem a lot in testing when restarting my container.

If you're attempting to download 5-10 different folders in one go, you're probably going to have to re-authenticate your MFA code every time a sync occurs. It's not worth it IMHO, may as well stick to "All Photos".

**Comment by boredazfcuk** [comment]
In answer to your other question, you can download an album to a folder with the same name, then keep the dates folder structure inside that album, by setting **albums_with_dates=true** in your config file.

**Comment by jinnxu75** [comment]
Thanks a lot.

I will just leave the screenshots there :)
