### ISSUE TITLE
icloudpd  Successful startup, login error 

### ISSUE THREAD

**Issue by MagicStarTrace** [boredazfcuk/docker-icloudpd#356]
sync-icloud.sh --Initialise 

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/15685376/7a11a29f-1037-4f3e-8018-4fe8826eaa26)
 
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/15685376/86c03829-c9ef-4116-af6f-a970cfa48d46)

**Comment by boredazfcuk** [comment]
Apple wants you to login to China servers but you haven't configured the container to do so.

**Comment by MagicStarTrace** [comment]
> Apple wants you to login to China servers but you haven't configured the container to do so.

Where can I configure to use china's server?

**Comment by boredazfcuk** [comment]
Set the **icloud_china** and **auth_china** variables to **true**
