### ISSUE TITLE
Strange Embedded Folders

### ISSUE THREAD

**Issue by schellbell** [boredazfcuk/docker-icloudpd#357]
I am finding random embedded folders that I cannot explain. For example, in 2015>10>09 there is an additional folder titled 20151009-162725, and within this folder is a photo dated 2019-06-07. Is this expected behavior? I have found and checked that photo in my iCloud library and there is it dated correctly as 2019-06-07. 

Furthermore, if I navigate in my downloaded folder to 2019>06>07, there is nothing there. Any suggestions?

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/26511627/61d80624-7f17-4137-9d03-6f3a16ddc999)
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/26511627/15077a75-2000-4771-8bde-6f19072ee220)

**Comment by schellbell** [comment]
I should add I've found dozens (or more) instances of this happening throughout my downloaded library

**Comment by schellbell** [comment]
**folder_structure** is blank, which my understanding means it defaults to {:%Y/%m/%d}. 

I have a few albums in folders in iCloud, but the issue doesn't seem to be unique to photos in those folders (ie not all photos in folders in iCloud download like this, and there are also plenty of photos that aren't in a folder which also download this way)

**Comment by boredazfcuk** [comment]
The container just mimics logging into icloud.com and downloading the photos.

If you remove them from your NAS/Server and re-run the script, does it download them to those locations again?

Are you also using HEIC to JPEG conversion? It could be something to do with that, I guess.

**Comment by boredazfcuk** [comment]
Closing this off as I couldn't duplicate it at all. Must be something to do with the folder_structure variable
