### ISSUE TITLE
Nothing happens after Keyring file exists, continuing

### ISSUE THREAD

**Issue by WilliamThomson8** [boredazfcuk/docker-icloudpd#365]
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Keyring file exists, continuing
-- | -- | --
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Directory is writable: /home/user/.local/share/
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Directory is writable: /config/python_keyring/
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Failsafe file iCloud/.mounted exists, continuing
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Check download directory mounted correctly...
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Directory is writable: /home/user/.local/share/
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Directory is writable: /config/python_keyring/
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Ignore Synology extended attribute directories: Disabled
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Authentication domain: com
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Downloading from: icloud.com
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Convert HEIC to JPEG: false
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Skip videos: false
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Live photo size: original
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Downloading photos from album: Download All Photos
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Number of most recently added photos to download: Download All Photos
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Skip live photos: false
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Skip download check: false
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Single pass mode: false
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Photo size: original
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Delete after download: false
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Auto delete: false
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Set EXIF date/time: false
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Synchronisation delay (minutes): 0
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Synchronisation interval: 86400
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Folder structure: {:%Y/%m/%d}
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Download destination directory: iCloud
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Cookie expiry notification period: 7
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Cookie path: /config/kelvinszeto58gmailcom
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Authentication Type: MFA
2023/08/02 21:08:27 | stdout | 2023-08-02 21:08:27 INFO     Apple ID: kelvinszeto58@gmail.com
2023/08/02 21:08:26 | stdout | 2023-08-02 21:08:26 INFO     Loading configuration from: /config/icloudpd.conf
2023/08/02 21:08:26 | stdout | 2023-08-02 21:08:26 INFO     Python version: 3.11.4
2023/08/02 21:08:26 | stdout | 2023-08-02 21:08:26 INFO     Alpine Linux 3.18.2
2023/08/02 21:08:26 | stdout | 2023-08-02 21:08:26 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023/08/02 21:08:26 | stdout | 2023-08-02 21:08:26 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.623 started *****

**Comment by boredazfcuk** [comment]
Can you update to the latest version and post another log please? I'm guessing it's unexpectedly entering some part of the code which does not perform any logging, so I've added some logging to those parts, which should give me a better clue at to where it's going wrong.
Also, can you set **enable_debugging=true** in your '/config/icloudpd.conf` file, please?

**Comment by bsmeding** [comment]
same here,
enabled debug logging (in config file there was no 'enable_debugging=true' option only 'debug_logging=true') now both debug logging options in de config file, without any changes

nothing happend after restart

**Comment by boredazfcuk** [comment]
This should be resolved in the latest version of the container. A change was made in an upstream dependency which resulted in all logging being sent to the stderr so it didn't show in the standard log. This has since been fixed and my container rebuilt.
