### ISSUE TITLE
Bark startup notification failed with status code: 000

### ISSUE THREAD

**Issue by yushangcl** [boredazfcuk/docker-icloudpd#367]
2023/8/5 13:53:52  2023-08-05 13:53:52 ERROR    Bark startup notification failed with status code: 000

config

bark_device_key=r3isE2******
bark_server=https://xxx.xxx.cn

ping https://xxx.xxx.cn ok

**Comment by HuLuXi** [comment]
不能加https

**Comment by HuLuXi** [comment]
解决了吗？

**Comment by yushangcl** [comment]
> 解决了吗？

解决了

**Comment by HuLuXi** [comment]
> 

咋弄啊

**Comment by HuLuXi** [comment]
我是提示代码400 也是bark

**Comment by Arnold4869** [comment]
你也试试别用域名，用192.168之类的ip试试

**Comment by zhengran14** [comment]
用http，不要用https

**Comment by boredazfcuk** [comment]
This is likely a DNS issue as similar problems have been reported and that was the cause of the 000 errors. Please check DNS servers can be contacted on TCP + UDP port 53.
