### ISSUE TITLE
How to Download Portrait Photos？

### ISSUE THREAD

**Issue by dongdong-2020** [boredazfcuk/docker-icloudpd#372]
Hello
I use icloudpd to download photos from iphone, and the downloaded portrait photos are not the original ones. How can I solve this? How can I make the downloaded photos the same as those seen on the phone.
For example, the background of the original portrait photo is blurred, but the downloaded photo does not.

**Comment by boredazfcuk** [comment]
Hi,

Unfortunately, the short answer is that you can't.

The photo that has been downloaded is the original. The "portrait" picture is an after-effect that is applied to the photo when you view the file on an iDevice. The same is true for any filters or edits made to the files.

The after effect files can be viewed on an iDevice when connected to a computer via USB. These after effect files (.AAE IIRC) can be opened in a text editor where the payload is encrypted. Unless someone figures out how to change that encrypted content into an overlay, and then apply that to to the photo, then we're stuck with only being able to download the original.
