### ISSUE TITLE
Bark startup notification failed with status code: 400

### ISSUE THREAD

**Issue by HuLuXi** [boredazfcuk/docker-icloudpd#382]
like the title, then it dont go next (nothing happan like the log)
and i have update the image, the older could run well, and the newest couldnot with the same setting.

**Comment by boredazfcuk** [comment]
The code used in Bark notifications was submitted via a PR. I have no way of debugging/testing it myself, so unless someone else can step up and diagnose the fault/submit a PR to fix it, then I'll just close it off in a month as unplanned.

**Comment by Arnold4869** [comment]
我用中文说了，你试试把bark地址改为192.168开头的地址，别用域名，我现在就这么使用的

**Comment by HuLuXi** [comment]
> 我用中文说了，你试试把bark地址改为192.168开头的地址，别用域名，我现在就这么使用的

我试了 不顶用

**Comment by ershouqingge** [comment]
发一下你的配置

**Comment by HuLuXi** [comment]
> The code used in Bark notifications was submitted via a PR. I have no way of debugging/testing it myself, so unless someone else can step up and diagnose the fault/submit a PR to fix it, then I'll just close it off in a month as unplanned.

i found that the service of bark should contain the port, and http:// or https:// can not there
so only 192.6.X.X:XXX or XX.X.com:80 will goes well
if not the photo download will never starts, and it will post 400(for the prefixes : http or https) or 000(for port) error code

**Comment by boredazfcuk** [comment]
> i found that the service of bark should contain the port, and http:// or https:// can not there so only 192.6.X.X:XXX or XX.X.com:80 will goes well if not the photo download will never starts, and it will post 400(for the prefixes : http or https) or 000(for port) error code

Thanks for this. I've updated the configuration guide to explain the errors that will be reported if the server is not configured in this specific way.

**Comment by HuLuXi** [comment]
> > i found that the service of bark should contain the port, and http:// or https:// can not there so only 192.6.X.X:XXX or XX.X.com:80 will goes well if not the photo download will never starts, and it will post 400(for the prefixes : http or https) or 000(for port) error code
> 
> Thanks for this. I've updated the configuration guide to explain the errors that will be reported if the server is not configured in this specific way.

> e.g. [https://server.domain.com:443](https://server.domain.com/): or [http://127.16.0.1:80](http://127.16.0.1/). Failure to include the http/https prefix with result in error code 400 and failure to include the port will result in a 000 error.

no, the coorrect is server. domain. com:443 or 127.16.0.1:80
the http ot https **must not be** included
