### ISSUE TITLE
Albums within Folders

### ISSUE THREAD

**Issue by gxander85** [boredazfcuk/docker-icloudpd#386]
I have a folder in my iCloud library for my photography work. Within that folder I have five albums that I wish to download using the download albums function. However, I cannot figure out how to access these. These albums also do not appear in the log, only the parent folder does.

Structure is:
Folder: XANDER85 Photography
Albums within: Gallery, Vertical, Square, Logo, Instagram

I wanted to download them into a dir on my NAS into iCloud/XANDER85 Photography and then sub dirs for each album.

How can I achieve this?

**Comment by boredazfcuk** [comment]
The upstream package used to download photos doesn't support downloading to folders unfortunately. If it ever does, I will add that functionality.
