### ISSUE TITLE
Feature Request - Add until-found option

### ISSUE THREAD

**Issue by BuSHari** [boredazfcuk/docker-icloudpd#39]
Hi,

Can you please add a variable for the until-found option?

Thanks...

**Comment by boredazfcuk** [comment]
Hi,

I've added a `until_found` variable. Please test and reopen the issue if it doesn't work as expected.

Thanks.

**Comment by BuSHari** [comment]
Thanks i see its working, but under your functions 'CheckFiles()' and 'Generate2FACookie()' you are not using that option and it's still read the whole library.


Thankds...

**Comment by boredazfcuk** [comment]
Generate2FACookie() uses `--recent 0` so doesn't read any files...

CheckFiles() has to read all files to determine if files exist on the server which do not exist on disk.

**Comment by BuSHari** [comment]
OK understood... thanks!
