### ISSUE TITLE
Private db access disabled for this account

### ISSUE THREAD

**Issue by ramirezrick** [boredazfcuk/docker-icloudpd#390]
I'm an't get it to work. I keep seeing this on the logs:

> 2023-09-10 10:15:17 INFO     Check for new files using password stored in keyring file
> 2023-09-10 10:15:17 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
> **private db access disabled for this account.  Please wait a few minutes then try again.  The remote servers might be trying to throttle requests. (ACCESS_DENIED)**
> 2023-09-10 10:15:20 ERROR    Failed check for new files files
> 2023-09-10 10:15:20 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
> 2023-09-10 10:15:20 ERROR    Error debugging info:
> 2023-09-10 10:15:20 ERROR    
> 2023-09-10 10:15:20 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
> 2023-09-10 10:15:20 INFO     Web cookie expires: 2023-11-09 @ 13:28:16
> 2023-09-10 10:15:20 INFO     Two factor authentication cookie expires: 2023-12-09 @ 13:28:30
> 2023-09-10 10:15:20 INFO     Days remaining until expiration: 90
> 2023-09-10 10:15:20 INFO     Synchronisation ended at 10:15:20
> 2023-09-10 10:15:20 INFO     Total time taken: 00:00:03
> 2023-09-10 10:15:20 INFO     Next synchronisation at 10:15:17

**Comment by martinbjeldbak** [comment]
Do you have iCloud Advanced Data Protection (https://support.apple.com/en-au/HT212520) on by any chance? Seems like this may be culprit as per https://github.com/boredazfcuk/docker-icloudpd/issues/109#issuecomment-1658207395

**Comment by johnhaley81** [comment]
Is there any way to get this to work AND have ADP on?

**Comment by AndreyNikiforov** [comment]
> work AND have ADP o

`icloudpd` downloads photos emulating web access. ADP blocks web access by default. ADP seems to allow enabling web access for short period of time (~1hr), so you may try that path.

**Comment by ramirezrick** [comment]
> Do you have iCloud Advanced Data Protection (https://support.apple.com/en-au/HT212520) on by any chance? Seems like this may be culprit as per [#109 (comment)](https://github.com/boredazfcuk/docker-icloudpd/issues/109#issuecomment-1658207395)

Once I turned it off, it worked. Thanks.
