### ISSUE TITLE
Failsafe file ... ile is not present. Waiting for failsafe file to be created... Help Please

### ISSUE THREAD

**Issue by authorleon** [boredazfcuk/docker-icloudpd#394]
I am using a QANP with your docker, after hours, I think i am at the last step. 

I am getting this error. 

2023-09-23 17:35:33 WARNING  Failsafe file /share/1_cloud_storage_sync_LIVE/iCloud//.mounted file is not present. Waiting for failsafe file to be created...

If someone could please help as I am a little lost. 

I have create the .mount file but now joy

**Comment by hbierik** [comment]
The file must be named .mounted and not .mount and it looks like you have one / too much in the paths that you configured.

**Comment by authorleon** [comment]
Hi, Sorry about that. It was rather late. Okay. I am getting this same issue: 

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/32468012/02e0b2e2-a69c-442f-9e5f-ee09b5af9ba2)

**Comment by authorleon** [comment]
I updated the config with the above file path as well. Still no joy:

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/32468012/e68261ed-c57a-4935-9d0e-9f0dd2e91c5e)

**Comment by authorleon** [comment]
Hi, anyone? I am sure I am missing something simple here.

**Comment by boredazfcuk** [comment]
Looks like the /share/ZFS22_DATA/ volume isn't connected to your container.

**Comment by authorleon** [comment]
okay, is that done through moutns? If so, how would I do that? I did look on google. But I am not quite sure.

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/32468012/513f2e87-e1f4-4433-bf0c-68e7d5dc40d0)

Please let me know, thank you

**Comment by Floki-78** [comment]
> okay, is that done through moutns? If so, how would I do that? I did look on google. But I am not quite sure.
> 
> ![image](https://user-images.githubusercontent.com/32468012/270897807-513f2e87-e1f4-4433-bf0c-68e7d5dc40d0.png)
> 
> Please let me know, thank you

It is a simple .txt file with the extension renamed to .mounted and placed in the folder your photos are saved to.

**Comment by authorleon** [comment]
Yes, I have done that. But sill nothing 

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/32468012/4c7635e6-3737-4cf0-ad5d-9ae8399f7977)

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/32468012/484e7118-6f75-4287-87a8-c2fe5c7422f5)

**Comment by authorleon** [comment]
you mean txt.mounted?

**Comment by Floki-78** [comment]
> Yes, I have done that. But sill nothing
> 
> ![image](https://user-images.githubusercontent.com/32468012/270963320-4c7635e6-3737-4cf0-ad5d-9ae8399f7977.png)
> 
> ![image](https://user-images.githubusercontent.com/32468012/270963349-484e7118-6f75-4287-87a8-c2fe5c7422f5.png)
> 
> Whatever path I try to put, I get the same thing.
> 
> Please, if you could help me with this, Even if we need to Teamview. I appreciate it a lot.

Your container is not mapped to your download destination, hence why .mounted is not being found.

**Comment by Floki-78** [comment]
The paths that you posted images of do not correspond to what the output of icloudpd is looking for…
.mounted needs to placed into /home/user/icloud/

**Comment by authorleon** [comment]
Hi, 

Please have a look

The structure was made in root.

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/32468012/5950adf6-c64c-44bf-ac66-78c714fc94d5)

**Comment by authorleon** [comment]
Okay, I am making progress. 

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/32468012/a83b68e7-9141-4e79-9a51-2a0749d76040)

Now I am trying to find out where the files are.

**Comment by Floki-78** [comment]
> Hi,
> 
> Please have a look
> 
> The structure was made in root.
> 
> ![image](https://user-images.githubusercontent.com/32468012/270997060-5950adf6-c64c-44bf-ac66-78c714fc94d5.png)

Thats correct, which leads me to believe that you havent mapped the container download folder with your nas home folder.

**Comment by authorleon** [comment]
Okay, you are right. Question, is it safe to put the container in the root?

**Comment by Floki-78** [comment]
> Okay, you are right. Question, is it safe to put the container in the root?

I honestly dont know mate… i use docker installed from the app store and portainer to manage the containers. 
In some instances you may have to allow the container permission to access certain root folders.
