### ISSUE TITLE
private db access disabled for this account

### ISSUE THREAD

**Issue by gxander85** [boredazfcuk/docker-icloudpd#397]
I am receiving the following error and I suspect it might have to do with Advanced Data Protection launched in the recent iCloud updates. I have since disabled the service, but I can no longer access my photo library via the web. iCloud sync between devices appears to be working fine.

Wondering if anyone else has experienced this issue?

**Comment by boredazfcuk** [comment]
From CONFIGURATION.MD:

>If you have enabled Apple's Advanced Data Protection feature in iOS 16.2, you will need to disable it. This feature encrypts your photos on icloud.com and means it can only be accessed from your trusted devices, as Apple no longer stores your encryption keys on their servers. I presume that the Photos section of icloud.com will no longer allow you to view photos with the Advanced Data Protection option enabled.

This container emulates logging in to iCloud.com, navigating to Photos and downloading them. ADP disables this functionality.
