### ISSUE TITLE
Nextcloud upload 404 -- trailing / missing

### ISSUE THREAD

**Issue by hollanbm** [boredazfcuk/docker-icloudpd#415]
I'm getting the following error(s) when syncing up to nextcloud. It looks like the trailing slash on the end of the directory name is missing. `<s:message>File with name //iCloud2020 could not be located</s:message>`. I updated my config file, to add a `/` but it was removed on startup when I checked the config file inside the container.

All of the directories inside nextcloud are created successfully, but the files themselves aren't uploaded

image version
```
docker image ls | grep icloudpd
boredazfcuk/icloudpd            latest    d7cd7b012805   6 days ago     383MB
```

error message
```
2023-10-16 21:25:43 DEBUG    Full filename: /home/hollanbm/iCloud/2020/03/25/IMG_1593.HEIC
2023-10-16 21:25:43 DEBUG    Base filename: IMG_1593.HEIC
2023-10-16 21:25:43 DEBUG    New filename: 2020/03/25/IMG_1593.HEIC
2023-10-16 21:25:43 DEBUG    Directory name: 2020/03/25/
2023-10-16 21:25:43 DEBUG    Nextcloud file path: 2020/03/25
2023-10-16 21:25:43 INFO     Uploading /home/hollanbm/iCloud/2020/03/25/IMG_1593.HEIC to https://nextcloud.thehollandfam.com/remote.php/dav/files/hollanbm/iCloud2020/03/25/IMG_1593.HEIC... ash: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name //iCloud2020 could not be located</s:message>
</d:error>
404: out of range
Unexpected response: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name //iCloud2020 could not be located</s:message>
</d:error>
404
```

docker-compose.yml
```yaml
version: '3.8'
services:
  icloudpd:
    container_name: icloudpd
    image: boredazfcuk/icloudpd:latest
    healthcheck:
      test: /usr/local/bin/healthcheck.sh
      start_period: 30s
    restart: always
    environment:
      - TZ=America/Kentucky/Louisville
    volumes:
      - icloud_nfs:/home/hollanbm/iCloud
      - ${HOME:?err}/iCloudPD:/config

volumes:
  icloud_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.254.1.99,rw,noatime
      device: ":/mnt/Share/iCloud/Brad"

```

icloudpd.conf
```
agentid=
albums_with_dates=false
apple_id=brad@mydomain.com
auth_china=false
authentication_type=MFA
auto_delete=true
bark_device_key=
bark_server=
content_source_url=
convert_heic_to_jpeg=false
debug_logging=true
delete_accompanying=false
delete_after_download=false
delete_notifications=true
dingtalk_token=
directory_permissions=775
discord_id=
discord_token=
download_notifications=true
download_path=/home/hollanbm/iCloud/
file_permissions=0775
folder_structure={:%Y/%m/%d}
gotify_app_token=
group=hollanbm
group_id=1000
icloud_china=
iyuu_token=
jpeg_path=
jpeg_quality=90
libraries_with_dates=false
live_photo_size=original
media_id_delete=
media_id_download=
media_id_expiration=
media_id_startup=
media_id_warning=
nextcloud_delete=true
nextcloud_password=<password>
nextcloud_target_dir=iCloud/
nextcloud_upload=true
nextcloud_url=https://nextcloud.mydomain.com
nextcloud_username=hollanbm
notification_days=7
notification_type=Pushover
photo_album=
photo_library=
photo_size=original
prowl_api_key=
pushover_sound=pushover
pushover_token=<token>
pushover_user=<user>
recent_only=
set_exif_datetime=false
single_pass=false
skip_album=
skip_check=true
skip_download=false
skip_library=
skip_live_photos=false
skip_videos=false
synchronisation_delay=0
synchronisation_interval=86400
synology_ignore_path=false
telegram_chat_id=
telegram_polling=false
telegram_server=
telegram_silent_file_notifications=
telegram_token=
touser=
trigger_nextlcoudcli_synchronisation=
until_found=
user=hollanbm
user_id=1000
webhook_https=false
webhook_id=
webhook_path=/api/webhook/
webhook_port=8123
webhook_server=
wecom_id=
wecom_proxy=
wecom_secret=
```

**Comment by hollanbm** [comment]
I think this is the offending line of code
https://github.com/boredazfcuk/docker-icloudpd/blob/master/sync-icloud.sh#L1306C1-L1306C309

Should be

`curl_response="$(curl --silent --show-error --location --user "${nextcloud_username}:${nextcloud_password}" --write-out "%{http_code}" --upload-file "${full_filename%.HEIC}.JPG" "${nextcloud_url%/}/remote.php/dav/files/${nextcloud_username}/${nextcloud_target_dir}/${nextcloud_file_path}/${base_filename%.HEIC}.JPG")"`

missing the trailing `/` after ${nextcloud_target_dir}

**Comment by boredazfcuk** [comment]
Hi,
Set `download_path=`
Thanks.

**Comment by hollanbm** [comment]
> Hi, Set `download_path=` and `nextcloud_target_dir=iCloud` I think that should work. Thanks.
That worked!

I did notice this pop up in the debug logs
```
2023-10-18 19:45:45 INFO     Uploading /home/hollanbm/iCloud/2020/10/23/My Movie.mov to https://nextcloud.thehollandfam.com/remote.php/dav/files/hollanbm/iCloud/2020/10/23/My Movie.mov... curl: (3) URL using bad/illegal format or missing URL
Unexpected response: 000
```

I don't know how this filename got spaces in it. But it caused an exception on the curl upload since the params weren't URL encoded.

What cryptocurrency do you prefer? I appreciate the help/support over these past few issues of mine, and I want to send some cash your way to say thanks.

**Comment by boredazfcuk** [comment]
I've pushed a new version which encodes the URL for Nextcloud. It should now handle filenames with spaces. You made me realise that if people are downloading from albums, then their folder structure could have spaces and other special characters in the folder names.

It's probably worth running a `sync-icloud.sh --Upload-Library-To-Nextcloud` so that it will push your whole library up to Nextcoud, so it can fill in the ones that have been missed.

I don't really mind which crypto, thanks. I tend to use LTC for donating to Open Source projects and online transactions where I can. I'm holding ETH long term and didn't have any BTC until about a month ago when I got my first donation. At least I think it was, I just woke up one morning to find a random transaction lol

**Comment by hollanbm** [comment]
> I've pushed a new version which encodes the URL for Nextcloud. It should now handle filenames with spaces. You made me realise that if people are downloading from albums, then their folder structure could have spaces and other special characters in the folder names.
> 
> It's probably worth running a `sync-icloud.sh --Upload-Library-To-Nextcloud` so that it will push your whole library up to Nextcoud, so it can fill in the ones that have been missed.
> 
> I don't really mind which crypto, thanks. I tend to use LTC for donating to Open Source projects and online transactions where I can. I'm holding ETH long term and didn't have any BTC until about a month ago when I got my first donation. At least I think it was, I just woke up one morning to find a random transaction lol

Thanks for the help and quick fixes. Sent some LTC your way

**Comment by boredazfcuk** [comment]
Received... I had an email today telling me one of my domains is up for renewal so I'll put it towards that. Thanks.
