### ISSUE TITLE
Use Title as Filename

### ISSUE THREAD

**Issue by gxander85** [boredazfcuk/docker-icloudpd#417]
Is there functionality to use the Title as the Filename? I record a lot of videos that I then rename the Title and Caption to identify what they are. Being able to set this as an option, similar to how the export with Title as Name in Photos.app works, would see the downloaded file identified as it is in the Photo Library. Would make it much easier to find a file locally on my NAS should I need it.

**Comment by boredazfcuk** [comment]
That's not something that is possible at the moment. The only thing I could think would be to install a photo management container, such as PhotoPrism or Immich and point it to the iCloud download directory. If the metadata is still in the files, I'm guessing they would be able to find it.

I've no idea how true this is. Having a play around with these two applications is on my to do list, but I've heard they are both make finding photos a lot easier.

**Comment by boredazfcuk** [comment]
Closing as this isn't something which is currently supported, as iCloud only allows downloading via filename.
