### ISSUE TITLE
Moved photos from PrimarySync to SharedSync exist in both

### ISSUE THREAD

**Issue by Se7enair** [boredazfcuk/docker-icloudpd#418]
I use three different containers. One for my PrimarySync, one for the PrimarySync of my wife and one for the SharedSync.

Now I take a photo which is first saved in my private library. icloudpd syncs and downloads the photo to my PrimarySync folder.
After that I move the photo to the shared Library. Now the icloudpd for the SharedSync starts and download the photo again.

What I want is, that icloudpd recognizes moved photos and deletes them if there a not in the synced library anymore.

Is there already a way to do so? And if not, is it possible to implement?

**Comment by boredazfcuk** [comment]
Hi,
That's not possible to do within the container. Each container is a separate entity so has no knowledge of what the other is doing. It also doesn't track photos, it will just scan what's on icloud, and download anything which is missing, then remove anything that is in the 'Recently Deleted' album.

If the file is no longer in your PrimarySync and not in the 'Recently Deleted' album, then it would need to be removed manually. This is the same as when a photo is deleted, then removed from 'Recently Deleted' before a sync is performed. The container will never know the file has gone and manual removal is required.

I wouldn't be able to implement anything to resolve this. My project is just a container which just wraps additional functionality around the icloudpd application (https://github.com/icloud-photos-downloader/icloud_photos_downloader). If this capability was added to the upstream application, then I will add in the requires configuration options to allow that to work in my container.
