### ISSUE TITLE
pyicloud_ipd.exceptions.PyiCloudAPIResponseError

### ISSUE THREAD

**Issue by tst-pandit-pan** [boredazfcuk/docker-icloudpd#427]
I guess this is caused by Advanced Data Protection.

pyicloud_ipd.exceptions.PyiCloudAPIResponseError: private db access disabled for this account.  Please wait a few minutes then try again.  The remote servers might be trying to throttle requests. (ACCESS_DENIED)

Adding some prompt should do the job, thanks

<img width="1440" alt="Screenshot 2023-11-12 at 8 42 55 PM" src="https://github.com/boredazfcuk/docker-icloudpd/assets/112232636/f8b4b3c5-57b3-4329-9469-b0253dfb930b">

**Comment by boredazfcuk** [comment]
ADP is not currently supported in the upstream application that my container uses to perform the downloads: https://github.com/icloud-photos-downloader/icloud_photos_downloader

If the feature is added upstream, I can add it in, but it's development is not something I would be involved with.
