### ISSUE TITLE
livePhoto   _HEVC后缀能去掉吗? 

### ISSUE THREAD

**Issue by yunxiaofeng1001** [boredazfcuk/docker-icloudpd#429]
livePhoto 下载后两个文件. XXXX.HEIC   XXXX_HEVC.MOV  下载mov文件的时候有配置项可以删除_HEVC 后缀吗?

**Comment by ceozero** [comment]
+1  命名不一样无法导回手机啊。

**Comment by boredazfcuk** [comment]
I can't understand any of this.
