### ISSUE TITLE
Errors received when iCloud folder has special characters in the name

### ISSUE THREAD

**Issue by tchrischan** [boredazfcuk/docker-icloudpd#432]
It appears album names with parens and ampersands are not properly handled:

`2023-11-20 19:48:57 INFO     Downloading album: Esurance ( Clickercall
ash: syntax error: unexpected "(" (expecting ")")`

`2023-11-20 19:49:39 INFO     Downloading album: Caves & Busters
ash: Busters: not found`

**Comment by boredazfcuk** [comment]
I think this should work now. I don't think it was escaped properly, and recently spotted that, so amended it
