### ISSUE TITLE
Struggling to get an upload to Nextcloud working

### ISSUE THREAD

**Issue by gbeynon99** [boredazfcuk/docker-icloudpd#434]
I'm runnin Nextcloud-AIO on Unraid - everything works fine except the upload to Nextcloud. 

2023-11-27 10:41:22 INFO     Upload files to Nextcloud
2023-11-27 10:41:22 INFO     Checking Nextcloud connectivity...
2023-11-27 10:41:22 ERROR    Nextcloud connectivity check failed: 401

I am a total noob to this - where do I start looking?

nextcloud_delete=false
nextcloud_password=xxxxxx
nextcloud_target_dir=Photos
nextcloud_upload=true
nextcloud_url=http://192.168.1.99:11000
nextcloud_username=xxxx@xxxx.com

**Comment by boredazfcuk** [comment]
Try changing to:
```
nextcloud_delete=false
nextcloud_password=xxxxxx
nextcloud_target_dir=Photos
nextcloud_upload=true
nextcloud_url=http://192.168.1.99:11000/
nextcloud_username=xxxx
```
Note the trailing slash on the `nextcloud_url` and also the `nextcloud_username` is not in the e-mail address format. This username is actually used to build the WebDAV path to the files:
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/14807258/9123d8eb-bc14-4df2-bccf-0aa6ffe66a8f)

**Comment by boredazfcuk** [comment]
Closing as no response in over a month.
