### ISSUE TITLE
Second Instance of iCloudpd on Unraid - getting "Bad username or password"

### ISSUE THREAD

**Issue by heelphan** [boredazfcuk/docker-icloudpd#442]
Hello,
I have been using icloudpd for several months now on my Unraid server.  I have spun up a second instance (named iCloudpd-1) to back up my partner's photos.  When I run the `sync-icloud.sh --Initialise` command, I get to where I should enter the password for the iCloud account, I type in what I know to be the correct password and I get "Bad username or password".  Like I said, I know the password is correct.  I have tried manually typing it in and copying/pasting from notepad.  Have I done something wrong?  I can't really find any other instances of this happening.  I thought it possibly had something to do with the fact that this is my second instance on the server.

**Comment by gunner007cd** [comment]
Underlying iCloudPD is currently broken - Apple must've made changes.

https://github.com/boredazfcuk/docker-icloudpd/issues/441

**Comment by hukilounge** [comment]
Yep. Looks like a workaround has been discovered earlier today: [#729](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/729)

Hopefully boredazfcuk gets bored, and applies an update/fix to the Docker version  (We would really appreciate it!)

**Comment by boredazfcuk** [comment]
Latest version should work for icloud.com users and hopefully icloud.com.cn users too, but this is untested.

**Comment by boredazfcuk** [comment]
Closed as no response in over a month
