### ISSUE TITLE
ERROR    Failed to download new files

### ISSUE THREAD

**Issue by gadlou** [boredazfcuk/docker-icloudpd#444]
stdout: 2023-12-10 10:33:25 DEBUG    Authenticating...
stdout: 2023-12-10 10:33:26 ERROR    Unknown reason
stdout: 2023-12-10 10:33:26 ERROR    Failed to download new files
stdout: 2023-12-10 10:33:26 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
stdout: 2023-12-10 10:33:26 ERROR    Error debugging info:
stdout: 2023-12-10 10:33:26 ERROR    Traceback (most recent call last):
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
stdout:     req = self.session.post(
stdout:           ^^^^^^^^^^^^^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
stdout:     return self.request("POST", url, data=data, json=json, **kwargs)
stdout:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
stdout:     self._raise_error(code, reason)
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
stdout:     raise api_error
stdout: pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
stdout: 
stdout: During handling of the above exception, another exception occurred:
stdout: 
stdout: Traceback (most recent call last):
stdout:   File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
stdout:     sys.exit(main())
stdout:              ^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
stdout:     return self.main(*args, **kwargs)
stdout:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
stdout:     rv = self.invoke(ctx)
stdout:          ^^^^^^^^^^^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
stdout:     return ctx.invoke(self.callback, **ctx.params)
stdout:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
stdout:     return __callback(*args, **kwargs)
stdout:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
stdout:     core(
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
stdout:     icloud = authenticator(logger, domain)(
stdout:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
stdout:     icloud = pyicloud_ipd.PyiCloudService(
stdout:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
stdout:     self.authenticate()
stdout:   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
stdout:     raise PyiCloudFailedLoginException(msg, error)
stdout: pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
stdout: 2023-12-10 10:33:26 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
stdout: 2023-12-10 10:33:26 INFO     Web cookie expires: 2024-02-07 @ 16:27:09
stdout: 2023-12-10 10:33:26 INFO     Multifactor authentication cookie expires: 2024-03-08 @ 16:27:07
stdout: 2023-12-10 10:33:26 INFO     Days remaining until expiration: 89
stdout: 2023-12-10 10:33:26 INFO     Synchronisation ended at 10:33:26
stdout: 2023-12-10 10:33:26 INFO     Total time taken: 00:00:05
stdout: 2023-12-10 10:33:26 INFO     Next synchronisation at 22:33:21

**Comment by thedinz** [comment]
https://github.com/boredazfcuk/docker-icloudpd/issues/443

**Comment by Search-Warrent** [comment]
have the same issue.

**Comment by hukilounge** [comment]
Yep. Looks like a workaround has been discovered earlier today: [#729](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/729)

Hopefully boredazfcuk gets bored, and applies an update/fix to the Docker version  (We would really appreciate it!)

**Comment by liyangsnd** [comment]
The issue has been resolved. THX

**Comment by boredazfcuk** [comment]
Latest version should work for icloud.com users and hopefully icloud.com.cn users too, but this is untested.
