### ISSUE TITLE
possible permission problem in truechart setup

### ISSUE THREAD

**Issue by RobinQu** [boredazfcuk/docker-icloudpd#445]
I've already created an issue at [truechart](https://github.com/truecharts/charts/issues/15949). And I am feeling luck about report to upstream project in case you have more insights.

Detailed logs and chart setup is described in [the issue](https://github.com/truecharts/charts/issues/15949) as well.

Thanks!

**Comment by boredazfcuk** [comment]
> Error: Invalid value for '-d' / '--directory': Path '/home/apps/iCloud' is not readable.

I've seen this issue before when the /home/apps/iCloud directory is mounted to a directory on the host which is already mounted to a CIFS location.

**Comment by boredazfcuk** [comment]
Closed as no response in over a month. I believe this was fixed with a truechat update.
