### ISSUE TITLE
Nightly Scrape has failed for 3 days in a row

### ISSUE THREAD

**Issue by mattrowe84** [boredazfcuk/docker-icloudpd#447]
Not sure what the issue is or what changed, but was working fine for weeks and then just stopped working over the last couple of days and verified I was able to log into icloud without pop up per log's request.  Any help or suggestions?

12/13/2023 12:02:05 PM 2023-12-13 12:02:05 ERROR    Unknown reason
12/13/2023 12:02:05 PM2023-12-13 12:02:05 ERROR    Failed check for new files files
12/13/2023 12:02:05 PM2023-12-13 12:02:05 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
12/13/2023 12:02:05 PM2023-12-13 12:02:05 ERROR    Error debugging info:
12/13/2023 12:02:05 PM2023-12-13 12:02:05 ERROR    Traceback (most recent call last):
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
12/13/2023 12:02:05 PM    req = self.session.post(
12/13/2023 12:02:05 PM          ^^^^^^^^^^^^^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
12/13/2023 12:02:05 PM    return self.request("POST", url, data=data, json=json, **kwargs)
12/13/2023 12:02:05 PM           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
12/13/2023 12:02:05 PM    self._raise_error(code, reason)
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
12/13/2023 12:02:05 PM    raise api_error
12/13/2023 12:02:05 PMpyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
12/13/2023 12:02:05 PM
12/13/2023 12:02:05 PM During handling of the above exception, another exception occurred:
12/13/2023 12:02:05 PM
12/13/2023 12:02:05 PM Traceback (most recent call last):
12/13/2023 12:02:05 PM File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
12/13/2023 12:02:05 PM   sys.exit(main())
12/13/2023 12:02:05 PM             ^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
12/13/2023 12:02:05 PM    return self.main(*args, **kwargs)
12/13/2023 12:02:05 PM           ^^^^^^^^^^^^^^^^^^^^^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
12/13/2023 12:02:05 PM    rv = self.invoke(ctx)
12/13/2023 12:02:05 PM         ^^^^^^^^^^^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
12/13/2023 12:02:05 PM    return ctx.invoke(self.callback, **ctx.params)
12/13/2023 12:02:05 PM           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
12/13/2023 12:02:05 PM    return __callback(*args, **kwargs)
12/13/2023 12:02:05 PM           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
12/13/2023 12:02:05 PM    core(
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
12/13/2023 12:02:05 PM    icloud = authenticator(logger, domain)(
12/13/2023 12:02:05 PM            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
12/13/2023 12:02:05 PM    icloud = pyicloud_ipd.PyiCloudService(
12/13/2023 12:02:05 PM            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
12/13/2023 12:02:05 PM    self.authenticate()
12/13/2023 12:02:05 PM  File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
12/13/2023 12:02:05 PM    raise PyiCloudFailedLoginException(msg, error)
12/13/2023 12:02:05 PM pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.',
 PyiCloudAPIResponseError('Unknown reason'))
12/13/202312:02:05 PM 2023-12-13 12:02:05 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
12/13/202312:02:05 PMash: out of range

**Comment by boredazfcuk** [comment]
Latest version should now resolve this issue for icloud.com users and hopefully icloud.com.cn users (but this is untested).
