### ISSUE TITLE
Error, Unknown Reason, Can not download files.

### ISSUE THREAD

**Issue by fishmanxp** [boredazfcuk/docker-icloudpd#449]
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 INFO     Next synchronisation at 22:28:19
-- | -- | --
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 INFO     Total time taken: 00:00:01
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 INFO     Synchronisation ended at 22:28:20
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 INFO     Days remaining until expiration: 83
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 INFO     Multifactor authentication cookie expires: 2024-03-07 @ 14:00:01
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 INFO     Web cookie expires: 2024-02-06 @ 13:59:49
2023/12/14 22:28:20 | stdout | ash: out of range
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023/12/14 22:28:20 | stdout | pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
2023/12/14 22:28:20 | stdout | raise PyiCloudFailedLoginException(msg, error)
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
2023/12/14 22:28:20 | stdout | self.authenticate()
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
2023/12/14 22:28:20 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/14 22:28:20 | stdout | icloud = pyicloud_ipd.PyiCloudService(
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
2023/12/14 22:28:20 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/14 22:28:20 | stdout | icloud = authenticator(logger, domain)(
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
2023/12/14 22:28:20 | stdout | core(
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
2023/12/14 22:28:20 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/14 22:28:20 | stdout | return __callback(*args, **kwargs)
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2023/12/14 22:28:20 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/14 22:28:20 | stdout | return ctx.invoke(self.callback, **ctx.params)
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2023/12/14 22:28:20 | stdout | ^^^^^^^^^^^^^^^^
2023/12/14 22:28:20 | stdout | rv = self.invoke(ctx)
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
2023/12/14 22:28:20 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/14 22:28:20 | stdout | return self.main(*args, **kwargs)
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2023/12/14 22:28:20 | stdout | ^^^^^^
2023/12/14 22:28:20 | stdout | sys.exit(main())
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
2023/12/14 22:28:20 | stdout | Traceback (most recent call last):
2023/12/14 22:28:20 | stdout |  
2023/12/14 22:28:20 | stdout | During handling of the above exception, another exception occurred:
2023/12/14 22:28:20 | stdout |  
2023/12/14 22:28:20 | stdout | pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
2023/12/14 22:28:20 | stdout | raise api_error
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
2023/12/14 22:28:20 | stdout | self._raise_error(code, reason)
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
2023/12/14 22:28:20 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/14 22:28:20 | stdout | return self.request("POST", url, data=data, json=json, **kwargs)
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
2023/12/14 22:28:20 | stdout | ^^^^^^^^^^^^^^^^^^
2023/12/14 22:28:20 | stdout | req = self.session.post(
2023/12/14 22:28:20 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 ERROR    Traceback (most recent call last):
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 ERROR    Error debugging info:
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023/12/14 22:28:20 | stdout | 2023-12-14 22:28:20 ERROR    Failed check for new files files
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 ERROR    Unknown reason
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Check for new files using password stored in keyring file
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Check download directory mounted correctly...
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Keyring file exists, continuing
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Synchronisation starting at 22:28:19
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Sync user: user
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Keyring file exists, continuing
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Directory is writable: /config/python_keyring/
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Failsafe file /iCloud/.mounted exists, continuing
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Check download directory mounted correctly...
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Directory is writable: /config/python_keyring/
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Ignore Synology extended attribute directories: Disabled
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Authentication domain: cn
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Downloading from: icloud.com.cn
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Convert HEIC to JPEG: false
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Skip videos: false
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Live photo size: original
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Downloading photos from: Download All Photos
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Number of most recently added photos to download: Download All Photos
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Skip live photos: false
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Skip download check: false
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Single pass mode: false
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Photo size: original
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Delete after download: false
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Auto delete: false
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Set EXIF date/time: false
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Synchronisation delay (minutes): 0
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Synchronisation interval: 86400
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Folder structure: {:%Y/%m/%d}
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Download destination directory: /iCloud
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Cookie expiry notification period: 7
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Cookie path: /config/17161237qqcom
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Authentication Type: MFA
2023/12/14 22:28:19 | stdout | 2023-12-14 22:28:19 INFO     Apple ID: 17161237@qq.com
2023/12/14 22:27:51 | stdout | 2023-12-14 22:27:51 INFO     Loading configuration from: /config/icloudpd.conf
2023/12/14 22:27:51 | stdout | 2023-12-14 22:27:51 INFO     Python version: 3.11.5
2023/12/14 22:27:51 | stdout | 2023-12-14 22:27:51 INFO     Alpine Linux 3.18.3
2023/12/14 22:27:51 | stdout | 2023-12-14 22:27:51 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2023/12/14 22:27:51 | stdout | 2023-12-14 22:27:51 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.684 started *****

**Comment by eleaner** [comment]
similar thing happening here
suddenly - nothing changed, just stopped working

`pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))`

**Comment by eleaner** [comment]
```
 2023-12-15 18:36:02 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
 2023-12-15 18:36:03 ERROR    Unknown reason
 2023-12-15 18:36:03 ERROR    Failed check for new files files
 2023-12-15 18:36:03 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
 2023-12-15 18:36:03 ERROR    Error debugging info:
 2023-12-15 18:36:03 ERROR    Traceback (most recent call last):
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 220, in authenticate
     req = self.session.post(
           ^^^^^^^^^^^^^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
     return self.request("POST", url, data=data, json=json, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 105, in request
     self._raise_error(code, reason)
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 127, in _raise_error
     raise api_error
 pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
     sys.exit(main())
              ^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
     return self.main(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
     rv = self.invoke(ctx)
          ^^^^^^^^^^^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
     return ctx.invoke(self.callback, **ctx.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
     return __callback(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
     core(
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
     icloud = authenticator(logger, domain)(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
     icloud = pyicloud_ipd.PyiCloudService(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
     self.authenticate()
   File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 228, in authenticate
     raise PyiCloudFailedLoginException(msg, error)
 pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
 2023-12-15 18:36:03 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
```

**Comment by eleaner** [comment]
wait!
it looks like 1.0.685 works!
I must have been checking an older version

**Comment by adoramon** [comment]
same error


023/12/20 16:13:02 | stdout | ash: out of range
-- | -- | --
2023/12/20 16:13:02 | stdout | 2023-12-20 16:13:02 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2023/12/20 16:13:02 | stdout | pyicloud_ipd.exceptions.PyiCloudNoStoredPasswordAvailableException: No pyicloud password for liujun0616@outlook.com could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.
2023/12/20 16:13:02 | stdout | raise PyiCloudNoStoredPasswordAvailableException(
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
2023/12/20 16:13:02 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/20 16:13:02 | stdout | password = get_password_from_keyring(apple_id)
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/pyicloud_ipd/base.py", line 204, in __init__
2023/12/20 16:13:02 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/20 16:13:02 | stdout | icloud = pyicloud_ipd.PyiCloudService(
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/authentication.py", line 31, in authenticate_
2023/12/20 16:13:02 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/20 16:13:02 | stdout | icloud = authenticator(logger, domain)(
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 744, in core
2023/12/20 16:13:02 | stdout | core(
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/icloudpd/base.py", line 317, in main
2023/12/20 16:13:02 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/20 16:13:02 | stdout | return __callback(*args, **kwargs)
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2023/12/20 16:13:02 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/20 16:13:02 | stdout | return ctx.invoke(self.callback, **ctx.params)
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2023/12/20 16:13:02 | stdout | ^^^^^^^^^^^^^^^^
2023/12/20 16:13:02 | stdout | rv = self.invoke(ctx)
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1078, in main
2023/12/20 16:13:02 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023/12/20 16:13:02 | stdout | return self.main(*args, **kwargs)
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2023/12/20 16:13:02 | stdout | ^^^^^^
2023/12/20 16:13:02 | stdout | sys.exit(main())
2023/12/20 16:13:02 | stdout | File "/opt/icloudpd_latest/bin/icloudpd", line 8, in <module>
2023/12/20 16:13:02 | stdout | 2023-12-20 16:13:02 ERROR    Traceback (most recent call last):
2023/12/20 16:13:02 | stdout | 2023-12-20 16:13:02 ERROR    Error debugging info:
2023/12/20 16:13:02 | stdout | 2023-12-20 16:13:02 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2023/12/20 16:13:02 | stdout | 2023-12-20 16:13:02 ERROR    Failed check for new files files

**Comment by boredazfcuk** [comment]
Latest version should now resolve this issue for icloud.com users and hopefully icloud.com.cn users (but this is untested).

**Comment by eleaner** [comment]
@boredazfcuk 
it seems to be working now! thank you!
also my wife hoards 50k of photos so I had to tweak some of the options

**Comment by boredazfcuk** [comment]
> @boredazfcuk it seems to be working now! thank you! also my wife hoards 50k of photos so I had to tweak some of the options

Same... I removed around 1,200 .PNG files from her download directory: `find /home/wife/iCloud/ -name "*.PNG" -delete`

I thought same must have removed some of those screenshots of shopping websites over the years, but no, they all re-downloaded on the next synchronisation...
