### ISSUE TITLE
Container startup notification

### ISSUE THREAD

**Issue by eibenp** [boredazfcuk/docker-icloudpd#452]
Hi,

I would like to disable container startup notifications. Please help me how can I do this.

I am running icloudpd from command line because I synchronize multiple accounts in various configurations and don't want to run multiple containers parallel all the time. I am interested only in failures and container startup failures are handled by my environment. I do not need container startup notifications, only download results and cookie expiration notifications should be sent. Based on the documentation currently I am able to disable the download and delete notifications only.

**Comment by boredazfcuk** [comment]
Hi,

I've added a new variable: `startup_notification` which defaults to `true`. Set
```
startup_notification=false
```
in your icloudpd.conf file to disable them.
