### ISSUE TITLE
.mounted not found, why now?

### ISSUE THREAD

**Issue by thedinz** [boredazfcuk/docker-icloudpd#456]
lovely new error after updating just now

me/user/iCloud/.mounted file is not present. Waiting for failsafe file to be created...

But the file is present, its always been present, and nothing has changed....

**Comment by aMVents** [comment]
Hi, i'm running into this now, do you know how you fixed it? Or why you closed it?

**Comment by thedinz** [comment]
> Hi, i'm running into this now, do you know how you fixed it? Or why you closed it?

Because the issue was 100% on my side, i was not pointing to the right location.

If your .mounted file is for sure there make sure in the icloudpd.conf you are point to the right location

**Comment by thedinz** [comment]
> ok cool, thank you for your reply. I doubled checked the location and even made a new location for the .mounted file both in the icloudpd.conf file and the docker container Advanced settings in my Synology.
> 
> I'll make sure to check again as this was working on the weekend so I'm not sure what I changed.
> 
> Thanks again.

No problem, 

Not familiar with synology but in my case i mounted the photo directory as "icloud" so in my conf file i smply have download_path=/icloud

But you said you had it working before so not sure why that would change but i beleive in my case i had change the name ot the share from photos to icloud but did not update the conf file which is why it could not see the .mounted file.
