### ISSUE TITLE
Strange priority on Pushover notification

### ISSUE THREAD

**Issue by larstomas** [boredazfcuk/docker-icloudpd#46]
Notify "failure" code for Pushover looks like this:
`Notify "failure" "iCloudPD container failure" "-2" "iCloudPD failed to download new files for Apple ID: ${apple_id} - Exit code ${check_exit_code}"`

Where -2 is the priority. 

From [Pushover API](https://pushover.net/api):
`priority - send as -2 to generate no notification/alert, -1 to always send as a quiet notification, 1 to display as high-priority and bypass the user's quiet hours, or 2 to also require confirmation from the user`

I think "generate no notification/alert" dosen't go well together with "failure" :) 
If anything "failure" would be more like priority 1 "high-priority and bypass the user's quiet hours". 
An other option would be to remove "priority" from Pushover notifications. 

Do what you like.  😁

**Comment by boredazfcuk** [comment]
I've changed it to "2" now. Failures are supposed to be an "Emergency" level, whereas download notifications (specifically the file list previews are supposed to be "-2" so that they don't bother you by pinging your phone all the time.

Thanks again for drawing my attention to another problem!
