### ISSUE TITLE
photo_library option ignores folder_structure option

### ISSUE THREAD

**Issue by khargy** [boredazfcuk/docker-icloudpd#460]
If I use the photo_library option to download from my shared lib then all the files are downloaded into a flat folder with the same name as the photo_library option. it doesn't use the default folder_structure option or even use the option if I set an explicit one.

(I just recently upgraded to use the main branch as it seems the testing branch is currently broken)

**Comment by dohgren78** [comment]
I have the same issue

**Comment by khargy** [comment]
Ok, I figured out the libraries_with_dates option... 

Looks like that needs to be set to true to use the folder_structure option with the photo_library option... when I set that to true it works. 

So it seems like this is working as designed, although I would consider setting that as  true by default
