### ISSUE TITLE
no decode delegate for this image format `HEIC' @ error/constitute.c/ReadImage/746

### ISSUE THREAD

**Issue by syl779** [boredazfcuk/docker-icloudpd#461]
Pulled the latest version to start syncing again after the problems with authentication over the last few weeks (#443)

Have set the 2FA code.
Have downloaded the latest photos (yay).

Having trouble with converting to jpg - lots of errors like:

```
2023-12-23 23:28:04 INFO     Converting /icloud/2023/12/IMG_0234.HEIC to /icloud/2023/12/IMG_0234.JPG
convert: no decode delegate for this image format `HEIC' @ error/constitute.c/ReadImage/746.
convert: no images defined `/icloud/2023/12/IMG_0234.JPG' @ error/convert.c/ConvertImageCommand/3362.
```

Used to work fine.

**Comment by db145674** [comment]
this is the same error i'm getting all jpg files come out as 0 kbs. did you fix it?

**Comment by shanham67** [comment]
same here

**Comment by boredazfcuk** [comment]
Latest version pushed about an hour ago should fix this.

**Comment by syl779** [comment]
Taking a while converting a load of photos now, so that seems to have sorted it.

Thanks.
