### ISSUE TITLE
ERROR No route to icloud.com.cn found. When enable icloud_china

### ISSUE THREAD

**Issue by languede** [boredazfcuk/docker-icloudpd#467]
ERROR No route to **icloud.com.cn** found Please check your container's network settings.

## logs
...

2024-01-02 20:05:10.666734+08:00 2024-01-02 20:05:10 INFO     Alpine Linux 3.19.0
2024-01-02 20:05:10.670404+08:00 2024-01-02 20:05:10 INFO     Python version: 3.11.6
2024-01-02 20:05:10.761233+08:00 2024-01-02 20:05:10 INFO     Loading configuration from: /config/icloudpd.conf
2024-01-02 20:05:15.810793+08:00 2024-01-02 20:05:15 ERROR    No route to icloud.com.cn found. Please check your container's network settings - exiting
2024-01-02 20:05:15.814388+08:00 2024-01-02 20:05:15 ERROR    Error debug - traceroute: bad address 'icloud.com.cn'
...

## Description
* In my case the **docker-icloudpd** somehow failed to start when set **icloud_china** to _true_, 
however it works if set **icloud_china** to false that is to use icloud.com instead.
* I can access **icloud.com.cn** on my browser without problem, but if I trying to ping **icloud.com.cn**, it return _Request timeout for icmp_seq_ error.
* I am guessing the docker-icloudpd will ping to the icloud url before start up to check if the network is ready, somehow the icloud.com.cn does not response to ping request? so the docker-icloudpd think itself has no route to it?

I was install it as Kubernetes Helm chart on Truenas Scale.

#### Edit：
The sync-icloud --Initialise.sh also raise _ERROR No route to **icloud.com.cn** found Please check your container's network settings_ error, even if I set auth_china to false, it still shows **No route to **icloud.com.cn** found**

**Comment by boredazfcuk** [comment]
The icloudpd container first checks that it can get an IP address for icloud.com/icloud.com.cn

If it is successful, it attempts a traceroute to icloud.com/icloud.com.cn

The error message you have reported is because it cannot connect to icloud.com/icloud.com.cn

Check the /tmp/icloudpd/icloudpd_tracert.err file for further information.

**Comment by languede** [comment]
> The icloudpd container first checks that it can get an IP address for icloud.com/icloud.com.cn
> 
> If it is successful, it attempts a traceroute to icloud.com/icloud.com.cn
> 
> The error message you have reported is because it cannot connect to icloud.com/icloud.com.cn
> 
> Check the /tmp/icloudpd/icloudpd_tracert.err file for further information.

from ` /tmp/icloudpd/icloudpd_tracert.err `

```
traceroute: socket(AF_INET,3,1): Operation not permitted


```

**Comment by theikid** [comment]
I actually have the same issue with the app running on truenas scale. I can trace route to iCloud.com from my shell but got this error from the container.

**Comment by StevenMcElligott** [comment]
The container needs some elevated privileges to run inside the TrueCharts Helm Chart, you can file a bug report on the TrueCharts repo -> https://github.com/truecharts/charts/issues/new/choose

> I actually have the same issue with the app running on truenas scale. I can trace route to iCloud.com from my shell but got this error from the container. I don't have any network issues with other apps so I'm wondering if I need to configure something special for that specific container ?
