### ISSUE TITLE
Missing libheif-tools

### ISSUE THREAD

**Issue by damianorenzetti** [boredazfcuk/docker-icloudpd#471]
Hello, I noticed the HEIC->JPG conversion isn't working with the latest version of the container.
I fought with ImageMagick for a while and noticed libheif-tools was missing in your latest release.

A simple apk add libheif-tools solved it for me ;)

Thanks for the amazing work!!

**Comment by boredazfcuk** [comment]
Odd, I've tested latest version of the container and it's working fine.

I don't have libheif-tools installed, but I have libheif installed, and that's all that's needed for the convert command to work:

```
convert -quality 95 IMG_0324.HEIC IMG_0324.JPG
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
```

The set_mempolicy issue just a permissions problem as my container isn't running in privileged mode. It doesn't matter though... I checked the file that it output and it's fine.

**Comment by damianorenzetti** [comment]
Weird, for me it was converting but giving corrupted JPG files until I installed libheif-tools. No idea why!
