### ISSUE TITLE
No route to icloud.com

### ISSUE THREAD

**Issue by 3dBenny06** [boredazfcuk/docker-icloudpd#482]
I cant initialize icloudpd
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/100475848/0b9b3399-6748-4104-ac32-4177c9b43df4)
like you see it can reach icloud.com but the setup fails.

**Comment by boredazfcuk** [comment]
"Operation not permitted" means you have a permissions issue with your system,

It might work by adding the NET_RAW privilege but I've not tested this as it works without it on my system. To do that via command line add this when creating the container:
```
--cap-add=NET_RAW
```
or via a Docker Compose YAML file:
```
capabilities : 
        add: ["NET_RAW"]
```
If that doesn't work, try "NET_ADMIN" instead.

If that doesn't work either, you'll need to run the container privileged...
via command line:
```
--privileged
```
via Docker Compose YAML:
```
privileged: true
```
