### ISSUE TITLE
I wanted to run a 'sync' - ie delete the photos that have been deleted in icloud - but how to do it ? Auto Delete ?

### ISSUE THREAD

**Issue by vw-kombi** [boredazfcuk/docker-icloudpd#484]
I asusme it is the container setting 'Auto Delete', but the descrioption for this just says 'Scans the ".
I dont whan what to pu in there.

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/56822460/dfa5f98a-85e8-41a6-b5a0-695ea242fdef)

**Comment by boredazfcuk** [comment]
I don't know what you're using to configure the container, but it's not something I've created, so I cannot edit that message to something more appropriate.

I've extensively documented all configuration options in the CONFIGURATION.MD file. It should explain everything you need to know, but you're on the right track with auto_delete.

**Comment by vw-kombi** [comment]
Great - worked perfectly.  I am new to docker but I get what you are saying with the text - thats the person the took your docker and make it into an Unraid container for download in the community apps store that is missing that text.

It ram, deleted the photos, which is good - I wonder if you should have logging of that in the log however - you have logging for when it finds and ads photos, so maybe if it has found some deleted and then deletes some ?

**Comment by thomaslc66** [comment]
@boredazfcuk 
Looks like it's the " in your configuration file that is not well detected in the Unraid server UI and cut the phrase 

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/9827392/ca1399ab-0153-4793-adaf-e8b2e442717f)
