### ISSUE TITLE
Will the mov file in iCloud downloaded by my container automatically change the file name? My container is installed under Synology system!

### ISSUE THREAD

**Issue by shaoj0013** [boredazfcuk/docker-icloudpd#485]
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/16472419/9025ba32-f531-4190-8f10-544cd20c203d)

**Comment by shaoj0013** [comment]
The same file will appear, just with a different file name

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/16472419/a2684cfc-305d-4aa7-9231-cbbe7cb0a3c1)

**Comment by boredazfcuk** [comment]
Unfortunately not. The script just compares a list of files in the cloud with a list of files on the local system. If a file in the cloud is renamed, then icloudpd has no knowledge of that change. It will just see the file as an entirely new file and download it.
