### ISSUE TITLE
Feature request: Move Videos to different Folder

### ISSUE THREAD

**Issue by Silversurfer20002** [boredazfcuk/docker-icloudpd#490]
It would be great due to all the live Photos to move the Video File into a different Folder by the Folder_Strukture:
e.g. %Y/%M/%Type --> 2024/01/Photo | 2024/01/Video

**Comment by boredazfcuk** [comment]
This would require an upstream change. If I move photos/videos out of the download directory, the next syncronisation run would just re-download them.
