### ISSUE TITLE
Feature request: Initialize new Cockie via Telegram or different

### ISSUE THREAD

**Issue by Silversurfer20002** [boredazfcuk/docker-icloudpd#491]
It would be great if the cookie is unveiled to send a message via telegram like initialize get back a message with please send code and done ;-)

**Comment by cutzenfriend** [comment]
+1 <3

**Comment by PSeudoScripter** [comment]
Great Idea! I support this proposal!

**Comment by boredazfcuk** [comment]
I did manage to implement this for a short period, but then the upstream application changed the way the re-authentication was performed and it broke things. MFA has currently been blocked for the only device I can test this from, as i've made too many requests recently. I'm just waiting on a cool down. Will hopefully re-implement once I can test a bit more.
