### ISSUE TITLE
Gotify URL HTTP/HTTPS Syntax

### ISSUE THREAD

**Issue by undaunt** [boredazfcuk/docker-icloudpd#492]
The Gotify URL appears to be hardcoded as https [here](https://github.com/boredazfcuk/docker-icloudpd/blob/2259016706a4a0fd0da8bd423890294cc5f50ba6/sync-icloud.sh#L648). I have a forward auth in front of my entire Gotify container and would like to allow access to the backend at http://gotify instead of requiring the FQDN.

Currently as written I get a curl error 6 and http code 000 as it's trying to talk to an HTTP endpoint over HTTPS, or I get an auth error when I use the FQDN.

Would it be possible to update this to not require https and require the protocol as part of the URL, or enable an HTTP/HTTPS flag for gotify (or any notification URL?)

Thanks.

**Comment by rmlanghopto** [comment]
Just submitted #494 to address this, for Gotify at least. Thanks!

**Comment by boredazfcuk** [comment]
Is this confirmed working now? Can this be closed off?

**Comment by undaunt** [comment]
Works great, thanks everyone!
