### ISSUE TITLE
[TN SCALE] Bad docker api request when pulling image

### ISSUE THREAD

**Issue by jaysqvl** [boredazfcuk/docker-icloudpd#493]
Description:
Basically, whenever i try to deploy/run the app, I get the following error. I went to the link to inspect the api request and its basically just an unauthorized api request error which is why truenas scale can't pull the latest version of it. Not sure if this is a truenas scale issue or an issue with the repository/how the app is set-up to pull when downloading from the truecharts app catalogue.

Logs:

```2024-01-16 15:54:01
Add eth0 [172.16.0.127/16] from ix-net
2024-01-16 15:54:01
Error: ImagePullBackOff
2024-01-16 15:54:01
Pulling image "boredazfcuk/icloudpd:1.0.714@sha256:6a2b18a6e0f14d2307c993aab6fd842816c2906affe74147c2dc7ea47352a00f"
2024-01-16 15:54:01
Failed to pull image "boredazfcuk/icloudpd:1.0.714@sha256:6a2b18a6e0f14d2307c993aab6fd842816c2906affe74147c2dc7ea47352a00f": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/boredazfcuk/icloudpd@sha256:6a2b18a6e0f14d2307c993aab6fd842816c2906affe74147c2dc7ea47352a00f": failed to resolve reference "docker.io/boredazfcuk/icloudpd@sha256:6a2b18a6e0f14d2307c993aab6fd842816c2906affe74147c2dc7ea47352a00f": failed to do request: Head "https://registry-1.docker.io/v2/boredazfcuk/icloudpd/manifests/sha256:6a2b18a6e0f14d2307c993aab6fd842816c2906affe74147c2dc7ea47352a00f": dial tcp: lookup registry-1.docker.io: no such host```

System:
Truenas Scale Latest Bluefin Cobia
i7-4770
GTX 1070
32gb ram

**Comment by StevenMcElligott** [comment]
That's a network issue on your end my man, 

```dial tcp: lookup registry-1.docker.io: no such host``` at the end of the last line of the application events, so I'd look into that

**Comment by jaysqvl** [comment]
After pulling my hair out for a few hours trying to solve this, it seems a reinstall and reboot was all that was needed as the network for all of my apps stopped working during that time.
