### ISSUE TITLE
Enable "auto_delete", can not delete  IMG_XXX_HEVC.MOV , delete IMG_XXXX.HEIC only

### ISSUE THREAD

**Issue by maye459453500** [boredazfcuk/docker-icloudpd#502]
After sync photo, I get  IMG_XXX_HEVC.MOV and IMG_XXXX.HEIC

When I enable  "auto_delete",and delete this photo on iphone

sync once more，only IMG_XXXX.HEIC  be delete , can not delete  IMG_XXX_HEVC.MOV

I want to auto delete IMG_XXXX.HEIC  and IMG_XXX_HEVC.MOV when I delete this photo on my iPhone

Thanks!

**Comment by boredazfcuk** [comment]
How to do this is documented in CONFIGURATION.MD
