### ISSUE TITLE
failed to check for new files

### ISSUE THREAD

**Issue by Boerni-tech** [boredazfcuk/docker-icloudpd#503]
Hi,
I'm getting this error, permanently. I already did re-setup the whole environment, without any noticable improvement. I'm running icloudpd on unraid, twice. One instance for myself, one for my wife - her instace shows the same error. Any ideas?

> 2024-02-01 06:48:51 INFO     Synchronisation starting at 06:48:51
2024-02-01 06:48:51 INFO     Keyring file exists, continuing
2024-02-01 06:48:51 INFO     Check download directory mounted correctly...
2024-02-01 06:48:51 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
2024-02-01 06:48:51 INFO     Check for new files using password stored in keyring file
2024-02-01 06:48:51 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2024-02-01 06:49:05 ERROR    Failed check for new files files
2024-02-01 06:49:05 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024-02-01 06:49:05 ERROR    Error debugging info:
2024-02-01 06:49:05 ERROR    Traceback (most recent call last):
  File "starters/icloudpd.py", line 6, in <module>
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 328, in main
  File "icloudpd/base.py", line 908, in core
  File "pyicloud_ipd/services/photos.py", line 357, in photos
  File "pyicloud_ipd/services/photos.py", line 337, in photos_request
  File "requests/sessions.py", line 637, in post
  File "pyicloud_ipd/base.py", line 92, in request
PermissionError: [Errno 13] Permission denied: '/config/PERSONALEMAILADRESS.session'
[9112] Failed to execute script 'icloudpd' due to unhandled exception!
2024-02-01 06:49:05 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024-02-01 06:49:05 INFO     Web cookie expires: 2024-03-31 @ 11:49:01
2024-02-01 06:49:05 INFO     Multifactor authentication cookie expires: 2024-04-30 @ 11:49:13
2024-02-01 06:49:05 INFO     Days remaining until expiration: 89
2024-02-01 06:49:05 INFO     Synchronisation ended at 06:49:05
2024-02-01 06:49:05 INFO     Total time taken: 00:00:14
2024-02-01 06:49:05 INFO     Next synchronisation at 06:48:51

**Comment by mrblack7** [comment]
I've got the same issue on a new setup on a Synology NAS conainer


```
2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 INFO     Web cookie expires: 2024-04-13 @ 01:58:48
-- | -- | --
2024/02/12 18:15:47 | stdout | ash: out of range
2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024/02/12 18:15:47 | stdout | Error: Invalid value for '-d' / '--directory': Path '/xxxxxxx' is not readable.
2024/02/12 18:15:47 | stdout |  
2024/02/12 18:15:47 | stdout | Try 'icloudpd-1.17.3-linux-arm64.dynamic -h' for help.
2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR    Usage: icloudpd-1.17.3-linux-arm64.dynamic <options>
2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR    Error debugging info:
2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR    Failed check for new files files
2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Check for new files using password stored in keyring file
2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Failsafe file /xxxxxxx/.mounted exists, continuing
2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Check download directory mounted correctly...
2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Keyring file exists, continuing

```

**Comment by sergiomguedes** [comment]
> new setup on a Synology

I have the same problem! Any solution ?

**Comment by sergiomguedes** [comment]
> I've got the same issue on a new setup on a Synology NAS conainer
> 
> ```
> 2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 INFO     Web cookie expires: 2024-04-13 @ 01:58:48
> -- | -- | --
> 2024/02/12 18:15:47 | stdout | ash: out of range
> 2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
> 2024/02/12 18:15:47 | stdout | Error: Invalid value for '-d' / '--directory': Path '/xxxxxxx' is not readable.
> 2024/02/12 18:15:47 | stdout |  
> 2024/02/12 18:15:47 | stdout | Try 'icloudpd-1.17.3-linux-arm64.dynamic -h' for help.
> 2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR    Usage: icloudpd-1.17.3-linux-arm64.dynamic <options>
> 2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR    Error debugging info:
> 2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR     - Can you log into icloud.com without receiving pop-up notifications?
> 2024/02/12 18:15:47 | stdout | 2024-02-13 02:15:47 ERROR    Failed check for new files files
> 2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
> 2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Check for new files using password stored in keyring file
> 2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Failsafe file /xxxxxxx/.mounted exists, continuing
> 2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Check download directory mounted correctly...
> 2024/02/12 18:15:42 | stdout | 2024-02-13 02:15:42 INFO     Keyring file exists, continuing
> ```

@mrblak7
do you resolve the problem?

**Comment by mrblack7** [comment]
Not resolved yet.

If I run the standard icloudpd without docker, it works and downloads files no problem

**Comment by mrblack7** [comment]
Ok, so I got this working on my Synology NAS finally!

I had to use the following settings to set up the user and group permissions. The standard User group didn't have permissions to write to the shared folder, so I set it to use the administrator group and it works.

Hope this helps!

<img width="579" alt="Screenshot 2024-02-24 at 6 19 03 am" src="https://github.com/boredazfcuk/docker-icloudpd/assets/25524883/71d5f498-b66b-4ad0-a571-00b01c02997b">

**Comment by boredazfcuk** [comment]
Thanks for posting the solution.

**Comment by Boerni-tech** [comment]
Unfortunately, it is not solved on my side. I'm running it on unraid. I had to tune the group and group ID as well. It ran several times in the beginning and downloaded pictures, but now it stopped. So this is clearly no issue of the container or the unraid system. I'm raising another issue as it seems to have changed with the latest update, as well.

**Comment by boredazfcuk** [comment]
> PermissionError: [Errno 13] Permission denied: '/config/PERSONALEMAILADRESS.session'

You have a permission issue. You need the check the account you're using inside your container has access to the destination and that the container is running privileged.

**Comment by sergioguedes** [comment]
> Ok, so I got this working on my Synology NAS finally!
> 
> I had to use the following settings to set up the user and group permissions. The standard User group didn't have permissions to write to the shared folder, so I set it to use the administrator group and it works.
> 
> Hope this helps!
> <img alt="Screenshot 2024-02-24 at 6 19 03 am" width="579" src="https://private-user-images.githubusercontent.com/25524883/307431165-71d5f498-b66b-4ad0-a571-00b01c02997b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzU2NDcsIm5iZiI6MTcwODg3NTM0NywicGF0aCI6Ii8yNTUyNDg4My8zMDc0MzExNjUtNzFkNWY0OTgtYjY2Yi00YWQwLWE1NzEtMDBiMDFjMDI5OTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDE1MzU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlY2FlYjBmOGQ0OWVlMWIwNjhhMWIyNTU1NjU1YzVjOWExNDRkNzhmN2I1MWRiZTgyODdkZGQyNTkzNjVjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iXa8t681JTXL9D0469eeGV5JokEAcHCvV2A14WTgjB4">

Thank you very much, it solved my problem!
