### ISSUE TITLE
Only a fraction of total number of photos is downloaded

### ISSUE THREAD

**Issue by skumka** [boredazfcuk/docker-icloudpd#505]
I have 44k Photos 900 Videos on Apple iCloud. 

icloudpd sees only 714.
They are recognised as "recent". I have no idea per what that selection is done.

In Photos App I see in Apple iCloud there are couple of thousands  Recent Photos.

Interestingly, I tried to download files per Albums. It sees all photo inside the selected album to download, but nothing is downloaded.
See log:
2024-02-04 15:42:43 INFO Downloading album: Rok 2000-09 - Kreta
2024-02-04 15:42:45 DEBUG Authenticating...
2024-02-04 15:42:49 DEBUG Looking up all photos and videos from album Rok 2000-09 - Kreta...
2024-02-04 15:42:50 INFO Downloading 180 original photos and videos to /library ...
2024-02-04 15:42:51 INFO All photos have been downloaded
2024-02-04 15:42:51 INFO Synchronisation complete for user
2024-02-04 15:42:51 INFO Web cookie expires: 2024-04-04 @ 14:12:57
2024-02-04 15:42:51 INFO Multifactor authentication cookie expires: 2024-05-04 @ 14:15:20
2024-02-04 15:42:51 INFO Days remaining until expiration: 89
2024-02-04 15:42:51 INFO Synchronisation ended at 15:42:51
2024-02-04 15:42:51 INFO Total time taken: 00:00:08
2024-02-04 15:42:51 INFO Next synchronisation at 15:42:43

No one file exist on disk on the specified location, No such album is downloaded. Per what it sees :2024-02-04 15:42:51 INFO All photos have been downloaded ??????

**Comment by AndreyNikiforov** [comment]
What docker image are you using for icloudpd? "2024-02-04 15:42:51 INFO Web cookie expires: 2024-04-04 @ 14:12:57" suggests to me that you are not using [icloudpd/icloudpd](https://hub.docker.com/r/icloudpd/icloudpd) from this project as source code does not have such log statements.

**Comment by skumka** [comment]
![icloudpd](https://github.com/boredazfcuk/docker-icloudpd/assets/71942616/2baf4aad-ff81-4d1e-920d-f473df7428cb)

**Comment by AndreyNikiforov** [comment]
You can post the question to the project supporting docker image you are using or try reproducing the issue using image from this repo.

**Comment by skumka** [comment]
Hi,
I am sorry, maybe I am missing something. But I use docker image: boredazfcuk/icloudpd.
Isn't the one here?

**Comment by skumka** [comment]
In fact I think the problem is in the command icloudpd ( using [icloudpd/icloudpd](https://hub.docker.com/r/icloudpd/icloudpd)) which is used here in this container.

I have just placed the bug there with example.

**Comment by AndreyNikiforov** [comment]
> I am sorry, maybe I am missing something. But I use docker image: boredazfcuk/icloudpd.
> Isn't the one here?

Ugh. My bad -- missing morning coffee. Was checking issues in multiple repos and mixed things up. You are in the right place.

**Comment by skumka** [comment]
> > I am sorry, maybe I am missing something. But I use docker image: boredazfcuk/icloudpd.
> > Isn't the one here?
> 
> Ugh. My bad -- missing morning coffee. Was checking issues in multiple repos and mixed things up. You are in the right place.

No problem :-) 

To make the issue description essential:
**It looks that command sees 180 files to be downloaded but downloads 0 since there is "something" which make these photos "downloaded" for the command.**

**Comment by boredazfcuk** [comment]
The log file shows that it is set to download photos from a photo album `Rok 2000-2009 - Kreta` suggesting you have:
```
photo_album=Rok 2000-2009 - Kreta
```
set in your /config/icloudpd.conf configuration file. Just omit this by setting `photo_album=` and it should download from the `All Photos` album.

**Comment by boredazfcuk** [comment]
Closing as stale
