### ISSUE TITLE
DNG are recognized as movie

### ISSUE THREAD

**Issue by hoddelhs** [boredazfcuk/docker-icloudpd#507]
DNG (RAW) files from iPhone 15 pro max and iPhone 13 Pro are recognized as video and not exported, see error message.
in icloudpd.conf I have set skip_videos=true. 
I use icloudpd on a Synology 218+ with Docker

`2024/02/08 09:30:02	stdout	2024-02-08 08:30:02 DEBUG    Skipping IMG_9017.DNG, only downloading photos.(Item type was: movie)

2024/02/08 09:30:02	stdout	2024-02-08 08:30:02 DEBUG    Skipping IMG_9019.DNG, only downloading photos.(Item type was: movie)
`

**Comment by boredazfcuk** [comment]
Do they download correctly if you disable skipping videos with `skip_videos=`, or does it skip them entirely?

**Comment by hoddelhs** [comment]
if I skip_videos= then all DNG are copied correctly, including video and live images.
it also seems that only the iPhone 13pro and 15pro are affected

Am 25. Feb. 2024, 10:43 +0100 schrieb boredazfcuk/docker-icloudpd ***@***.***>:
>
> Do they download correctly if you disable skipping videos with skip_videos=, or does it skip them entirely?

**Comment by boredazfcuk** [comment]
This bug is logged upstream: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/675. Once a fix is created, I will roll it into this container.

**Comment by boredazfcuk** [comment]
I believe this is now fixed upstream and included in latest version of my container.
