### ISSUE TITLE
icloud sync stopped and asking to initialise telegram bot

### ISSUE THREAD

**Issue by Eagle248** [boredazfcuk/docker-icloudpd#514]
Icloud Sync has stopped and it is asking to initialise BOT. Can you please guide me, how to do that?

Bot has not been initialised or needs reinitialising. Please send a message to the bot from your iDevice and restart the container. Disabling remote wake

----------------------------
2/23/2024 21:30	stdout	2024-02-23 21:30:07 ERROR    ***** Please report problems here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
		
2/23/2024 21:30	stdout	2024-02-23 21:30:07 ERROR    Telegram startup notification failed with http status code: 000 and curl exit code: 6
		
2/23/2024 21:29	stdout	2024-02-23 21:29:44 INFO     Sending Telegram startup notification
		
2/23/2024 21:29	stdout	2024-02-23 21:29:44 DEBUG    Startup notification: Enabled
		
2/23/2024 21:29	stdout	2024-02-23 21:29:44 DEBUG    Telegram silent file notifications: false
		
2/23/2024 21:29	stdout	2024-02-23 21:29:44 INFO     Latest update id: 2560.......
		
2/23/2024 21:29	stdout	2024-02-23 21:29:34 INFO      - Bot has not been initialised or needs reinitialising. Please send a message to the bot from your iDevice and restart the container. Disabling remote wake
		
2/23/2024 21:29	stdout	2024-02-23 21:29:34 DEBUG    Bot check: 
		
2/23/2024 21:29	stdout	2024-02-23 21:29:10 DEBUG    Checking api.telegram.org for updates
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Check Telegram bot initialised...
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Telegram notification URL: (hidden)
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Telegram polling: true
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Telegram chat id: (hidden)
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Telegram token: (hidden)
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Notification title: boredazfcuk/iCloudPD
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Telegram notifications enabled
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    JPEG conversion quality: 100
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Convert HEIC to JPEG: true
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Skip videos: false
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Stop downloading when prexisiting files count is: Download All Photos
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Downloading photos from: Download All Photos
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Number of most recently added photos to download: Download All Photos
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Skip live photos: true
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Skip download check: true
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Single pass mode: false
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Photo size: original
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Delete after download: false
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Auto delete: false
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Set EXIF date/time: false
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Synchronisation delay (minutes): 0
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Synchronisation interval: 43200
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    File permissions: 640
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Directory permissions: 750
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Folder structure: {:%Y/%Y-%m}
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Download destination directory: /iCloud
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Cookie expiry notification period: 14
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Cookie path: /config/(hidden)
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 INFO     Authentication Type: MFA
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Apple ID: (hidden)
		
2/23/2024 21:28	stdout	2024-02-23 21:28:56 DEBUG    Route check to icloud.com successful
		
2/23/2024 21:28	stdout	2024-02-23 21:28:55 DEBUG    IP address for icloud.com: 
		
2/23/2024 21:28	stdout	
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 DEBUG    DNS server: 
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 DEBUG    Default gateway: 
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 DEBUG    LAN IP Address: 
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 DEBUG    Force GID: false
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 DEBUG    Local group: group:1000
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 DEBUG    Local user: user:1000
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 DEBUG    Running group id: 0
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 DEBUG    Running user id: 0
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 INFO     Loading configuration from: /config/icloudpd.conf
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 INFO     Python version: 3.11.6
		
2/23/2024 21:28	stdout	2024-02-23 21:28:47 INFO     Alpine Linux 3.19.0
		
2/23/2024 21:28	stdout	"2024-02-23 21:28:47 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
"
2/23/2024 21:28	stdout	2024-02-23 21:28:47 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader v1.0.718 started *****

**Comment by boredazfcuk** [comment]
> 2/23/2024 21:30 stdout 2024-02-23 21:30:07 ERROR Telegram startup notification failed with http status code: 000 and curl exit code: 6

Curl exit code 6 means "Cannot resolve host" so there is a name resolution/network issue with host system.
