### ISSUE TITLE
Stuck at generating list

### ISSUE THREAD

**Issue by cream68** [boredazfcuk/docker-icloudpd#515]
It seems as the iCloudpd docker is stuck at

> Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time

for about 2 days. It has been running without problems for months and most of the photos have already been downloaded. But after updating the docker image it seems to not work anymore. 

Also executing commands like `docker exec -it icloudpd sync-icloud.sh --List-Albums` does not show the list of albums and instead only shows:

> Valid multifactor authentication cookie found. Days until expiration: 88

Any ideas?

**Comment by makhlouta** [comment]
I have the same exact issue. I have two containers for different accounts, one is working fine and the other was working until 2 days ago. I tried reinitializing, restarting the container, nothing worked.

The output of the docker and the --List-Albums hang at the same line as @cream68 post.

**Comment by makhlouta** [comment]
I had a suspicion that this is something from Apple's side (throttling maybe?) as my other container is working fine with the other account.

Stopping the container for a day solved the problem.

**Comment by boredazfcuk** [comment]
Going to resolve this as I can't duplicate it and it looks like it may have been an Apple thing.
