### ISSUE TITLE
Sync Failure with iCloudpd When Filenames Contain Leading Spaces

### ISSUE THREAD

**Issue by johndlloyd** [boredazfcuk/docker-icloudpd#516]
**Summary:** iCloud Photo Downloader (icloudpd) fails to sync files when filenames contain leading spaces. This results in the application not detecting new files for synchronization.

**Steps to Reproduce:**
1. Have a photo in the iCloud library with a leading space in the filename (e.g., " FileName.jpg").
2. Run icloudpd to sync photos.
3. Observe that icloudpd completes the sync process but reports "No new files detected."

**Expected Behavior**: icloudpd should successfully sync files from iCloud, including those with leading spaces in their filenames.
**Actual Behavior**: icloudpd fails to detect and sync files with leading spaces in their filenames, resulting in a message indicating no new files were detected.

**Frequency**: Always when files with leading spaces are present in the iCloud library.

**Comment by boredazfcuk** [comment]
Windows doesn't support saving something with those filenames: https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/file-folder-name-whitespace-characters, and to be honest, I wholeheartedly agree with it. Users running this container in Docker Desktop on Windows are going to have a bad time if something like that is supported. Also, if they're downloading them onto a NAS device, then accessing them from a Windows device.
