### ISSUE TITLE
How to download photos from shared photo library (added by iOS 17)?

### ISSUE THREAD

**Issue by lifecolorist** [boredazfcuk/docker-icloudpd#519]
I create a shared photo library with my family. I can see it in my iPhone and in iCloud.com.
Here is the description of iCloud Shared Photo Library in IOS 17( https://support.apple.com/en-il/guide/iphone/iph28ac9ea81/17.0/ios/17.0)

But use icloudpd, it can only recogonized my private library.
I also use the parameter: photo_library="all libraries". But it also can't find my shared photo library.
This photo shows that I can see all my photo library on iCloud.com.
<img width="541" alt="image" src="https://github.com/boredazfcuk/docker-icloudpd/assets/7791152/424c083b-440e-4e1c-b790-60be8ef355ad">

**Comment by mhqschen** [comment]
photo_library="all libraries" works for me.
