### ISSUE TITLE
Download All Photos

### ISSUE THREAD

**Issue by curo1305** [boredazfcuk/docker-icloudpd#52]
Hello,

I have a question/issue. I created the container and the cookies and everything works up to this point perfectly. Thank you for this.

But the script just downloaded the pictures of the last 6 month and not all of them. Is there an argument I am missing? Or is there a somewhat another way to download all photos in the iCloud?

Thanks for the help.
curo1305

My docker commands are

```
touch /media/volume/home/myUser/Pictures/iCloud/.mounted

docker create \
    --name icloudpd \
    --hostname icloudpd_machine \
    --network host \
    --restart=always \
    --env user=myUser \
    --env user_id=1001 \
    --env group=myUser \
    --env group_id=1001 \
    --env apple_id=notmyactual@email.com \
    --env authentication_type=2FA \
    --env command_line_options="--folder-structure={:%Y} --recent 50 --auto-delete" \
    --env TZ=Europe/London \
    --env recent_only=False \
    --volume /media/volume/docker/icloud:/config \
    --volume /media/volume/home/myUser/Pictures/iCloud:/home/myUser/iCloud \
    boredazfcuk/icloudpd

docker exec -it icloudpd /usr/local/bin/sync-icloud.sh
```

**Comment by curo1305** [comment]
Ok sorry I figured it out. the '--recent 50' command_line_option was in the way.

**Comment by boredazfcuk** [comment]
Sorry for not getting back sooner. I've slacked off loads since Christmas. Need to get back into work mode...

Glad you solved your issue.
