### ISSUE TITLE
delete_after_download does not work with Shared Library

### ISSUE THREAD

**Issue by b00llean** [boredazfcuk/docker-icloudpd#520]
I have following config set in docker envs:

photo_library=SharedSync-xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
auto_delete=false
delete_after_download=true

but all the photos are getting downloaded just fine and not getting deleted. I have also set debug_logging=true and not seeing any errors.

**Comment by boredazfcuk** [comment]
This has not been implemented in the upstream application: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/802

Once it is, it will be added to my container.
