### ISSUE TITLE
WARNING: failsafe file not found 

### ISSUE THREAD

**Issue by WSTDESIGN** [boredazfcuk/docker-icloudpd#529]
I never get to download because it says the failsafe file does not exist. Problem is the .mounted file is there just is not being seen.

Can anyone help me get this to work? Would be forever grateful.

Thanks

**Comment by frebens** [comment]
I've been at this for the last 3 days solid.
I'm also unable to have the .mounted file picked up.
I've tried various iterations of folders combinations/permissions, but no luck
Does anyone have a screenshot of the variables that is set related to file paths?

I've set 'download_path=/volume1/homes/freben/iCloud' as per recommendation and moved the .mounted file there, but the script still get's stuck on WARNING Failsafe...

**Comment by lonevvolf** [comment]
I am using this on Synology, and haven't had this issue.  I would recommend to check the user_id, group, and group_id settings.  They should match those from the Synology host user that you want to run under.  I haven't set download_path setting at all in my config.

**Comment by frebens** [comment]
![Screenshot 2024-04-09 at 14 34 41](https://github.com/boredazfcuk/docker-icloudpd/assets/86057462/2f97bbbb-d8d4-40fc-b0c8-a953b03f6691)
![Screenshot 2024-04-09 at 14 35 33](https://github.com/boredazfcuk/docker-icloudpd/assets/86057462/7015c5ff-0460-40bb-9344-1d976a0933d4)

**Comment by lonevvolf** [comment]
A few notes.
1) You can remove synology_photos_app_fix, it doesn't work
2) Is the user_id the same as your synology user?
3) group should be a name like "users", group_id should be the id
4) Try not using a home folder for the download_path - I would suggest using a base shared folder

**Comment by frebens** [comment]
Thanks, I have done as suggested.
I've even gone so far as to remove everything I've done so far and started from scratch.
Here is the log it produced after I've done the 2FA.

<img width="1720" alt="Screenshot 2024-04-10 at 12 55 37" src="https://github.com/boredazfcuk/docker-icloudpd/assets/86057462/a48f13f9-821c-4a13-8176-daff2e6d13b5">

<img width="1761" alt="Screenshot 2024-04-10 at 12 56 01" src="https://github.com/boredazfcuk/docker-icloudpd/assets/86057462/3b263ef8-3550-41a7-be10-31b4e79f22d3">

Folder permissions set to allow user freben
<img width="749" alt="Screenshot 2024-04-10 at 12 57 24" src="https://github.com/boredazfcuk/docker-icloudpd/assets/86057462/88956a2d-0d9f-45a8-99b8-dbce92885399">

Folder with .mounted file as per the config
<img width="1000" alt="Screenshot 2024-04-10 at 12 59 05" src="https://github.com/boredazfcuk/docker-icloudpd/assets/86057462/f8309e53-48e7-492b-9585-223f09dee7e3">

Config of the container. Note I cannot add anything related to group or group_id as the process identifies it is already there and exits:
<img width="701" alt="Screenshot 2024-04-10 at 13 09 28" src="https://github.com/boredazfcuk/docker-icloudpd/assets/86057462/71c7da96-b147-45a9-baeb-725541aab5fd">

Thanks for your help!

**Comment by petercockroach** [comment]
Following this as well. I was able to work around this issue by running `sudo docker exec -it icloudpd touch /home/user1/iCloud/.mounted` which worked successfully. I believe this proves that the container was successfully able to create this file with its given permissions. Now I'm just waiting to see if my photos actually start downloading, but I spent a lot of time trying to figure this one out

**Comment by boredazfcuk** [comment]
If you create the failsafe file using `sudo docker exec -it icloudpd touch /home/user1/iCloud/.mounted` or something similar, then you are creating that file inside the container. This defeats the purpose of the failsafe mechanism.

It's likely the photos will be downloaded inside the container, rather than on a volume, so all photos will be deleted whenever the container is re-created/upgraded.

**Comment by petercockroach** [comment]
@boredazfcuk yeah, I totally agree and understand this but I did this merely as a debugging exercise to see if it made any progress. The peculiar part is that no assets are writing to the disk even within the container so there's some sort of write error going on. Whether it's a permissions problem or something else is what I'm not clear on. 

@frebens whwn you create a file with a . preceding it, it is a hidden file. You should still be able to see it with ls or by turning on your option to view hidden files within your GUI

**Comment by boredazfcuk** [comment]
The script doesn't create the .mounted file. It has to be a manual process performed outside of the container.

It's basically a marker so you can say "this is the volume I want my photos to appear in".

When the container launches, if it can't see the .mounted file, it knows that the volume isn't attached to the container correctly. This way it avoids downloading all the photos inside the container and losing them when the container is upgraded.

Also, the Docker container files are often contained in the root partition. If you don't map a volume correctly, then download 2TB to the container, chances are that you will fill the root partition of your server.

The only other way I could test for this would be to mount the Docker sock file inside the container and start querying that. Seems a bit overly complicated and also gives permission to the script to interact with the Docker system. 

I feel that's a major security concern for users as it would mean I could start querying all sorts of stuff from within the container, with a few modifications to the script.

Creating the mounted marker file is a simpler and more secure way of telling the container it's looking at the correct place.

**Comment by petercockroach** [comment]
Thanks for the reply. Pardon my ignorance but could you elaborate a bit about when the .mounted file is created? I now understand the script doesn't create it, but at what point during the process is it created and by what function?

**Comment by frebens** [comment]
> What's the status on this?

I was unfortunately unable to make this work on my Synology NAS. 
I am hoping someone much more clever than me can solve it.

**Comment by WSTDESIGN** [comment]
> I am using this on Synology, and haven't had this issue. I would recommend to check the user_id, group, and group_id settings. They should match those from the Synology host user that you want to run under. I haven't set download_path setting at all in my config.

Can you please elaborate on this? Maybe provide screenshots or something so I'm clear on this. I'm fairly certain all the permissions are correct.

**Comment by WSTDESIGN** [comment]
> The script doesn't create the .mounted file. It has to be a manual process performed outside of the container.
> 
> It's basically a marker so you can say "this is the volume I want my photos to appear in".
> 
> When the container launches, if it can't see the .mounted file, it knows that the volume isn't attached to the container correctly. This way it avoids downloading all the photos inside the container and losing them when the container is upgraded.
> 
> Also, the Docker container files are often contained in the root partition. If you don't map a volume correctly, then download 2TB to the container, chances are that you will fill the root partition of your server.
> 
> The only other way I could test for this would be to mount the Docker sock file inside the container and start querying that. Seems a bit overly complicated and also gives permission to the script to interact with the Docker system.
> 
> I feel that's a major security concern for users as it would mean I could start querying all sorts of stuff from within the container, with a few modifications to the script.
> 
> Creating the mounted marker file is a simpler and more secure way of telling the container it's looking at the correct place.

Can you please elaborate on mapping the volume. I'm not clear on this. Every time I try to add a folder the second field is looking for another folder? Another file? No matter what I put in the second field the container settings will not save and I get a form error. I also am finding when I go to map the volume I don't get the option of selecting any shared folders... I don't have clue what is going here.. very frustrating.

**Comment by boredazfcuk** [comment]
>  I would suggest it be added to the README or better yet, include it as part of the Initialization process - even if it's just a warning to the user to create it manually along with the command to do so.

It's already part of the configuration guide. It will also tell you about it if running `sync-icloud.sh --help`

**Comment by boredazfcuk** [comment]
> Can you please elaborate on mapping the volume. I'm not clear on this. 

When working with containers, if you delete the container, or upgrade it, you will lose everything inside it. For this reason, you need to map external volumes to directories inside the container which act as persistent storage. The container needs two of these persistent volumes. One to store the /config data and another for your download location, which would default to /home/user/iCloud if the download_path variable is not configured.

> Every time I try to add a folder the second field is looking for another folder? Another file? No matter what I put in the second field the container settings will not save and I get a form error. I also am finding when I go to map the volume I don't get the option of selecting any shared folders... I don't have clue what is going here.. very frustrating.

I'm not sure what any of this means. It sounds like a problem with the container managing system on the device you're using to be honest. That's not something I'm familiar with as I don't use any UnRAID, TrueNAS or Synology type NAS devices.

**Comment by WSTDESIGN** [comment]
Okay.. I'm on synology. I've attached a screen shot of the fields in the container manager that frebens had. He added /config to the second field. So I would map the folder docker/icloudpd then /config for the config data and leave the download path to default. I understand now.

![IMG_4240](https://github.com/boredazfcuk/docker-icloudpd/assets/90526156/fc401f99-9ae7-46e7-8883-923bca313df8)

 My other issue is making the .mounted file still. I read that you need to make the file outside of the container by the user with full permissions. I'm not exactly sure how to do that. I've tried two different ways and none of them have worked. 

I tried ssh in as the user went to the folder a did touch .mounted. It creates the file just fine but still getting the error.

i tried using a text editor and creating a text doc .mounted.txt and removed the .txt and placed in the folder that didn't work.

I'm just not clear how to create the file outside of the container. Could you please help me in understanding that part? Not sure what I'm not doing...

thanks

**Comment by boredazfcuk** [comment]
I'm not familiar with the Synology Container Manager, but try creating two volumes and attach them to the container. One called "config" and attach it to "/config" and a second one, called "photos" and mapped to "/photos". Then set the "download_path" variable to "/photos"

Then, on the NAS, find the location that the volume lives using whatever file manager is on there, and create a file called ".mounted" in it.

I don't have a Synology so I don't really know what to advise beyond that.

**Comment by boredazfcuk** [comment]
The container does pretty much both of those on every sync. Just need to set the `directory_permissions` and `file_permissions` variables with the permissions you want.

I have mine set to 750 for directories and 640 for files, which is the default. What you've done there is the equivalent of setting both directory and file permissions to 777. The would make sense for directories, as they need to be executable to be able to move through them. By setting them to 777, you're allowing everyone with access to the system to be able to browse the folders.

Setting file permissions to 777 is a little overkill though. They're photos, not programs that need to be executed, so should really be set to 666 tops. This would allow read/write access for everyone who has access to the system, but doesn't set an unnecessary executable bit.

**Comment by michaelsmolka** [comment]
Hey guys,
sorry for bringing this topic up again. I'm stuck at the fu****g failsafe thingy on synology for hours now.
Tried nearly everything i could find about this without any success.
Is anybody here who got it finally working on a syno NAS? This .mounted file is where it should be but the script seems to ignore it.

Here is where it always ends up for me:

`...
2024-07-07 18:54:45 INFO     Container initialisation complete                   
2024-07-07 18:54:45 DEBUG    Group, users:100, already created                   
2024-07-07 18:54:45 DEBUG    User, michael:1026, already created                 
2024-07-07 18:54:45 DEBUG    Set owner and group on icloudpd temp directory      
2024-07-07 18:54:45 DEBUG    Set owner and group on config directory             
2024-07-07 18:54:45 INFO     Directory is writable: /config/python_keyring/      
2024-07-07 18:54:45 DEBUG    Configure password                                  
2024-07-07 18:54:45 DEBUG    Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg                                                       
2024-07-07 18:54:45 INFO     Check download directory mounted correctly...       
2024-07-07 18:54:45 WARNING  Failsafe file /volume1/homes/michael/Photos/icloud_M/.mounted file is not present. Waiting for failsafe file to be created...    `

P.S.: Sorry for my english, i'm not a native speaker, just trying to do my best...

**Comment by lonevvolf** [comment]
I am in a Synology and this part is working fine for me. Be sure to check:
User id in the container config - should match the user id from synology 
Username in the container config - should match the user in the synology
Group id in the container config - should match the user’s group
Permission on the photos folder should be correct for that user

**Comment by michaelsmolka** [comment]
Thanks for the quick reply.
Userid, username, Groupid, group in the config are set according to this output of id command:
`uid=1026(michael) gid=100(users) groups=100(users)`
in the config file:
```
...
group=users
group_id=100
...
user=michael
user_id=1026
...
``` 
The folder containig the .mounted-file is owned by this user, permissions are set to full access for this user and reand an write for "everyone" user group, same for the file itself.

Must be wrong something else.

**Comment by michaelsmolka** [comment]
The folder path is set in the config and in my docker run as well, maybe I missed a "/" somewhere? (Although I c&p the path from file manager.)

config: `download_path=/volume1/homes/michael/Photos/icloud_M`
```
docker run -d \
   --name iCloudPD \
   --restart=always \
   --env TZ=Europe/Berlin \
   --volume /volume1/docker/icloudPD/config:/config \
   --volume /volume1/homes/michael/Photos/icloud_M:/home/boredazfcuk/iCloud \
   boredazfcuk/icloudpd:latest
```

**Comment by boredazfcuk** [comment]
Your download path is wrong. You've mounted `/volume1/homes/michael/Photos/icloud_M` to `/home/boredazfcuk/iCloud` inside the container, so your download path would need to be `/home/boredazfcuk/iCloud`.

But for that to be valid, you'd need your username to be `boredazfcuk` but I know from another post that it's `michael`.

For simplicity, just mount your volume like `--volume /volume1/homes/michael/Photos/icloud_M:/photos` and set `download_path=/photos`

**Comment by michaelsmolka** [comment]
Thank you for your time. Now it seems to work. Will let it run and hope tomorrow morning seeing files appearing in my folder. ;-)
Don't know, how I ended up with that wrong configuration. Changed and tried so much this weekend, probably some c&p from somwhere. But anyhow: finally it's sunday evening and the project is done so far.
Thynk you very much.

Btw: Is there a way to map the log into the docker folder?

**Comment by michaelsmolka** [comment]
Just for my understanding: By setting `download_path=/photos` in the config file, I tell the script to create this folder `/photos` within the container? (It is not already there, so i could name it whatever I want, as long as I do the volume mapping to the same folder name.)
And with the volume mapping in the "docker run" I make it permanently available for direct access.
Did I get it right?
(I'm quite new to all this linux and server stuff and still have to learn very much)

**Comment by WSTDESIGN** [comment]
Can you tell me where the config to the container is or how I find it? I'm not familiar..

**Comment by michaelsmolka** [comment]
the config file is created from the script by the first run in  the config volume mounted in the "docker run" as mentioned above in my case:
```dockerfile
   --volume /volume1/docker/icloudPD/config:/config \
``` 
I created the container by running this [command](https://github.com/boredazfcuk/docker-icloudpd/issues/529#issuecomment-2212535978) in the Task Planner (don't know the exact english name for this, as I am on a German language setting, but I guess you can figure it out by looking at the screeshot):
<img width="532" alt="Task Planner" src="https://github.com/boredazfcuk/docker-icloudpd/assets/102899353/8b884c0a-71d1-40d7-845c-128745a82422">

Afterwards I opened a terminal by double clicking on the container and then "action"->"open terminal". 
<img width="1265" alt="entering Terminal" src="https://github.com/boredazfcuk/docker-icloudpd/assets/102899353/e23e89ae-eef7-4c6f-a2bc-4c89ac07eeca">
By klicking on the small arrow besides the "create" button I started a new terminal with the comand: `sync-icloud.sh --Initialise`:
<img width="925" alt="Terminal" src="https://github.com/boredazfcuk/docker-icloudpd/assets/102899353/c2b3e31b-ef25-4177-b536-4d597a99e47f">

Then just follow the onscreen instructions in the terminal window. (as described [here](https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md#configuring-a-password))

Hope that helps.

**Comment by boredazfcuk** [comment]
>Btw: Is there a way to map the log into the docker folder?

No, the logs are directed to stdout so that they can be viewed in Docker, or a Docker management too, such as Portainer.

>Just for my understanding: By setting download_path=/photos in the config file, I tell the script to create this folder /photos within the container?

Yes. The download_path tells the application where to download the files to inside the container. By mapping a volume to this location, it means the files end up outside of the container in the mapped directory instead.

>(It is not already there, so i could name it whatever I want, as long as I do the volume mapping to the same folder name.)

Yes. I don't actually configure the download path variable as it will create it automatically and defaults to /home/<user>/iCloud. So in my container they live in /home/boredazfcuk/iCloud and my iPad's container downloads to /home/iPad/iCloud. Some people wanted to be able to specify the location inside the container so I made it configurable. Some people have it set to /downloads, /photos, /pictures, /data etc.

>And with the volume mapping in the "docker run" I make it permanently available for direct access.

The volume mapping is so that the data the container saves to that folder is persistent across deletes/recreates. Whenever I push a new version of the container, you have to delete/recreate the container, as Docker doesn't really do upgrades. Data stored on mapped volumes is persistent, so won't be removed. Anything that isn't on a mapped volume gets destroyed. If you don't map persistent volumes to your /config and download_path locations, then those locations will be removed when the container is recreated. That would mean reconfiguring the container, re-initialising it with the password/cookie, and then re-downloading all the photos too.

>Did I get it right?

Pretty much, yeah.

**Comment by michaelsmolka** [comment]
@boredazfcuk thank you very much.

**Comment by boredazfcuk** [comment]
> Can you tell me where the config to the container is or how I find it? I'm not familiar..

You need to connect to your container's command line, with something like:
`docker exec -it icloudpd /bin/ash`

Then you can edit the config file directly with:
`editconfig`

**Comment by cheezay3** [comment]
failsafe file not present
I manually created the file‘ .mounted ’in my desktop and upload to the web gui of my NAS, reboot the Container but still warning
 ' failsafe file /vol1/1000/Photos/icloud/.mounted file is not present. Waiting for failsafe file to be created...', ha-ha, very funny.
i check the sudo command `sudo docker exec -it icloudpd touch  /vol1/1000/Photos/icloud/.mounted.`  sudo: not found. 
what'd  i do next ?

**Comment by willpine80** [comment]
I had this issue too, having created the .mounted file in the correct location.

I found that the "download_path" in the icloudpd.conf file created upon the original initialization of the container (stored on my physical /config Synology storage directory) defaulted to "/home/user/iCloud", rather than <user> being the actual user ID that the container is running with.  I have my storage volume mapped to "/home/dockerusr/iCloud" in the container.

I manually opened the icloudpd.conf file, changed the value to "/home/<userID>/iCloud", saved it and restarted the container and it is now running as expected.  Hope this helps someone else...

**Comment by d-l-h** [comment]
As per [CONFIGURATION.md](https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md) I mounted `/home/boredazfcuk/iCloud` as download volume in Docker (Synology Container Manager).

I had to change in `/config/icloudpd.conf` line 22 from `download_path=/home/user/iCloud` to `download_path=/home/boredazfcuk/iCloud`

Still some permission issues existed. As the script runs as `user` I had to run
`chown -R user /home/boredazfcuk/iCloud`
and 
`chmod -R 755 /home/boredazfcuk/iCloud`

now change to `user` by typing `su user`

And finally `touch /home/boredazfcuk/iCloud/.mounted` which worked and now we can start synchronization
