### ISSUE TITLE
SOLVED : ERROR    Could not create folder /home/user/iCloud/xxxxxx

### ISSUE THREAD

**Issue by Hakoexe** [boredazfcuk/docker-icloudpd#530]
I am running into this error: 
i was able to complete the `sync-icloud.sh --Initialise` command and enter my pw and 2fa codes via the phone 
i have the `.mounted` file in the folder and there is only one main folder - no sub folders 
any help with this would be appreciated 

```
> 2024-03-26 22:29:24 DEBUG    Downloading /home/user/iCloud/2011/10/15/IMG_2761.JPG...
> 2024-03-26 22:29:24 ERROR    Could not create folder /home/user/iCloud/2011/10/15
> 2024-03-26 22:29:24 DEBUG    Downloading /home/user/iCloud/2009/10/07/IMG_0733.JPG...
> 2024-03-26 22:29:24 ERROR    Could not create folder /home/user/iCloud/2009/10/07
> 2024-03-26 22:29:24 DEBUG    Downloading /home/user/iCloud/2009/03/09/IMG_1095.JPG...
> 2024-03-26 22:29:24 ERROR    Could not create folder /home/user/iCloud/2009/03/09
> 2024-03-26 22:29:24 DEBUG    Downloading /home/user/iCloud/2007/02/28/IMG_0098.JPG...
> 2024-03-26 22:29:24 ERROR    Could not create folder /home/user/iCloud/2007/02/28
> 2024-03-26 22:29:24 DEBUG    Downloading /home/user/iCloud/2009/03/09/IMG_1095.JPG...
> 2024-03-26 22:29:24 ERROR    Could not create folder /home/user/iCloud/2009/03/09
> 2024-03-26 22:29:24 DEBUG    Downloading /home/user/iCloud/2007/02/28/IMG_0098.JPG...
> 2024-03-26 22:29:24 ERROR    Could not create folder /home/user/iCloud/2007/02/28
> 2024-03-26 22:29:24 INFO     All photos have been downloaded
> 2024-03-26 22:29:25 INFO     Synchronisation complete for user
> 2024-03-26 22:29:25 INFO     Web cookie expires: 2024-05-25 @ 22:11:13
> 2024-03-26 22:29:25 INFO     Multifactor authentication cookie expires: 2024-06-24 @ 22:11:32
> 2024-03-26 22:29:25 INFO     Days remaining until expiration: 89
> 2024-03-26 22:29:25 INFO     Synchronisation ended at 22:29:25
> 2024-03-26 22:29:25 INFO     Total time taken: 00:18:28
> 2024-03-26 22:29:25 INFO     Next synchronisation at 22:10:57
```

**Comment by Hakoexe** [comment]
Not sure if the Dev is still working on this or not but found the error 
in unraid the container is not set up correctly by default 

you will need to change these settings for this issue:


` directory_permissions: This specifies the permissions to set on the directories in your download destination. Default: 750.
file_permissions: This specifies the permissions to set on the files in your download destination. Default: 640.` 

You will also need to change these as well in the unraid container. these perms can be found when you edit the docker container

` user_id: This is the User ID number of the above user account. This can be any number that isn't already in use. Ideally, you should set this to be the same ID number as the user's ID on the host system. This will avoid permissions issues if syncing to your host's home directory. Default: '1000
`

Also i would STRONGLY recommend to read the `CONFIGURATION OPTIONS` and `TROUBLESHOOTING `
here is the link to that: 
https://github.com/boredazfcuk/docker-icloudpd/blob/master/CONFIGURATION.md

Good luck everyone!

**Comment by boredazfcuk** [comment]
The Unraid container template is not part of this project, although I do know that it utilises it.

I've not abandoned the project, It's just that every time I look at the issues that are raised, most of them look like they'd be solved if people just read the configuration guide I spent many, many hours writing and updating... or if they just searched the issues for their problem as they'd find half a dozen identical issues... which are again down to not reading the config guide.

So, I'd like to say thanks for actually taking the time to read it :)

**Comment by Hakoexe** [comment]
glad to hear its not abandoned and fully understand - i would love to see whoever owns the template to update it and the guide was very helpful. 

thanks again for your time spending on this project. 
 :)

**Comment by boredazfcuk** [comment]
It's can be found here: https://github.com/Womabre/unraid-docker-templates

Last updated four months ago, which is probably around the time I released new versions (apart from the push this week), so it may well be that he's actually still developing it.
