### ISSUE TITLE
auto_delete=true

### ISSUE THREAD

**Issue by pablo808** [boredazfcuk/docker-icloudpd#533]
Hello,

I am using a vanilla install icloudpd on unraid and it's working great downloading a copy of the images/video.

I enabled auto_delete=true but icloudpd never deletes the file.  Are their any other options which I may be missing?

Thanks.

**Comment by boredazfcuk** [comment]
Are you referring to photos downloaded from a shared library?

Currently the upstream project used to download the photos will not work for Shared Libraries. See here: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/802

**Comment by pablo808** [comment]
No, just my regular library. 

I think I figured it out.  I also had 'until_found=1' in the icloudpf.conf.  
I removed this and can confirm auto_delete=true works as expected.

Thanks.

**Comment by thomaslc66** [comment]
@boredazfcuk 
It seems to come from your configuration.md file
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/9827392/db4c9eab-6a22-4dc0-a518-5e367d50efb4)
But the issue is that there's " " and that seems to be not really well handled by Unraid UI.
