### ISSUE TITLE
Synology does not auto-index

### ISSUE THREAD

**Issue by katakraos** [boredazfcuk/docker-icloudpd#534]
Everything is working perfectly, but I have the following problem on synology. It does not autoindex the photos for "Synology Photos", set the variable "synology_photos_app_fix=true" but it still does not work. The path where I download the photos is "/volume1/homes/USER/Photos/Icloud:/icloud".
However, if I use the force indexing function from Syonology photos it works correctly.

Does anyone have the same problem?

Thanks for the great work on this docker.

**Comment by boredazfcuk** [comment]
I don't have a Synology device so can't say for sure, but I think the fix only worked for DSM v6. Lots of people reported it didn't work, except for one guy, who said it forced indexing as expected. Guessing he had an older device with older DSM version.

**Comment by katakraos** [comment]
I am sorry for not having searched in closed cases on this subject, I saw that it has already been discussed many times, I will try the solution that has already been said. 

https://github.com/boredazfcuk/docker-icloudpd/issues/165#issuecomment-1269205183
