### ISSUE TITLE
Group and Group id always reseted

### ISSUE THREAD

**Issue by thomaslc66** [boredazfcuk/docker-icloudpd#546]
Hello,

I was wondering why when I'm trying to set a group name or group id in the config files, they are always erased and replaced by :

group=group
group_id=100

I have this error when running the sync-icloud.sh --Initialise script that tells me that the ID 100 is already in use.
So I've tried to change the name of the group to match my system group name, I've tried to erase those config variables as in the CONFIGURATION.md files it's saying that the default is 1000, but it's always setting this to 100 and the name to the group and I cannot change it.

Could someone let me know how to do it asit seems a bit weird to me that config variables are overwritten, has somebody already experienced this issue ?

**Comment by boredazfcuk** [comment]
If you have created the container with environment variables, it will use those to set the values in the icloudpd.conf configuration file.

Usually you would specify a user/group ID which is 1000 or greater, as everything below that is usually reserved for system accounts.

Setting it to 100 will conflict with the group ID of the guest account. This will then prevent it from creating the `group` group.

You can override this by setting `force_gid=true` but I'd suggest setting to something higher than 1000 where possible, as it may lead to unwanted behaviour.
