### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by modkeyIT** [boredazfcuk/docker-icloudpd#547]
I've installed the latest icloudpd but when I try to run the command to login with my username, I get the following error:

```
/var/services/homes/myusername/icloudpd-venv/bin/icloud --username "myicloud@icloud.com"
Failed to execv() /tmp/staticx-dGGFle/icloud: Permission denied
```

**Comment by boredazfcuk** [comment]
The `icloud` utility lives in a subdirectory of `/opt` in my container. I think you may have raised this in the wrong GitHub repo?
