### ISSUE TITLE
command_line_options: --folder-structure={:%Y} - not working ?

### ISSUE THREAD

**Issue by nodecentral** [boredazfcuk/docker-icloudpd#55]
Hi @boredazfcuk 

QQ - I tired your example of ‘ --env command_line_options="--folder-structure={:%Y}’  but it returned an error ?

Does it still work for you ?

Looking at the [link](https://github.com/icloud-photos-downloader/icloud_photos_downloader#usage) you shared for these, it’s not clear what the other date options are ? 

Ideally I would like the sort by just the year like you suggested..

**Comment by boredazfcuk** [comment]
Folder structure options are set using the **folder_structure** variable. e.g:
```
--env folder_structure={:%Y}
```

The **command_line_options** variable is for options that can't set using the documented variables. There's a few things I haven't created variables (e-mail notifications for one) so I just added it so that people had the option to configure these things.

**Comment by nodecentral** [comment]
Many thanks, that helps as I was just following the ‘Creating a Container’ example you have on your GitHub page.

````
--env notification_days=14 \
--env command_line_options="--folder-structure={:%Y} --recent 50 --auto-delete" \
--env synchronisation_interval=21600 \
--env TZ=Europe/London \
--volume icloudpd_boredazfcuk_config:/config \
--volume /home/boredazfcuk/iCloud:/home/boredazfcuk/iCloud \
boredazfcuk/icloudpd
````

**Comment by boredazfcuk** [comment]
Cool. Thanks for letting me know. I've amended the example and the readme.

I've changed the script so that more stuff is configured through variables now. I did this example a fair while back when the **folder_structure**, **recent_only** and **auto_delete** variables didn't exist.

**Comment by boredazfcuk** [comment]
Closing this off as it should be resolved and I've nothing back to say otherwise.
