### ISSUE TITLE
Telegram Bot has not been initialised or needs reinitialising

### ISSUE THREAD

**Issue by jiawen1929** [boredazfcuk/docker-icloudpd#551]
Telegram startup notification failed with http status code: 000 and curl exit code: 35
[run.log](https://github.com/boredazfcuk/docker-icloudpd/files/15038308/run.log)

**Comment by boredazfcuk** [comment]
https status code 000 basically means "connection failure". Curl exit code 35 is an SSL/certificate error. Check your config and any proxy in between.

**Comment by boredazfcuk** [comment]
Closing as stale
