### ISSUE TITLE
Connection error in the log

### ISSUE THREAD

**Issue by tommibru** [boredazfcuk/docker-icloudpd#557]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/validate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1542b490ca40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[530] Failed to execute script 'icloudpd' due to unhandled exception!

**Comment by boredazfcuk** [comment]
Name resolution issue. Check your networking, DNS settings and firewalls between the container and the DNS server.

**Comment by boredazfcuk** [comment]
Closed as stale
