### ISSUE TITLE
Telegram support for multiple docker containers

### ISSUE THREAD

**Issue by Eksistenze** [boredazfcuk/docker-icloudpd#558]
I'm not sure if this is the correct forum for asking this.
I am using multiple docker containers to automate all of the family members' photo backups.  Is it possible to manage this through a single chat bot on telegram or would I need to create multiple bots?

**Comment by boredazfcuk** [comment]
Yeah, when messaging the bot, you have to prefix the message with the "user" variable from the container. This is so each container knows which one is being called so "boredazfuck sync", "thewife auth" or "ipad sync" etc

Just have to make sure the "user" variable is unique across all containers.
