### ISSUE TITLE
Error: Invalid value for '-d' / '--directory': Path is not readable

### ISSUE THREAD

**Issue by srirampsbb** [boredazfcuk/docker-icloudpd#561]
I'm seeing this error:
Error: Invalid value for '-d' / '--directory': Path '/home/madhurya/iCloud' is not readable (similar to #549 but the proposed solutions there didn't work as detailed below)
The destination is not an SMB Location
The source directory is mounted locally (on my Synology NAS):
```
~/icloudpd_boredazfcuk$ df -h  "/var/services/homes/madhuram/icloudpd_boredazfcuk/madhurya_icloudPD_data"
Filesystem      Size  Used Avail Use% Mounted on
  -               3.5T  1.1T  2.5T  31% /volume1/homes
```
I am able to login to the container (as root) and list the destination dir contents fine. Also, this dir was working before, I just created a new container with the latest image so not sure what I'm missing here

Also tried :z option for the mount but that didn't help either:
```
  "Mounts": [
      {
          "Type": "bind",
          "Source": "/var/services/homes/madhuram/icloudpd_boredazfcuk/madhurya_icloudPD_data",
          "Destination": "/home/madhurya/iCloud",
          "Mode": "rw,z",
          "RW": true,
          "Propagation": "rprivate"
      },
```

**Comment by boredazfcuk** [comment]
What happens when you login as the user account that the downloads are performed with? E.g.:
`docker exec -it --user <user> icloudpd ash`

**Comment by srirampsbb** [comment]
@boredazfcuk thanks for the response. It indeed was a permission issue. 
I changed the user_id, group_id  group name in the icloudpd config file to exactly match that of the NAS user I was logged in as and it worked.
