### ISSUE TITLE
Failed to execute script 'icloud' due to unhandled exception!   

### ISSUE THREAD

**Issue by Inrrs** [boredazfcuk/docker-icloudpd#562]
Enter iCloud password for 66666@163.com:                                     
Traceback (most recent call last):                                               
File "starters/icloud.py", line 5, in <module>                                 
File "pyicloud_ipd/cmdline.py", line 200, in main                              
File "pyicloud_ipd/base.py", line 305, in __init__                             
File "pyicloud_ipd/base.py", line 367, in authenticate                         
File "pyicloud_ipd/base.py", line 399, in _authenticate_with_token             
NameError: name 'PyiCloudConnectionException' is not defined. Did you mean: 'PyiCloudFailedLoginException'?                                                       
[424] Failed to execute script 'icloud' due to unhandled exception!              
2024-05-10 12:30:53 ERROR    Keyring file does not exist. Please try again

![Uploading 图片1.png…]()

**Comment by jmmfam** [comment]
same issue

**Comment by boredazfcuk** [comment]
I can't tell anything from such a tiny log file.

**Comment by Athrunsky** [comment]
> I can't tell anything from such a tiny log file.

looks like this issue type all come from Chiniese iCloud users.
I have same issue,and search old issues log which you fixed it on 2 weeks ago, rolled that into the latest container.
I don't know what information I can provide to help fix this problem.
image ver: v1.0.819
Alpine Linux 3.19.1
Python version: 3.11.9

**Comment by boredazfcuk** [comment]
> > I can't tell anything from such a tiny log file.
> 
> looks like this issue type all come from Chiniese iCloud users.

The issue type of people posting tiny, useless log files? Yes, I agree.

**Comment by boredazfcuk** [comment]
There has been an update to the upstream code which should now give a more accurate error message for this issue. Please replicate the issue and post the new information.

**Comment by boredazfcuk** [comment]
Closed as no response

**Comment by jokerxsun** [comment]
“I encountered the same issue. My account is from the U.S. region, but during the setup process, it was requesting iCloud.com.cn, while it should be accessing iCloud.com. So by adding the following parameters, the issue was resolved: --env icloud_china=false --env auth_china=false.”
<img width="963" alt="image" src="https://github.com/user-attachments/assets/21edb2e6-4f1b-448f-b597-89facaa5105e">

<img width="985" alt="image" src="https://github.com/user-attachments/assets/59d5cad1-e979-450c-9e4c-ce78b9a264f1">
