### ISSUE TITLE
how to use reauth.sh now

### ISSUE THREAD

**Issue by Arnold4869** [boredazfcuk/docker-icloudpd#566]
It seems like the script is not running as described in the configuration file.，I use to run it success in 1.0.733，but when i restart icloudpd ，it is also tell me the cookie isnot works，so i pull the latest image，but i cant run it like `docker exec -it icloudpd reauth.sh`

**Comment by boredazfcuk** [comment]
I've noticed that reauth.sh only seems to work when the cookie is already valid. Stick to using sync-icloud.sh --reinitialise for the time being.

**Comment by boredazfcuk** [comment]
This should be fixed now. If not, let me know and I'll reopen.
