### ISSUE TITLE
Missing photos on NextCloud

### ISSUE THREAD

**Issue by MPatern** [boredazfcuk/docker-icloudpd#571]
Hello, 

I setup icloudpd for download in a folder and nextcloud. But not all going to the nextcloud folder.
In my folder I've all (125GB) but on nextcloud i've only 66GB.
Can someone help me? :)

![2024-05-28 13_22_45-Window](https://github.com/boredazfcuk/docker-icloudpd/assets/111791220/d01802de-6cfd-4d85-8826-68bf63afe5f4)
![2024-05-28 13_23_01-Window](https://github.com/boredazfcuk/docker-icloudpd/assets/111791220/e3e58cdf-56dc-4b25-bd31-543902d5c351)

Best regards
Mathieu

**Comment by boredazfcuk** [comment]
The Nextcloud sync will only copy newly downloaded files to the Nextcloud server. If you've been backing up icloud for a few years, then switched on Nextcloud sync, none of those original files will have been backed up.

You can try re-uploading your whole library to Nextcloud by running `docker exec -it icloudpd sync-icloud.sh --Upload-Library-To-Nextcloud`
