### ISSUE TITLE
SharedLibrary not synced

### ISSUE THREAD

**Issue by sepl2604** [boredazfcuk/docker-icloudpd#573]
Dear all

First off: many thanks for this great library, works (almost) perfectly.

I currently have two docker containers running. One for myself and one for my wife. I have different config files and different destination folders for the media files. The config files are identical except `apple_id`, obviously.

```
agentid=
albums_with_dates=false
apple_id=foo@bar.baz
auth_china=false
authentication_type=MFA
auto_delete=false
bark_device_key=
bark_server=
content_source_url=
convert_heic_to_jpeg=false
debug_logging=false
delete_accompanying=false
delete_after_download=false
delete_notifications=true
dingtalk_token=
directory_permissions=750
discord_id=
discord_token=
download_notifications=true
download_path=
file_permissions=640
folder_structure={:%Y/%m/%d}
gotify_app_token=
gotify_https=
gotify_server_url=
group=group
group_id=1000
icloud_china=
iyuu_token=
jpeg_path=
jpeg_quality=90
libraries_with_dates=true
media_id_delete=
media_id_download=
media_id_expiration=
media_id_startup=
media_id_warning=
nextcloud_delete=false
nextcloud_password=
nextcloud_upload=false
nextcloud_url=
nextcloud_username=
notification_days=7
notification_type=
photo_album=
photo_library="all libraries"
photo_size=original
prowl_api_key=
pushover_sound=
pushover_token=
pushover_user=
recent_only=
set_exif_datetime=false
single_pass=false
skip_album=
skip_check=false
skip_download=false
skip_library=
skip_live_photos=false
skip_videos=false
startup_notification=true
synchronisation_delay=0
synchronisation_interval=86400
synology_ignore_path=false
telegram_chat_id=
telegram_polling=true
telegram_server=
telegram_silent_file_notifications=
telegram_token=
touser=
trigger_nextlcoudcli_synchronisation=
until_found=
user_id=1000
webhook_https=false
webhook_id=
webhook_path=/api/webhook/
webhook_port=8123
webhook_server=
wecom_id=
wecom_proxy=
wecom_secret=
```

My container created a `PrimarySync` and `SharedSync-XXX`, but the wife's one didn't.

![9324](https://github.com/boredazfcuk/docker-icloudpd/assets/54438678/89b77baa-fc64-4b3b-b194-5d1c62fbf466)

Am I missing something or could a setting be different in my wife's iCloud?

Many thanks for any hints or feedbacks.
Stefan

**Comment by sepl2604** [comment]
enabled DEBUG log mode and saw, that the shared library does not appear for my wife's account

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/54438678/e73f3c2d-8ff8-4e82-a56f-b9d351e7c500)

**Comment by boredazfcuk** [comment]
This is correct. Shared libraries only appear for the Apple ID that creates the library.

If you log into icloud.com you should see the same.

**Comment by sepl2604** [comment]
Many thanks for the quick reply. 

When I log in with my wife’s account I have the possibility to switch between her account only and combined (hers and the shared one) see here 

https://support.apple.com/guide/icloud/use-icloud-shared-photo-library-mm544e1bd039/icloud#:~:text=Switch%20between%20your%20Photos%20Libraries%20views&text=In%20Photos%20on%20iCloud.com%2C%20click%20the%20pop%2Dup,what%20you're%20currently%20viewing.

This popup appears on her and mine account. 

But in this case I will split mine and the shared library in two different docker containers so I can reference the shared one in immich. 

Thanks a lot!

Cheers
Stefan

**Comment by RezzZ** [comment]
> This is correct. Shared libraries only appear for the Apple ID that creates the library.
> 
> If you log into icloud.com you should see the same.

hmm just found this answer while I was wondering why I didn't get any of my shared folders downloaded. So libraries / shared albums, shared WITH me, cannot be synced/backed-up?

**Comment by Symbiot78** [comment]
I am still struggling to see the shared albums my wife created on her account.
I have icloudpd setup for my wife's account but no shared libraries/albums are shown.
it downloads all albums on her icloud. it downloads "primarySync" but no shared folders.

I had a hope that it would grab each shared album and create a folder then download the images to that/those folders.
