### ISSUE TITLE
icloud.com.cn : Failed to download new files 

### ISSUE THREAD

**Issue by fishmanxp** [boredazfcuk/docker-icloudpd#575]
I can't download photos, I don't know what wrong with this.
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/15833327/d67327ef-f938-4d6f-aa72-fa3fd89b1ecb)
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/15833327/940e5360-caa6-44f3-8e08-de2363c09401)
![boredazfcuk-icloudpd](https://github.com/boredazfcuk/docker-icloudpd/assets/15833327/218764d0-4307-4b84-8129-378f5bb87e24)

**Comment by fishmanxp** [comment]
![微信截图_20240605220824](https://github.com/boredazfcuk/docker-icloudpd/assets/15833327/26b1c4ba-0e9c-452d-b5a7-4e6fdfb39872)

**Comment by boredazfcuk** [comment]
>'Invalid email/password combination'

Try removing your keyring are re-authenticating

**Comment by fishmanxp** [comment]
I have removed keyring and re-authenticated, but the error is the same.

**Comment by boredazfcuk** [comment]
>'Invalid email/password combination'

Maybe your password, or e-mail address, has unsupported characters in it? Error message is pointing to invalid credentials, so not much more I can suggest.
