### ISSUE TITLE
Shared Library Not Downloading

### ISSUE THREAD

**Issue by srirampsbb** [boredazfcuk/docker-icloudpd#577]
I recently created a shared library and noticed that the photos from the shared library aren't getting downloaded. Here is my config snippet:
```
2024-06-09 15:52:38 INFO     Single pass mode: false
2024-06-09 15:52:38 INFO     Skip download check: false
2024-06-09 15:52:38 INFO     Downloading photos from library: all libraries
2024-06-09 15:52:38 INFO     Stop downloading when prexisiting files count is: Download All Photos
```
I tried re-initializing, restarting and manually triggering the container from telegram but I Just see:
```
2024-06-09 15:52:51 INFO     Check for new files using password stored in keyring file
2024-06-09 15:52:51 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2024-06-09 15:53:14 INFO     Check successful
2024-06-09 15:53:14 INFO     No new files detected. Nothing to download
```
Any pointers would help

**Comment by boredazfcuk** [comment]
Try switching off the new files check. I don't use shared libraries, so don't know if it actually works with shared libraries, as I've no way to test it.

**Comment by BananaElf9** [comment]
Hi Srirampsbb - can you tell me how you got to that point? I've just downloaded the photos using 

`docker run -it --rm --name icloudpd -v F:\icloudpd-app:/data -e TZ=timezone icloudpd/icloudpd:latest icloudpd --directory /data --username myemail.com --watch-with-interval 10000"
`
in the powershell. This has worked but does not download the shared library. I tried to fiddle around with docker desktop and create an icloudpd.config file but couldn't for the life of me make it happen. Any help will be greatly appreciated. I have little experience with docker.

**Comment by AndreyNikiforov** [comment]
`icloudpd` can only download assets from one library at a time, which you have to specify with `--library` parameter. If not specified, default PrimarySync library is used. You can use `--list-libraries` parameter to get a list as well.

I do not use shared libraries myself and the above is based on my reading of the code.

**Comment by AndreyNikiforov** [comment]
> `docker run -it --rm --name icloudpd -v F:\icloudpd-app:/data -e TZ=timezone icloudpd/icloudpd:latest icloudpd --directory /data --username myemail.com --watch-with-interval 10000" ` 

Note: you are using ` icloudpd/icloudpd` image from [upstream project](https://github.com/icloud-photos-downloader/icloud_photos_downloader). This repo uses `boredazfcuk/icloudpd` image and supports additional configs.

**Comment by apriliars3** [comment]
> `icloudpd` can only download assets from one library at a time, which you have to specify with `--library` parameter. If not specified, default PrimarySync library is used. You can use `--list-libraries` parameter to get a list as well.
> 
> I do not use shared libraries myself and the above is based on my reading of the code.

I want download from Shared library, I use 

docker exec -it icloudpd sync-icloud.sh --List-Libraries 

and output

2024-06-27 19:18:25 INFO     Shared libraries:
2024-06-27 19:18:25 INFO      - PrimarySync

icloudpd.conf with

photo_album="all albums"
photo_library="all libraries"
photo_size=original

but only download iCloud Photos that I have on the iPhone in my Photo app.

How can I donwload Shared Photos and iCloud Photos Library? Thanks

**Comment by AndreyNikiforov** [comment]
The list of libraries has only one "PrimarySync" and its the one used by default. I assume if you specify it in `photo_library` config, it should work

**Comment by apriliars3** [comment]
> photo_library="all libraries"



> The list of libraries has only one "PrimarySync" and its the one used by default. I assume if you specify it in `photo_library` config, it should work

No new files only iCloud on phone, not Shared Photos, I need to use this config?

photo_library="PrimarySync"

**Comment by apriliars3** [comment]
How can download my SharedSync Photos in a floder?

docker exec -it icloudpd sync-icloud.sh --List-Libraries

2024-07-01 17:35:23 INFO     Container initialisation complete
2024-07-01 17:35:23 INFO     Script launch parameters: --List-Libraries
2024-07-01 17:35:23 INFO     Directory is writable: /config/python_keyring/
2024-07-01 17:35:31 INFO     Shared libraries:
2024-07-01 17:35:31 INFO      - PrimarySync

**Comment by boredazfcuk** [comment]
> How can download my SharedSync Photos in a folder?
> 
> docker exec -it icloudpd sync-icloud.sh --List-Libraries
> 
> 2024-07-01 17:35:23 INFO Container initialisation complete 2024-07-01 17:35:23 INFO Script launch parameters: --List-Libraries 2024-07-01 17:35:23 INFO Directory is writable: /config/python_keyring/ 2024-07-01 17:35:31 INFO Shared libraries: 2024-07-01 17:35:31 INFO - PrimarySync

This is showing that you do not have a shared library. Shared libraries can only be downloaded by the account which creates them, this seems like you're trying to download someone else's shared library.

**Comment by boredazfcuk** [comment]
Closing as Op has not responded in weeks.
