### ISSUE TITLE
Docker Container keeps stopping after downloading files

### ISSUE THREAD

**Issue by Palito93** [boredazfcuk/docker-icloudpd#578]
Hello, 

I have 2 docker containers which have been running without any issues for weeks now.

But lately both docker containers keep shutting down after downloading pictures. 
Here's a screenshot of the debug:

![Screenshot 2024-06-10 071829](https://github.com/boredazfcuk/docker-icloudpd/assets/172239814/71c858b8-3bf1-4c0f-82a3-70bf3868074c)

**Comment by Leckbesteck** [comment]
I have the exact same problem.

**Comment by dunezilla** [comment]
Same here. Same debug.

**Comment by boredazfcuk** [comment]
What notification method do you have configured, if any?

**Comment by Palito93** [comment]
I have no notification method enabled (and never had if that matters)

**Comment by boredazfcuk** [comment]
Yeah, that's what I was thinking because it usually states the notification type in the log entry, but yours appears to be blank. The logic should check to make sure the notification type is set before sending one, so seems the logic is flawed, so a genuine bug. I will check shortly

**Comment by Palito93** [comment]
Thank you very much!

This started happening maybe a week ago if i had to guess a time.

**Comment by dunezilla** [comment]
Same. No notificationsThanks,Lee ThomasOn Jun 10, 2024, at 2:07 PM, Palito93 ***@***.***> wrote:﻿
Thank you very much!



This started happening maybe a week ago if i had to guess a time.

**Comment by boredazfcuk** [comment]
This was the result of a PR I merged which added support for SMTP notifications. Previously, it would only match if notifications were configured. After the PR was merged, it would  match notifications that were not SMTP, so including unconfigured notifications.

I've built and pushed a new container to Dockerhub
