### ISSUE TITLE
--env folder_structure={:%Y} not being honoured in the creation process.

### ISSUE THREAD

**Issue by nodecentral** [boredazfcuk/docker-icloudpd#58]
Hi

I’ve just built an Icloudpd container, and while I specified the following for the environment.
````
--env folder_structure={:%Y}
````
It’s being reported on the console and confirmed by the folder structure created, that it’s set to the following format..
````
2021-01-27 23:27:16 INFO     Folder structure: {:%Y/%m/%d}
````

**Comment by boredazfcuk** [comment]
If the **folder_structure** variable is not set with the `--env` parameter, it defaults to `{:%Y/%m/%d}` so it's possible that the variable isn't being created correctly.

If you connect to the docker command line, and run `env` it will show you all the environment variables that are visible from within the environment. Can you check that you see `folder_structure={:%Y}`?

**Comment by nodecentral** [comment]
Sorry, please could you help me with the full command line to see the environment values ?

**Comment by boredazfcuk** [comment]
Sorry, it's just:
```
docker exec -it <name of your container> /bin/ash
```
which will give you a command line on the container.

Then just type `env` and hit return. It should throw something back like:
```
/ # env
synchronisation_interval=43200
apple_id=not@myemail.com
HOSTNAME=syncstack_icloudpd_1
notification_type=Telegram
SHLVL=1
user_id=1000
telegram_chat_id=12345678
HOME=/root
command_line_options=
set_exif_datetime=True
group_id=1000
config_dir=/config
TERM=xterm
user=user
folder_structure={:%Y/%m}
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
group=group
auto_delete=True
jpeg_quality=100
convert_heic_to_jpeg=True
telegram_token=12332199:AAnahnottodaythanks7eo
PWD=/
TZ=Europe/London
/ #
```

Or you could just run the `env` command directly without bothering with the shell:
```
docker exec -it <nane of your container> env
```

Anyways, I have work in 7 hours so really oughta go get some sleep...

**Comment by nodecentral** [comment]
Thanks, 

running the env command - it,looks,like it’s there, but it’s not being honoured  ?

````
# docker exec -it icloudpd-icloud-com env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=MyQNAP
TERM=xterm
user=myname 
user_id=501
group=users
group_id=100
apple_id=myemail@icloud.com
apple_password=mypassword
notification_type=Prowl
interactive_only=True
prowl_api_key=Myprowlkey 
TZ=Europe/London
notification_days=14
folder-structure={:%Y}
synchronisation_interval=172800
config_dir=/config
HOME=/root

**Comment by boredazfcuk** [comment]
The variable in your env is incorrect.

The correct variable name is **folder_structure**, but you have **folder-structure** with a hyphen instead of underscore.

**Comment by nodecentral** [comment]
Doh !!

thanks @boredazfcuk

**Comment by boredazfcuk** [comment]
No worries, bud. Enjoy :)
