### ISSUE TITLE
Help with docker desktop icloudpd (using windows 11) and incorporating Shared Libraries

### ISSUE THREAD

**Issue by BananaElf9** [boredazfcuk/docker-icloudpd#582]
The below is from the configuration.md file

Set photo_album="all albums" in your configuration file /config/icloudpd.conf to download all albums.

I'm very new to docker and programming in general and am struggling to run the docker script with icloudpd.conf

i've successfully used the script like this in powershell:
docker run -it --rm --name icloudpd -v F:\icloudpd-app:/data -e TZ=(My Timezone) icloudpd/icloudpd:latest icloudpd --directory /data --username (my icloud email) --watch-with-interval 10000

it asked me for my password and 2FA

this ran the script but did not incorporate my wife's shared album in icloud which is why I'm trying the config route.

Any tips to get me in the right direction will be helpful, thanks!

**Comment by boredazfcuk** [comment]
> icloudpd/icloudpd:latest

This isn't my container the repo you need for that is here: https://github.com/icloud-photos-downloader/icloud_photos_downloader

My container is a wrapper for the same application which aims to provide additional functionality around it, however, it's not designed to be run with `docker run` command and I don't support the `--watch-with-interval` parameter either, as my container has options to configure a synchronisation interval instead.
