### ISSUE TITLE
Error downloaded files notification failed with http status code: and curl exit code: ash: out of range

### ISSUE THREAD

**Issue by JuliusB1601** [boredazfcuk/docker-icloudpd#584]
Since a few days I always get this message. After this error occurred, the container stops working. The restart is no problem and the new files are always downloaded correctly, but this message stops the container. 
I haven't tried the debug_logging=true yet, but will post it, when the error occurs again. 

 Does anyone know this problem and how to fix it?

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/73830610/47f6b971-c79a-4a1c-b98c-8f3fd29fb862)
![image](https://github.com/boredazfcuk/docker-icloudpd/assets/73830610/a66960de-dd4c-4616-a051-fee41bafa128)

**Comment by boredazfcuk** [comment]
This was a bug introduced by some code which allows SMTP notifications. This has been fixed in latest version.
