### ISSUE TITLE
Trouble creating the .mounted file

### ISSUE THREAD

**Issue by DaveHamilton** [boredazfcuk/docker-icloudpd#587]
Something is amiss, and I'm trying to sort out what I've got going wrong. Similar to issue #49 I am getting stuck at the "WARNING Failsafe file /downloads/.mounted is not present". 

The odd part is that I can go into a Terminal inside of Container Manager on my Synology, run `sh` and then issue a `cd /downloads` and see the folder to which I have it mapped. I can even do a `touch testwithin` and it appears, and I can even chown that file to my heart's content.

And if I create a `.mounted` inside of this folder, then it moves on. But when it moves on, it never actually saves anything to that folder, further indicating that it's got an issue actually creating a file in there. But it's definitely looking in the right place.

Any ideas? I have permissions on that folder set to 777 so in theory that shouldn't be stopping anything.

<img width="683" alt="image" src="https://github.com/boredazfcuk/docker-icloudpd/assets/1993106/c4dbf351-e0cd-4f18-8035-23dd0607347b">
<img width="1172" alt="image" src="https://github.com/boredazfcuk/docker-icloudpd/assets/1993106/a2b5d1e6-b39f-47c7-b02b-62c6f1746e23">
<img width="726" alt="image" src="https://github.com/boredazfcuk/docker-icloudpd/assets/1993106/b016b05b-5154-427c-98d9-1214fef52ca4">

**Comment by boredazfcuk** [comment]
Try again with the latest version. I found a bug related to user switching and can see your user is displayed as an ID rather than a named user, so it must be affected by the bug. If it doesn't fix the issue, please reopen.
