### ISSUE TITLE
Does iCloudPD Monitor Deletions and Replicate Them to iCloud?

### ISSUE THREAD

**Issue by chrisborell** [boredazfcuk/docker-icloudpd#588]
I have a specific use case and was wondering if iCloudPD supports it. I am using **Immich** to manage my photo library and would like to ensure that any photo deletions made in Immich are replicated in iCloud.

Specifically, does iCloudPD:

1. Monitor the local photo directory for deletions?
2. Automatically delete the corresponding photo in iCloud when a photo is deleted locally?
3. If so, how to do it?

Thanks in advance for your assistance!

**Comment by boredazfcuk** [comment]
Hi,

To answer your questions:

1) No
2) No
3) I don't know if any application which provides that functionality.

Thanks
