### ISSUE TITLE
SMB or NFS Mount on Host

### ISSUE THREAD

**Issue by cutzenfriend** [boredazfcuk/docker-icloudpd#589]
Scenario:

VM has mounted a Synology volume on /mnt/x (tried SMB and NFS) and running Container has mount /mnt/x -> /home/* inside the container. Already tried to use the mount option ":z". Doesn't help.

I always get this error. If I go inside the container with sh I can write / read inside /home/* without any issues.

```
icloudpd  | 2024-06-27 12:29:16 ERROR    IOError while writing file to /home/*/iCloud/2015/02/15/IMG_9616.JPG. You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
icloudpd  | 2024-06-27 12:29:17 ERROR    IOError while writing file to /home/*/iCloud/2015/02/15/IMG_9611.JPG. You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
```

**Comment by boredazfcuk** [comment]
This error is always down to permissions.

Are you performing the test writes as the root account, or the user account which actually performs the writes? The shell prompt should be green if you are logged on as the user, not red.

**Comment by cutzenfriend** [comment]
The script within the container runs as root. Inside the config I added username, id and group. But this user doesn't get created when I start the container.

<img width="655" alt="image" src="https://github.com/boredazfcuk/docker-icloudpd/assets/1510611/8520eba6-cb14-44bb-9719-37775eb124f5">

**Comment by boredazfcuk** [comment]
> The script within the container runs as root.

Script uses `su` to switch users. This error you're raised is always permissions. Maybe your container is running rootless, or unprivileged, or your SMB/NFS shares are filtering the changes, etc.

Try removing the /config mount from the container's configuration and see if that creates the icloudpd.conf file as expected. Edit the file from within the container to remove some lines, then restart it and see if they get put back.

**Comment by cutzenfriend** [comment]
Okay I changed some parameters of the mount command. If I recreate the container it runs until this log entry and then stops:

```
icloudpd  | 2024-06-28 18:39:39 INFO     Failsafe file /home/user/iCloud/.mounted exists, continuing
icloudpd  | 2024-06-28 18:39:39 INFO     Directory is writable: /config/python_keyring/
icloudpd  | 2024-06-28 18:39:39 INFO     Keyring file exists, continuing
icloudpd  | 2024-06-28 18:39:39 INFO     Sync user: user
icloudpd  | 2024-06-28 18:39:39 INFO     Synchronisation starting at 18:39:39
icloudpd  | 2024-06-28 18:39:39 INFO     Keyring file exists, continuing
```

sh inside the docker is "green" an I can read and write everywhere. Host system is an Alpine Linux if that helps.

**Comment by cutzenfriend** [comment]
I started from scratch an downloaded everything from the start. This worked.

**Comment by boredazfcuk** [comment]
Thanks for letting me know
