### ISSUE TITLE
grep: /config/icloudpd.conf: No such file or directory

### ISSUE THREAD

**Issue by docscooby** [boredazfcuk/docker-icloudpd#593]
fairly new to this, downloaded via community apps for unraid. created mounted file and am now running into this error.

**Comment by ryanmilley** [comment]
Same thing happening here. Worked fine when I tried it last week. Made a fresh unraid install and its giving that error. During bootup of the container it says it can't write the config file and to check my permissions. I tried manually using chmod with no luck

**Comment by boredazfcuk** [comment]
This is likely due to some code left in by mistake which latest version of the container should fix.
