### ISSUE TITLE
Folder_structure option ignored when specifying photo_library option

### ISSUE THREAD

**Issue by stingray75** [boredazfcuk/docker-icloudpd#594]
I've been using iCloudPD to download my photos from my personal library into YYYY/MM folders for many years - thanks so much for your work on this.  I've just started using a shared library with my wife, so I have been moving some of my media from my personal library into the shared library.

In iCloudPD I set the _photo_library_ option to "all libraries". 

This successfully downloads from both libraries, however, it's now ignoring the _folder_structure_ option, resulting all personal photos/videos being downloaded into a single folder PrimarySync and shared media into a single folder SharedSync - it's not creating the YYYY/MM folders beneath. This is a problem with 75k photos as some file names are the same.

I can understand that the _photo_album_ option doesn't create subfolders, as it's likely that albums will only contain a small amount of photos, but I don't get why the _photo_library_ option does this.

It's also creating duplicates, as media I've moved from personal to shared is now downloading from shared but not being removed from my already downloaded personal folder.  I'll raise this as a separate issue.

**Comment by stingray75** [comment]
Looking through the code, I just found the _libraries with dates_ option!  It would be useful if you could reference this option under the readme photo_library section. :-)

**Comment by RezzZ** [comment]
> libraries_with_dates

thanks for this. I added the all libraries later on and ended up with icloudpd redownloading everything to the PrimarySync folder without year/month/day subfolders. I stopped the container, updated the config file, moved all already downloaded year folders to the PrimarySync folder and restarted the container. All working again :)
