### ISSUE TITLE
Moving photos between personal and shared library results in duplicate files

### ISSUE THREAD

**Issue by stingray75** [boredazfcuk/docker-icloudpd#595]
If I take a photo and it's stored in my iCloud Photos personal library, it will be downloaded into the /photos/PrimarySync folder.  If I then move that photo to my shared library, it will then also be downloaded into /photos/SharedSync, resulting in two copies of the file. And vice versa moving from shared to personal.

Is it possible for iCloudPD to detect that a file has been moved from one library to the other, and delete the original? I have check_files set to false as I have 100k photos/videos, not sure if that has any bearing on this.

**Comment by boredazfcuk** [comment]
No, it's not possible to do this. It does not do file tracking, so there is no way to recognise if a file has been removed from PrimarySync/SharedSync
