### ISSUE TITLE
Feature request: telegram notification

### ISSUE THREAD

**Issue by eldudemeister** [boredazfcuk/docker-icloudpd#6]
Hi, would it be possible to incorporate telegram as a notification service for when the cookie is due to expire? Admittedly I'm not sure how feasible this is but I have it as a notification service for other docker containers and would be nice to incorporate this too.

**Comment by boredazfcuk** [comment]
Sorted.

You'll just three variables to get it working:
```
NOTIFCATIONTYPE=Telegram
APIKEY=1234567890:abcdefghijklmnopqrstuvwxyz123456789
TELEGRAMCHATID=987654321
```
APIKEY is the <token> that you get when you create your bot
TELEGRAMCHATID is the chat_id that is given to you after you start a conversation with the bot and then got the the URL https://api.telegram.org/bot<TOKEN>/getUpdates

**Comment by eldudemeister** [comment]
That's amazing, all set up, thanks so much!

**Comment by boredazfcuk** [comment]
No worries. Let me know if you don't get the notification though, please.

I rebuild and reset my container fairly frequently during testing, so I've never had a cookie get within 7 days of the renewal period. I regenerate it too often!
