### ISSUE TITLE
Can't Convert from HEIC to JPEG

### ISSUE THREAD

**Issue by Wongolian** [boredazfcuk/docker-icloudpd#604]
Since June 10th been unable to convert my photos to JPEG. I am running iOS 18 beta for what its worth which is why I am assuming I've been having this issue.

![image](https://github.com/boredazfcuk/docker-icloudpd/assets/48544232/f9641292-77b5-4a9b-87de-9ef90f07df32)

**Comment by boredazfcuk** [comment]
There is a fix upstream: https://github.com/strukturag/libheif/issues/1190

Once the fixed version hits the Alpine libraries I'll update the container.

**Comment by boredazfcuk** [comment]
Seems that the fixed version of libheif has been built and pushed to the Alpine Linux testing branch a few hours ago: https://pkgs.alpinelinux.org/packages?name=libheif&branch=edge&repo=&arch=&maintainer=

As Alpine Linux 20.0.2 was released yesterday, this likely means that the next version of Alpine, which should hopefully include this updated version of libheif, is a month or so away.

**Comment by boredazfcuk** [comment]
Alpine Linux 3.20.3 was released a few days ago. Still didn't have the updated version (1.18.2-r0) however, I've rebuilt the container using just the libheif package from the edge release. Please test and report back.

**Comment by Wongolian** [comment]
> Alpine Linux 3.20.3 was released a few days ago. Still didn't have the updated version (1.18.2-r0) however, I've rebuilt the container using just the libheif package from the edge release. Please test and report back.

Testing looks good. Photos are converting to viewable jpgs again. Thanks!
