### ISSUE TITLE
something wrong on the conf synchronisation_interval

### ISSUE THREAD

**Issue by CrazyFnOption** [boredazfcuk/docker-icloudpd#607]
if you set synchronisation_interval less than the time you used to pull out the photoes from icloud, you will sync photo next day..
just like this
`2024-07-07 18:43:25 INFO     Total time taken: 00:06:02
2024-07-07 18:43:25 INFO     Next synchronisation at 18:37:23`

**Comment by boredazfcuk** [comment]
>if you set synchronisation_interval less than the time you used to pull out the photoes from icloud

I don't understand what you mean. What have you set **synchronisation_interval** to?

**Comment by boredazfcuk** [comment]
Closing as abandoned
