### ISSUE TITLE
what format the fully qualified domain name of the telegram_server should be

### ISSUE THREAD

**Issue by mrsoshining** [boredazfcuk/docker-icloudpd#612]
因为一些特殊的原因，我想使用telegram_server这个参数，但我不知道代理服务器的完全限定域名应该是什么格式的，我从网上找的或者自己搭建的，类似https://t.me/proxy?server=47.2*.*.*7&port=65092&secret=eed6e9a3a5ab755a6baf20b2e6ce241ca9617a7572652e6d6963726f736f66742e636f6d这样的格式仿佛不起作用。能给我一个示例吗？

**Comment by boredazfcuk** [comment]
I have no idea what any of that says.

**Comment by mrsoshining** [comment]
> I have no idea what any of that says.
Sorry, I meant：
Due to some special reasons, I want to use the parameter telegram_server, but I don't know what format the fully qualified domain name of the proxy server should be. The ones I found online or set up myself, like https://t.me/proxy?server=47.2*.*.*7&port=65092&secret=eed6e9a3a5ab755a6baf20b2e6ce241ca9617a7572652e6d6963726f736f66742e636f6d, don't seem to work. Could you provide me with an example?
Thank you very much!

**Comment by mrsoshining** [comment]
> > I have no idea what any of that says.
> 
> Sorry, I meant： Due to some special reasons, I want to use the parameter telegram_server, but I don't know what format the fully qualified domain name of the proxy server should be. The ones I found online or set up myself, like https://t.me/proxy?server=47.2*.*.*7&port=65092&secret=eed6e9a3a5ab755a6baf20b2e6ce241ca9617a7572652e6d6963726f736f66742e636f6d, don't seem to work. Could you provide me with an example? Thank you very much!

I don't know if the format of telegram_server is the same as the MTProto proxy used in the Telegram app. Thank you.

**Comment by boredazfcuk** [comment]
I don't know it either as I don't use it personally. I need to check the code to see what it wants when I get some spare time.

**Comment by mrsoshining** [comment]
> I don't know it either as I don't use it personally. I need to check the code to see what it wants when I get some spare time.

Thanks！

**Comment by mrsoshining** [comment]
> ```
>          if [ "${telegram_server}" ] ; then
>             notification_url="https://${telegram_server}/bot${telegram_token}/sendMessage"
>          else
>             notification_url="https://api.telegram.org/bot${telegram_token}/sendMessage"
>          fi
> ```
> 
> The **telegram_server** variable is just a hostname e.g. proxy.server.com.
> 
> It assumes https, so if your server is http, then changes will be required.

thanks!Maybe I need to build a telegram bot api local server?

**Comment by pkuGeo** [comment]
> ```
>          if [ "${telegram_server}" ] ; then
>             notification_url="https://${telegram_server}/bot${telegram_token}/sendMessage"
>          else
>             notification_url="https://api.telegram.org/bot${telegram_token}/sendMessage"
>          fi
> ```
> 
> The **telegram_server** variable is just a hostname e.g. proxy.server.com.
> 
> It assumes https, so if your server is http, then changes will be required.

maybe notification_url="${telegram_server}/bot${telegram_token}/sendMessage" will be better

**Comment by boredazfcuk** [comment]
> > ```
> >          if [ "${telegram_server}" ] ; then
> >             notification_url="https://${telegram_server}/bot${telegram_token}/sendMessage"
> >          else
> >             notification_url="https://api.telegram.org/bot${telegram_token}/sendMessage"
> >          fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The **telegram_server** variable is just a hostname e.g. proxy.server.com.
> > It assumes https, so if your server is http, then changes will be required.
> 
> maybe notification_url="${telegram_server}/bot${telegram_token}/sendMessage" will be better
> 
> thus users can decide whether http or https to provider. I have encounter this problem now. I need a proxy to access telegram services. But after I finished my "telegram server" I found I that I should provide https service. And next problem is that I could only provide self signed certificate which could not pass the SSL check of iCloudPD

Latest version now has a new variable. Set **telegram_http=true** for it to use http:// instead of https://
