### ISSUE TITLE
HEIC to JPEG only works with default jpeg_path

### ISSUE THREAD

**Issue by cjdbury** [boredazfcuk/docker-icloudpd#614]
Running icloudpd container v1.0.906_10-07-2024 on Unraid. The log terminal would start listing all the photos, saying it was converting, but nothing would ever show up in my JPEG path. When I set JPEG path to blank, it started working.

**Comment by boredazfcuk** [comment]
I can't really see anything in the code that suggests there's an error. The only thing I can think is permissions. I've used a new version to Dockerhub which now sets permissions on the jpeg_path, just to make sure nothing odd is happening.

Give that a go and see what happens. If it doesn't work, post a log snippt. I want to see what your jpeg_path is, maybe there's something odd with the naming.

**Comment by boredazfcuk** [comment]
Closing as no response. Presumably working as per last comment now.
