### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by tinopst** [boredazfcuk/docker-icloudpd#617]
Hi

anyone knows how I need to set the .conf file to have a 1:1 folder/album structure?
In my Photo Library (icloud) I have some folders like "Travel", "Family" etc. Under those folder I have create various albums.
ex:
Family --> Christmas
Family --> Birthday
Travel --> New York
Travel --> London

What exactly do I need to set to keep the same folder/album structure?

thanks

**Comment by tinopst** [comment]
Is nobody able to help me with this?

thanks

**Comment by boredazfcuk** [comment]
It's not possible to sync folder structures with this utility. Photo album is the best you'll get, but even then, syncing half a dozen or more albums at once usually results in Apple forcibly expiring your multi-factor authentication cookie and then you need to re-initialise the container.
