### ISSUE TITLE
unable to perform sync-icloud.sh --Initialise (Traceback error) - on Truenas Scale Dragonfish-24.04.2

### ISSUE THREAD

**Issue by mrkongster** [boredazfcuk/docker-icloudpd#619]
Hmm... after migrating to Dragonfish and lost the Truechart thing, I am having trouble with my previously working find icloudpd.  I am not sure what happen, may be I messed it up.  I had to reinstall the icloudpd docker build on this Dragonfish version.

When I am using the 'latest' version of build, I get the error and had to wait for 2 minutes, then it goes to asking my password, but once I enter, the MFA didn't get trigger and go straight to error.  

I read on a Reddit post https://www.reddit.com/user/Jian_Yang_94040/; I revert to an older build, build 1.0.816 which the reddit poster had someone said it worked for them.  However, I now don't have the error causing me to wait 2 minutes, but I don't get the prompt asking for my password either.  Instead, I get this Traceback (most recent call last) message pointing to File "urllib3/connection.py" for example.  My error log is attached.  Can someone help with with this?  

Anthony
[2024.07.21 initialize error 02.txt](https://github.com/user-attachments/files/16326815/2024.07.21.initialize.error.02.txt)

**Comment by boredazfcuk** [comment]
>Failed to establish a new connection: [Errno 113] No route to host

You have network issues in your container. It cannot find a route out of your network to get to the Internet.
