### ISSUE TITLE
wecom token get , curl request fail

### ISSUE THREAD

**Issue by fanhuameng** [boredazfcuk/docker-icloudpd#623]
Hi all
   me use wecom get token， but curl request fail;
   curl usar-agent define paramter is “curl 7.61.1”, the server intercepts curl request, user-agent;
   curl needs to add the user-agent parameter;
Thank you for your help.

**Comment by boredazfcuk** [comment]
I don't understand what you mean by "curl needs to add the user-agent parameter".

When curl contacts a website it sends its User Agent in the format: “curl/version.number”, so "curl/7.61.1" in the example above.

The user agent in curl can be changed to emulate other browsers, but I've no idea if this would fix it, or what to even emulate if that is the issue.

**Comment by fanhuameng** [comment]
Some sites restrict access to Curl in the nginx profile;
The site returns 403 when accessed through curl， ；
Adding the parameter  --user-agent  to curl solves this problem；

--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"


![Snipaste_2024-07-13_19-37-04](https://github.com/user-attachments/assets/5198b4fb-c63b-493d-9e8b-f21d2d662496)

**Comment by boredazfcuk** [comment]
I've pushed a new version which will use a fake user agent for Wecom notifications when you set **fake_user_agent=true** in your icloudpd.conf. Let me know if that resolves the issue.

**Comment by fanhuameng** [comment]
Trust me, you're wrong on this one
![Snipaste_2024-08-31_21-23-25](https://github.com/user-attachments/assets/cd9c98fc-2e0c-4b80-8962-fdd822188be9)

**Comment by boredazfcuk** [comment]
Oops. Got them the wrong way around. Try again.

**Comment by fanhuameng** [comment]
These two places also need to be modified
![image](https://github.com/user-attachments/assets/efb8408f-9212-4abe-8ca8-834e9378eac9)
![Uploading image.png…]()

**Comment by fanhuameng** [comment]
These two places also need to be modified
![Snipaste_2024-08-31_21-51-29](https://github.com/user-attachments/assets/99d3b4c8-5ba6-4b68-bca0-65f988ce834d)
![Snipaste_2024-08-31_21-52-27](https://github.com/user-attachments/assets/5d1342af-12e9-4e10-820a-1af24f1af899)

**Comment by fanhuameng** [comment]
I tried to modify the code in July. That should do the trick;
![Snipaste_2024-09-01_04-00-26](https://github.com/user-attachments/assets/faa2d22f-f425-4d8f-8728-0e6c01bce633)
![Snipaste_2024-09-01_04-00-43](https://github.com/user-attachments/assets/dbb80bca-1f37-4009-ab70-428576daa2b2)

**Comment by boredazfcuk** [comment]
I've just pushed a new version out which should have similar changes I made yesterday. Try again.

**Comment by fanhuameng** [comment]
Yes, thank you very much;
This is working fine.
![Snipaste_2024-09-01_19-58-43](https://github.com/user-attachments/assets/8e170292-a8b9-4606-836b-be8220c780bd)

**Comment by fanhuameng** [comment]
Yes, thank you very much;
This is working fine.

The log on my server says the request was answered.
![Snipaste_2024-09-01_19-58-43](https://github.com/user-attachments/assets/5f31fe9b-8be9-46ea-8838-4a7f2489e5c6)
