### ISSUE TITLE
Advanced data protection needs to be disabled to work?

### ISSUE THREAD

**Issue by Austinzveare** [boredazfcuk/docker-icloudpd#626]
While troubleshooting this to try and get it to work I found a comment in a now close issue that said that you need advanced data protection to be disabled for this docker to work, lo and behold that did the trick. If possible I'd like for this not to be the case as disabling something like that just to get this to work is a non-starter for me.

**Comment by mmshivesh** [comment]
This is by design, as they are contradictory needs. End-to-end encryption means that Apple even disables access online at iCloud.com, and all data is _only_ accessible from devices you possess.

> When you turn on Advanced Data Protection, access to your iCloud data on the web at iCloud.com is disabled to ensure that your data is available only on your trusted devices
> Source: [Apple support article](https://support.apple.com/en-us/108756)

**Comment by boredazfcuk** [comment]
> While troubleshooting this to try and get it to work I found a comment in a now close issue that said that you need advanced data protection to be disabled for this docker to work, lo and behold that did the trick.

The fourth and fifth sentences of the README file: Please note, Apple's Advanced Data Protection (ADP) is not supported. ADP must be disabled for this container to work.

>If possible I'd like for this not to be the case as disabling something like that just to get this to work is a non-starter for me.

Not possible as far as I'm aware. I have no interest in enabling ADP on my own account as having a backup of my photos is more important to me. Without ADP enabled on my own account, I have no way of testing any features relating to its functions.
