### ISSUE TITLE
Is icloudpd sync or backup?

### ISSUE THREAD

**Issue by antonispgs** [boredazfcuk/docker-icloudpd#628]
Will my local photos be deleted if I delete them from iCloud when icloudpd syncs the following day? Or does it only download the photos and that’s it?

**Comment by AndreyNikiforov** [comment]
> Will my local photos be deleted if I delete them from iCloud when icloudpd syncs the following day? Or does it only download the photos and that’s it?

`icloudpd` can work either way. It actually supports [three modes of operation](https://icloud-photos-downloader.github.io/icloud_photos_downloader/mode.html)

`icloudpd` is not a back up tool though, more like a `copy` tool which can be used as part of your backup strategy/workflow.
