### ISSUE TITLE
icloudpd doesn't download "normal" photos and videos when using the "photo_album:xxx" option

### ISSUE THREAD

**Issue by NutellaPizzza** [boredazfcuk/docker-icloudpd#631]
Hi everyone,
to be honest, I'm not sure if it's a user error or an error from icloudpd.

I'm using icloudpd for the first time, it's been running on my Synology NAS DS923+ in Docker for about a week.

At the beginning I just let icloudpd run and configured only the most important options. Here I had the problem that icloudpd did not find the .mounted file at first.

After a lot of trial and error, I came across the solution on Reddit: set the download_path to /iCloud/iCloud instead of just /iCloud. It then worked for me.

Now to the actual problem:
During the first synchronizations, a folder structure to yyyy-mm-dd was created as desired and all pictures & videos were synchronized.

Then I also wanted to sync my albums and shared albums. 
To do this, I added the following options to the config:
photo_album="all albums”
photo_library="all libraries"
skip_album="Hidden,All Photos,Time-lapse,Videos,Screenshots,Live,Recently Deleted,Bursts,Panoramas”
skip_library=
(I have left skip_library empty, see log & conf “albums”)

My idea was to save the photos to yyyy-mm-dd as before and also save my iCloud albums such as “London 2024” or "WhatsApp" as an extra folder while skipping "All Photos", "Screenshots" etc. as I have them in my yyyy-mm-dd folders.
This creates the problem that icloudpd shows that new photos & videos have been found (as it shows in the logs), but does not download them. It skips them and starts to download the other albums such as “WhatsApp”.

To test this, I have left the above options blank again:
photo_album=
photo_library=
skip_album=
skip_library=

And suddenly icloudpd downloads again as desired in the format yyyy-mm-dd (log & conf “normal”). Just without my albums.

Please see the attached logs an configuration files (I renamed the logs and config files so you can tell them apart).
For privacy reasons, I replaced my iCloud mail with XXX.

Could you provide support here?
Have I made a configuration error or is it icloudpd?

Thank you very much!

NutellaPizza
[icloudpd logs and conf.zip](https://github.com/user-attachments/files/16648091/icloudpd.logs.and.conf.zip)

**Comment by boredazfcuk** [comment]
It won't download libraries/albums and photos at the same time. You would need two/three containers for that. One to download All Photos and another to download the libraries/albums. Due to a quirk in the way that icloudpd works, downloading multiple albums will result in multiple login attempts to icloud.com. Apple will detect this and force the expiry of the multi-factor authentication token, requiring the container to be re-initialised again.

**Comment by NutellaPizzza** [comment]
Thanks for the explanation, I will try it with two conatiners.
