### ISSUE TITLE
Add http_proxy and https_proxy Support for Docker to Enable Telegram Usage

### ISSUE THREAD

**Issue by WPF0414** [boredazfcuk/docker-icloudpd#634]
Hi,

I am currently facing an issue due to regional restrictions that prevent me from using Telegram. To work around this, I need to configure http_proxy and https_proxy for Docker to route the traffic through a proxy server.

Could you please add support for setting http_proxy and https_proxy environment variables in the Docker configuration? This would allow me to use Telegram successfully despite the regional restrictions.

Thank you for your assistance!

**Comment by boredazfcuk** [comment]
According to this: https://www.baeldung.com/ops/docker-setting-proxy you just need to create your container with those as variables. Have you tried that? If so what's failing?

**Comment by WPF0414** [comment]
Hello, I’m using http_proxy and https_proxy, and it shows "Bot has been initialised." However, the error message is: "Telegram startup notification failed with HTTP status code: 400 and curl exit code: 0." I’m sure my tg_token and chat_id are correct, but I’m not sure where the problem is.
