### ISSUE TITLE
Unable to use apps user

### ISSUE THREAD

**Issue by airbornetrooper82573** [boredazfcuk/docker-icloudpd#636]
Tried setting this up but when I configure to use my apps user and apps group, both are 568, I get this error: useradd warning: apps's uid 568 outside of the UID_MIN 1000 and UID_MAX 6000 range.

**Comment by airbornetrooper82573** [comment]
I think I got past this by enabling the force_gid. Now I'm getting:
icloudpd-icloudpd-1  | 2024-08-24 13:06:35 INFO     Check download directory mounted correctly...
icloudpd-icloudpd-1  | 2024-08-24 13:06:35 WARNING  Failsafe file /photos/.mounted file is not present. Waiting for failsafe file to be created...

I can ssh into /mnt/tank/icloudpd/ and I see both /config and /photos. Both are apps:apps ownership. I was able to initialize and all the config settings are in /config. Not sure why it keeps saying photos isn't present.

**Comment by boredazfcuk** [comment]
You did create the the .mounted file as per the configuration guide?

**Comment by airbornetrooper82573** [comment]
Apologies, I must have skipped over that part. I was able to shell into the container and manually create and as soon as I hit save it started running!

**Comment by boredazfcuk** [comment]
Cool. Thanks for the update.
