### ISSUE TITLE
Next sync date format change

### ISSUE THREAD

**Issue by elliotcz97** [boredazfcuk/docker-icloudpd#638]
First of all, thank you for the amazing docker, I love it!

I have one question, is it possible, that you change the line: 
`LogInfo "Next synchronisation at $(date +%H:%M:%S -d "${sleep_time} seconds")" `

I want that it shows the full date, with year and months. The current date format is okay if u download daily, but I download at a 3 day period, and it would be nice to see the date of the next synchronization instead of just the time.

Can you add a toggle for that so that we can switch between exact date and the current one?

Thank you in advance!

**Comment by boredazfcuk** [comment]
I've just pushed a new version which should use the locale's setting for the date format if the next synchronisation date is more than 20 hours in the future. Give it a go and let me know if it doesn't work.

**Comment by elliotcz97** [comment]
Checked it out today, and it is working as you described, displaying a full date.

Thank you for your fast response and update!
