### ISSUE TITLE
Telegram Notification Fail

### ISSUE THREAD

**Issue by WuhanSy** [boredazfcuk/docker-icloudpd#64]
<img width="859" alt="截屏2021-05-13 上午4 56 04" src="https://user-images.githubusercontent.com/23512897/118043612-2d405300-b3a8-11eb-931f-81cdc446ea0e.png">

Sending the message failed. However, there is no problem using the api test!

e.g:https://api.telegram.org/bot"Token"/sendMessage?chat_id="chat_id"&text=Hello World

**Comment by boredazfcuk** [comment]
I've just tested it from a brand new container I started from my server and it tested OK.

You can create a new container, start it, send a test notification (from inside the container itself), stop and remove the container, all with one command:

```
docker run --rm --name test_icloudpd boredazfcuk/icloudpd \
   curl --silent --request POST "https://api.telegram.org/bot<Token&API>/sendMessage" \
   --data chat_id="<ChatID>" \
   --data parse_mode="markdown" \
   --data text="This is a test message"
```

It should then return an "OK" message similar to this:

```
{"ok":true,"result":{"message_id":1234,"from":{"id":<ID>,"is_bot":true,"first_name":"icloudpd","username":"my_bot"},"chat":{"id":<ChatID>,"first_name":"J","type":"private"},"date":99999999,"text":"This is a test message"}}
```

**Comment by WuhanSy** [comment]
It’s perfect! thank you!

发自我的iPhone

**Comment by boredazfcuk** [comment]
Cool. I'll close the issue. It's likely that the problem with the other container is due to it's network or DNS settings.
