### ISSUE TITLE
我配置了HTTP_PROXY但是好像不生效

### ISSUE THREAD

**Issue by ershouqingge** [boredazfcuk/docker-icloudpd#644]
<html>
<body>

2024/09/06 11:25:13 | stdout | 2024-09-06 11:25:13 ERROR    ***** Please post the above debug log, along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
-- | -- | --
2024/09/06 11:25:13 | stdout | 2024-09-06 11:25:13 ERROR    Telegram startup notification failed with http status code: 000 and curl exit code: 28
2024/09/06 11:23:06 | stdout | 2024-09-06 11:23:06 INFO     Sending Telegram startup notification
2024/09/06 11:23:06 | stdout | 2024-09-06 11:23:06 DEBUG    Startup notification: Enabled
2024/09/06 11:23:06 | stdout | 2024-09-06 11:23:06 DEBUG    Telegram silent file notifications: false
2024/09/06 11:23:06 | stdout | 2024-09-06 11:23:06 INFO     Latest update id: 0
2024/09/06 11:22:56 | stdout | 2024-09-06 11:22:56 INFO      - Bot has not been initialised or needs reinitialising. Please send a message to the bot from your iDevice and restart the container. Disabling remote wake
2024/09/06 11:22:56 | stdout | 2024-09-06 11:22:56 DEBUG    Bot check:
2024/09/06 11:20:49 | stdout | 2024-09-06 11:20:49 DEBUG    Checking api.telegram.org for updates
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 INFO     Check Telegram bot initialised...
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 DEBUG    Telegram notification URL: (hidden)
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 DEBUG    Telegram base URL: (hidden)
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 DEBUG    Telegram uses HTTP: false
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 DEBUG    Telegram polling: true
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 DEBUG    Telegram chat id: (hidden)
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 DEBUG    Telegram token: (hidden)
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 DEBUG    Cleaned notification title: �
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 INFO     Telegram notifications enabled
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 INFO     Convert HEIC to JPEG: false
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 INFO     Skip videos: false
2024/09/06 11:20:48 | stdout | 2024-09-06 11:20:48 INFO     Live photo size: original

</body>
</html>

**Comment by boredazfcuk** [comment]
Curl status 28 is a timeout.

Check your network and proxy server.

**Comment by ershouqingge** [comment]
> Curl status 28 is a timeout.
> 
> Check your network and proxy server.

代理通过环境变量设置为
http_proxy:http://127.0.0.1:7890
这样是可行的吗

**Comment by ershouqingge** [comment]
> English only please. I can't read that.

Sorry, I thought you were using a translation, my proxy is set via environment variables to http_proxy:http://127.0.0.1:7890, I was wondering if this is correct?

**Comment by languis** [comment]
代理连接超时了，检测下代理的连接性吧。

**Comment by boredazfcuk** [comment]
> > English only please. I can't read that.
> 
> Sorry, I thought you were using a translation, my proxy is set via environment variables to http_proxy:http://127.0.0.1:7890, I was wondering if this is correct?

https://github.com/boredazfcuk/docker-icloudpd/issues/634

Probably need that too
