### ISSUE TITLE
delete from backups?

### ISSUE THREAD

**Issue by JuanIsOnline** [boredazfcuk/docker-icloudpd#645]
Good day, all. I didn't know where else to ask as I couldn't seem to figure it out with the documentation. 

Is there a way to get `icloudpd` to delete photos you have deleted from iCloud?

**Comment by boredazfcuk** [comment]
No. The icloupd is a one-way sync. It will evaluate what's on icloud.com and copy that to the local disk.

However, it will also scan icloud.com's 'Recently Deleted' directory and remove any local files which it finds in there, provided the auto_delete=true variable is set.

So if you take a photo, let icloupd sync, delete the photo so it sits in 'Recently Deleted', sync icloupd again, the local file will be removed.

If you take a photo, let icloudpd sync, delete the photo and then remove it from (or empty) 'Recently Deleted', before letting icloudpd sync again, it will not know you have remove the file.

The best approach I have found is to only send photos to 'Recently Deleted' the day after they are taken (and sync every 12 hrs).

Means what is on your server is pretty much same as what is on your phone. Especially if you use the "remote sync" feature of the telegram integration. Can take a bunch of photos, then force icloupd at home to sync everything you've just shot.

**Comment by JuanIsOnline** [comment]
Thanks so much for this detailed explanation. I appreciate it. Curious, did I miss this information somewhere in the documentation? I searched for `delete` and `remove` but didn't see much. I ask cause I am sure others might want to know the same and maybe you can add that somewhere, it was an awesome explanation. Thanks again!
