### ISSUE TITLE
Is it safe to use?

### ISSUE THREAD

**Issue by HowlGao** [boredazfcuk/docker-icloudpd#646]
Since iCloud photos are very personal data, and it'll get the password, token and some other credentials. could anyone help me to understand if it's safe to use? thanks!

I found it'll run `opt/icloudpd/lib/icloud`, which is a binary file. I think it'll run icloudpd binary executable file as well. And there's no source code found based on this repo.

BTW, this is a great tool to backup iCloud photos and I also use it heavily. But I still want to know if any evidence could prove that it's safe to use. Thanks a lot!

**Comment by AndreyNikiforov** [comment]
> could anyone help me to understand if it's safe to use?

Nobody knows. Upstream [icloudpd](https://github.com/icloud-photos-downloader/icloud_photos_downloader) has all source code available and you can check yourself that there are no intentional mechanisms to take control of your personal data, but that just one [small?] aspect of "safe".

**Comment by boredazfcuk** [comment]
Yeah, it's blind faith. I have a different password for my Apple ID to everything else and multi-factor authentication (as per best practice). Even if my password was taken by something currently unknown, it couldn't be used without me approving the login via multi-factor authentication.

Another consideration is that this could be stealing photos, but it doesn't run for long enough to be uploading files elsewhere. It also doesn't have any network traffic originating from it while the container isn't actively syncing.
