### ISSUE TITLE
telegram 重置身份校验有bug

### ISSUE THREAD

**Issue by RICwang** [boredazfcuk/docker-icloudpd#647]
看了代码，好像没有执行任何操作，如下图
![image](https://github.com/user-attachments/assets/4a2ffe64-3cbe-4844-a9ee-9b0d5a69c1e2)

**Comment by boredazfcuk** [comment]
I can't read your post, so I'm not sure what you're getting at, but I deliberately didn't implement this feature for China as I don't know what the Chinese translations would be for:

```
"iCloudPD remote synchronisation initiated" "0" "iCloudPD has detected a remote authentication request for Apple ID:"
```
and
```
"Starting remote authentication process"
```

another translation which I'm missing is:
```
"iCloudPD remote synchronisation complete" "0" "iCloudPD has completed a remote synchronisation request for Apple ID:"
```

just in case you're multi-lingual and feel like translating it for me. However, seeing as you didn't write your original question in English, I'm guessing you're not.

**Comment by RICwang** [comment]
Sorry, I thought you were a Chinese developer,
I mean, when the icloud_china is set to true, the ”user auth“ message is sent to the telegram, and the program only performs the message notification, but does not trigger a new authentication.

**Comment by RICwang** [comment]
![image](https://github.com/user-attachments/assets/617be8f5-230f-455c-94d8-37f543648062)
I looked at all the judgments about ${icloud_china} and just translated the content of the notification, so I wonder if it should be changed to this?

**Comment by RICwang** [comment]
`
                           elif [ "$(echo "${check_update_text}" | tr [:upper:] [:lower:])" = "$(echo "${user} auth" | tr [:upper:] [:lower:])" ]; then
                              LogDebug "Remote authentication message match: ${check_update_text}"
                              if [ "${icloud_china}" = false ]; then
                                 Notify "remotesync" "iCloudPD remote synchronisation initiated" "0" "iCloudPD has detected a remote authentication request for Apple ID: ${apple_id}"
                              else
                                 Notify "remotesync" "iCloudPD remote synchronisation initiated" "0" "iCloudPD has detected a remote authentication request for Apple ID: ${apple_id}"
                              fi
                              rm "/config/${cookie_file}" "/config/${cookie_file}.session"
                              LogDebug "Starting remote authentication process"
                              /usr/bin/expect /opt/authenticate.exp &
`
like this

**Comment by RICwang** [comment]
```
                           elif [ "$(echo "${check_update_text}" | tr [:upper:] [:lower:])" = "$(echo "${user} auth" | tr [:upper:] [:lower:])" ]; then
                              LogDebug "Remote authentication message match: ${check_update_text}"
                              if [ "${icloud_china}" = false ]; then
                                 Notify "remotesync" "iCloudPD remote synchronisation initiated" "0" "iCloudPD has detected a remote authentication request for Apple ID: ${apple_id}"
                              else
                                 Notify "remotesync" "iCloudPD remote synchronisation initiated" "0" "iCloudPD将以Apple ID: ${apple_id}发起身份验证"
                              fi
                              rm "/config/${cookie_file}" "/config/${cookie_file}.session"
                              LogDebug "Starting remote authentication process"
                              /usr/bin/expect /opt/authenticate.exp &
```

Like this
