### ISSUE TITLE
something wrong when checking new files

### ISSUE THREAD

**Issue by dixoncheng0518** [boredazfcuk/docker-icloudpd#652]
**Describe the bug**
there are 2 containers in my nas for different icloud account.
One is broken, the other one works fine. 

**System (please complete the following information):**
 - OS: Synology DSM docker

**Debug log file**
<html>
<body>

2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 DEBUG    Polling Telegram for updates newer than: 924483479
-- | -- | --
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 INFO     Monitoring Telegram for remote commands prefix: dixon
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 INFO     Next synchronisation at Tue Sep 17 08:26:41 2024
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 INFO     Total time taken: 00:00:03
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 INFO     Synchronisation ended at 08:26:44
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 DEBUG    iCloud login counter = 3
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 INFO     Days remaining until expiration: 29
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 INFO     Multifactor authentication cookie expires: 2024-10-15 @ 15:45:26
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 INFO     Web cookie expires: 2024-11-14 @ 15:45:13
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 DEBUG    Web cookie exists
2024/09/16 08:26:44 | stdout | ash: out of range
2024/09/16 08:26:44 | stdout | 2024-09-16 08:26:44 DEBUG    Telegram failure notification sent successfully
2024/09/16 08:26:43 | stdout | 2024-09-16 08:26:43 INFO     Sending Telegram failure notification
2024/09/16 08:26:43 | stdout | 2024-09-16 08:26:43 ERROR    ***** Please post the above debug log, along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
2024/09/16 08:26:43 | stdout | [7246] Failed to execute script 'icloudpd' due to unhandled exception!
2024/09/16 08:26:43 | stdout | pyicloud_ipd.exceptions.PyiCloudAPIResponseException: private db access disabled for this account.  Please wait a few minutes then try again.The remote servers might be trying to throttle requests. (ACCESS_DENIED)
2024/09/16 08:26:43 | stdout | File "pyicloud_ipd/session.py", line 196, in _raise_error
2024/09/16 08:26:43 | stdout | File "pyicloud_ipd/session.py", line 167, in request
2024/09/16 08:26:43 | stdout | File "requests/sessions.py", line 637, in post
2024/09/16 08:26:43 | stdout | File "pyicloud_ipd/services/photos.py", line 168, in __init__
2024/09/16 08:26:43 | stdout | File "pyicloud_ipd/services/photos.py", line 281, in __init__
2024/09/16 08:26:43 | stdout | File "pyicloud_ipd/base.py", line 549, in photos
2024/09/16 08:26:43 | stdout | File "icloudpd/base.py", line 1218, in core
2024/09/16 08:26:43 | stdout | File "icloudpd/base.py", line 745, in main
2024/09/16 08:26:43 | stdout | File "click/core.py", line 783, in invoke
2024/09/16 08:26:43 | stdout | File "click/core.py", line 1434, in invoke
2024/09/16 08:26:43 | stdout | File "click/core.py", line 1078, in main
2024/09/16 08:26:43 | stdout | File "click/core.py", line 1157, in __call__
2024/09/16 08:26:43 | stdout | File "starters/icloudpd.py", line 6, in <module>
2024/09/16 08:26:43 | stdout | 2024-09-16 08:26:43 ERROR    Traceback (most recent call last):
2024/09/16 08:26:43 | stdout | 2024-09-16 08:26:43 ERROR    Error debugging info:
2024/09/16 08:26:43 | stdout | 2024-09-16 08:26:43 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
2024/09/16 08:26:43 | stdout | 2024-09-16 08:26:43 ERROR    Failed check for new files files
2024/09/16 08:26:43 | stdout | 2024-09-16 08:26:43 ERROR    private db access disabled for this account.  Please wait a few minutes then try again.The remote servers might be trying to throttle requests. (ACCESS_DENIED)
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 DEBUG    Launch command: /opt/icloudpd/bin/icloudpd --directory /Photos --cookie-directory /config --username dixoncheng0518@qq.com --domain cn --folder-structure {:%Y/%m/%d} --only-print-filenames
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 INFO     Generating list of files in iCloud. This may take a long time if you have a large photo collection. Please be patient. Nothing is being downloaded at this time
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 INFO     Check for new files using password stored in keyring file
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 INFO     Failsafe file /Photos/.mounted exists, continuing
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 INFO     Check download directory mounted correctly...
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 DEBUG    Valid multifactor authentication cookie found. Days until expiration: 29
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 DEBUG    Multifactor authentication cookie exists
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 DEBUG    Check MFA Cookie
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 INFO     Keyring file exists, continuing
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 INFO     Synchronisation starting at 08:26:41
2024/09/16 08:26:41 | stdout | 2024-09-16 08:26:41 DEBUG    Telegram remotesync notification sent successfully
2024/09/16 08:26:40 | stdout | 2024-09-16 08:26:40 INFO     Sending Telegram remotesync notification
2024/09/16 08:26:40 | stdout | 2024-09-16 08:26:40 DEBUG    Remote sync initiated
2024/09/16 08:26:40 | stdout | 2024-09-16 08:26:40 DEBUG    Remote sync message match: dixon
2024/09/16 08:26:40 | stdout | 2024-09-16 08:26:40 DEBUG    New message received: dixon
2024/09/16 08:26:40 | stdout | 2024-09-16 08:26:40 DEBUG    Processing update: 924483479
2024/09/16 08:26:40 | stdout | 2024-09-16 08:26:40 DEBUG    Updates to process: 1
2024/09/16 08:26:39 | stdout | 2024-09-16 08:26:39 DEBUG    Polling Telegram for updates newer than: 924483478

</body>
</html>

**Comment by boredazfcuk** [comment]
`private db access disabled for this account.  Please wait a few minutes then try again.The remote servers might be trying to throttle requests. (ACCESS_DENIED)`

I get this error when restarting my containers a lot. It basically hammers Apple's servers and then the lock access to your account. I've had it take a couple of days before the account has been accessible again.

`Can you log into icloud.com.cn without receiving pop-up notifications?`

Can you actually do this? Sometimes when logging in, you will be asked to unlock your account, once you do, the above error will be resolved.
