### ISSUE TITLE
Add support for physical keys

### ISSUE THREAD

**Issue by infyx** [boredazfcuk/docker-icloudpd#655]
**Is your feature request related to a problem? Please describe.**
When physical keys are added to iCloud MFA, you no longer get the option to input numbers as your second authentication.  They keys are required.

**Describe the solution you'd like**
Support added for various physical keys (yubikey, RSA, etc)

**Describe alternatives you've considered**
Not sure there are any alternatives due to the way Apple does authentication once keys are added to the account. 

**Additional context**

**Comment by boredazfcuk** [comment]
This wouldn't be something my container would handle. I just wrap additional functionality around the icloud-photos-downloader application and package it into a Docker container.
