### ISSUE TITLE
Trouble with permissions - Shared folder not accessible for mapping the container 

### ISSUE THREAD

**Issue by WSTDESIGN** [boredazfcuk/docker-icloudpd#656]
I seem to be having a permissions issue between container manager and my shared homes folder. Also when I create the failsafe file icloudpd can't see the file so there must be a permissions issue there as well. When I go to map the volume of the container to the shared folders on the nas I am not given the option to select my shared folder so i can't get this to download to the proper folder. I made sure the permissions were set in file station, I am the owner with full access and the account used to create the file. There must the something about setting permissions I am not understanding here. Can anyone help me get through this? Apologies I am not necessarily well versed in any of this. 

Thank you

**Comment by boredazfcuk** [comment]
Closing as no response
