### ISSUE TITLE
Download Both RAW and JPEG/HEIF Files

### ISSUE THREAD

**Issue by HowardLu132** [boredazfcuk/docker-icloudpd#659]
When there is a RAW+JPEG (or JPEG+RAW) file, is it possible to Download both RAW and JPEG file?

Current solution of JPEG+RAW file seems to only download single file, RAW or JPEG/HEIF.

Thank you!

**Comment by boredazfcuk** [comment]
**photo_size**: Image size to download. Can be set to **original**, **medium**, **thumb**, **adjusted**, **alternative** or any combination of those five in a comma-separated string if multiple size types are to be downloaded e.g. **photo_size=original,adjusted**. Adjusted are the edited photos that can be made by using filters, or by using the markup tool in the Photos app. Alternative are RAW file types. Default: original.

I use original and adjusted for HEIC and edited photos. I'm guessing medium and alternative will download raw+jpg.

I think photo_size would probably be more accurate if it was changed to photo_types.

**Comment by HowardLu132** [comment]
> **photo_size**: Image size to download. Can be set to **original**, **medium**, **thumb**, **adjusted**, **alternative** or any combination of those five in a comma-separated string if multiple size types are to be downloaded e.g. **photo_size=original,adjusted**. Adjusted are the edited photos that can be made by using filters, or by using the markup tool in the Photos app. Alternative are RAW file types. Default: original.
> 
> I use original and adjusted for HEIC and edited photos. I'm guessing medium and alternative will download raw+jpg.
> 
> I think photo_size would probably be more accurate if it was changed to photo_types.

Understood, I will have a try, thank you for developing this great project!

**Comment by boredazfcuk** [comment]
Closing this and assuming no news is good news.
