### ISSUE TITLE
heic to jpeg 0kb

### ISSUE THREAD

**Issue by sk454632887** [boredazfcuk/docker-icloudpd#660]
During the process of converting HEIC to JPEG, it prompts "convert: Invalid input: Unspecified: Metadata not correctly assigned to image (2.0) `/iCloud/2024/10/02/IMG-9913. HEIC '@ error/heic.c/IsHEIFSuccess/144."
The downloaded JPEG file size is 0kb
May I ask how to solve it? Thank you!

**Comment by boredazfcuk** [comment]
Issue identified and fixed back in August:
https://github.com/boredazfcuk/docker-icloudpd/issues/604

Upgrade to latest version.
