### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by moaxxx** [boredazfcuk/docker-icloudpd#665]
Please set debug_logging=true in your icloudpd.conf file then reproduce the error
2024/10/12 20:34:26	stdout	[432] Failed to execute script 'icloudpd' due to unhandled exception!
2024/10/12 20:34:26	stdout	pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('Bad Gateway (502)'))
2024/10/12 20:34:26	stdout	  File "pyicloud_ipd/base.py", line 219, in authenticate
2024/10/12 20:34:26	stdout	  File "pyicloud_ipd/base.py", line 157, in __init__
2024/10/12 20:34:26	stdout	  File "icloudpd/authentication.py", line 53, in authenticate_
2024/10/12 20:34:26	stdout	  File "icloudpd/base.py", line 1179, in core
2024/10/12 20:34:26	stdout	  File "icloudpd/base.py", line 745, in main
2024/10/12 20:34:26	stdout	  File "click/core.py", line 783, in invoke
2024/10/12 20:34:26	stdout	  File "click/core.py", line 1434, in invoke
2024/10/12 20:34:26	stdout	  File "click/core.py", line 1078, in main
2024/10/12 20:34:26	stdout	  File "click/core.py", line 1157, in __call__
2024/10/12 20:34:26	stdout	  File "starters/icloudpd.py", line 6, in <module>
2024/10/12 20:34:26	stdout	Traceback (most recent call last):
2024/10/12 20:34:26	stdout	
2024/10/12 20:34:26	stdout	The above exception was the direct cause of the following exception:
2024/10/12 20:34:26	stdout	
2024/10/12 20:34:26	stdout	pyicloud_ipd.exceptions.PyiCloudAPIResponseException: Bad Gateway (502)
2024/10/12 20:34:26	stdout	  File "pyicloud_ipd/session.py", line 196, in _raise_error
2024/10/12 20:34:26	stdout	  File "pyicloud_ipd/session.py", line 122, in request
2024/10/12 20:34:26	stdout	  File "requests/sessions.py", line 637, in post

**Comment by benjistern** [comment]
Also running into this same issue

**Comment by boredazfcuk** [comment]
Template ignored
