### ISSUE TITLE
ERROR    Failed to create configuration file: /config/icloudpd.conf - Cannot continue, exiting

### ISSUE THREAD

**Issue by eleaner** [boredazfcuk/docker-icloudpd#671]
**Describe the bug**
I am running `sync-icloud.sh --Initialise`
and receiving `ERROR    Failed to create configuration file: /config/icloudpd.conf - Cannot continue, exiting`
I tried /config/ to be bound to filesystem and volume
I tried different user ID

**Expected behaviour**
I am expecting initialization

**Actual behaviour**
A clear and concise description of what actually happened.

**System (The following information must be entered or the issue will be closed):**
latest docker icloudpd 1.23.4
Debian 12

**Debug log file**
impossible - cannot load icloudpd.conf

**Comment by boredazfcuk** [comment]
If the container has failed to create the configuration file, then you must have a permissions problem on the /config volume mount.

**Comment by eleaner** [comment]
if it only were that simple.
I took a config file from backup and it all works but (as said above) neither user change nor `chmod +R 777` seems to be working
well - not really working - experiencing the same authorization problem as others

**Comment by boredazfcuk** [comment]
Additional checks added to make sure that the /config directory exists, that the /config/icloudpd.conf file exists, and that it will fail prior to launching the main script, if it cannot create these before it populates the configuration file with the defaults.
