### ISSUE TITLE
RE AUTH not working 

### ISSUE THREAD

**Issue by Hakoexe** [boredazfcuk/docker-icloudpd#673]
I having issues re running the command `sync-icloud.sh --Initialise` when i am reauth for the 2fa for my apple id

i am not able to get the prompt and instead im getting these error 
![image](https://github.com/user-attachments/assets/26553b2e-0f38-4ca7-8fbd-ddd013ac2c33)

I have tried the `docker container exec -it reauth.sh` but that also doesnt work 

My only idea is that the password to the apple id account is not correct - but i have not changed the pw so im just seeing if there is anything else before i go re building the container 

i am using unraid and on the latest build os and of the docker container

**Comment by maydaytek** [comment]
Check #670 - this is a known issue. Appears to be a result of an endpoint change from Apple.

**Comment by boredazfcuk** [comment]
Duplicate
