### ISSUE TITLE
Possible to delete old photos after download

### ISSUE THREAD

**Issue by Eagle248** [boredazfcuk/docker-icloudpd#674]
Any possibility to add functionality to auto delete old pictures from the icloud after successful download?

as icloud storage is expensive i was just wondering if icloudpd can auto delete old pictures which are older than example 120 days. By this way iCloud storage is always available.

Thank you for looking into this.

**Comment by boredazfcuk** [comment]
There are two options for removing files. **auto_delete** to delete files found in your 'Recently Deleted' folder, or **delete_after_download** to automatically delete files after download.

My container only wraps additional functionality around the icloud-photos-downloader utility. If the feature is implemented upstream, I will add options to configure it here too.
