### ISSUE TITLE
Can’t input password

### ISSUE THREAD

**Issue by Ryguy226** [boredazfcuk/docker-icloudpd#677]
Hello on unraid and performed an update and my token must of expired. I have tried everything from removing keyring and reinstalled docker. I run the set up command in console but i wont let me input my password. I have check my password on the apple site. But after the command runs and asks for password my keyboard wont input to console is this a bug?

**Comment by Ryguy226** [comment]
No one has an issue entering password?

**Comment by Ryguy226** [comment]
I got it to work not sure but i changed my password and it resolved my issue

**Comment by harkonnen0069** [comment]
I'm having the same issue, it is not fixed.  This is a genuine issue and makes the docker worthless as I cannot log in.

The console just WILL NOT accept any typing in the password field.

Super frustrating.
