### ISSUE TITLE
Cant re-auth and re-intialise after update

### ISSUE THREAD

**Issue by maplexu1994** [boredazfcuk/docker-icloudpd#678]
**Describe the bug**
Today(10/29) receive container's warning then update the container. However, got stuck in re-auth step and re-Initialse does not work.

**System (The following information must be entered or the issue will be closed):**
 - OS: [e.g. Debian, Ubuntu, Windows, Synology DSM]
 - Version [e.g. 12, 24, 11, 8]

**Debug log file**
<html>
<body>

date | stream | content
-- | -- | --
2024/10/29 11:42:01 | stdout | 2024-10-29 11:42:01 ERROR    Invalid cookie file has been removed. Restarting container in 5 minutes
2024/10/29 11:42:01 | stdout | 2024-10-29 11:42:01 ERROR    Cookie is not multifactor authentication capable, authentication type may have changed
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 ERROR     - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 ERROR     - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 ERROR     - Please create your cookie using the --Initialise script command line option
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 ERROR    Waiting for valid cookie file to be created...
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 ERROR    Multifactor authentication cookie does not exist
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Keyring file exists, continuing
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Synchronisation starting at 11:38:41
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Sync user: maplexu1994
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Keyring file exists, continuing
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Directory is writable: /config/python_keyring/
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Failsafe file /iCloud/.mounted exists, continuing
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Check download directory mounted correctly...
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Directory is writable: /config/python_keyring/
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Container initialisation complete
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Ignore Synology extended attribute directories: Disabled
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Authentication domain: cn
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Fake user agent for curl: Disabled
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Downloading from: icloud.com.cn
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Convert HEIC to JPEG: false
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Skip videos: false
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Live photo size: original
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Stop downloading when prexisiting files count is: Download All Photos
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Downloading photos from: Download All Photos
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Number of most recently added photos to download: Download All Photos
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Skip live photos: false
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Skip download check: true
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Single pass mode: false
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Align RAW: as-is
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Photo size: original
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Delete empty directories:
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Delete after download: false
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Auto delete: true
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Set EXIF date/time: false
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Synchronisation delay (minutes): 0
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Synchronisation interval: 86400
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     File Match Policy: name-size-dedup-with-suffix
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Live Photo MOV Filename Policy: suffix
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Keep Unicode: false
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Folder structure: {:%Y/%m}
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Download destination directory: /iCloud
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Cookie expiry notification period: 7
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Cookie path: /config/maplexu1994gmailcom
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Apple ID: maplexu1994@gmail.com
2024/10/29 11:38:41 | stdout | 2024-10-29 11:38:41 INFO     Debug logging: Disabled
2024/10/29 11:38:17 | stdout | 2024-10-29 11:38:17 INFO     Loading configuration from: /config/icloudpd.conf
2024/10/29 11:38:17 | stdout | 2024-10-29 11:38:17 INFO      - Current version is up to date
2024/10/29 11:38:14 | stdout | 2024-10-29 11:38:14 INFO     Checking for updates...
2024/10/29 11:38:14 | stdout | 2024-10-29 11:38:14 INFO     icloud-photos-downloader version: 1.24.1
2024/10/29 11:38:13 | stdout | 2024-10-29 11:38:13 INFO     Python version: 3.12.7
2024/10/29 11:38:13 | stdout | 2024-10-29 11:38:13 INFO     Alpine Linux 3.20.3
2024/10/29 11:38:13 | stdout | 2024-10-29 11:38:13 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024/10/29 11:38:13 | stdout | 2024-10-29 11:38:13 INFO     ***** boredazfcuk/icloudpd container v1.0.989_28-10-2024 started *****

</body>
</html>

**Comment by maplexu1994** [comment]
And now container is still in "warning" status. Try "reset" on synology but also not work.

**Comment by boredazfcuk** [comment]
>System (The following information must be entered or the issue will be closed):
>
>    OS: [e.g. Debian, Ubuntu, Windows, Synology DSM]
>    Version [e.g. 12, 24, 11, 8]
