### ISSUE TITLE
Photo_Size not working

### ISSUE THREAD

**Issue by neilmccreery** [boredazfcuk/docker-icloudpd#68]
If you set photo_size to anything other than original the code errors out. 

Problem is icloudpd code labels it as "--size" and your code show "--photo-size". Looks like they may have changed that on you at some point. Easy fix though. Enjoy!

**Comment by boredazfcuk** [comment]
Probably just me mixing up `--size` with `--live-photo-size`.

Sorted now and I've pushed a new version to Dockerhub. Thanks for letting me know.
