### ISSUE TITLE
Case Sensitivity on the File Extension

### ISSUE THREAD

**Issue by gxander85** [boredazfcuk/docker-icloudpd#682]
I updated my container on QNAP Container Station yesterday and reset my full iCloud Library download and fired it off.

What I noticed was the files that are downloaded are no longer taking into account the existing file that has already been downloaded because the case of the extension is now different.

eg.
original file IMG_0001.jpg
new file IMG_0001.JPG

These are exactly the same image and have now been downloaded twice.

As soon as I discovered the bug, I stopped my download.
The last thing I need is my 100k+ library of 10 years being duplicated on my NAS.

How can we fix this?

**Comment by boredazfcuk** [comment]
Same thing happened on my containers a few months ago.  Only JPGs were affected and not HEICs.

The fix is to make sure that the files on the local drive are named with the same case on the local drive as they are in iCloud.

I fixed it by downloading everything again and using an app called AllDup from a Windows laptop to identify and remove the duplicates.

Alternatively, just rename all the .jpg files to .JPG files....

Something like

```
for file in $(find /home/ -name "*.JPG" -type f); do
   mv "$file" "${file%.jpg}.JPG"
done
```

**Comment by gxander85** [comment]
Is it impacted by .mov / .MOV or .mp4 / .MP4 at all?
Because that’s where most my storage is taken up.

**Comment by boredazfcuk** [comment]
I can't say for sure, but I think mp4/MP4 may be affected. I didn't have many of those however. 

I think a lot of the affected files were also stored by non-Apple Apps, so the Camera app would store files HEIC/MOV/JPG fine, but saving JPG/MP4 files out of WhatsApp/Signal/Telegram/SnapChat/etc would result in files that have issues.

**Comment by gxander85** [comment]
Thanks for the advise regarding AllDup.

I tried to fix it with Advanced Renamer and adjusted the case to UPPER for everything. 
But it appears that made it worse. Even some of the dates were different.

So, I appended my existing library to \_Library and using that as a backup.
Downloading fresh to \Library and then using AllDup to do the legwork, selecting all within folder *_Library* and then just deleting them.

Any files left over, I have moved to a secondary Check folder, I will load those back into iCloud and then repeat the process.

Annoying that the upstream system changed as I have 100k+ items in my Photo Library over 20 years haha.

But I got a process working.
You can close this issue.

**Comment by gxander85** [comment]
Thanks for the advise regarding AllDup.

I tried to fix it with Advanced Renamer and adjusted the case to UPPER for everything. 
But it appears that made it worse. Even some of the dates were different.

So, I appended my existing library to \_Library and using that as a backup.
Downloading fresh to \Library and then using AllDup to do the legwork, selecting all within folder *_Library* and then just deleting them.

Any files left over, I have moved to a secondary Check folder, I will load those back into iCloud and then repeat the process.

Annoying that the upstream system changed as I have 100k+ items in my Photo Library over 20 years haha.

But I got a process working.
You can close this issue.
