### ISSUE TITLE
error output but dont know if matters

### ISSUE THREAD

**Issue by pkuGeo** [boredazfcuk/docker-icloudpd#688]
from the logs of the icloudpd, there's some lines of error output:

jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13
jq: parse error: Invalid numeric literal at line 1, column 13

don't know if these output lines mean any mistake

**Comment by boredazfcuk** [comment]
Template ignored. Not enough information to do anything about it either.
