### ISSUE TITLE
icloudpd.conf empty at first run?

### ISSUE THREAD

**Issue by Symbiot78** [boredazfcuk/docker-icloudpd#691]
just wondering if the .conf file is supposed to be empty? mine is and I recreated the container a few times to be sure.

if it's by design then all good - really just wanted a headstart in setting this us and not starting from scratch :)

**Comment by Symbiot78** [comment]
not sure what i did.. i chowned the conf file restarted the container.. did some other stuff.. and suddenly the file was populated .. .

**Comment by boredazfcuk** [comment]
Thanks. I created a brand new container from scratch and can see it wasn't creating the file properly before attempting to add missing defaults.
