### ISSUE TITLE
wrong date Cookie expired?

### ISSUE THREAD

**Issue by RezzZ** [boredazfcuk/docker-icloudpd#694]
`2024-11-13 10:03:56 ERROR    Cookie expired at: 2024-11-14 07:13:04
2024-11-13 10:03:56 ERROR    Expired cookie file has been removed. Restarting container in 5 minutes`

as it is still the 13th of November, i think the cookie expired message shows the wrong date?

this is my log on my unraid server using a dockerized icloudpd version (latest)

**Comment by boredazfcuk** [comment]
Template ignored

**Comment by RezzZ** [comment]
What does that mean? Template ignored?

**Comment by RezzZ** [comment]
Weird. Can't recall a template. Normally I would fill it in if presented...

**Comment by RezzZ** [comment]
Weird. Can't recall a template. Normally I would fill it in if presented...

**Comment by RezzZ** [comment]
![image](https://github.com/user-attachments/assets/7ccbc4a9-b17c-4e50-86a7-cf5cdba279ad)
Ahh I probably selected no templeted as I wasn't ready to call it a bug just yet
