### ISSUE TITLE
new 问题

### ISSUE THREAD

**Issue by luoling76** [boredazfcuk/docker-icloudpd#695]
dout: 2024-11-13 17:18:17 INFO     ***** boredazfcuk/icloudpd container v1.0.1005_11-11-2024 started *****
stdout: 2024-11-13 17:18:17 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
stdout: 2024-11-13 17:18:17 INFO     Alpine Linux 3.20.3
stdout: 2024-11-13 17:18:17 INFO     Python version: 3.12.7
stdout: 2024-11-13 17:18:18 INFO     icloud-photos-downloader version: 1.24.3
stdout: 2024-11-13 17:18:18 INFO     Checking for updates...
stdout: 2024-11-13 17:18:18 INFO      - Current version is up to date
stdout: 2024-11-13 17:18:18 INFO     Loading configuration from: /config/icloudpd.conf
stdout: 2024-11-13 17:18:47 INFO     Debug logging: Disabled
stdout: 2024-11-13 17:18:47 INFO     Apple ID: 359033567@qq.com
stdout: 2024-11-13 17:18:47 INFO     Cookie path: /config/359033567qqcom
stdout: 2024-11-13 17:18:47 INFO     Cookie expiry notification period: 7
stdout: 2024-11-13 17:18:47 INFO     Download destination directory: /iCloud
stdout: 2024-11-13 17:18:47 INFO     Folder structure: {:%Y/%m/%d}
stdout: 2024-11-13 17:18:47 INFO     Keep Unicode: false
stdout: 2024-11-13 17:18:47 INFO     Live Photo MOV Filename Policy: suffix
stdout: 2024-11-13 17:18:47 INFO     File Match Policy: name-size-dedup-with-suffix
stdout: 2024-11-13 17:18:47 INFO     Synchronisation interval: 86400
stdout: 2024-11-13 17:18:47 INFO     Synchronisation delay (minutes): 0
stdout: 2024-11-13 17:18:47 INFO     Set EXIF date/time: false
stdout: 2024-11-13 17:18:47 INFO     Auto delete: false
stdout: 2024-11-13 17:18:47 INFO     Delete after download: false
stdout: 2024-11-13 17:18:47 INFO     Delete empty directories: false
stdout: 2024-11-13 17:18:47 INFO     Photo size: original
stdout: 2024-11-13 17:18:47 INFO     Align RAW: as-is
stdout: 2024-11-13 17:18:47 INFO     Single pass mode: false
stdout: 2024-11-13 17:18:47 INFO     Skip download check: true
stdout: 2024-11-13 17:18:47 INFO     Skip live photos: false
stdout: 2024-11-13 17:18:47 INFO     Number of most recently added photos to download: Download All Photos
stdout: 2024-11-13 17:18:47 INFO     Downloading photos from: Download All Photos
stdout: 2024-11-13 17:18:47 INFO     Stop downloading when prexisiting files count is: Download All Photos
stdout: 2024-11-13 17:18:47 INFO     Live photo size: original
stdout: 2024-11-13 17:18:47 INFO     Skip videos: false
stdout: 2024-11-13 17:18:47 INFO     Convert HEIC to JPEG: true
stdout: 2024-11-13 17:18:47 WARNING  2024-11-13 17:18:47 WARINING Telegram notifications enabled, but configured incorrectly - disabling notifications
stdout: 2024-11-13 17:18:47 INFO     Downloading from: icloud.com.cn
stdout: 2024-11-13 17:18:47 INFO     Fake user agent for curl: Disabled
stdout: 2024-11-13 17:18:47 INFO     Authentication domain: cn
stdout: 2024-11-13 17:18:47 INFO     Ignore Synology extended attribute directories: Disabled
stdout: 2024-11-13 17:18:47 INFO     Container initialisation complete
stdout: 2024-11-13 17:18:47 INFO     Directory is writable: /config/python_keyring/
stdout: 2024-11-13 17:18:47 INFO     Check download directory mounted correctly...
stdout: 2024-11-13 17:18:47 INFO     Failsafe file /iCloud/.mounted exists, continuing
stdout: 2024-11-13 17:18:47 INFO     Directory is writable: /config/python_keyring/
stdout: 2024-11-13 17:18:47 INFO     Keyring file exists, continuing
stdout: 2024-11-13 17:18:47 INFO     Sync user: user
stdout: 2024-11-13 17:18:47 INFO     Synchronisation starting at 17:18:47
stdout: 2024-11-13 17:18:47 INFO     Keyring file exists, continuing
stdout: 2024-11-13 17:18:48 INFO     Check download directory mounted correctly...
stdout: 2024-11-13 17:18:48 INFO     Failsafe file /iCloud/.mounted exists, continuing
stdout: 2024-11-13 17:18:49 ERROR    Failed to download new files
stdout: 2024-11-13 17:18:49 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
stdout: 2024-11-13 17:18:49 ERROR    Error debugging info:
stdout: 2024-11-13 17:18:49 ERROR    Usage: icloudpd <options>
stdout: Try 'icloudpd -h' for help.
stdout: 
stdout: Error: Invalid value for '-d' / '--directory': Path '/iCloud' is not readable.
stdout: 2024-11-13 17:18:49 ERROR    Please set debug_logging=true in your icloudpd.conf file then reproduce the error
stdout: 2024-11-13 17:18:49 ERROR    ***** Once you have captured this log file, please post it along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
stdout: 2024-11-13 17:18:49 INFO     Web cookie expires: 2025-01-10 @ 07:39:05
stdout: 2024-11-13 17:18:49 INFO     Multifactor authentication cookie expires: 2024-12-11 @ 07:39:20
stdout: 2024-11-13 17:18:49 INFO     Days remaining until expiration: 27
stdout: 2024-11-13 17:18:49 INFO     Synchronisation ended at 17:18:49
stdout: 2024-11-13 17:18:49 INFO     Total time taken: 00:00:02
stdout: 2024-11-13 17:18:49 INFO     Next synchronisation at Thu Nov 14 17:18:47 2024
stdout: 2024-11-13 17:22:18 INFO     ***** boredazfcuk/icloudpd container v1.0.1005_11-11-2024 started *****
stdout: 2024-11-13 17:22:18 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
stdout: 2024-11-13 17:22:18 INFO     Alpine Linux 3.20.3
stdout: 2024-11-13 17:22:18 INFO     Python version: 3.12.7
stdout: 2024-11-13 17:22:19 INFO     icloud-photos-downloader version: 1.24.3
stdout: 2024-11-13 17:22:19 INFO     Checking for updates...
stdout: 2024-11-13 17:22:19 INFO      - Current version is up to date
stdout: 2024-11-13 17:22:19 INFO     Loading configuration from: /config/icloudpd.conf
stdout: 2024-11-13 17:22:19 DEBUG    Running user id: 0
stdout: 2024-11-13 17:22:19 DEBUG    Running group id: 0
stdout: 2024-11-13 17:22:19 DEBUG    Local user: user:1000
stdout: 2024-11-13 17:22:19 DEBUG    Local group: group:1000
stdout: 2024-11-13 17:22:19 DEBUG    Force GID: false
stdout: 2024-11-13 17:22:19 DEBUG    LAN IP Address: 172.17.0.7
stdout: 2024-11-13 17:22:19 DEBUG    Default gateway: 172.17.0.1
stdout: 2024-11-13 17:22:19 DEBUG    DNS server: 100.100.100.100
stdout: 2024-11-13 17:22:19 DEBUG    IP address for icloud.com.cn: 198.18.6.224
stdout: 2024-11-13 17:22:48 DEBUG    Route check to icloud.com.cn successful
stdout: 2024-11-13 17:22:48 INFO     Debug logging: Enabled
stdout: 2024-11-13 17:22:48 INFO     Apple ID: (hidden)
stdout: 2024-11-13 17:22:48 INFO     Cookie path: /config/(hidden)
stdout: 2024-11-13 17:22:48 INFO     Cookie expiry notification period: 7
stdout: 2024-11-13 17:22:48 INFO     Download destination directory: /iCloud
stdout: 2024-11-13 17:22:48 INFO     Folder structure: {:%Y/%m/%d}
stdout: 2024-11-13 17:22:48 DEBUG    Directory permissions: 750
stdout: 2024-11-13 17:22:48 DEBUG    File permissions: 640
stdout: 2024-11-13 17:22:48 INFO     Keep Unicode: false
stdout: 2024-11-13 17:22:48 INFO     Live Photo MOV Filename Policy: suffix
stdout: 2024-11-13 17:22:48 INFO     File Match Policy: name-size-dedup-with-suffix
stdout: 2024-11-13 17:22:48 INFO     Synchronisation interval: 86400
stdout: 2024-11-13 17:22:48 INFO     Synchronisation delay (minutes): 0
stdout: 2024-11-13 17:22:48 INFO     Set EXIF date/time: false
stdout: 2024-11-13 17:22:48 INFO     Auto delete: false
stdout: 2024-11-13 17:22:48 INFO     Delete after download: false
stdout: 2024-11-13 17:22:48 INFO     Delete empty directories: false
stdout: 2024-11-13 17:22:48 INFO     Photo size: original
stdout: 2024-11-13 17:22:48 INFO     Align RAW: as-is
stdout: 2024-11-13 17:22:48 INFO     Single pass mode: false
stdout: 2024-11-13 17:22:48 INFO     Skip download check: true
stdout: 2024-11-13 17:22:48 INFO     Skip live photos: false
stdout: 2024-11-13 17:22:48 INFO     Number of most recently added photos to download: Download All Photos
stdout: 2024-11-13 17:22:48 INFO     Downloading photos from: Download All Photos
stdout: 2024-11-13 17:22:48 INFO     Stop downloading when prexisiting files count is: Download All Photos
stdout: 2024-11-13 17:22:48 INFO     Live photo size: original
stdout: 2024-11-13 17:22:48 INFO     Skip videos: false
stdout: 2024-11-13 17:22:48 INFO     Convert HEIC to JPEG: true
stdout: 2024-11-13 17:22:48 DEBUG    JPEG conversion quality: 100
stdout: 2024-11-13 17:22:48 WARNING  2024-11-13 17:22:48 WARINING bark notifications enabled, but configured incorrectly - disabling notifications
stdout: 2024-11-13 17:22:48 DEBUG    Startup notification: Enabled
stdout: 2024-11-13 17:22:48 DEBUG    Download notifications: Enabled
stdout: 2024-11-13 17:22:48 DEBUG    Delete notifications: Enabled
stdout: 2024-11-13 17:22:48 INFO     Downloading from: icloud.com.cn
stdout: 2024-11-13 17:22:48 INFO     Fake user agent for curl: Disabled
stdout: 2024-11-13 17:22:48 INFO     Authentication domain: cn
stdout: 2024-11-13 17:22:48 DEBUG    Nextcloud upload: Disabled
stdout: 2024-11-13 17:22:48 INFO     Ignore Synology extended attribute directories: Disabled
stdout: 2024-11-13 17:22:48 DEBUG    Activated Python virtual environment for icloudpd
stdout: 2024-11-13 17:22:48 INFO     Container initialisation complete
stdout: 2024-11-13 17:22:48 DEBUG    Group, group:1000, already created
stdout: 2024-11-13 17:22:48 DEBUG    User, user:1000, already created
stdout: 2024-11-13 17:22:48 DEBUG    Set owner and group on icloudpd temp directory
stdout: 2024-11-13 17:22:48 DEBUG    Set owner and group on config directory
stdout: 2024-11-13 17:22:48 INFO     Directory is writable: /config/python_keyring/
stdout: 2024-11-13 17:22:48 DEBUG    Configure password
stdout: 2024-11-13 17:22:48 DEBUG    Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
stdout: 2024-11-13 17:22:48 INFO     Check download directory mounted correctly...
stdout: 2024-11-13 17:22:48 INFO     Failsafe file /iCloud/.mounted exists, continuing
stdout: 2024-11-13 17:22:48 DEBUG    Set owner and group on icloudpd temp directory
stdout: 2024-11-13 17:22:48 DEBUG    Set owner and group on config directory
stdout: 2024-11-13 17:22:48 INFO     Directory is writable: /config/python_keyring/
stdout: 2024-11-13 17:22:48 INFO     Keyring file exists, continuing
stdout: 2024-11-13 17:22:48 INFO     Sync user: user
stdout: 2024-11-13 17:22:48 INFO     Synchronisation starting at 17:22:48
stdout: 2024-11-13 17:22:48 INFO     Keyring file exists, continuing
stdout: 2024-11-13 17:22:48 DEBUG    Check MFA Cookie
stdout: 2024-11-13 17:22:49 DEBUG    Multifactor authentication cookie exists
stdout: 2024-11-13 17:22:49 DEBUG    Valid multifactor authentication cookie found. Days until expiration: 27
stdout: 2024-11-13 17:22:49 INFO     Check download directory mounted correctly...
stdout: 2024-11-13 17:22:49 INFO     Failsafe file /iCloud/.mounted exists, continuing
stdout: 2024-11-13 17:22:49 DEBUG    Starting download of new files for user: user
stdout: 2024-11-13 17:22:49 DEBUG    Downloading new files using password stored in keyring file...
stdout: 2024-11-13 17:22:49 DEBUG    Starting Photo download
stdout: 2024-11-13 17:22:49 DEBUG    iCloudPD launch command: /opt/icloudpd/bin/icloudpd --log-level debug --directory /iCloud --cookie-directory /config --domain cn --username 359033567@qq.com --no-progress-bar --size original --folder-structure {:%Y/%m/%d} 2>/tmp/icloudpd/icloudpd_download_error
stdout: 2024-11-13 17:22:50 ERROR    Failed to download new files
stdout: 2024-11-13 17:22:50 ERROR     - Can you log into icloud.com.cn without receiving pop-up notifications?
stdout: 2024-11-13 17:22:50 ERROR    Error debugging info:
stdout: 2024-11-13 17:22:50 ERROR    Usage: icloudpd <options>
stdout: Try 'icloudpd -h' for help.
stdout: 
stdout: Error: Invalid value for '-d' / '--directory': Path '/iCloud' is not readable.
stdout: 2024-11-13 17:22:50 ERROR    ***** Please post the above debug log, along with a description of your problem, here: https://github.com/boredazfcuk/docker-icloudpd/issues *****
stdout: 2024-11-13 17:22:50 DEBUG    Web cookie exists
stdout: 2024-11-13 17:22:50 INFO     Web cookie expires: 2025-01-10 @ 07:39:05
stdout: 2024-11-13 17:22:50 INFO     Multifactor authentication cookie expires: 2024-12-11 @ 07:39:20
stdout: 2024-11-13 17:22:50 INFO     Days remaining until expiration: 27
stdout: 2024-11-13 17:22:50 DEBUG    iCloud login counter = 1
stdout: 2024-11-13 17:22:50 INFO     Synchronisation ended at 17:22:50
stdout: 2024-11-13 17:22:50 INFO     Total time taken: 00:00:02
stdout: 2024-11-13 17:22:50 INFO     Next synchronisation at Thu Nov 14 17:22:48 2024

**Comment by boredazfcuk** [comment]
Template ignored
