### ISSUE TITLE
QNAP Container - Please upgrade to latest version (How To)

### ISSUE THREAD

**Issue by gxander85** [boredazfcuk/docker-icloudpd#697]
I use Container Station on QNAP's QTS environment and everything works great. Except when I need to update it.
The only way I know how to achieve this is to pull the new docker version directly and effectively 'start over'.
I have searched the CONFIGURATION.md file for how to run a command script to update, but I couldn't find anything.

For someone that doesn't know much about this, is there an easier way to update to the current version?
I can run a command via the Execute Console in Container Station, but don't know what to run.

Thanks in advance.

2024-11-14 00:36:25 INFO     ***** boredazfcuk/icloudpd container v1.0.993_03-11-2024 started *****
2024-11-14 00:36:25 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-11-14 00:36:25 INFO     Alpine Linux 3.20.3
2024-11-14 00:36:25 INFO     Python version: 3.12.7
2024-11-14 00:36:28 INFO     icloud-photos-downloader version: 1.24.3
2024-11-14 00:36:28 INFO     Checking for updates...
2024-11-14 00:36:28 INFO      - Current version (v993) is out of date. Please upgrade to latest version (v1005). Continuing in 2 minutes...
2024-11-14 00:38:28 INFO     Loading configuration from: /config/icloudpd.conf

**Comment by boredazfcuk** [comment]
>The only way I know how to achieve this is to pull the new docker version directly

Pulling the new Docker container is how you update. Pull the new container, remove the old one, create the new one, start it up, job done.

There shouldn't be any 'starting over'. If it's losing it's config, or worse, removing your photos, then you don't have your persistent volumes mapped correctly.

**Comment by gxander85** [comment]
Unfortunately, it is not that simple with QNAP Container Station.

I can deploy the latest version by searching for the docker application again.
However, upon deployment, it is effectively "as new" and all the environment settings and configuration need to be entered again.

So yes, I do have to start over each time.

It would be great if there is some way to execute a command like I do to re-authenticate, that will enable an update to the current image.

**Comment by boredazfcuk** [comment]
Weird... seems pretty simple from what I can see:
https://savoir-faire.neocities.org/tutorials/how_to_update_container_compose_in_qnap_container

In-container updates are against the whole premise of Docker. Containers are supposed to be ephemeral and were designed to be created/destroyed on each execution, some of them only existing for mere moments. They're also designed to provide a consistent environment, so if you tell me you're running v1.2.3, and I download version 1.2.3, our images are identical and I can easily replicate the same container behaviour as you.

So unfortunately, in-container updates are not something I'll ever look into, as Docker have implemented a far better container image management system than I ever could.

**Comment by gxander85** [comment]
The issue is the Environment settings that need to be reset each time you pull the 'latest' version.
I have customised the program to use a specific set of variables that work with my large iCloud library. 

I cannot work out a way to pull the latest image, but apply the current config settings and continue using without having to enter in any details again.

There is no way (that I know of) to pull the latest image to an installed and configured container.

This is what I am seeking assistance with. The link you provided just shows how to pull a new image. Not how to update an existing. There is no function to action point 4 "Edit the corresponding docker compose file, click Edit Application, then simply click Apply."
