### ISSUE TITLE
Occasional Connection Failures

### ISSUE THREAD

**Issue by Suyknow** [boredazfcuk/docker-icloudpd#698]
**Describe the bug**
I have been using this project for over a year, and I greatly appreciate the convenience it has brought me. However, in the past two to three months, I've occasionally encountered connection issues. The error message usually indicates that I cannot connect to icloud.com.cn, even though I'm certain that I can connect to it normally. Additionally, I can resolve the IP address of icloud.com.cn correctly via nslookup inside the Docker container.

I have configured my own DNS settings, trying several different ones, including Google's DNS(8.8.8.8), Aliyun's DNS(223.5.5.5), and my internal router's DNS(192.168.x.1). The result is always the same: occasional connection issues. The probability of this "occasional" issue occurring is around 50%. It doesn't happen every time, but it can happen several times in a row.

Thanks again for your help!

**System (The following information must be entered or the issue will be closed):**
 - OS: [QNAP QTS]
 - Version [5.2.1.2930] with Docker version 27.1.2-qnap2

**Debug log file**
attached
[iCloudpd_logs.txt](https://github.com/user-attachments/files/17754273/iCloudpd_logs.txt)
[nslookup_logs.txt](https://github.com/user-attachments/files/17754275/nslookup_logs.txt)

**Comment by boredazfcuk** [comment]
Hi,

I'm not sure what to suggest. The code in the container is working OK, as it's fine 50% of the time. The code doesn't change for the other 50%, so it has to be a problem external to the container, and therefore, not something I can 'fix' by amending the code.

>Max retries exceeded with url

This being in your error log does suggest that your container is hitting the Apple servers more than it should do though. How large is your library? How frequently are you syncing?

**Comment by Suyknow** [comment]
> Hi,
> 
> I'm not sure what to suggest. The code in the container is working OK, as it's fine 50% of the time. The code doesn't change for the other 50%, so it has to be a problem external to the container, and therefore, not something I can 'fix' by amending the code.
> 
> > Max retries exceeded with url
> 
> This being in your error log does suggest that your container is hitting the Apple servers more than it should do though. How large is your library? How frequently are you syncing?

Hi,

I’m also quite confused about this issue. Additionally, my understanding of “Max retries exceeded with url” is that it doesn’t indicate a rejection by icloud.com.cn but rather that the container failed to establish a connection with icloud.com.cn after multiple attempts (though I’m not entirely sure if my understanding is correct).

My iCloud library contains only 3,736 photos, and the sync frequency is once every 12 hours, which shouldn’t be excessive.

The success rate in the past few days seems to have improved significantly, from 50% to over 90%. Although I still haven’t pinpointed the exact cause, I’ll just leave it as it is for now. Thank you!
