### ISSUE TITLE
Directory is not writable: /config/python_keyring/

### ISSUE THREAD

**Issue by CXI71X** [boredazfcuk/docker-icloudpd#700]
**Describe the bug**
Running /sync-icloud.sh --Init
after upgrading DSM and Docker image

**Actual behaviour**
ERROR    Directory is not writable: /config/python_keyring/
Launch failed.

**System (The following information must be entered or the issue will be closed):**
 - OS: [Synology DSM 7.2.2-72806 Update 1]
    Python version: 3.12.7
    Alpine Linux 3.20.3

**Debug log file**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

> stream | content
> -- | --
> stdout | 2024-11-16 21:50:59 ERROR      Directory is not writable: /config/python_keyring/
> stdout | /usr/local/bin/sync-icloud.sh: line 919: [: : integer   expression expected
> stdout | su: unknown user
> stdout | 2024-11-16 21:50:59 INFO       Container initialisation complete
> stdout | 2024-11-16 21:50:59 INFO       Ignore Synology extended attribute directories: Disabled
> stdout | 2024-11-16 21:50:59 INFO       Authentication domain: com
> stdout | 2024-11-16 21:50:59 INFO       Fake user agent for curl: Disabled
> stdout | 2024-11-16 21:50:59 INFO       Downloading from: icloud.com
> stdout | 2024-11-16 21:50:59 INFO       Convert HEIC to JPEG: false
> stdout | 2024-11-16 21:50:59 INFO       Skip videos: false
> stdout | 2024-11-16 21:50:59 INFO       Live photo size:
> stdout | 2024-11-16 21:50:59 INFO       Stop downloading when prexisiting files count is: Download All Photos
> stdout | 2024-11-16 21:50:59 INFO       Downloading photos from: Download All Photos
> stdout | 2024-11-16 21:50:59 INFO       Number of most recently added photos to download: Download All Photos
> stdout | 2024-11-16 21:50:59 INFO       Skip live photos: false
> stdout | 2024-11-16 21:50:59 INFO       Skip download check: true
> stdout | 2024-11-16 21:50:59 INFO       Single pass mode: false
> stdout | 2024-11-16 21:50:59 INFO       Align RAW:
> stdout | 2024-11-16 21:50:59 INFO       Photo size: original
> stdout | 2024-11-16 21:50:59 INFO       Delete empty directories:
> stdout | 2024-11-16 21:50:59 INFO       Delete after download: false
> stdout | 2024-11-16 21:50:59 INFO       Auto delete: false
> stdout | 2024-11-16 21:50:59 INFO       Set EXIF date/time: false
> stdout | 2024-11-16 21:50:59 INFO       Synchronisation delay (minutes): 0
> stdout | 2024-11-16 21:50:59 INFO       Synchronisation interval: 86400
> stdout | 2024-11-16 21:50:59 INFO       File Match Policy:
> stdout | 2024-11-16 21:50:59 INFO       Live Photo MOV Filename Policy:
> stdout | 2024-11-16 21:50:59 INFO       Keep Unicode:
> stdout | 2024-11-16 21:50:59 INFO       Folder structure: {:%Y/%m/%d}
> stdout | 2024-11-16 21:50:59 INFO       Download destination directory: /iCloud
> stdout | 2024-11-16 21:50:59 INFO       Cookie expiry notification period: 7
> stdout | 2024-11-16 21:50:59 INFO       Cookie path: /config/88888888gmailcom
> stdout | 2024-11-16 21:50:59 INFO       Apple ID: 88888888@gmail.com
> stdout | 2024-11-16 21:50:59 INFO       Debug logging: Disabled
> stdout | 2024-11-16 21:50:58 INFO       Loading configuration from: /config/icloudpd.conf
> stdout | 2024-11-16 21:50:58 INFO        - Current version is up to date
> stdout | 2024-11-16 21:50:57 INFO       Checking for updates...
> stdout | 2024-11-16 21:50:57 INFO       icloud-photos-downloader version: 1.24.3
> stdout | 2024-11-16 21:50:56 INFO       Python version: 3.12.7
> stdout | 2024-11-16 21:50:56 INFO       Alpine Linux 3.20.3
> stdout | 2024-11-16 21:50:56   INFO     ***** For support, please go   here: https://github.com/boredazfcuk/docker-icloudpd *****
> stdout | 2024-11-16 21:50:56 INFO       ***** boredazfcuk/icloudpd container v1.0.1005_11-11-2024 started   *****
> 

</body>

</html>

**Comment by Symbiot78** [comment]
I saw this as well. 
for me it was because the group my user belongs to didn't have read/write permissions on the shared folder. 
even though the user did have the correct permissions - when I added read/write to the users group.. things worked.

**Comment by CXI71X** [comment]
> I saw this as well. for me it was because the group my user belongs to didn't have read/write permissions on the shared folder. even though the user did have the correct permissions - when I added read/write to the users group.. things worked.

Thanks for the feedback. Do you know which user is the docker using?

**Comment by CXI71X** [comment]
Reinstalled container and created another config folder. It works again.

**Comment by Symbiot78** [comment]
perfect. My user was set in the config. I matched the user_id & group_id of my synology.

**Comment by boredazfcuk** [comment]
Looks like this is sorted, so closing.
