### ISSUE TITLE
possibility to use u2f keys

### ISSUE THREAD

**Issue by Melgan** [boredazfcuk/docker-icloudpd#704]
I have secured my apple account with u2f keys (yubico 5c nfc). As far as I can understand this will not work as you not (yet) implement u2f. Would be great to add this functionality

**Comment by boredazfcuk** [comment]
This project is just a container that wraps additional functionality around another project: https://github.com/icloud-photos-downloader/icloud_photos_downloader

If support for hardware keys is added upstream, then I will add whatever is necessary for them to work within my container, but as such, it is not something I would be a part of developing.
