### ISSUE TITLE
Container not updating to the latest version

### ISSUE THREAD

**Issue by juleklO** [boredazfcuk/docker-icloudpd#708]
**Describe the bug**
A clear and concise description of what the bug is. English only please. If you can't be bothered to run it through Google Translate, or whatever, neither can I. Any issues raised that ignore this template will be closed as unplanned.

I created a new container with basic env variables. I used `image: boredazfcuk/icloudpd`. After starting the container/stack the logs loop on the following error: 
```
2024-12-10 18:51:37 INFO     ***** boredazfcuk/icloudpd container v1.0.1005_11-11-2024 started *****
2024-12-10 18:51:37 INFO     ***** For support, please go here: https://github.com/boredazfcuk/docker-icloudpd *****
2024-12-10 18:51:37 INFO     Alpine Linux 3.20.3
2024-12-10 18:51:37 INFO     Python version: 3.12.7
2024-12-10 18:51:38 INFO     icloud-photos-downloader version: 1.24.3
2024-12-10 18:51:38 INFO     Checking for updates...
2024-12-10 18:51:38 INFO      - Current version (v1005) is out of date. Please upgrade to latest version (v1050). Continuing in 2 minutes...
```

Restarting the container does not help. Changing the image to `image: boredazfcuk/icloudpd:latest` does not help either.

**Expected behaviour**

The container/image should pull the latest version (v1050) automatically.

**Actual behaviour**
A clear and concise description of what actually happened.

The container is stuck on the request to update the image.

**System (The following information must be entered or the issue will be closed):**
 - OS: [e.g. Debian, Ubuntu, Windows, Synology DSM]
 - Version [e.g. 12, 24, 11, 8]

- OS: OpenMediaVault
- Version: Linux 6.1.0-0.deb11.21-amd64 

**Debug log file**
Please add a the output of a debug log file which shows the error and all configured variables. You will need to set **debug_log=true** in your /config/icloudpd.conf file and re-generate a log file. Please feel free to remove all of the irrelevant lines, such as the filenames of the downloaded files and anything that contains personally identifiable information.

I've tried to generate the log, but it does not get created...

**Comment by bauzer714** [comment]
@juleklO  - your container/image is definitely old.  The container itself (v1005 - 11 November 2024), Alpine (3.20.3) , icloud-photos-downloader (1.24.3) version are outdated.

Just pulled the latest container (1050 - 9 December 2024)  

![image](https://github.com/user-attachments/assets/60c0aae4-861e-45b7-88a8-3f32df7c31e6)

![image](https://github.com/user-attachments/assets/8c6ce92c-e888-4eb5-abbf-a7456e2e1aba)

**Comment by juleklO** [comment]
Hi there,
cheers for the help @bauzer714 

I've rewritten the docker compose one more time, I've changed a couple of things, but the most important thing was:
- I repulled the image while changing to `image: boredazfcuk/icloudpd:latest`
- at this step the issue still persisted
- I've changed the compose to `image: boredazfcuk/icloudpd:`, while NOT repulling the image
- issue still appeared
- went back to `image: boredazfcuk/icloudpd:latest` but repulled again

This weird roundabout way solved the issue for me, weird but hey it works!
