### ISSUE TITLE
Duplicate .heic and .mov

### ISSUE THREAD

**Issue by robflate** [boredazfcuk/docker-icloudpd#71]
Can I just confirm that iCloudpd is downloading 2 files from iCloud for each Live Photo. E.g.;

- IMG_100.HEIC
- IMG_100_HEIC.MOV

So both files are directly from iCloud, it's not that iCloudpd is creating the .MOV or something? Thanks.

**Comment by boredazfcuk** [comment]
Hi,

"Live photos" consist of two files. Both of these are downloaded from iCloud.

When you look through your library, the picture you see in the gallery is the .HEIC file. When you tap to play the Live photo, the moving part is the .MOV file.

Thanks.
