### ISSUE TITLE
I am unable to convert my photos to JPEG format

### ISSUE THREAD

**Issue by seohyunxian** [boredazfcuk/docker-icloudpd#710]
Hello everyone, my English is not very good, so I can only briefly describe the problem。

Here are the problems I encountered

2024-12-11 23:59:26 INFO New files downloaded: 1
Convert HEIC files to JPEG
Convert HEIC to JPEG...
Converting /downloads/2024/12/11/IMG_2036.HEIC to /home/alex/iCloud/2024/12/11/IMG_2036. JPG
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick conver”
convert: unable to open image '/home/alex/iCloud/2024/12/11/IMG_2036.JPG': No such file or directory @ e rror/blob. c/OpenBlob/3596.
touch: cannot touch '/home/alex/iCloud/2024/12/11/IMG_2036.JPG': No such file or directory chown: cannot access '/home/alex/iCloud/2024/12/11/IMG_2036.JPG': No such file or directory

I am unable to convert my HEIC file properly，Opening the debug log also has this error.

Thank you in advance for any help you have given me

**Comment by boredazfcuk** [comment]
Hi... thanks for reporting an issue with the code. This is now fixed in the latest version of the container which I've just pushed to Dockerhub.
