### ISSUE TITLE
I have been unable to successfully convert my photos to JPEG

### ISSUE THREAD

**Issue by seohyunxian** [boredazfcuk/docker-icloudpd#711]
**Describe the bug**
I'm very sorry, but in the new version, I still cannot successfully convert the photo file to JPEG. I apologize for disturbing your rest.

**Debug log file**
2024-12-14 22:24:46 INFO     Convert HEIC to JPEG...
2024-12-14 22:24:46 INFO     Converting /downloads/2024/12/14/IMG_2192.HEIC to /jpeg/2024/12/14/IMG_2192.JPG
**magick: unable to open image '/jpeg/2024/12/14/IMG_2192.JPG': No such file or directory @ error/blob.c/OpenBlob/3596.**
2024-12-14 22:24:46 DEBUG    Timestamp of HEIC file: Sat Dec 14 22:21:33 2024
**touch: cannot touch '/jpeg/2024/12/14/IMG_2192.JPG': No such file or directory**
2024-12-14 22:24:46 DEBUG    Setting timestamp of /jpeg/2024/12/14/IMG_2192.JPG to Sat Dec 14 22:21:33 2024
2024-12-14 22:24:46 DEBUG    Correct owner and group of /jpeg/2024/12/14/IMG_2192.JPG to alex:home
**chown: cannot access '/jpeg/2024/12/14/IMG_2192.JPG': No such file or directory**

This issue also occurred in the previous version, and I don't know where I went wrong. It seems that the configuration files are functioning properly, but it prompts me that I cannot find the directory where the conversion files are stored.

**System (The following information must be entered or the issue will be closed):**
 - OS: Debian
 - Docker Version [27.1.1]

**config file**
download_path=/downloads
convert_heic_to_jpeg=true
jpeg_path=/jpeg
jpeg_quality=90
group=home
group_id=2077
user=alex
user_id=2077
I have activated privilege mode

Thank you for your dedication to the project,

**Comment by boredazfcuk** [comment]
I've just pushed a new version to Dockerhub. Try that one. I think the code wasn't creating destination directories correctly when jpeg_path was specified. I think it should be OK now, but haven't tested it. Let me know if it works.

**Comment by seohyunxian** [comment]
> I've just pushed a new version to Dockerhub. Try that one. I think the code wasn't creating destination directories correctly when jpeg_path was specified. I think it should be OK now, but haven't tested it. Let me know if it works.

Awesome, it's working now, thank you for developing this great project!

**Comment by boredazfcuk** [comment]
Odd... I did a find/replace on `convert` to `magick`. I must have messed that up somehow...

Anyway, I've built and pushed a new container which fixes this issue... again.
