### ISSUE TITLE
Folder Structure not honored with Shared Library

### ISSUE THREAD

**Issue by epheterson** [boredazfcuk/docker-icloudpd#713]
**Describe the bug**
I have three iCloudPD instances, and the Shared Library one is acting up in terms of folder structure. It puts all images for 2024 into a SharedSync-{ID} directory instead of the defined year / month / day structure:
folder_structure={:%Y/%m/%d}

I've compared my config files between the ones that work and don't, only difference is the photo_library= line (either blank, or pointing to the shared library).

Folder structure does appear correctly in the Docker logs on both:
Folder structure: {:%Y/%m/%d}

**Expected behaviour**
All containers behave the same way and honor folder structure defined in config file:
folder_structure={:%Y/%m/%d}

**Actual behaviour**
Personal library iCloudPD instances work as expected, but SharedLibrary instance is not using the folder structure. Instead all files go into one folder.

**System (The following information must be entered or the issue will be closed):**
 - OS: Synology DSM
 - Version 7.2.2

boredazfcuk/icloudpd container v1.0.1056_15-12-2024
icloud-photos-downloader version: 1.25.0

**Comment by boredazfcuk** [comment]
>It puts all images for 2024 into a SharedSync-{ID} directory

This is the expected, default behaviour.

**Comment by gligoran** [comment]
> > It puts all images for 2024 into a SharedSync-{ID} directory
> 
> This is the expected, default behaviour.

@boredazfcuk I'm running into the same issue as @epheterson above. Can you elaborate on what you mean by this? When does icloudpd not use the `folder_structure` variable?

**Comment by epheterson** [comment]
Thanks, I see the date folders now! It appears to be re-downloading everything now, but that's alright.
