### ISSUE TITLE
readme.md vs code default value differ

### ISSUE THREAD

**Issue by bauzer714** [boredazfcuk/docker-icloudpd#72]
JPEG Quality ReadME indicates 

jpeg_quality: If HEIC to JPEG conversion is enabled, this variable will let you set the quality of the converted file by specifying a number from 0 (lowest quality) to 100 (highest quality) If convert_heic_to_jpeg is set, and this variable isn't, it will default to 100.

However, in code the default value is configured to 90.

`echo "$(date '+%Y-%m-%d %H:%M:%S') INFO     JPEG conversion quality: ${jpeg_quality:=90}"`

![image](https://user-images.githubusercontent.com/13224936/123973397-bc6dee00-d989-11eb-84ae-117e47a27d35.png)

I'll let you decide which should be corrected.

**Comment by boredazfcuk** [comment]
Thanks for bringing this to my attention, I've updated the documentation so that noting changes from a user perspective... i.e., their logs will be telling them the correct value, and the average file size isn't going to suddenly increase.
