### ISSUE TITLE
Downloaded Files Webhook Invalid Json

### ISSUE THREAD

**Issue by bauzer714** [boredazfcuk/docker-icloudpd#79]
The downloaded webhook is executed with an invalid json. 

Raw Capture:
```
{ "data" : "boredazfcuk/iCloudPD - New files detected for Apple ID test@example.local: 25 Last 10 file names: 2021/07/18/IMG\_6719.HEIC
2021/07/18/4CEB2CD5-6849-4643-92A4-924BD0EAAD51.jpg
2021/07/18/IMG\_6717.JPG
2021/07/18/IMG\_6716.HEIC
2021/07/18/IMG\_6715.HEIC
2021/07/18/IMG\_6714.HEIC
2021/07/18/IMG\_6713.JPG
2021/07/18/IMG\_6712.JPG
2021/07/18/IMG\_6711.HEIC
2021/07/18/IMG\_6710.HEIC" }
```

Short term solution
- Remove escape of underscores
- Replace newlines with an escaped newline that the webhook can work with?  Perhaps replace `\n` with `\\n`

I assume the same issue exists for deleted files as the code appears to be the same.

**Comment by boredazfcuk** [comment]
Is there any chance you can test this modification?

I think that the `DownloadedFilesNotification` function can be changed to give you the output you want if line 406 is changed from:
```
webhook_payload="$(echo -e "${notification_title} - New files detected for Apple ID ${apple_id}: ${new_files_count} Last ${new_files_preview_count} file names: ${new_files_preview//_/\\_}")"
```
to
```
webhook_payload="$(echo -e "${notification_title} - New files detected for Apple ID ${apple_id}: ${new_files_count} Last ${new_files_preview_count} file names: ${new_files_preview//\n/\\n}")"
```
(The same can be done for `DeletedFilesNotification` on line 428.)

The `echo -e` at the start of the command means all `\n` are output as actual carriage return characters, so the string needs to be sent to Webhook as `\\n`.

The `${new_files_preview//_/\\_}` part is that escapes the underscores. Changing it to `${new_files_preview//\n/\\n}` should remove the escaping of underscores and have an escaped newline character that Webhook understands.

At least that's what I think is happening!

**Comment by bauzer714** [comment]
I opened the defect for tracking for myself to fix during the US afternoon. Appreciate you jumping on this so quickly. I'll confirm and add additional comment.
