### ISSUE TITLE
Notifications Ambiguous "Last"

### ISSUE THREAD

**Issue by bauzer714** [boredazfcuk/docker-icloudpd#81]
While working on #79 I noticed that the "Last" files doesn't match what my expectation was, this is potentially due to the use of "Last" being a bit ambiguous.

Scenario: 10 files from July 19, 2021 and 10 files from July 18, 2021 are downloaded - the "Last" files that are returned would be the July 18 in the notification payload.

The "Last" is correct from the perspective of "last 10 files downloaded", but would be incorrect from a perspective of "last 10 photos taken".

I don't use delete, but if it processes in the same order, it may make more sense as it would be the last 10 deletes processed.

**My Recommendation**
   1. For downloads use `head` rather than `tail` and update the `Last` verbiage to `Most Recent`
   2. For deletes, leave as is until someone has a use case to warrant update.

**Comment by boredazfcuk** [comment]
When I first implemented the feature, it the app would go through photos chronologically chronologically, so the most recent downloads would appear at the bottom. I'm guessing an upstream change has reversed this order. That would make the process a lot faster for people with massive libraries.... Imagine having 10K+ pictures, or whatever, every sync would have to trawl through 10K photos before reaching the recent ones.

 It must have changed at some point and I've not noticed, but this is definitely the ideal behaviour. Thanks for PR.
