### ISSUE TITLE
Error in exec format

### ISSUE THREAD

**Issue by maudio691** [boredazfcuk/docker-icloudpd#85]
Hello
I was using your container like 1 year ago now.

And i have now a problem with this latest updates.

I see that a big changes now.

Now i pulled your container and now it appears me this.

QNAP
Alpine AL-212
standard_init_linux.go:219: exec user process caused: exec format error    

Thank in advance

**Comment by maudio691** [comment]
i think in in the 1st line you have missed a B?
bin/bash?

**Comment by boredazfcuk** [comment]
Hi,

Thanks for bringing this to my attention. It seems the latest DockerHub image I've pushed only has the amd64 architecture in it. 

This is odd, as I build all my images for i386, amd64, arm64, arm/v7 and arm/v6. My builds process is all scripted now, so it's not like I've done anything different.

I did upgrade my local Registry container the other day (https://hub.docker.com/_/registry), maybe it's something to do with that. I also changed the URL I pull the manifests from when running my hub-release script, so I'll try changing that back too. The one I was using had stopped returning the info I needed, maybe the new one that is working, doesn't support multi-arch images.

I'll look into it and get back to you.

**Comment by maudio691** [comment]
Many thanks, script changed a lot since ive pulled it from last year. Ill wait your correction.

**Comment by boredazfcuk** [comment]
I've pushed a new multi-arch image to DockerHub so things should be OK if you update.

I'm not sure why this is occurring though as my build scripts haven't changed in months. They build a local image and push it to my local registry. I then run the beta version on my local server and when I'm happy with it, I just run a "hub-release" script which adds the DockerHub tags and then pushes it to Dockerhub. It seems to be stripping out the non-amd64 images at this point now, for some reason.

I'll just have to keep this in mind and check the Dockerhub manifests after each build. I'll keep this open as a reminder until I've fixed my automated build scripts.

**Comment by maudio691** [comment]
Hi,

I run the cointainer and also in the terminal i execute the initializer but it appears me this. In what way i have to put the permission to this because i have enabled all.

su: can't execute '/bin/ash': Permission denied                                                                                                                                         
2021-08-02 18:21:19 INFO     Correct owner on config directory, if required                                                                                                             
2021-08-02 18:21:19 INFO     Correct group on config directory, if required                                                                                                             
2021-08-02 18:21:19 INFO     Generate 2FA cookie with password:                                                                                                                         
2021-08-02 18:21:19 INFO     Check for new files using password stored in keyring file.                                                                                                 
su: can't execute '/bin/ash': Permission denied                                                                                                                                         
2021-08-02 18:21:19 INFO     Two factor authentication cookie generated. Sync should now be successful.

**Comment by boredazfcuk** [comment]
The container doesn't require any additional permissions. It works with the default permissions assigned by Docker.

However, I'm just wondering if your version of Docker is a bit old, and maybe works differently. Can you run `docker version` from a terminal prompt and post the results?

On my server I get:
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.8
  GitCommit:        7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc:
  Version:          1.0.0
  GitCommit:        v1.0.0-0-g84113ee
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Another possibility is that your device is running the docker daemon as a restricted user, rather than root, and this is somehow affecting it. Can you also run:
```
ps -ef | grep dockerd
```
and post the results?

I get: 
```
root     29060 12915  0 21:56 pts/0    00:00:00 grep --color dockerd
root     29849     1  1 20:56 ?        00:00:51 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```
which shows dockerd us running as the root user.

**Comment by maudio691** [comment]
PID   USER     TIME  COMMAND                                                                                                                                                            
    1 root      0:00 {sync-icloud.sh} /bin/ash /usr/local/bin/sync-icloud.sh                                                                                                            
   92 root      0:00 sleep 300                                                                                                                                                          
  126 root      0:00 ps -ef | grep dockerd                

i have this in with the command that you said.

**Comment by maudio691** [comment]
Container Station 2.4.0.2316
( 2021/08/02 )
[Important Notes]
- QNAP is ending support for LXC containers by the end of 2021. Container Station will not support the creation and modification of LXC containers. Ensure to backup all relevant data and files before LXC containers reach the end of support.
- LXC containers have been removed from the recommended list for x86-64 models. Users looking for alternative containers can search for images from the LXD image server for creating LXD containers.
 
[New Features]
- Supports searching images from the LXD image server for creating LXD containers on x86-64 models.
- Supports container duplication.
- Supports image creation from Docker containers.
- Supports pulling images prior to container creation.
 
[Enhancements]
- Updated Docker Compose to version 1.29.2
 
[Fixed Issues]
- The application would display blank values for network interface and mode if both IPv4 and IPv6 settings were configured for network adapters in Network & Virtual Switch.
- Container Station would mount the container volume at the incorrect location path if the host folder name contained "share". Back up and recreate the container to mount at the correct path, and reboot the system manually to delete the incorrect folder.
 
[Compatibility]
- Container Station 2.4 is compatible only with the following firmware and applications: QTS 4.5.3.1697 (or later), QuTS hero h4.5.3.1698 (or later), QuFirewall 1.4.0 (or later), QIoT Suite 2.0.008 (or later)

**Comment by boredazfcuk** [comment]
> 
> 
> PID USER TIME COMMAND
> 1 root 0:00 {sync-icloud.sh} /bin/ash /usr/local/bin/sync-icloud.sh
> 92 root 0:00 sleep 300
> 126 root 0:00 ps -ef | grep dockerd
> 
> i have this in with the command that you said.

Sorry, you need to run that on the host machine, rather than inside the container.

Looking at this: https://www.linuxserver.io/blog/2017-09-17-how-to-setup-containers-on-qnap

...it seems that Docker is run as a non-root user, I think you'll need to use the user and group id returned when you run that command.

**Comment by boredazfcuk** [comment]
Just closing this off as it should be sorted now. I think your error was down to all except the amd64 image being stripped out when I was uploading to dockerhub. Just pull the latest version and it should be OK. If not, just reopen the issue.
