### ISSUE TITLE
Failsafe : can't find .mounted file

### ISSUE THREAD

**Issue by DarKOrange75** [boredazfcuk/docker-icloudpd#89]
Hi all,

I've been trying to make this work for hours now and I run out of ideas :-(

I can't get this to work, the script can't find the .mounted file which is present and has r/w permissions for everyone in a shared folder with same permissions... Please see picture.

Thank you for your help :-)

Laurent

<img width="933" alt="Capture d’écran 2021-08-18 à 01 53 38" src="https://user-images.githubusercontent.com/40524270/129815733-bc13ccf9-9438-49fa-b8e5-30c4d412302a.png">
<img width="1274" alt="Capture d’écran 2021-08-18 à 01 53 14" src="https://user-images.githubusercontent.com/40524270/129815522-240545d0-1c13-4e8d-9e5c-af9c311746e4.png">
<img width="1161" alt="Capture d’écran 2021-08-18 à 01 52 16" src="https://user-images.githubusercontent.com/40524270/129815523-0ad503fb-b8b5-42e9-a15d-aa62fb95e2cd.png">
<img width="1200" alt="Capture d’écran 2021-08-18 à 02 02 30" src="https://user-images.githubusercontent.com/40524270/129816099-42f1b241-43e1-451b-8b91-1502983f875e.png">
<img width="733" alt="Capture d’écran 2021-08-18 à 02 14 28" src="https://user-images.githubusercontent.com/40524270/129816834-bf19c1d0-cd0c-4f88-9892-91025eab24c8.png">

**Comment by bauzer714** [comment]
You set the download_path environment variable to /iCloud, but map /home/laurent/iCloud.

Option 1 is delete the variable (assuming the user you set is laurent)

Option 2, Set the third volume mapping for the mount path to /iCloud

**Comment by boredazfcuk** [comment]
I’m overseas at the moment with no access to a laptop, so will struggle to help for another week or so.

I think @bauzer714 has answered your question though. Give that a try and post back if you’re still stuck.

**Comment by DarKOrange75** [comment]
Thank you @bauzer714 for your fast answer, the 2nd option worked :-)

And thank you @bauzer714 for the hard work :-)

**Comment by bauzer714** [comment]
@boredazfcuk does all the hard work. I simply pretend to know what I'm doing, on occasion.

**Comment by DarKOrange75** [comment]
I made a mistake with the nicknames ;-) Any way thank you both for helping me :-)
