### ISSUE TITLE
Access Shared Albums

### ISSUE THREAD

**Issue by robertomano24** [boredazfcuk/docker-icloudpd#9]
Hi,

Does this container allow me to access Shared Albums?

Thanks!

**Comment by boredazfcuk** [comment]
I have no idea to be honest.

It's just a container to get [this](https://github.com/ndbroadbent/icloud_photos_downloader) Python script installed with the correct versions of its dependent packages.

Looking at the documentation for the link above, it has an option to download albums:
```-a, --album <album>             Album to download (default: All Photos)```

It might work by specifying the shared album's name, but it's not something I've tested.

**Comment by boredazfcuk** [comment]
So... I've dug up this issue for the underlying library which is used to connect to icloud.com and download the photos: [HERE](https://github.com/picklepete/pyicloud/issues/107)

It says that it isn't possible, as the shared libraries are not available on icloud.com.

I think the library doesn't do anything other than log into the website and download the pictures as you would with your browser. As the shared libraries are not available on the icloud.com website, they're not available to download when using this library.
