### ISSUE TITLE
Telegram startup notification sent successfully, or not...

### ISSUE THREAD

**Issue by bijca** [boredazfcuk/docker-icloudpd#99]
Hi,

Since an update two weeks ago, I no longer receive notifications in Telegram, while iCloudPD indicates it does send them:

`2021-09-07 14:40:44 INFO     Notification title: boredazfcuk/iCloudPD
2021-09-07 14:40:44 INFO     Telegram notifications enabled
2021-09-07 14:40:44 INFO     Telegram token: *****
2021-09-07 14:40:44 INFO     Telegram chat id: ****
2021-09-07 14:40:44 INFO     Telegram notification URL: https://api.telegram.org/bot****
2021-09-07 14:40:44 INFO     Notification period: 7
2021-09-07 14:40:44 INFO     Sending Telegram startup notification
2021-09-07 14:40:44 INFO     Telegram startup notification sent successfully'

I have deleted the containers and their data, recreated the bot, recreated the chat, but I am no longer getting the notifications.

However, when using this command (I've found in another issue) the notification is received.

'docker run --rm --name test_icloudpd boredazfcuk/icloudpd \
   curl --silent --request POST "https://api.telegram.org/bot<Token&API>/sendMessage" \
   --data chat_id="<ChatID>" \
   --data parse_mode="markdown" \
   --data text="This is a test message"'

**Comment by boredazfcuk** [comment]
Hi,

The command that you found is exactly the same command as what is run from within the container.

The script also checks the exit code of the curl command that sends the message, to detect wheterh it was successful or not... If there was a problem connecting, or the command was incorrect, it would fail, and the script would detect that.

This suggests that the Token or Chat ID is not correct. It could also be a Telegram problem in your part of the world...

I know the code is correct, as I use the Telegram option myself. I run four containers and get messages that way every few hours.

Out of curiosity, how are you specifying the Chat ID when you manually test it? I remove the preceding `-` character as I've found it's required. Maybe there are inconsistencies across Telegrams network and yours expects it to be there.

**Comment by josephsiu** [comment]
Any chance to get webhook support for Slack? I tried to implement everything according to the webhook, but I"m not getting any start up notification in the slack channel. Sorry to cross post here as I'm not sure where to ask.

**Comment by boredazfcuk** [comment]
> Any chance to get webhook support for Slack? I tried to implement everything according to the webhook, but I"m not getting any start up notification in the slack channel. Sorry to cross post here as I'm not sure where to ask.

Yeah man. I’ll make whatever modifications are needed to get it working. Just create it as a new issue though… so t’other dude doesn’t get a bunch of notifications about it… and we’ll work through it there.

**Comment by bijca** [comment]
Hi,

I'm using docker compose:

_# iCloudPD-name
  icloudpd:
    container_name: iCloudPD-name
    network_mode: bridge
    restart: unless-stopped
    environment:
      - user=*****
      - user_id=1026
      - group=users
      - group_id=100
      - apple_id=name@gmail.com
      - notification_type=Telegram
      - telegram_token=1789646951:AAGXFA8mtZFERVP8wDSsDcGEvoigB3XnDA*
      - telegram_chat_id=-5420285**
      - TZ=Europe/Amsterdam # Change to your timezone
      - convert_heic_to_jpeg=True
      - jpeg_quality=100
      - auto_delete=True
    volumes:
      - /volume1/docker/appdata/icloudpd-name/:/config # <Named volume which is mapped to /config>
      - /volume1/photo/iCloud-name/:/home/name/iCloud # <Bind mount to the destination folder on the host>
    image: boredazfcuk/icloudpd_

Like I said, this worked perfectly until an update 2/3 weeks ago. Did someting changed regarding this option? And you're sure there's no difference between the command above en the config in the container?

Thanks!

**Comment by boredazfcuk** [comment]
There’s only one change related to the Telegram notification system around that time, and nothing prior to that for a long time… It was in regards to how the chat ID is handled. I hadn’t documented it, but the preceding `-` on the chat ID needed dropping for notifications to work. One user was adding it into his .env file, so obviously his notifications didn’t work.

The change just strips the `-` character from the Chat ID if it’s specified. I tested with my Chat ID set to `-12345` and `12345` and both work.

**Comment by bijca** [comment]
Hi,

I'm not able to fix it, for now I've switched to Prowl.

Thanks!
